- CONTRIBUTING.md
- DCO
- Development.md
- LICENSE
- NOTICE
- README.md
- Zenhub.md
- code-of-conduct.md
- src/app/ee/LICENSE
- src/app/ee/README.md
What this PR does / why we need it:
Add all required license information for the open source of Kubermatic Kubernetes Platform and updates the README
Does this PR introduce a user-facing change?:
```release-note
Open sourcing Kubermatic Kubernetes Platform
```
> [release/v2.14] Update README and add FOSS and KERO License (#2394)

- src/app/cluster/cluster-details/cluster-details.component.html
- src/app/cluster/cluster-details/cluster-details.component.ts
- src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.html
- src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.scss
- src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.spec.ts
- src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.ts
- src/app/core/services/api/api.service.ts
- src/app/shared/entity/cluster.ts
- src/app/shared/model/ClusterForm.ts
- src/app/shared/utils/admission-plugin-utils/admission-plugin-utils.ts
- src/app/testing/services/api-mock.service.ts
- src/app/wizard-new/service/cluster.ts
- src/app/wizard-new/step/cluster/component.ts
- src/app/wizard-new/step/cluster/style.scss
- src/app/wizard-new/step/cluster/template.html
- src/app/wizard-new/step/provider-settings/ssh-keys/template.html
- src/app/wizard-new/step/summary/component.ts
- src/app/wizard-new/step/summary/template.html
- src/app/wizard/set-cluster-spec/set-cluster-spec.component.html
- src/app/wizard/set-cluster-spec/set-cluster-spec.component.scss
- src/app/wizard/set-cluster-spec/set-cluster-spec.component.ts
- src/app/wizard/set-datacenter/set-datacenter.component.ts
- src/app/wizard/set-settings/ssh-keys/cluster-ssh-keys.component.html
- src/app/wizard/summary/summary.component.html
- src/app/wizard/summary/summary.component.scss
- src/app/wizard/summary/summary.component.ts
- src/app/wizard/wizard.component.ts
- src/assets/css/_theme.scss
Redesign Admission Plugin view: It is now a dropdown instead of seperate checkboxes.
Implement new struct: Instead of having multiple fields in the cluster spec, we now have one slice where all admission plugins are saved. The old fields will be transfered into the new slice once the cluster gets edited.
Copy of https://github.com/kubermatic/dashboard/pull/2393, because of broken fork
Fixes #2011
Fixes #1987
/
```release-note
Use new field `AdmissionPlugins` in cluster struct, instead of `UsePodSecurityPolicyAdmissionPlugin` & …
```
> Restructure Admission Plugins

- hack/run-in-docker.sh
> hack/run-in-docker.sh: use node 12 which is now required

- Makefile
To be honest I am not entirely sure if this will work on the CI as previous way did work locally for me. This way is taken from the Kubermatic repo with the small change that is "escaping" the `\-${VERSION}` string. Locally echo does not allow to print `-ee` as `-e` is an argument that this command takes. Not sure why it behaves differently on the CI as CI uses `bash` also.
PS. That's why I never wanted to be a DevOps :slightly_smiling_face: 
```release-note
NONE
```
> Fix build/push for the CE image

- src/app/wizard/summary/summary.component.html
Fix summary view for admission plugins. This only happened in the current wizard and though it will be replaced soon, I wanted to have this one fixed, as it is attracts my attention every single time. 😅 
/
```release-note
NONE
```
> Fix summary view for admission plugins

- src/app/node-data-new/basic/provider/openstack/component.ts
- src/app/node-data/openstack-node-data/openstack-node-data.component.ts
Fix default image for openstack when RHEL or Flatcar is selected. 
/
```release-note
NONE
```
> Fix default image for openstack for rhel and flatcar

- src/app/shared/entity/provider/gcp.ts
- src/app/wizard/step/provider-settings/provider/extended/gcp/template.html
Add and use gcp subnetworks path, as it is the needed value for cluster creation
Related to https://github.com/kubermatic/dashboard/issues/2093
/hold
https://github.com/kubermatic/kubermatic/pull/5646 has to be merged first
```release-note
NONE
```
> Add and use gcp subnetworks path

- src/app/shared/entity/provider/gcp/GCP.ts
- src/app/wizard-new/step/provider-settings/provider/extended/gcp/template.html
- src/app/wizard/set-settings/provider-settings/gcp/gcp-provider-options/gcp-provider-options.component.html
Add and use gcp subnetworks path
cherry picked from https://github.com/kubermatic/dashboard/pull/2483
/
```release-note
NONE
```
> [release/2.14] Add and use gcp subnetworks path

- src/app/node-data/basic/provider/alibaba/component.ts
- src/app/node-data/basic/provider/alibaba/template.html
- src/app/node-data/basic/provider/aws/component.ts
- src/app/node-data/basic/provider/aws/template.html
- src/app/node-data/basic/provider/azure/component.ts
- src/app/node-data/basic/provider/azure/template.html
- src/app/node-data/basic/provider/gcp/component.ts
- src/app/node-data/basic/provider/gcp/template.html
- src/app/node-data/basic/provider/packet/component.ts
- src/app/node-data/basic/provider/packet/template.html
- src/app/node-data/service/provider/alibaba.ts
- src/app/node-data/service/provider/aws.ts
- src/app/node-data/service/provider/azure.ts
- src/app/node-data/service/provider/digitalocean.ts
- src/app/node-data/service/provider/gcp.ts
- src/app/node-data/service/provider/hetzner.ts
- src/app/node-data/service/provider/openstack.ts
- src/app/node-data/service/provider/packet.ts
- src/app/shared/utils/common-utils.ts
- Updated providers logic in the wizard to choose the smallest/cheapest instance by default
- Updated display name format to show all information after selecting an instance
- Fixed an issue with triggering refresh of sizes and related endpoints when datacenters are refreshed
```release-note
Cheapest/smallest provider instance will be chosen by default in the wizard
```
> Choose smallest/cheapest instance as the default one

- cypress/integration/stories/machine-deployments.spec.ts
Disable node deployment test case until e2e networking issue is fixed.
```release-note
NONE
```
> Skip ND test case

- src/app/project/project.component.html
- src/app/project/project.component.ts
- src/app/settings/admin/admin-settings.component.html
- src/app/shared/entity/settings.ts
- src/app/testing/services/settings-mock.service.ts
Add option to restrict project creation to admins
Fixes #2603
/
```release-note
Added option to restrict project creation to admins via the Admin Settings
```
> Add option to restrict project creation to admins

- src/app/core/components/navigation/project/component.ts
- src/app/core/components/navigation/project/template.html
Fixes #2626 
```release-note
Fix project selector auto-scroll to selected value on refresh
```
> Fix project selector jumping to selected value on refresh

- src/app/cluster/cluster-list/cluster-list.component.html
- src/app/cluster/cluster-list/cluster-list.component.spec.ts
- src/app/cluster/cluster-list/cluster-list.component.ts
- src/app/core/interceptors/error-notifications/error-notifications.service.ts
- src/app/core/services/cluster/cluster.service.ts
- src/app/project/project.component.spec.ts
- src/app/project/project.module.ts
- src/app/settings/admin/admin-settings.component.html
- src/app/shared/entity/settings.ts
- src/app/testing/services/settings-mock.service.ts
API error with information about the disabled external cluster import feature is silenced and `Connect Cluster` button is hidden after disabling the feature. We could think about improving the error behavior of handling the GET of a single cluster in case someone uses a direct link? Not sure what should be done in this case though.
Fixes #2642
```release-note
Add option to enable/disable external cluster import feature from admin settings.
```
> Add option to enable/disable external cluster import from admin settings

- src/app/node-data/basic/provider/vsphere/component.ts
- src/app/node-data/basic/provider/vsphere/template.html
- src/app/node-data/extended/provider/vsphere/component.ts
- src/app/node-data/extended/provider/vsphere/template.html
Since VM template is not really an optional parameter I have made it a required one. Optional parameters are allowed to be empty and only then they can be a part of extended options.
Fixes #2682
```release-note
NONE
```
> Make vsphere VM template a required parameter

- src/app/shared/entity/cluster.ts
- src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
- src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
- src/app/wizard/step/summary/template.html
- Added `Datastore` and `Datastore Cluster` support to vsphere provider in wizard
- Fix summary view layout
Fixes #2611
```release-note
Add Datastore/Datastore Cluster support to the VSphere provider in the wizard.
```
> Add datastore support to vsphere provider

- src/app/cluster/cluster-details/component.spec.ts
- src/app/cluster/cluster-details/component.ts
- src/app/cluster/cluster-details/template.html
- src/app/core/services/cluster/service.ts
**What this PR does / why we need it**: It basically reverts https://github.com/kubermatic/dashboard/pull/2574 but this time uses new endpoint from https://github.com/kubermatic/kubermatic/pull/6130.
Fixes https://github.com/kubermatic/dashboard/issues/2771
/hold
Wait for https://github.com/kubermatic/kubermatic/pull/6130 to be merged.
/cherry-pick release/v2.15
/assign @floreks 
```release-note
Restore list of cluster nodes.
```
> Restore list of cluster nodes

- Makefile
- src/app/core/components/footer/template.html
- src/app/shared/entity/version-info.ts
- src/app/testing/fake-data/versionInfo.fake.ts
- version.js
As we tag releases on the release/XXX branches, a `git describe` on the master branch does not yield useful information. Currently it says something like `v2.14.0+255.g24fa837d`, because we more or less accidentally tagged that version on the exact moment we split the release branch away.
This PR changes the behaviour to treat master as 2.16.0. It was easier to hardcode the version into the Makefile than trying to do arithmetic and trying to calculate it based on the latest release branch.
I couldn't see where all the fields from the VersionInfo type are actually used, so maybe we can now skip the git-describe dependency alltogether?
```release-note
NONE
```
> Provide a better version info

- src/app/cluster/cluster-details/node-list/template.html
- src/app/node-data/basic/provider/openstack/component.ts
- src/app/node-data/basic/provider/openstack/template.html
- src/app/shared/entity/node.ts
- src/app/testing/fake-data/node.fake.ts
- src/app/wizard/step/summary/template.html
Added support for 2 new Openstack fields.
- `instanceReadyCheckPeriod`
- `instanceReadyCheckTimeout`
Related to https://github.com/kubermatic/kubermatic/pull/6139.
```release-note
Add support for 'instanceReadyCheckPeriod' and 'instanceReadyCheckTimeout' to the Openstack provider.
```
> Add support for new Openstack variables

- src/app/shared/components/label-form/label-form.component.html
**What this PR does / why we need it**: The behavior was invalid because the delete button was by default acting like submit button. Adding type "button" to it fixes the issue.
Fixes https://github.com/kubermatic/dashboard/issues/2891
```release-note
Fixed the bug with labels that were removed from form after pressing enter key.
```
> Do not remove labels when pressing enter key in the label form

- src/app/cluster/cluster-details/edit-cluster/component.ts
- src/app/cluster/cluster-details/edit-cluster/style.scss
- src/app/cluster/cluster-details/edit-cluster/template.html
- src/app/shared/components/label-form/label-form.component.html
- src/app/shared/components/label-form/label-form.component.ts
- src/app/shared/entity/cluster.ts
- src/app/shared/model/ClusterForm.ts
- src/app/shared/services/cluster.service.ts
- src/app/wizard/step/cluster/component.ts
- src/app/wizard/step/cluster/style.scss
- src/app/wizard/step/cluster/template.html
- src/app/wizard/step/summary/template.html
Added option to specify a Pod Node Selector Configuration during cluster creation or cluster edit. It will only be visible, when Pod Node Selector is enabled as Admission Plugin.
Fixes #2884
```release-note
Add option to specify Pod Node Selector Configuration
```
> Pod Node Selector Config

- src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.html
- src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.scss
- src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.ts
- src/app/shared/components/label-form/label-form.component.html
- src/app/shared/components/label-form/label-form.component.ts
- src/app/shared/entity/cluster.ts
- src/app/shared/model/ClusterForm.ts
- src/app/shared/services/cluster.service.ts
- src/app/wizard/step/cluster/component.ts
- src/app/wizard/step/cluster/style.scss
- src/app/wizard/step/cluster/template.html
- src/app/wizard/step/summary/template.html
Added option to specify a Pod Node Selector Configuration during cluster creation or cluster edit. It will only be visible, when Pod Node Selector is enabled as Admission Plugin.
cherry picked from https://github.com/kubermatic/dashboard/pull/2929
```release-note
Add option to specify Pod Node Selector Configuration
```
> [release/v2.15] Pod Node Selector Config

- .prow.yaml
- go.mod
- go.sum
* the validate-prow-yaml job is always maintained in the infra repo, never the project repos (for easier Prow upgrades and because certalized jobs have slightly different semantics that in-repo jobs)
* the Prometheus dependency has been bumped to have an actual reason to make a PR in the first place
* the prow.yaml has been reformatted while I was at it
```release-note
NONE
```
> update Go dependencies, cleanup .prow.yaml

- .prow.yaml
- hack/e2e/ci-setup-kubermatic-in-kind.sh
- src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.html
- src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.ts
- src/app/shared/components/label-form/label-form.component.html
- src/app/shared/components/label-form/label-form.component.ts
- src/app/shared/entity/ClusterEntity.ts
- src/app/shared/entity/ClusterEntityPatch.ts
- src/app/shared/model/ClusterForm.ts
- src/app/wizard/set-cluster-spec/set-cluster-spec.component.html
- src/app/wizard/set-cluster-spec/set-cluster-spec.component.ts
- src/app/wizard/set-datacenter/set-datacenter.component.ts
- src/app/wizard/summary/summary.component.html
- src/app/wizard/wizard.component.ts
Added option to specify a Pod Node Selector Configuration during cluster creation or cluster edit. It will only be visible, when Pod Node Selector is enabled as Admission Plugin.
"cherry picked" from #2929
```release-note
Add option to specify Pod Node Selector Configuration
```
> [release/v2.14] Pod Node Selector Config

- src/app/core/services/wizard/provider/azure.ts
- src/app/core/services/wizard/provider/provider.ts
- src/app/shared/entity/provider/azure.ts
- src/app/wizard/step/provider-settings/provider/extended/aws/component.ts
- src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
- src/app/wizard/step/provider-settings/provider/extended/azure/template.html
Fixes https://github.com/kubermatic/dashboard/issues/2921
Fixes https://github.com/kubermatic/dashboard/issues/2920
Fixes https://github.com/kubermatic/dashboard/issues/2918
```release-note
Azure resource groups, security groups and route tables will be now loaded from the API to provide autocompletion.
```
> Use endpoints to get Azure resource groups, security groups and route tables

- .prow.yaml
- Makefile
- containers/cypress/Dockerfile
- containers/cypress/build-and-release.sh
- hack/e2e/fixtures/kubermatic.yaml
- hack/e2e/fixtures/oauth_values.yaml
- hack/e2e/fixtures/seed.yaml
- hack/e2e/run-tests.sh
- hack/e2e/setup-kind-cluster.sh
- hack/e2e/setup-kubermatic-in-kind.sh
The Helm chart is deprecated and soon to be removed. It's high time this repo switches to the KKP Installer.
This PR effectively brings the e2e setup code in-sync with what KKP does. Instead of using the Helm chart from the KKP repo, we now compile the installer and use that to install KKP (i.e. as before, the jobs clone the KKP repo and reuse some of its code).
Noteworthy is that the setup process is now split into 2 scripts:
* setup-kind-cluster.sh just sets up a kind cluster
* setup-kubermatic-in-kind.sh then follows and takes care of installing KKP
This has been done because
* it keeps the dashboard mostly in-sync with how KKP does it and
* KKP does it because separating kind from KKP makes it easier to run upgrade tests (i.e. tests where KKP is …
> Migrate from Helm to Kubermatic Installer in e2e tests

- src/app/shared/model/Config.ts
- src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
- src/assets/config/config.json
Signed-off-by: Olaf Klischat <o.klischat@syseleven.de>
This pre-fills the username and domain name fields in the cluster creation wizard / openstack settings with the user's login name (for the username) and a default domain name (configurable in a new option in the dashboard config file).
I think these things were there in 2.14. (at least the username thing)
What I'd also like (and was also there in 2.14 I think) would be after the project is selected and the floating IP pool list loaded, to pre-select the first floating ip pool if there's only one. But I couldn't get that to work, so maybe later in a separate PR.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
> openstack wizard: pre-fill username and domain fields

- Makefile
Time to get the 2.16 release on its way. Part of https://github.com/kubermatic/kubermatic/issues/6439
```release-note
NONE
```
> declare master branch as 2.17-dev

- package-lock.json
- package.json
Reverted ngx-monaco-editor to v9.0.0 as v10.0.0-beta.1 was breaking the editor with 
- locally: `ngx-monaco-editor.js:48 GET http://localhost:8000/assets/vs/loader.js net::ERR_ABORTED 404 (Not Found)`
- dev: `Uncaught SyntaxError: Unexpected numbermain.a5fb73c17db805ba8809.js:1` & `ERROR TypeError: window.require is not a function`
See https://github.com/atularen/ngx-monaco-editor/issues/122 or https://github.com/atularen/ngx-monaco-editor/issues/189 as a reference
```release-note
NONE
```
> revert ngx-monaco-editor to v9.0.0

- src/app/settings/admin/template.html
- src/app/shared/entity/settings.ts
- src/app/testing/services/settings-mock.service.ts
This adds new resource quota related fields to the admin panel
Fixes #3010
```release-note
Added resource quota settings to the admin panel.
```
> Add resource quota settings to admin panel

- src/app/node-data/basic/provider/aws/component.ts
- src/app/node-data/basic/provider/aws/template.html
- src/app/shared/entity/provider/aws.ts
- Used `pretty_name` instead of `name`
- Added GPU count information if available to the description
- Sorted instances by their price (cheapest to the most expensive)
Fixes #3037
```release-note
AWS node sizes in the wizard now provide GPU information.
```
> Add GPU information to AWS node sizes

- src/app/shared/entity/health.ts
Fixes issue with additional health checks being provided by the API and checked by the frontend when they are not relevant to us. It was blocking i.e. machines from being loaded.
```release-note
NONE
```
> Cluster health state should only be checked for known statuses

- src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
External networks cannot be used as cluster networks and will result in
a failure during cluster creation when selected.
Filter external networks in the cluster creation wizard for openstack to
prevent users from selecting those options.
Fixes #
```release-note
Filter external openstack networks during cluster creation
```
> Filter external networks in openstack wizard

- src/app/wizard/step/cluster/component.ts
This PR changes the pattern used to validate cluster names during cluster creation to the [same one](https://github.com/kubermatic/dashboard/blob/b062244f8645f14f9cdb015fa63d236141fde013/src/app/cluster/cluster-details/edit-cluster/component.ts#L67) that is used when editing the cluster.
**Which issue(s) this PR fixes** 
This fixes a bug where it is possible to create a cluster that can't be edited later.
```release-note
NONE
```
> Validate name during cluster creation with the same pattern as on edit

- Makefile
When a commit had multiple tags (like we have for 2.16.0 and 2.16.1), the old code would accidentally take _both_ tags and break its own Go compiling:
> CGO_ENABLED=0 go build -a -ldflags '-w -extldflags -static -X 'main.Edition=ce' -X 'main.Version=v2.16.0 v2.16.1'' -o dashboard .
As it happens quite frequently that the dashboard has multiple tags on the same revision, this PR makes it so that the "effective" version is always taken from `PULL_BASE_REF`. This allows us to rerun older, failed jobs and not have them accidentally use a newer tag.
Once this is merged and backported, we need to release a 2.16.2.
```release-note
NONE
```
> fix makefile for commits with multiple version tags

- src/app/core/components/changelog/style.scss
- src/app/core/components/changelog/template.html
- src/app/core/components/changelog/theme.scss
As noticed by @maciaszczykm some styling was overridden for the labels. This PR fixes it.
```release-note
NONE
```
> Fix label styling

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/cleanup.md
- .github/ISSUE_TEMPLATE/design-change.md
- .github/ISSUE_TEMPLATE/design.md
- .github/ISSUE_TEMPLATE/failing-test.md
- .github/ISSUE_TEMPLATE/feature.md
Instead of team/ui assign correct label sig/ui to new issues
```release-note
NONE
```
> Assign correct label to new issues

- .prow.yaml
sig-infra is cleaning up Secrets in the CI cluster, and `quay` is now deprecated and `kubermatic-quay` should be used instead.
```release-note
NONE
```
> adjust .prow.yaml to recent cleanup efforts

- .prow.yaml
- containers/custom-dashboard/Dockerfile
- containers/cypress/Dockerfile
- containers/cypress/build-and-release.sh
- containers/go-node/Dockerfile
- containers/go-node/build-and-release.sh
- containers/test-chrome/Dockerfile
- containers/test-chrome/release.sh
:tada:
```release-note
NONE
```
> Update to Go 1.16.1

- src/app/cluster/cluster-details/constraints/constraint-dialog/template.html
@lsviben noticed a typo in constraint dialog. Instead of `Template Name` it should be `Constraint Name`. 👍 
```release-note
NONE
```
> OPA- fix typo

- cypress/integration/stories/node-deployment.spec.ts
- cypress/integration/stories/ssh-keys.spec.ts
- cypress/pages/clusters.po.ts
- cypress/pages/ssh-keys.po.ts
- cypress/pages/wizard.po.ts
- cypress/utils/condition.ts
- cypress/utils/endpoint.ts
- cypress/utils/view.ts
- src/app/wizard/step/cluster/ssh-keys/template.html
Added a story to test ssh key management.
- Create ssh key
- Create a cluster with created ssh key
- Edit ssh keys from the cluster details:
- remove the ssh key from the cluster
- re-add the ssh key to the cluster
- remove ssh key from the project
Fixes #2952
```release-note
NONE
```
> Add e2e tests for ssh keys

- src/app/serviceaccount/token/add/steps/name/component.ts
- src/app/serviceaccount/token/add/steps/name/template.html
It adds validation for the token names on the frontend side. The methods from label form were reused as the token name is stored in the label in the end.
Fixes https://github.com/kubermatic/dashboard/issues/3145.
If we would like to change the place where the token name is saved then it would take more time and might even be a breaking change. That's why this fix change doesn't touch that subject.
```release-note
Added validation for service account token names.
```
> Add validation for token names

- src/app/settings/admin/custom-link-form/template.html
Preiously enter key was invoking delete button which was by default "submit" type.
Fixes https://github.com/kubermatic/dashboard/issues/3220.
```release-note
Do not delete custom links after pressing enter key.
```
> Do not delete custom links after pressing enter key

- .prow.yaml
- cypress/integration/providers/alibaba.spec.ts
- cypress/pages/wizard.po.ts
- cypress/utils/preset.ts
- cypress/utils/provider.ts
- hack/e2e/setup-kubermatic-in-kind.sh
- src/app/node-data/basic/provider/alibaba/component.ts
- src/app/node-data/basic/provider/alibaba/template.html
- src/app/wizard/step/cluster/component.ts
I have found and fixed a bug in wizard that most likely was introduced with the OPA integration and caused some fields reset after admin settings were updated by someone. Additionally, `vSwitchID` field was not automatically filled out in the wizard.
Both fixes have to be cherry-picked to the v2.17 release branch.
Closes #2942
```release-note
NONE
```
> Add alibaba e2e and fix wizard issues

- main.go
I have added `config` and `assets/config` directories to the no-cache zone to make sure all files there will be always taken from the server.
Fixes #3137
```release-note
NONE
```
> Fix cachin' too stronk

- src/app/cluster/cluster-details/cluster-details.component.ts
- src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.ts
- src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.ts
- src/app/cluster/services/node.service.ts
- src/app/node-data/dialog/template.html
currently on some places the term "Machine Deployment" is used while in
some others "Node Deployment" is used.
This PR fixes this by re-naming everything that is left on "Node
Deployment" to "Machine Deployment"
```release-note
Re-Naming every occurrence of "Node Deployment" in the UI to "Machine Deployment"
```
> Re-Name Node Deployment to Machine Deployment

- src/app/project/style.scss
- src/app/project/template.html
Previously longer names with `-` in it were automatically wrapped and this was causing some visual glitches. I've set `nowrap` and switched to CSS method as it is more stable (not all letters have the same width and this sets limit on div size not letter count).
Fixes https://github.com/kubermatic/dashboard/issues/3271.
```release-note
NONE
```
> Fix project card headers

- src/app/serviceaccount/add-serviceaccount/template.html
- src/app/serviceaccount/edit-serviceaccount/template.html
- src/app/shared/utils/member-utils/member-utils.spec.ts
- src/app/shared/utils/member-utils/member-utils.ts
Closes https://github.com/kubermatic/dashboard/issues/3326.
```release-note
Add project managers group as an option for service accounts.
```
> Add project managers group to SA

- src/app/node-data/basic/provider/openstack/template.html
- src/app/shared/entity/node.ts
See:
- https://github.com/kubermatic/kubermatic/blob/master/pkg/api/v1/types.go#L1408
- https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/openstack/provider.go#L188-L205
- https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/openstack/provider.go#L207-L223
Fixes https://github.com/kubermatic/dashboard/issues/3382.
```release-note
NONE
```
> Fix handling of instanceReadyCheckPeriod and instanceReadyCheckTimeout variables

- src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
Fixes https://github.com/kubermatic/kubermatic/issues/7152.
```release-note
vNet resource group instead of resource group will be used if it is specified.
```
>  Use vNet resource group instead of resource group if it is specified

- Makefile
- package-lock.json
- package.json
Bump dashboard release 2.17.0 to 2.17.1
```release-note
NONE
```
> bumped dashboard to 2.17.1

- src/app/core/components/sidenav/style.scss
Fixes https://github.com/kubermatic/dashboard/issues/3435.
```release-note
Fixed custom link icon display in the sidenav.
```
> Fix custom link icon display in the sidenav

- src/app/cluster/cluster-details/cluster-delete-confirmation/template.html
https://github.com/kubermatic/kubermatic/pull/7189
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain
Our cluster cleanup algorithm can still leave some residual volumes in the cloud provider. Deleting dynamically provisioned `PVs` bypasses kubernetes triggers for remote volumes cleanup. Mostly we leverage dynamically provisioned `PVs`, at which point we can rely on the CSI plugins and cloud providers to do their job. For statically provisioned `PVs` that have `retain` as their `ReclaimPolicy`, we can't do much and need to leave it to the user to cleanup the volumes in the cloud provider manually.
I didn't want to overload the message here by adding all the context explained above, but I think it might be worth adding a better explanation than what I am proposing, I am …
> Clarify PV cleanup during cluster delete

- src/app/core/services/node-data/provider/openstack.ts
- src/app/core/services/wizard/provider/openstack.ts
- src/app/core/services/wizard/provider/provider.ts
- src/app/shared/entity/cluster.ts
- src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
- src/app/wizard/step/provider-settings/provider/basic/openstack/template.html
- src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
- Added 2 new fields (app credentials id/secret)
- Some logic refactoring 
I am still not sure if I have checked all scenarios as there were basically no functional requirements here and providing app credentials highly impacts other related endpoints such as projects/floatingIPs/securityGroups/networks/subnets listing.
We should reconsider keeping mutually exclusive fields on a single wizard step as it makes the underlying logic very complex and it is hard to ensure a nice user experience.
Closes #3470
```release-note
Added support for Application Credentials to the Openstack provider
```
> Add support for app credentials to the openstack provider

- src/app/cluster/cluster-details/alertmanager-config/component.spec.ts
- src/app/cluster/cluster-details/alertmanager-config/component.ts
- src/app/cluster/cluster-details/alertmanager-config/template.html
- src/app/settings/admin/component.spec.ts
- src/app/settings/admin/defaults/template.html
- src/app/shared/entity/settings.ts
- src/app/testing/services/settings-mock.ts
- src/assets/css/material/_main.scss
Added admin settings for alermanager domain & a link to alertmanager ui.
Fixes #3280
```release-note
Added admin settings for alermanager domain and the link to alertmanager ui.
```
> admin settings for alermanager domain + link to alertmanager ui

- src/app/wizard/step/cluster/component.ts
The OPA integration checkbox sometimes got reset during cluster creation due to a reload of the admin settings.
```release-note
NONE
```
> fix reset of opa integration checkbox

- src/app/core/services/cluster-spec.ts
Fixes https://github.com/kubermatic/dashboard/issues/3536.
Previous implementation was based on a wrong assumption that cluster setter in the service is always invoked with full cluster objects. In reality sometimes partial cluster objects are sent and this was causing overwrites of cluster network. I've changed pure assignment to the merge method, however it uses a different customizer. I'm not sure why in the code above the changed one we are ignoring the source array and using destination one. In my case I needed to do the opposite.
```release-note
NONE
```
> Use merge when applying cluster network changes to avoid overrides

- src/app/core/components/changelog/style.scss
- src/assets/css/global/_main.scss
Set min-height to 400px and adjusted dialog height scaling to better work on smaller screens.
Fixes #3590
```release-note
NONE
```
> Adjust changelog dialog to work with smaller screens

- src/app/node-data/extended/provider/aws/component.ts
- src/app/node-data/extended/provider/aws/style.scss
- src/app/node-data/extended/provider/aws/template.html
- src/app/shared/animations/push.ts
- src/app/shared/entity/node.ts
- src/app/wizard/step/summary/template.html
- src/app/wizard/template.html
- src/assets/css/material/_main.scss
- Added support for spotInstanceMaxPrice field
- Added support for spotInstancePersistentRequest field
- Added slight animation when showing those additional fields
- Updated the way we disable `mat-step` animations to not disable animations for all inner children.
- 
Closes #3606
```release-note
Extend AWS spot instance support with 'spotInstanceMaxPrice' and 'spotInstancePersistentRequest' fields.
```
> Extend AWS spot instance configuration options

- src/app/shared/validators/base-form.validator.ts
- src/app/wizard/component.ts
- src/app/wizard/step/provider-settings/provider/basic/component.ts
Removed provider control removal and recreation on datacenter change. As it does not influence provider fields, it should not be required and it also does not override the provide form initialization.
Fixes #3611
```release-note
NONE
```
> Fix issue with wizard form validation on settings step

- src/app/cluster/cluster-details/node-list/template.html
- src/app/node-data/extended/provider/aws/component.ts
- src/app/node-data/extended/provider/aws/template.html
- src/app/shared/validators/larger-than.validator.ts
- src/app/shared/validators/validators.ts
- src/app/wizard/step/summary/template.html
- Added `largerThan` validator
- Updated spot instance validation to allow numbers bigger than 0
Fixes #3613
```release-note
NONE
```
> Update aws spot instance max price to be bigger than 0

- src/app/cluster/cluster-details/alertmanager-config/component.spec.ts
- src/app/cluster/cluster-details/alertmanager-config/component.ts
- src/app/settings/admin/defaults/template.html
- src/app/shared/entity/settings.ts
- src/app/testing/services/settings-mock.ts
Rename `User Cluster Alertmanager Domain` to `User Cluster Alertmanager Prefix` and adjust related link in Alertmanager Tab.
```release-note
NONE
```
> Adjust User Cluster Alertmanager Link

- cypress/plugins/index.ts
Temporary skip provider e2e tests as they are blocking ci too much atm
```release-note
NONE
```
> temporary skip provider + opa e2e tests

- src/app/core/services/api.ts
- src/app/wizard/step/cluster/component.ts
Using a new `providers/{provider_name}/versions` endpoint to list cluster versions.
Closes #3647
```release-note
NONE
```
> Use new cluster version API endpoint

- src/assets/css/_images.scss
Replace tick icon by the new check icon, as it is no longer available and neither steps in wizard nor the health status in cluster details view was displaying checkmarks anymore.
```release-note
NONE
```
> Replace tick icon

- .prow.yaml
- containers/chrome-headless/Dockerfile
- containers/chrome-headless/release.sh
Disables log colors to see if that speeds up time needed to display all logs in prow.
```release-note
NONE
```
> Turn off e2e log colors and update job images

- Makefile
The old repo was deprecated in May 2020.
Closes https://github.com/kubermatic/dashboard/issues/3669.
```release-note
NONE
```
> Stop pushing to quay.io/kubermatic/ui-v2

- src/app/dynamic/enterprise/metering/list/component.ts
- src/app/dynamic/enterprise/metering/list/template.html
Request to the reports endpoint will not be made when metering is disabled.
Fixes #3668
```release-note
NONE
```
> Request reports only if metering is enabled

- cypress/plugins/index.ts
Enables provider tests to check automatically if all the providers are working. I'm not adding hold as it doesn't belong to the 2.18 milestone anyways.
```release-note
NONE
```
> Enable provider tests

- src/app/shared/components/cluster-summary/template.html
- src/app/shared/entity/cluster.ts
- src/app/wizard/step/cluster/component.ts
- src/app/wizard/step/cluster/template.html
By default, all our clusters have Canal CNI. Backend already exposes CNI configuration knobs and internally we can spin up a cluster with Cilium. This exposes the CNI config to the end user.
depends on: https://github.com/kubermatic/kubermatic/pull/7853, https://github.com/kubermatic/kubermatic/pull/7851, https://github.com/kubermatic/kubermatic/pull/7862
closes: https://github.com/kubermatic/kubermatic/issues/7577
```release-note
Allow users to select one of the two supported CNIs - Canal or Cilium
```
> Expose CNI config in wizard

- src/app/settings/admin/bucket-settings/edit-bucket-setting-dialog/component.ts
- src/app/settings/admin/bucket-settings/edit-bucket-setting-dialog/template.html
This is a manual backport of #3726.
```release-note
NONE
```
> [release/v2.18] remove default endpoint hint + make it required (#3726)

- src/app/cluster/cluster-details/template.html
This is a followup to https://github.com/kubermatic/dashboard/pull/3709, I forgot to include CNI information in cluster details
```release-note
NONE
```
> Display CNI plugin type in cluster details

- src/app/node-data/component.ts
- src/app/node-data/template.html
- Make RHEL subscription manager user/password fields optional
- Add small note saying that they are still required in order to register a machine
- Enable RHEL and Flatcar for VSphere
- Remove old logic that enabled VSphere OS based on the image templates defined in the datacenter spec
Fixes #3819
Fixes #3820
```release-note
Add support for RHEL and Flatcar to the VSphere provider. Make RHEL subscription manager fields optional.
```
> Update OS selection logic for vsphere and RHEL fields

- package.json
- src/app/shared/components/select-cluster-template/component.ts
- src/app/shared/components/select-cluster-template/template.html
Fixes https://github.com/kubermatic/dashboard/issues/3832.
```release-note
Disable dialog select form until existing template is selected.
```
> Disable form until existing template is selected

- src/app/cluster/cluster-details/component.ts
- src/app/cluster/cluster-details/template.html
- src/app/shared/utils/health-status/cluster-health-status.ts
Fixes https://github.com/kubermatic/dashboard/issues/3694.
Previous check was preventing from loading the data if the cluster had no machine deployments created. Machine deployments are loaded in the same `combineLatest` as OPA stuff.
```release-note
Fix a bug where OPA data was not retrieved when there were no machine deployments in the cluster.
```
> Improve OPA loading check

- src/app/cluster/cluster-details/edit-cluster/component.ts
- src/app/cluster/cluster-details/edit-cluster/style.scss
- src/app/cluster/cluster-details/edit-cluster/template.html
Closes https://github.com/kubermatic/edgematic/issues/74.
```release-note
Allow audit policy preset changes during cluster edit.
```
> Allow audit policy preset changes during cluster edit

- src/app/cluster/cluster-details/template.html
Fixes https://github.com/kubermatic/dashboard/issues/3909.
```release-note
Hidden edit provider settings action for kubeAdm as it is not supported.
```
> Hide edit provider settings action for kubeAdm as it is not supported anyways

- package-lock.json
- package.json
The latest release for `ngx-clipboard` seems to be broken. The `click to copy` functionality fails for dialogs and modals.
Fixes #3906 
The intended release for `ngx-clipboard` is of [v15.0.0](https://github.com/maxisam/ngx-clipboard/releases/tag/v15.0.0) but the published package is `v14.0.2` which doesn't have any tags/releases in the code-base as well. Hence I can't track/investigate about this issue in the package.
```release-note
NONE
```
> Downgrade ngx-clipboard

- src/app/shared/entity/cluster.ts
We have decided to allow Docker to be used on Kubernetes clusters up to 1.24.0.
```release-note
NONE
```
cc: @moadqassem
> Bump END_OF_DOCKER_SUPPORT_VERSION to 1.24.0

- src/assets/css/global/_main.scss
Before (disabled):
After:
Fixes https://github.com/kubermatic/dashboard/issues/3999.
```release-note
NONE
```
> Hide CNI version picker arrow if it is disabled

- src/app/cluster/details/cluster/mla/alertmanager-config/component.spec.ts
- src/app/cluster/details/cluster/mla/alertmanager-config/component.ts
- src/app/cluster/details/cluster/mla/alertmanager-config/style.scss
- src/app/cluster/details/cluster/mla/alertmanager-config/template.html
- src/app/cluster/details/cluster/mla/component.ts
- src/app/cluster/details/cluster/mla/template.html
- src/app/cluster/details/cluster/template.html
Add warning to grafana link if node-exporter and/or kube-state-metrics addons aren't enabled
Fixes https://github.com/kubermatic/kubermatic/issues/7961
```release-note
NONE
```
> Add warning to grafana link if special addons aren't enabled

- src/app/core/module.ts
- src/app/core/services/auth/guard.ts
- src/app/routing.ts
Added view guard to properly check for admin user before allowing access to the view.
Fixes #4026
```release-note
NONE
```
> Block non-admin access to admin settings

- src/app/node-data/component.ts
SLES doesn't support `containerd` as container runtime. Hide it from the list of supported operating systems from dashboard.
Similarly, RHEL is not supported on GCP.
Fixes #4072 #4075
```release-note
NONE
```
> Hide SLES if container runtime is containerd and remove RHEL as supported OS for GCP

- src/app/cluster/details/cluster/mla/component.ts
- src/app/cluster/details/cluster/mla/template.html
Fixes mla tab, as the current `isLoading()` function basically every time returned true. Especially in case there aren't any default rule groups it is not possible that this tab ever gets enabled.
```release-note
NONE
```
> Fix mla tab

- src/app/settings/admin/bucket-settings/destinations/component.ts
- src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts
- src/app/settings/admin/bucket-settings/destinations/destination-dialog/style.scss
- src/app/settings/admin/bucket-settings/destinations/destination-dialog/template.html
- src/app/settings/admin/bucket-settings/destinations/template.html
- src/app/shared/entity/datacenter.ts
Add option to set a default destination. It'll then be used for automatic etcd backups after cluster creation.
Fixes #4079
```release-note
Add option for administrators to specify default destination in "Backup Destinations" view.
```
> Add option to set a default destination

- src/app/cluster/details/cluster/template.html
Fix for an issue when after using cluster patch event rate limit config breaks the cluster details view.
```release-note
NONE
```
> Fix undefined error on cluster details

- src/app/shared/components/event-list/style.scss
Fixes #4103
```release-note
NONE
```
> Fix long event messages causing page to stretch

- src/app/cluster/details/cluster/template.html
- src/app/shared/components/cluster-summary/component.ts
- src/app/shared/components/cluster-summary/template.html
- src/app/shared/components/property/template.html
Added key labels to the provider and ssh keys fields.
Fixes #4107
```release-note
NONE
```
> Update provider/ssh keys fields key display

- src/app/node-data/basic/provider/openstack/component.ts
The information taken from the edited MD was overridden during defaulting. Now they are saved and reused.
Fixes #4100
```release-note
NONE
```
> Fix the default image selection in the MD edit dialog

- cypress/integration/providers/kubevirt.spec.ts
- package-lock.json
- package.json
- src/app/node-data/basic/provider/kubevirt/component.ts
- src/app/node-data/basic/provider/kubevirt/template.html
- src/app/shared/entity/node.ts
This PR introduces the following changes for machine deployment create/edit view for **KubeVirt**:
* Fix regex for validating memory size for Kubevirt machines. Right now values without units are allowed which results in machine provisioning failures. For example, "1" is a valid value.
* Defaults for node were not defined which were initializing the values as `undefined`
* Default namespace to `kube-system`
```release-note
* Minor fixes covering machine deployment creation/edit for KubeVirt
```
> Fixes for Kubevirt machine deployment creation

- src/app/cluster/details/shared/version-picker/style.scss
- src/app/cluster/details/shared/version-picker/template.html
As decided in slack, we wanted to move the update available indicator next to the dropdown arrow.
Also slightly reduced the width of the whole version picker, as we also shortened the name to "Control Plane" and there is plenty of space left.
Fixes #4113
```release-note
NONE
```
> Move update indicator

- src/app/cluster/details/cluster/component.ts
- src/app/cluster/details/cluster/template.html
- src/app/shared/components/event-list/component.ts
- src/app/shared/components/expansion-panel/component.ts
- src/app/shared/components/expansion-panel/template.html
- Additional custom events grouping by the message/type/id
- Expand additional information section by default when cluster is not in running state
Fixes #4116
```release-note
NONE
```
> Update event grouping and more information section logic

- src/app/cluster/details/external-cluster/component.ts
- src/app/cluster/details/external-cluster/template.html
- src/app/core/services/cluster.ts
Adds a button for https://github.com/kubermatic/kubermatic/pull/8122.
Closes https://github.com/kubermatic/dashboard/issues/4146.
```release-note
Add option to get kubeconfig for external clusters.
```
> Add option to get kubeconfig for external clusters

- src/app/core/services/wizard/provider/aws.ts
- src/app/node-data/basic/provider/aws/component.ts
- src/app/shared/entity/provider/aws.ts
- src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
- src/app/wizard/step/provider-settings/provider/basic/aws/template.html
- Fixed an issue with VPC ID
- Fixed an issue with the Subnets not loading
- Fixed an issue with the stuck in `Loading` state of the subnets field when there were no subnets to show.
Fixes #4180
```release-note
NONE
```
> Fix AWS wizard

- .prow.yaml
- Makefile
- hack/e2e/fixtures/kubermatic.yaml
- hack/e2e/setup-kubermatic-in-kind.sh
- package-lock.json
- package.json
Bumps version to `v2.18.6`. No changes to `release/v2.18` have happened since `v2.18.5`.
Please approve if there are no pending backports to `release/v2.18` you would like to get out.
```release-note
NONE
```
Signed-off-by: Marvin Beckers <marvin@kubermatic.com>
> [release/v2.18] Bump release version to v2.18.6

- src/app/node-data/basic/provider/azure/component.ts
- src/app/node-data/basic/provider/azure/template.html
changing the default value for the OS disk size in MD for Azure Provider from 0 to 30GB 
when creating a machine with lower than 30GB it fails in machine-controller that minimal size for OS disk is 30GB.
“closes #4201”
```release-note
NONE
```
> changing the default OS disk size to 30

- Makefile
- package-lock.json
- package.json
We need another KKP release `v2.18.7` to fix some issues with `nodeport-proxy-envoy` introduced with `v2.18.6`.
Bumps version to v2.18.7.
```release-note
NONE
```
> [release/v2.18] Bump release version to v2.18.7

- src/app/node-data/extended/provider/aws/component.ts
- src/app/node-data/extended/provider/aws/template.html
Require from user to provide max spot instance price if spot instance checkbox is checked.
```release-note
NONE
```
> Require spot instance max price

- src/app/core/services/settings.ts
- src/app/core/services/user.ts
We use PATCH endpoint response to set the settings too and without defaulting it was setting only initialized (already changed) fields. Now, if the field is not set it will be defaulted in the service.
Fixes https://github.com/kubermatic/dashboard/issues/4232.
```release-note
Fixed settings defaulting after first settings update.
```
> Default unset settings returned from PATCH endpoint too

- src/app/serviceaccount/token/style.scss
The button text looks too light compared to the plus icon next to it.
so the PR fix the text font weight to looks more like the plus icon next to it 
“closes #4234”
```release-note
NONE
```
> fixing font weight for Add token Button

- src/app/core/services/node-data/provider/azure.ts
Updated the code so that the sizes will be downloaded only once and there will be no additional requests.
Fixes #4257
```release-note
NONE
```
> Fix an issue with continuous polling the azure sizes in the dialog mode

- src/app/cluster/details/cluster/template.html
1. Changing the "External CCM" label to "External CCM/CSI migration". This information should reflect the status of the migration to the external CCM/CSI.
2. Addition of a new field in the "additional cluster information > MISC" section related to the external CCM/CSI setting for the current cluster.
```release-note
Addition of a new field in the "additional cluster information > MISC" section related to the external CCM/CSI setting for the current cluster.
```
> CCM/CSI info addition 

- src/app/cluster/details/cluster/edit-cluster/component.ts
- src/app/settings/admin/defaults/template.html
- src/app/wizard/step/cluster/component.ts
Current enforce checkboxes were both checking and disabling the related fields instead of only disabling them. I have updated the logic to match other settings.
```release-note
NONE
```
> Update the MLA admin settings logic

- src/app/shared/entity/preset.ts
There has been an issue with preset creation due to the required emails type change.
```release-note
NONE
```
> Fix an issue with preset creation when domain is provided

- src/app/cluster/details/cluster/edit-provider-settings/alibaba-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/anexia-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/aws-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/azure-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/digitalocean-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/equinix-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/gcp-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/hetzner-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/kubevirt-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/nutanix-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/openstack-provider-settings/component.ts
- src/app/cluster/details/cluster/edit-provider-settings/vsphere-provider-settings/component.ts
Closes https://github.com/kubermatic/dashboard/issues/4283. The dialog and the form work but there was 500ms debounce, so once the form was filled it took 500ms to validate. Debounce in that case is not required as we are not connecting to any API and without it the UI will be nicer to use.
```release-note
NONE
```
> Remove debounce from provider settings form and fix subscription leak

- src/app/node-data/basic/provider/azure/component.ts
- src/app/node-data/basic/provider/azure/template.html
- src/app/shared/components/cluster-summary/template.html
- src/app/shared/components/openstack-credentials/application/component.ts
- src/app/shared/components/openstack-credentials/component.ts
- src/app/shared/components/openstack-credentials/default/component.ts
- src/app/shared/entity/cluster.ts
- src/app/wizard/step/cluster/component.ts
- src/app/wizard/step/cluster/template.html
- src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
- src/app/wizard/step/provider-settings/provider/basic/azure/component.ts
- src/app/wizard/step/provider-settings/provider/basic/gcp/component.ts
- src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
- src/app/wizard/step/provider-settings/provider/extended/aws/component.ts
- src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
- src/app/wizard/step/provider-settings/provider/extended/gcp/component.ts
- Refactored the preset enable/disable logic
- Added support for the allowed IP range override to the second wizard step for the supported providers
- Updated default os disk size for the Azure provider when RHEL OS is selected
Fixes #3924
Fixes #4259
```release-note
Added allowed IP range override support to the GCP, Azure, AWS, and OpenStack providers.
Updated OS default disk size to 64GB for the Azure provider when RHEL OS is selected.
```
> Add allowed IP range override support and update the azure os disk size default for RHEL

- src/app/settings/admin/presets/dialog/steps/settings/component.ts
- src/app/settings/admin/presets/dialog/steps/settings/provider/openstack/component.ts
- src/app/settings/admin/presets/dialog/steps/settings/provider/openstack/template.html
- src/app/shared/components/openstack-credentials/component.ts
- Make `Domain` optional when app credentials are used
Fixes https://github.com/kubermatic/dashboard/issues/4323
```release-note
NONE
```
> Make Domain optional when app credentials are used

- src/app/core/components/notification-panel/template.html
when we clear the notifications the animation for  it first make it look like columns then it clear them,, so this PR fix it so the animation wouldn't change the arrange of the notification before clear them 
"closes #4233 "
-->
```release-note
NONE
```
> ajust clear notification

- .prow.yaml
- src/app/serviceaccount/token/component.ts
- src/app/serviceaccount/token/template.html
- src/app/shared/entity/service-account.ts
- blocked edit when token is invalid
- added warning icon with tooltip to inform about invalid token
- made e2e optional for further investigation (https://github.com/kubermatic/dashboard/issues/4344)
Fixes #4331
```release-note
Added warning icon with a message for invalid service account tokens.
```
> Add warning for invalid SA tokens

- src/app/shared/entity/external-cluster.ts
To keep in sync with https://github.com/kubermatic/kubermatic/pull/9408.
```release-note
NONE
```
> Update external cluster statuses

- cypress/integration/stories/external-cluster.spec.ts
- cypress/pages/clusters.po.ts
- src/app/cluster/details/external-cluster/component.ts
- src/app/cluster/list/component.ts
- src/app/cluster/list/template.html
At the moment after disconnecting external cluster users get redirected to the cluster list view. It displays always the first tab, so the internal clusters. this PR redirect the user to the external cluster list view .
"closes #4265 "
```release-note
NONE
```
> support Redirects to external cluster view 

- hack/e2e/setup-kubermatic-in-kind.sh
KKP recently changed its CRD directory to prevent code duplication and to keep it up-to-date. This PR ensures the dashboard can still be installed.
```release-note
NONE
```
> fix installation in e2e tests

- src/app/core/services/settings.ts
- src/app/dynamic/enterprise/metering/schedule-config/report-list/component.spec.ts
- src/app/dynamic/enterprise/metering/schedule-config/report-list/component.ts
- src/app/dynamic/enterprise/metering/schedule-config/report-list/template.html
- src/app/dynamic/enterprise/metering/service/metering.ts
- src/test/services/metering-mock.ts
Metering report list component now supports remove report action. 
I also decided to move all report related methods from setting service to metering service.
Fixes #4429 
```release-note
Enable metering report removal
```
> Add metering report removal action to the report list component.

- src/app/cluster/details/cluster/template.html
Signed-off-by: Waseem Abbas <waseemabbas8261@gmail.com>
Hide MLA section if it is not enabled on seed level for cluster details view.
Fixes #4482 
```release-note
Hide MLA section if it is not enabled on seed level
```
> Hide MLA section if it is not enabled on seed level

- src/app/shared/utils/health-status.ts
MachineDeployment health in the dashboard does not consider whether replicas where updated. That can result in incorrect UI information during a MachineDeployment upgrade (it should be showing that the MachineDeployment is updating, but as long as enough old Machines are still available, it will not).
This PR includes `md.status.updatedReplicas` in the if condition for status "Running".
```release-note
MachineDeployment health is only considered "Running" if replicas are all updated
```
Signed-off-by: Marvin Beckers <marvin@kubermatic.com>
> Only consider MachineDeployment running if replicas are updated

- Makefile
- package-lock.json
- package.json
We (cc @xrstf) plan to cut another KKP patch release, 2.20.3. This adds the required dashboard version bump.
```release-note
NONE
```
Signed-off-by: Marvin Beckers <marvin@kubermatic.com>
> [release/v2.20] Bump version to 2.20.3

- src/app/node-data/basic/provider/alibaba/component.ts
- src/app/node-data/basic/provider/anexia/component.ts
- src/app/node-data/basic/provider/aws/component.ts
- src/app/node-data/basic/provider/gcp/component.ts
- src/app/node-data/basic/provider/kubevirt/component.ts
- src/app/node-data/basic/provider/openstack/component.ts
Signed-off-by: Waseem Abbas <waseemabbas8261@gmail.com>
Edit machine deployment dialog was displaying default values in combobox elements instead of what was configured. This has been fixed by removing `_clearX` method calls when combobox options are loading.
Fixes #4472 
Reason for removing these clear method calls:
- `_onXLoading` method is called when combobox options are loading
- `_onXLoading` method calls `_clearX` method
- `_clearX` method calls `reset` method of combobox
- Combobox emits `changed` event with `null` value
- `null` value gets assigned to property in `_nodeDataService.nodeData.spec.cloud.X` hence replacing original value
- Combobox options finish loading so `_setDefaultX` is called
- `_setDefaultX` method loads value from `_nodeDataService.nodeData.spec.cloud.X` …
> Show updated config instead of default values in edit machine deployment dialog 

- src/app/cluster/details/cluster/node-list/component.ts
- src/app/cluster/details/cluster/node-list/style.scss
- src/app/cluster/details/cluster/node-list/template.html
- src/app/cluster/details/external-cluster/external-node-list/component.ts
- src/app/cluster/details/external-cluster/external-node-list/style.scss
- src/app/cluster/details/external-cluster/external-node-list/template.html
- src/app/shared/entity/node.ts
- src/app/shared/utils/node.ts
This PR adds functionality to display multiple Internal IPs in node details of a machine deployment.
#4529 
```release-note
NONE
```
> 4529 display multiple internal IPs in node details of machine deployment

- .github/dependabot.yml
Signed-off-by: Waseem Abbas <waseemabbas8261@gmail.com>
`approved` label from `dependabot.yml` has been removed so that someone from the owners list has to manually `/approve` it and PRs by dependabot are not merged automatically by just the addition of `/lgtm` label.
```release-note
NONE
```
> Remove `approved` label for dependabot

- package-lock.json
- package.json
Signed-off-by: Waseem Abbas <waseemabbas8261@gmail.com>
`swagger-ui` version was bumped to `4.12.0` which broke the swagger rest-api page so this PR reverts the version to `4.8.1`
```release-note
NONE
```
> Revert `swagger-ui` version to `4.8.1`

- src/app/cluster/details/cluster/machine-deployment-details/template.html
- src/app/cluster/details/cluster/node-list/template.html
- src/app/core/services/node.ts
- src/app/node-data/basic/provider/nutanix/component.ts
- src/app/node-data/basic/provider/openstack/component.ts
- src/app/node-data/basic/provider/vsphere/component.ts
- src/app/node-data/template.html
- src/app/shared/components/cluster-summary/template.html
- src/app/shared/entity/datacenter.ts
- src/app/shared/entity/node.ts
- src/app/shared/model/NodeProviderConstants.ts
- src/assets/css/_images.scss
Signed-off-by: Talha Jamil TJ <talha.jamil@kubermatic.com>
fixes the spelling of rocky linux from "rockylinux" to "rockyLinux" in **OperatingSystem** enum
Now while editing machine deployments **Rocky Linux** will be selected by default
Closes #4571 
```release-note
NONE
```
> Pre-select rocky linux while editing machine deployment

- src/app/cluster/details/cluster/component.ts
- src/app/core/services/cluster.ts
- Updated the `Open Dashboard` button to use new endpoint
Related to https://github.com/kubermatic/kubermatic/issues/9804
Fixes #4558
On hold until https://github.com/kubermatic/kubermatic/pull/10072 gets merged and https://github.com/kubermatic/kubermatic/issues/10015 will be done.
```release-note
NONE
```
> Update 'Open Dashboard' endpoint usage

- src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts
- src/app/core/services/cluster.spec.ts
- src/app/core/services/cluster.ts
- src/app/shared/types/request-type.ts
Fixes bug where on the machine deployment details page the nodes where not specific to the machine deployment selected, the page was showing all the node 
`URL: https://dev.kubermatic.io/projects/<project-id>/clusters/external/<cluster-id>/md/<node-group>`
closes #4540 
```release-note
Bug fix: on the machine deployment details page, show the correct nodes instead of all nodes
```
> External Clusters Machine Deployment Nodes Details Fix

- src/app/core/services/feature-gate.ts
- src/app/core/services/node.ts
- src/app/node-data/component.ts
- src/app/node-data/template.html
- src/app/shared/components/cluster-summary/component.ts
- src/app/shared/components/cluster-summary/template.html
- src/app/shared/entity/machine-deployment.ts
- src/app/shared/model/NodeSpecChange.ts
- src/app/wizard/component.ts
- src/app/wizard/step/cluster/component.ts
- src/app/wizard/step/cluster/template.html
- src/app/wizard/step/summary/component.ts
adding new field to add operating system profile when creating new MD  
"closes #4580"
```release-note
Allow the user to specify the operating system profile when creating machine deployment.
```
> Add an option to specify "Operating System Profile" when creating machine deployments

- src/app/node-data/kubelet-version/component.ts
Signed-off-by: Olaf Klischat <olaf.klischat@gmail.com>
One-line fix for the Kubelet version selector dropdown component. In the fallback case, i.e. when the list of possible kubelet upgrade versions from the API contains neither the current ("selected") Kubelet version nor the current control plane version of the cluster, the code is supposed to just select the last one of the list of possible Kubelet upgrade versions. It does this by doing `control.setValue(versions.pop())`. versions.pop() however removes the last element from the list, resulting in a selector that's empty by default and is just missing the last (newest) upgrade version in the dropdown. This PR fixes this to `control.setValue(versions[versions.length - 1])`.
Example with this.versions == ["1.19.12", "1.20.14", "1.21.8"], …
> kubelet version selector fallback case fix

- cypress/fixtures/digitalocean/machinedeployment.json
- cypress/fixtures/digitalocean/machinedeployments.json
- src/app/cluster/details/cluster/node-list/template.html
- src/app/node-data/extended/provider/digitalocean/component.ts
- src/app/node-data/extended/provider/digitalocean/template.html
- src/app/shared/components/cluster-summary/template.html
- src/app/shared/entity/node.ts
- src/test/data/node.ts
This PR removes IPv6 control from extended settings of DigitalOcean cloud provider in create cluster wizard and edit cluster dialog.
#4566 
```release-note
DigitalOcean: Option to configure IPv6 has been removed from node settings since it can now be configured using dual-stack network configuration in cluster creation wizard.
```
> Remove IPv6 control for DigitalOcean cloud provider

- src/app/core/services/node-data/provider/aws.ts
- src/app/node-data/basic/provider/aws/component.ts
- src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
Only list subnets and VPCs that support IPv6 when dual-stack networking is enabled for AWS.
Closes #4474 
```release-note
AWS: Only list subnets and VPCs that support IPv6 when dual-stack networking is enabled.
```
> Filter subnets and VPCs when dual-stack network is selected for AWS cloud provider

- src/app/wizard/step/cluster/component.ts
Default values of IPv4 and IPv6 CIDR mask size controls is set to `null` so that form control is not invalid.
If value is set to `''` for `number-stepper` component then this is considered an invalid value so form becomes invalid. In order to fix this, value needs to be either `null`/`undefined` or a valid number.
```release-note
NONE
```
> Fix default values of CIDR mask size controls

- src/app/cluster/details/cluster/component.ts
- src/app/cluster/details/cluster/template.html
- src/app/shared/entity/health.ts
the current behavior for the open dashboard button is that the button will be available only when all cluster components health is up so in this PR we change the availability for the open dashboard button according to the k8s dashboard health ,  
also the same for kubeconfig and share buttons 
Fixes #4579
```release-note
NONE
```
> Check k8s dashboard health

- src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts
- src/app/settings/admin/bucket-settings/destinations/destination-dialog/template.html
This is a follow-up for https://github.com/kubermatic/kubermatic/pull/9717 which adds validation at the front-end for destination name for backups.
Fixes #
```release-note
Add validations for backup destination names
```
> Add validations for backup destination names in seed

- src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts
- src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html
- src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
- src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
- src/app/core/module.ts
- src/app/core/services/external-machine-deployment.ts
This PR allows to Delete External Cluster machine deployment from External cluster details page and External Cluster Machine Deployment details page.
**External cluster details page:**
https://user-images.githubusercontent.com/17727069/177599481-3f08cc4b-9eef-481d-a5ce-b155bde405e1.mp4
**External Cluster Machine Deployment details page**
https://user-images.githubusercontent.com/17727069/177599547-d828a99b-1a00-4e99-953f-04558ab76eb0.mp4
Fixes # https://github.com/kubermatic/dashboard/issues/4629
```release-note
Add support for deleting machine deployments of External Cluster (EKS,AKS,GKE)
```
> Delete External Cluster MD 

- src/app/core/services/external-cluster.ts
- src/app/external-cluster-wizard/component.ts
- src/app/external-cluster-wizard/module.ts
- src/app/external-cluster-wizard/steps/external-cluster/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/style.scss
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
- src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
- src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
- src/app/external-cluster-wizard/steps/external-cluster/template.html
- src/app/external-cluster-wizard/template.html
- src/app/project-overview/create-resource-panel/component.ts
- src/app/project-overview/create-resource-panel/template.html
- src/app/shared/entity/external-cluster.ts
- src/app/shared/entity/provider/aks.ts
- src/app/shared/types/error-type.ts
This feature allows to Create External Cluster of type AKS provider from UI. This feature is accessible under Clusters and navigating to External Clusters tab.
**Select Provider:**
**Credentials:**
**Cluster Details Step:**
Fixes #4569 
**Important:**
Currently, When you will try to create AKS cluster UI hangs as Backend is not responding status but external is created to cloud provider and issue is on KKP side where POD fails to return status to Frontend that needs to be investigated and figured out.
However once you press **Create External Cluster** button you can come back to 
- "Import" external cluster dialog 
- Select AKS external. Provider
- Select Preset
- You will …
> Create External Cluster AKS

- src/app/core/services/wizard/provider/openstack.ts
- src/app/shared/components/cluster-summary/template.html
- src/app/shared/entity/cluster.ts
- src/app/shared/entity/provider/openstack.ts
- src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts
- src/app/wizard/step/provider-settings/provider/extended/openstack/application/template.html
- src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
- src/app/wizard/step/provider-settings/provider/extended/openstack/default/template.html
- src/app/wizard/step/provider-settings/provider/extended/openstack/shared/types/ip-version.ts
- src/app/wizard/step/provider-settings/provider/extended/openstack/shared/types/state.ts
- src/test/data/cluster.ts
Add IPv6 subnet ID and IPv6 subnet pool for OpenStack cluster provider.
Fixes #4469 
```release-note
Add IPv6 subnet ID and IPv6 subnet pool for OpenStack cluster provider.
```
> Add IPv6 subnet ID and IPv6 subnet pool for OpenStack cluster provider

- README.md
- src/app/cluster/details/cluster/component.ts
- src/app/cluster/details/cluster/template.html
- src/app/core/services/feature-gate.ts
- src/app/node-data/component.ts
- src/app/wizard/step/cluster/component.ts
- src/app/wizard/step/cluster/template.html
This PR does the following things:
- Enable Operating System Manager by default in the `Cluster Settings` step in the cluster creation wizard.
- Remove usage of the `experimental` keyword with OSM
- Display health status for OSM and Kubernetes dashboard on cluster summary page.
- Some other fixes
Fixes #
```release-note
Operating System Manager is enabled by default for new clusters.
```
> Enable OSM by default

- src/app/cluster/details/external-cluster/component.ts
- src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/component.ts
- src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/style.scss
- src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html
- src/app/cluster/details/external-cluster/template.html
- src/app/cluster/list/external-cluster/component.ts
- src/app/cluster/list/external-cluster/template.html
- src/app/cluster/module.ts
- src/app/core/services/cluster.ts
- src/app/core/services/external-cluster.ts
- src/app/shared/entity/external-cluster.ts
This PR adds functionality to delete external cluster(AKS/EKS/GKE) from cloud provider
- Delete external cluster
https://user-images.githubusercontent.com/17727069/179901663-d9e02537-6c1d-421c-9883-373c1b11acef.mp4
- When no **nodegroups** are attached user can't delete the external cluster unitl nodegroups are removed and just warning is shown to notify to user.
Fixes #4627 
- Adds code improvement by moving `Disconnect` functionality  
**Notes:**
[Allows user to delete External Cluster from the Cloud Provider #10330](https://github.com/kubermatic/kubermatic/pull/10330)
> By default the cluster will `Disconnect` which means the KKP cluster object will be deleted cluster …
> Delete external cluster from the cloud provider

- hack/e2e/run-tests.sh
It's time to migrate to yq4. See https://mikefarah.gitbook.io/yq/upgrading-from-v3 for more information.
I chose to make it explicit what version we're using for now, in order to slowly get rid of yq3 over the next few PRs. It is a bit annoying that devs would need a  `yq4` binary on their machines, but I suspect many have v3 and v4 around, like I do.
I have no idea why exactly we had to YAML-to-JSON the kubeconfig, and also why it should not have been encoded. So I simply removed `yq` here alltogether.
Fixes #
```release-note
NONE
```
> migrate to yq4

- src/app/cluster/details/external-cluster/template.html
- src/app/cluster/list/external-cluster/template.html
This PR doesn't show `delete` icon  when cluster is `imported`:
- on List page
- on Details page
https://user-images.githubusercontent.com/17727069/180807427-59936c98-4137-44b5-93c9-e04fecfd31a9.mp4
Fixes #
```txt
{
"isImported": "true" || "false"
"project-id": "jgm2x2q9rc"
}
```
Since `string` value is returned from Backend so had to implicit check of string on UI
```release-note
NONE
```
> Remove delete functionality for imported cluster

- src/app/cluster/list/cluster/component.ts
On the list cluster view, we keep polling for machine deployments even if the cluster is marked for deletion. This is just a wasteful API call that results in an undesired error message.
Fixes #
```release-note
NONE
```
> Skip polling for machine deployments when cluster is marked for deletion

- src/app/cluster/details/cluster/node-list/template.html
- src/app/node-data/basic/provider/kubevirt/component.ts
- src/app/node-data/basic/provider/kubevirt/template.html
- src/app/shared/components/chip-list/component.ts
- src/app/shared/components/cluster-summary/template.html
- src/app/shared/entity/node.ts
- src/app/shared/entity/provider/kubevirt.ts
Configure pod affinity/anti-affinity and node affinity preset settings for KubeVirt provider.
Fixes #4433 
```release-note
Configure pod affinity/anti-affinity and node affinity preset settings for KubeVirt provider.
```
> Configure pod affinity/anti-affinity and node affinity preset settings

- src/app/core/services/cluster-spec.ts
- src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts
Instead of adding a kubevirt specific check in `cluster-spec` service, its better to set `preAllocatedDataVolumes` directly in cluster spec object.
Fixes #
```release-note
NONE
```
> Remove kubevirt specific check in Cluster Spec service

- src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts
Use `Gi` unit for pre-allocated data volume disk size
Fixes #
```release-note
NONE
```
> Use `Gi` unit for pre-allocated data volume disk size

- src/app/shared/components/save-cluster-template/component.ts
- src/app/shared/components/save-cluster-template/template.html
This PR adds regex to allow name to contain alphanumeric characters and dashes.
https://user-images.githubusercontent.com/17727069/181500794-b0f280ec-3b31-47b0-8ac0-57dcaa08be54.mp4
Fixes #4477 
```release-note
NONE
```
> Add regex to allow cluster template name to only contain alphanumeric characters and dashes

- src/app/node-data/basic/provider/kubevirt/component.ts
- src/app/shared/components/combobox/component.ts
This PR fixes 2 issues:
1. When removing secondary disks from initial nodes step in wizard, value was not being updated in `nodeData`.
2. Secondary Disks were not shown in edit machine deployment dialog.
Fixes #4721 
```release-note
Display configured secondary disks in edit machine deployment dialog.
```
> Incorrect number of secondary disks

- src/app/cluster/details/cluster/component.ts
- src/app/cluster/details/cluster/edit-cluster/component.ts
- src/app/cluster/details/cluster/edit-cluster/template.html
- src/app/cluster/details/cluster/template.html
- src/app/shared/components/cluster-summary/template.html
- src/app/shared/entity/cluster.ts
- src/app/wizard/step/cluster/component.ts
- src/app/wizard/step/cluster/template.html
Fixes #4391
```release-note
Support for disabling kubernetes-dashboard for user clusters
```
> Support for disabling kubernetes-dashboard for user clusters

- src/app/core/services/project.ts
- src/app/project-overview/component.ts
- src/app/project-overview/members-overview/component.ts
- src/app/project-overview/members-overview/template.html
- src/app/project-overview/template.html
**role:** Editor/Viewer 
**role:** Owner:
Fixes #4723 
```release-note
Display owners only when group project binding has role editors/viewers.
```
> Hide members and prevent API call when ownership is other than `owner`

- src/app/node-data/basic/provider/kubevirt/component.ts
- src/app/node-data/basic/provider/kubevirt/style.scss
- src/app/node-data/basic/provider/kubevirt/template.html
- src/app/wizard/step/provider-settings/provider/basic/kubevirt/template.html
This PR adds following UI improvements for KubeVirt provider:
1. 
2. 
3. When VM Flavor is selected then CPUs and Memory of selected flavor are displayed instead of empty fields:
https://user-images.githubusercontent.com/13975988/181762019-37ee7886-ec64-4a90-a7f3-d4921b53ea03.mov
Fixes #4500 
```release-note
NONE
```
> KubeVirt UI improvements

- src/app/cluster/details/external-cluster/component.ts
- src/app/cluster/details/external-cluster/template.html
add extra detail for external cluster specification in the external cluster page
Fixes #4673 
```release-note
add extra detail in external cluster page
```
> Extend external cluster specification 

- src/app/core/services/feature-gate.ts
- src/app/settings/admin/interface/component.ts
- src/app/settings/admin/interface/template.html
Disable OIDC Kubeconfig setting if `oidcKubeCfgEndpoint` feature gates is disabled.
Fixes #4193 
```release-note
Disable OIDC Kubeconfig setting if feature gates is disabled.
```
> Disable OIDC kubeconfig if feature gates is disabled

- src/app/cluster/details/cluster/component.ts
- src/app/cluster/details/cluster/template.html
Remove condition for hiding Share button if `enableOIDCKubeconfig` setting is enabled and display Share button regardless of `enableOIDCKubeconfig` setting value.
Fixes #4762 
```release-note
Display share kubeconfig button even if OIDC Kubeconfig setting is enabled.
```
> Display Share Kubeconfig button even if OIDC Kubeconfig setting is enabled

- cypress/integration/v2/stories/admin-settings/defaults.spec.ts
Fixes #
```release-note
NONE
```
> Remove share kubeconfig button checks from e2e tests

- src/app/cluster/details/external-cluster/component.ts
- src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
- src/app/core/services/external-cluster.ts
- src/app/core/services/external-machine-deployment.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
- src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
- src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/gke/style.scss
- src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
- src/app/node-data/basic/provider/kubevirt/template.html
display all the available k8s versions in drop down list when creating new external Cluster.
Fixes #4741
```release-note
add k8s versions drop down list when creating new external Cluster
```
> Add kubernetes versions list in create external cluster 

- src/app/dynamic/enterprise/quotas/quota-widget/style.scss
- src/app/dynamic/enterprise/quotas/quota-widget/template.html
- src/assets/css/global/_main.scss
Fixes incorrect width of quota widget progress bars on small screens
> Before 
> After
Fixes #4750
```release-note
NONE
```
> Fixed quota-widget width on extended view

- src/app/node-data/component.ts
- src/app/node-data/template.html
- src/app/shared/entity/operating-system-profile.ts
OperatingSystemProfiles should be filtered based on supported operating system and cloud provider.
Fixes #
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Filter OperatingSystemProfiles before listing them

- src/app/cluster/details/cluster/edit-cluster/component.ts
- src/app/cluster/details/cluster/edit-cluster/template.html
- src/app/shared/components/event-rate-limit/component.ts
Values for `Event rate limit` plugin were not being displayed properly on the edit cluster modal. This bug was there because the values were not being propagated to the `km-wizard-cluster-event-rate-limit` component.
Fixes #4789
/kind bug
```release-note
Fix a bug where the edit cluster view was not loading the correct configuration for the event rate limit plugin.
```
```documentation
NONE
```
> Fix for edit event rate limit

- src/app/cluster/details/cluster/edit-cluster/component.ts
With https://github.com/kubermatic/dashboard/pull/4442 we changed the behavior of how form changes are synced with the DTOs. As a side effect, in the edit cluster view we were now setting the `spec.eventRateLimitConfig` unconditionally which was incorrect.
This PR ensures that we only propagate those values when the plugin `EventRateLimit` is enabled.
Fixes #4806
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Check if plugin is enabled before consuming the event rate limit config

- src/app/shared/entity/provider/gcp.ts
- src/app/wizard/step/provider-settings/provider/basic/gcp/component.ts
- src/app/wizard/step/provider-settings/provider/extended/gcp/component.ts
- src/app/wizard/step/provider-settings/provider/extended/gcp/template.html
In GCP, when dual-stack network is selected:
1. Mark Network and Subnetwork as required.
2. Only display dual-stack subnetworks.
Fixes #4679 
/kind feature
```release-note
GCP Network and Subnetwork are required when dual-stack network is selected.
```
```documentation
NONE
```
> Improve GCP dual stack usability

- hack/e2e/setup-kubermatic-in-kind.sh
This PR ensures that the dashboard can deal with an unenoded, cleartext kubeconfig, which is what we want to keep in Vault in the future. The same applies for the GCP ServiceAccount.
/kind cleanup
```release-note
NONE
```
> prepare for kubevirt kubeconfig fixes

- src/app/cluster/details/external-cluster/component.ts
- src/app/cluster/details/external-cluster/template.html
- src/app/cluster/list/external-cluster/template.html
since in the custom external cluster we  don't provide the feature for adding MD in this pr we hide the add MD button for custom external cluster  
Fixes #4745
/kind cleanup
```release-note
NONE
```
> Hide add MD button in custom external cluster details page

- src/app/settings/admin/bucket-settings/destinations/edit-credentials-dialog/template.html
Reverse order of fields in backup credentials dialog.
Fixes #4775 
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Reverse order of fields in backup credentials dialog

- src/app/cluster/details/cluster/machine-deployment-details/template.html
- src/app/cluster/details/cluster/node-list/template.html
- src/app/core/services/node.ts
- src/app/node-data/basic/provider/nutanix/component.ts
- src/app/node-data/basic/provider/openstack/component.ts
- src/app/node-data/basic/provider/vsphere/component.ts
- src/app/node-data/component.ts
- src/app/node-data/template.html
- src/app/shared/components/cluster-summary/template.html
- src/app/shared/entity/datacenter.ts
- src/app/shared/entity/node.ts
- src/app/shared/model/NodeProviderConstants.ts
- src/assets/css/_images.scss
It seems that rockylinux was renamed into rockyLinux which has messed up couple of properties in the api and in the OSSpec. For example matching the name with operating system name doesn't work, which leads to failures when trying to pick a template for rockylinux in vsphere for example. Same thing will happen to KubeVirt, Openstack and Bare metal provisioning in the future. This PR reverts back rockylinux to it's original name. 
Fixes #
/kind bug
```release-note
None
```
```documentation
None
```
> Rename rockylinux in the correct format

- src/app/node-data/basic/provider/kubevirt/component.ts
Make KubeVirt pod affinity/anti-affinity preset settings mutually exclusive so if only one of them can be configured.
Fixes #4793 
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Make KubeVirt affinity settings mutually exclusive

- src/app/cluster/details/cluster/edit-cluster/component.ts
- src/app/core/services/project.ts
- src/app/dynamic/enterprise/quotas/project-quota-dialog/component.spec.ts
- src/app/dynamic/enterprise/quotas/project-quota-dialog/component.ts
- src/app/dynamic/enterprise/quotas/project-quota-dialog/style.scss
- src/app/dynamic/enterprise/quotas/project-quota-dialog/template.html
- src/app/dynamic/enterprise/quotas/quota-widget/template.html
- src/app/project/edit-project/component.ts
- src/app/shared/components/add-project-dialog/component.ts
- src/app/shared/components/number-stepper/component.ts
- src/app/shared/components/number-stepper/template.html
- src/app/shared/validators/async-label-form.validator.ts
- src/app/shared/validators/async.validators.ts
- src/app/wizard/step/cluster/component.ts
- src/assets/css/global/_main.scss
- src/assets/css/global/_theme.scss
While in `edit mode`:
- Project name is moved to the top
- submit button will stay disabled when quotas are unchanged
Select component is replaced with a typeahead 
Issues with number inputs are fixed
Units added to quota widget on hover
Fixed background colour of yellow progress bar
Fixes #4740
/kind bug
/kind design
```documentation
NONE
```
```release-note
NONE
```
> Issues with resource quotas

- src/app/dynamic/enterprise/metering/service/metering.ts
Fixes a bug where raw data was mistakenly shown as reports.
The scheduleName effectively acts as a prefix filter, therefore we can use it and set the prefix for legacy reports.
Fixes #4807
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Add legacy report prefix to not show raw data csv files

- src/app/wizard/step/cluster/template.html
Add technology preview hint for dual-stack networking
Fixes #4853 
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Add technology preview hint for dual-stack networking

- src/app/dynamic/enterprise/quotas/quota-widget/template.html
Use flex layout to display project quota details.
**Before**
**After**
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Use flex layout to display project quota details

- src/app/cluster/details/external-cluster/external-node-list/component.ts
- src/app/cluster/details/external-cluster/template.html
This PR fixes to display "no nodes available" when nodes list is empty but it was showing `loading` icon.
**Before:**
(Cluster was running && Nodes were empty)
**After:**
**Case-1:**
(Cluster was running && Nodes were empty)
**Case-2:**
(Cluster was running && Nodes list):
https://user-images.githubusercontent.com/17727069/185710814-21bf6813-b9e5-4c28-87e4-ab2668d84cf6.mp4
Fixes #4744 
/kind bug
Issue was `isClusterRunning` was not passed in case of **MD details** page. Although cluster was in running state. Instead of passing cluster **state** from parent in details page NOW state is checked inside nodes list as we are already passing external …
> Fix issue to display empty placeholder in case no nodes exists

- src/app/cluster-template/component.ts
- src/app/cluster-template/template.html
- src/app/project-overview/create-resource-panel/component.ts
- src/app/project-overview/create-resource-panel/template.html
When user only has view-only permission of a project, we need to disable options of `Create Resource` button and disable the `Create Cluster Template` button.
Fixes #4882
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Disabled buttons in project view when user only has view-only permission

- src/app/dynamic/enterprise/metering/config/config-dialog/component.ts
- src/app/dynamic/enterprise/metering/config/config-dialog/template.html
- src/app/dynamic/enterprise/metering/schedule-config/add-dialog/component.ts
- src/app/dynamic/enterprise/metering/schedule-config/add-dialog/template.html
- src/app/settings/admin/presets/dialog/steps/preset/component.ts
Instead of relying on the API requests to fail, we should explicitly validate resource names at the front-end side as well for early failure.
Fixes #
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Add resource name validations where applicable

- src/app/dynamic/enterprise/quotas/service.ts
From the REST API perspective this should be PUT hence we decided to replace PATCH with PUT in the backend. At the moment PATCH and PUT points to the same logic under the hood so it should be safe to update the Dashboard.
/kind bug
Depends on https://github.com/kubermatic/kubermatic/pull/10857 
```release-note
NONE
```
> Replace quota update PATCH with PUT

- src/app/settings/user/style.scss
- src/app/settings/user/template.html
- src/app/shared/entity/member.ts
As for today the only way to check OIDC groups assigned to user is to decode JWT token. This PR adds simple list of decoded OIDC groups to user settings view.
Fixes #4711 
/kind feature
```release-note
NONE
```
```documentation
https://github.com/kubermatic/docs/blob/master/content/kubermatic/master/architecture/role-based-access-control/groups-support/_index.en.md
```
> Display OIDC groups in user settings

- src/app/shared/components/event-rate-limit/template.html
This fix layout of wizard and dialog when "Event Rate" plugin
**Cluster creation wizard:**
https://user-images.githubusercontent.com/17727069/188080335-54af8f56-a4e7-4437-8c36-6d9a18a2f617.mp4
**Edit Cluster Dialog**
Fixes #4896 
/kind design
2 column layout was approve by @cschieder. As per video at some breakpoint layout expands to full width that is something not related to specifically this PR change. It is more sort of how page elements are Semantically structured without proper classes IMO, therefore we can look it how to fix semantics of page in sep PR.
**Does this PR introduce a user-facing …
> Fix layout on edit/create cluster when Event Rate plugin is selected

- src/app/core/services/external-cluster.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
- src/app/external-cluster-wizard/template.html
- src/app/shared/components/external-cluster-credentials/provider/aks/component.ts
- src/app/shared/components/external-cluster-credentials/provider/eks/component.ts
- src/app/shared/components/external-cluster-credentials/provider/eks/template.html
- src/app/shared/components/external-cluster-credentials/provider/gke/component.ts
Signed-off-by: khizerrehan <khizerrehan92@gmail.com>**What this PR does / why we need it**:
This PR allows to change `Region` irrespective of Preset or Credentials are added.
**Create Wizard:**
Allows functionality to change region and fetch VPCs based on region selected.
https://user-images.githubusercontent.com/17727069/187850914-82368991-3afb-420e-a760-a5d565a51549.mp4
**Import Wizard:**
Allows functionality to change region in order to list cluster based on that region. 
https://user-images.githubusercontent.com/17727069/187850677-790be252-fb5f-4119-a73e-05634dcec087.mp4
Fixes: #4915 
[Backend PR](https://github.com/kubermatic/kubermatic/pull/10888)
Fixes #
/kind cleanup
/kind design …
> Allow to change region for EKS external cluster on Import dialog and Create wizard

- src/app/cluster/details/external-cluster/component.ts
- src/app/cluster/details/external-cluster/template.html
add primary label for imported external clusters in the cluster page  
Fixes #4918
/kind design
```release-note
NONE
```
```documentation
NONE
```
> add imported label for external cluster

- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
- src/app/shared/entity/provider/aks.ts
Signed-off-by: khizerrehan <khizerrehan92@gmail.com>**What this PR does / why we need it**:
This PR updates payload for aks cluster spec and cloud spec while creating external cluster of AKS type.
Fixes #4933 
This PR doesn't introduces any special change but now `location` is part of `cloud` instead of `cluster` spec
```release-note
None
```
```documentation
None
```
> Move location to aks cloud spec instead of cluster spec

- src/app/cluster/details/external-cluster/template.html
- src/app/core/services/external-cluster.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
- src/app/shared/components/combobox/template.html
- src/app/shared/entity/provider/aks.ts
Signed-off-by: khizerrehan <khizerrehan92@gmail.com>**What this PR does / why we need it**:
This PR integrates new endpoint to fetch resource groups list and show them in dropdown. Instead of user typing Resource group now it can be selected from dropdown.
**Minor fixes:**
- Display of location on details page from cloud instead of cluster spec
- Add support for hint as content projection inside shared component.
Fixes #4950
/kind design
```release-note
None
```
```documentation
None
```
> Add Resource Group list dropdown for AKS 

- src/app/core/services/external-cluster.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
- src/app/shared/entity/provider/eks.ts
add an endpoint for listing the service roleArn list for EKS cluster creation wizard 
Fixes #4949
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Add ClusterServiceRole dropdown list for EKS

- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
Fixed logic AKS form,
The user can now increment and decrement the `Count` control when `Enable Autoscaling` is not selected.
Fixes #4955
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Count value in AKS cannot be incremented if Auto Scaling is disabled

- .github/dependabot.yml
As discussed with `sig-ui`, there is no value in assigning this PR to the SIG members by default. 
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Remove default assignees for Dependabot PRs

- src/app/node-data/component.ts
Packet was re-branded to Equnix Metal in machine-controller. Although those changes were not propagated in our API or Dashboard. OSPs use `equinixmetal` instead of `packet` and it leads to a conflict when listing OSPs on the front-end.
This PR adds a special case for listing OSPs for Equinix Metal.
Fixes #
/kind bug
```release-note
Fix for listing Operating System Profiles for Equinix Metal
```
```documentation
NONE
```
> Fix for listing Operating System Profiles for Equinix Metal

- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
- src/app/shared/validators/base-form.validator.ts
It fixes the external cluster wizard when a user goes back and re-selects preset.
Fixes #4940
/kind bug
```release-note
The cluster details step form will be filled with default values when the user re-selects preset/credentials
```
```documentation
NONE
```
> Default values are not shown in external cluster wizard when preset/credentials are cleared and selected again

- src/app/external-cluster-wizard/component.ts
- src/app/external-cluster-wizard/template.html
Fix check to disable `Next` and `Create External Cluster` buttons in external cluster wizard.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix check to disable action buttons in external cluster wizard

- .prow/build-image.yaml
- .prow/tests-e2e.yaml
- .prow/tests-unit.yaml
- .prow/verify.yaml
- containers/chrome-headless/Dockerfile
- containers/chrome-headless/release.sh
- containers/custom-dashboard/Dockerfile
KKP has [moved to Go 1.19](https://github.com/kubermatic/kubermatic/pull/10665), so let's follow suite.
/kind chore
```release-note
NONE
```
> update to Go 1.19

- src/app/cluster/details/cluster/edit-cluster/component.ts
- src/app/cluster/details/cluster/edit-cluster/template.html
- src/app/shared/components/label-form/component.spec.ts
- src/app/shared/components/label-form/component.ts
- src/app/shared/components/label-form/template.html
- src/app/shared/types/common.ts
- src/app/shared/utils/cluster.ts
- src/app/wizard/step/cluster/component.ts
- src/app/wizard/step/cluster/template.html
- src/assets/css/_variables.scss
Enforces the labels of `clusterDefaultNodeSelector` namespace
Fixes #4985
/kind feature
```release-note
PodNodeSelector admission plugin: node labels with clusterDefaultNodeSelector namespace are enforced
```
```documentation
NONE
```
> PodNodeSelector admission plugin: enforce node labels with clusterDefaultNodeSelector

- src/app/cluster/details/cluster/template.html
- src/app/cluster/details/external-cluster/template.html
Disable delete cluster button if cluster is being deleted.
Fixes #4959 
/kind design
```release-note
Delete button on cluster details page is disabled if cluster is being deleted.
```
```documentation
NONE
```
> Disable delete cluster button if cluster is being deleted

- src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/component.ts
- src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/template.html
- src/app/shared/entity/provider/aks.ts
add column `Location` to AKS import dialog to show the cluster location and send it in the payload for the import endpoint  
Fixes #5039
/kind feature
-->
```release-note
NONE
```
```documentation
NONE
```
> Add  location to import aks external cluster

- src/app/cluster/details/external-cluster/component.ts
- src/app/cluster/details/external-cluster/template.html
- src/app/cluster/list/external-cluster/component.ts
- src/app/cluster/list/external-cluster/template.html
- src/app/shared/entity/external-cluster.ts
Hide delete button for external clusters which are deleted (e.g. from provider side) or do not exist.
Fixes #4959 
/kind bug
```release-note
Delete button is not shown for external clusters which are already deleted.
```
```documentation
NONE
```
> Hide delete button for already deleted external clusters

- src/app/core/services/external-cluster.ts
Fixed issue in external cluster EKS credential step where not selecting `provider preset`, entering `Access Key ID` and `Secret Access Key` and then changing regions was causing no `vpcs` API request.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> External cluster wizard: fixed EKS region changes subscription

- src/app/core/services/external-cluster.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
Fixed bug in external cluster AKS wizard, where changing the credentials preset was not updating `Kubernetes version`, `locations` and `resource groups` API calls.
- No Ticket exists
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> External cluster wizard: fixed AKS preset change bug

- Makefile
- package-lock.json
- package.json
Bumps the version to v2.20.8 so we can release an out-of-band set of patches for KKP.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.20] Bump version to 2.20.8

- src/app/node-data/component.ts
- src/app/shared/entity/datacenter.ts
Support for consuming default OperatingSystemProfiles from the seed specification, if specified.
Fixes #5053
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Use default OperatingSystemProfile values from datacenter

- .prow/tests-e2e.yaml
- src/app/cluster/details/cluster/share-kubeconfig/template.html
- src/app/project/template.html
- src/app/settings/admin/interface/template.html
- src/app/settings/user/template.html
- src/app/shared/components/addon-list/install-addon-dialog/template.html
- src/app/shared/components/addon-list/template.html
- src/app/shared/components/application-list/add-application-dialog/template.html
- src/app/shared/components/application-list/template.html
- src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html
This is required because KKP followed with renaming the default branch to `main` via https://github.com/kubermatic/kubermatic/pull/11206.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> adopt to kubermatic repo main branch renaming

- src/app/shared/components/add-external-cluster-dialog/component.ts
- src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/component.ts
- src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/eks/component.ts
- src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/gke/component.ts
- src/app/shared/components/add-external-cluster-dialog/style.scss
- src/app/shared/components/add-external-cluster-dialog/template.html
add a `Back` button in the import external cluster dialog so the user can navigate through the dialog steps
Fixes #4910
/kind design
```release-note
Add a Back button in the import external cluster dialog.
```
```documentation
NONE
```
> add Back button to the Import external cluster dialog

- Dockerfile
- Makefile
This PR fixes the Dockerimage to have a proper default command (for now, in the future we should not rely on this) and also pushes the Docker image to the correct repository.
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> fix docker repo name, fix default command in docker image

- hack/ci/download-gocache.sh
- hack/ci/upload-gocache.sh
This adds the missing scripts to deal with the gocache.
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> fix gocache handling

- certs/OWNERS
- cmd/dashboard/OWNERS
- containers/OWNERS
- cypress/OWNERS
- fixtures/OWNERS
- pkg/OWNERS
- src/OWNERS
Sets up the OWNERS file for sig-api and sig-ui to differentiate areas of responsibility
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Set sig-api and sig-ui OWNERS accordingly

- pkg/handler/routes_v1_websocket.go
- pkg/handler/websocket/terminal.go
This PR:
- Adds network policy to allow only egress to k8s api server from the web terminal pod.
- Extends the web terminal endpoint to implement pod expiration message/refresh.
- Adds cleanup job for user web terminal temporary k8s resources.
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Web terminal: expiration implementation + security improvements + cleanup job for temporary resources

- src/app/cluster/list/external-cluster/component.ts
- src/app/cluster/list/external-cluster/template.html
- src/app/dynamic/enterprise/quotas/quota-widget/component.ts
- src/app/dynamic/enterprise/quotas/quota-widget/style.scss
- src/app/dynamic/enterprise/quotas/quota-widget/template.html
- src/app/external-cluster-wizard/routing.ts
- src/app/external-cluster-wizard/steps/external-cluster/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
- src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
- src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
- src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
- src/app/external-cluster-wizard/steps/external-cluster/template.html
- src/app/external-cluster-wizard/template.html
- src/app/shared/components/add-external-cluster-dialog/component.ts
- src/app/shared/components/add-external-cluster-dialog/steps/cluster/component.ts
- src/app/shared/components/add-external-cluster-dialog/steps/cluster/style.scss
- src/app/shared/components/add-external-cluster-dialog/steps/cluster/template.html
- src/app/shared/components/add-external-cluster-dialog/template.html
Added quota widget to external cluster pages (list, wizard and import cluster)
Fixes #5078
As external clusters are currently not affected by quotas, so instead of the actual quota widget `Does not apply to external cluster` is shown 
```release-note
The quota widget is shown on the external cluster list, wizard, and import dialog
```
```documentation
NONE
```
> Quota Information Presence for External Clusters

- .husky/pre-commit
- .husky/pre-push
We only need to run pre-commit or pre-push hooks when there is some change in `/src, /cypress or package.json`.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Refactor husky pre-commit and pre-push hooks

- .prow/tests-e2e.yaml
- hack/ci/setup-kubermatic-in-kind.sh
- hack/ci/testdata/kubermatic.yaml
- hack/e2e/setup-kind-cluster.sh
Now that https://github.com/kubermatic/kubermatic/pull/11229 is merged we can get rid of the hack to inject our Docker image for the API and just rely on the operator for us. :tada: 
I ran one test version first where I purposefully did not push the dashboard image into kind, in order to verify that the operator is indeed picking up our injected version. As expected, the prowjob failed: https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_dashboard/5167/pre-dashboard-api-e2e/1586437233034924032
I also removed the /scratch hack, which I introduced a long time ago but seemingly more modern kind versions are configured slightly differently. Since we do not use this tmpfs in kubermatic anymore, I figure it's not needed in …
> Use the operator's native support for a custom dashboard/api image

- pkg/handler/routes_v1_websocket.go
- pkg/test/e2e/api/settings_test.go
- pkg/test/e2e/utils/client.go
This PR disables the Web Terminal feature (backend side) if it's not enabled by configuration.
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Block Web Terminal access if the feature is not enabled

- .prow.yaml
E2E tests in `release/v2.20` branch have become too flaky so until those tests are fixed (#5104), marking them as `optional` should make patch release process a bit smoother.
Also, those E2E tests are ignored and are being rewritten since `2.21`.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Mark E2E tests as optional in release v2.20

- src/app/node-data/basic/provider/kubevirt/component.ts
- src/app/node-data/basic/provider/kubevirt/template.html
- src/app/shared/components/chip-list/template.html
- src/app/shared/validators/others.ts
- src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts
- src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html
- In the third step while creating a cluster while using the KubeVirt provider, `ADVANCED DISK CONFIGURATION` will be expanded by default.
- Info text under `ADVANCED DISK CONFIGURATION` will stay visible after the user clicks the `Add local Disk` button
- Validation is added to **Custom local disks** `name` and **ADVANCED SCHEDULING SETTINGS** `Node affinity preset values` inputs
Fixes #4715
```release-note
- While creating a cluster while using the KubeVirt provider, "ADVANCED DISK CONFIGURATION" will be expanded by default.
- Info text under "ADVANCED DISK …
```
> KubeVirt UI/UX improvements

- cmd/kubermatic-api/swagger.json
- pkg/api/v2/types.go
- pkg/handler/v2/networkdefaults/networkdefaults.go
- pkg/handler/v2/networkdefaults/networkdefaults_test.go
- pkg/handler/v2/networkdefaults/networkdefaults_unit_test.go
- pkg/handler/v2/routes_v2.go
- pkg/test/e2e/utils/apiclient/models/network_defaults.go
- pkg/validation/cluster.go
Signed-off-by: Sachin Tiptur <sachin@kubermatic.com>
This PR implements web hook validation  and default value for ExposeStrategy. This is required for feature [#11119](https://github.com/kubermatic/kubermatic/issues/11119)
Fixes #
/kind feature
This PR changes are part of Allowed API server source IP ranges feature. This has only validation and defaulting changes, other feature logic is part of Kubermatic repo.
```release-note
NONE
```
```documentation
NONE
```
> Add Support for ExposeStrategy in network defaults

- src/app/node-data/basic/provider/openstack/component.ts
Fixes a small bug where `serverGroup` field in initial machine deployment step(wizard) was being incorrectly initialized.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix for server group defaulting

- pkg/handler/websocket/terminal.go
https://github.com/kubermatic/kubermatic/pull/11286 built a new image with a more recent kubectl binary on board. This PR makes sure the dashboard is making use of that the image.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update web-terminal Docker image to 0.3

- pkg/api/v2/types.go
- pkg/provider/kubernetes/featuregates.go
We need to return `OpenIDAuthPlugin` feature gate in order to conditionally let the administrator enable or disable the kubernetes dashboard functionality.
Relates to #5220 
Swagger gen is broken at the moment, hence I did not attach it.
```release-note
NONE
```
```documentation
NONE
```
> Add OpenIDAuthPlugin feature gate to API

- cmd/kubermatic-api/main.go
- pkg/handler/middleware/middleware.go
- pkg/handler/v1/project/project.go
- pkg/handler/v2/preset/preset.go
- pkg/provider/kubernetes/etcdbackupconfig.go
- pkg/provider/kubernetes/etcdrestore.go
The problem this PR tries to fix is that when a particular Seed is misconfigured or not responding, the requests which need to go through the whole list of seeds and get its kubeconfigs and/or create some providers based on them fail because that Seed is broken. 
The new approach would be to ignore those Seeds, and just list (for example Clusters) from working Seeds. This enables the API/UI to still work, at least for the working Seeds. BUT on the other hand the issue is hidden now, and just appears in logs.
To make it clear to API/UI that some Seeds are broken and the results they are getting may not be complete, we will add a new Seed health endpoint, which will return information about Seed health. #5225
Fixes …
> Ignore broken seeds during API requests

- cmd/kubermatic-api/swagger.json
- hack/update-swagger.sh
- hack/verify-swagger.sh
- pkg/api/v2/types.go
- pkg/handler/v2/routes_v2.go
- pkg/handler/v2/seedoverview/seedoverview.go
- pkg/handler/v2/seedoverview/seedoverview_test.go
Admin seed details view.
Fixes [#9834](https://github.com/kubermatic/kubermatic/issues/9834)
/kind feature
```release-note
New admin api endpoint for fetching seed's details.
```
```documentation
TBD
```
> Seed overview API endpoint

- pkg/resources/machine/machinedeployment.go
Machine deployment for vSphere, contains the credentials for vcenter, written explicitly. This pr removes that overwriteCloudSpec field and rely only on the OSM configs 
Fixes https://github.com/kubermatic/kubermatic/issues/4974
/kind bug
```release-note
Remove the overwriteCloudSpec field from vSphere Machine Deployment 
```
```documentation
None
```
> Remove vSphere overwrite cloud spec from machine deployment

- .prow/frontend.yaml
Since full E2E jobs for dashboard are non-functional, we are disabling automated runs. Also, the integration tests should be mandatory and not optional.
The full E2E jobs will be brought back when https://github.com/kubermatic/dashboard/issues/4828 is fixed.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update configuration for E2E prow job

- hack/ci/setup-kubermatic-in-kind.sh
- hack/lib.sh
This is to make the dashboard API tests more reliable. Instead of following KKP and breaking everytime a change is made over there, we now deduce the KKP version based on what we have in our go.mod. With a bit of Github hackery we can translate Go's pseudo version into the full Git commit hash.
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Use the same version for the KKP installer as is pinned in go.mod

- modules/web/src/app/cluster/details/cluster/machine-deployment-details/template.html
- modules/web/src/app/core/services/node-data/provider/nutanix.ts
- modules/web/src/app/core/services/provider/nutanix.ts
- modules/web/src/app/core/services/wizard/provider/nutanix.ts
- modules/web/src/app/node-data/basic/provider/nutanix/component.ts
- modules/web/src/app/node-data/basic/provider/nutanix/style.scss
- modules/web/src/app/node-data/basic/provider/nutanix/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
This PR adds support for configuring categories in Nutanix provider.
**Cluster Wizard:**
**Cluster Wizard Summary:**
**Edit Machine Deployment:**
**Machine Deployment Details:**
Fixes #4160 
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Add support for Nutanix categories

- modules/web/src/app/core/services/feature-gate.ts
- modules/web/src/app/settings/admin/interface/component.ts
- modules/web/src/app/settings/admin/interface/template.html
Logic to disable the `Enable Kubernetes Dashboard` checkbox in the `admin setting > interface` page based on `OIDCKubeCfgEndpoint` and `OpenIDAuthPlugin` feature gates 
Fixes #5220
/kind feature
```release-note
In the interface section of admin settings, Enable Kubernetes Dashboard checkbox will be disabled when either OIDCKubeCfgEndpoint or OpenIDAuthPlugin feature flags are disabled
```
```documentation
NONE
```
> Added logic disable "Enable Kubernetes Dashboard" checkbox

- modules/api/pkg/machine/convert.go
We don't want system categories we use to categorize KKP resources in Nutanix to be visible to end users. This hides the categories in our API response.
This is a follow-up to #5275.
Fixes #
/kind cleanup
```release-note
KKP specific Nutanix categories (`KKPProject` and `KKPCluster`) are hidden in API responses
```
```documentation
NONE
```
> Remove Nutanix system categories from api response

- modules/web/src/app/cluster/details/cluster/node-list/component.ts
- modules/web/src/app/cluster/details/cluster/node-list/template.html
- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
- modules/web/src/app/shared/components/cluster-summary/component.ts
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/shared/entity/provider/kubevirt.ts
Display instance type and preference category instead of `kind` on cluster summary and node list details page.
**Cluster Summary:**
**Node Details:**
Fixes #
/kind feature
```release-note
Display instance type and preference category instead of `kind` on cluster summary and node list details page.
```
```documentation
NONE
```
> Display instance type and preference category instead of kind

- modules/web/src/app/cluster/details/cluster/node-list/template.html
- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
- modules/web/src/app/node-data/basic/provider/kubevirt/template.html
- modules/web/src/app/node-data/basic/provider/kubevirt/topology-spread-contraint-form/component.ts
- modules/web/src/app/node-data/basic/provider/kubevirt/topology-spread-contraint-form/style.scss
- modules/web/src/app/node-data/basic/provider/kubevirt/topology-spread-contraint-form/template.html
- modules/web/src/app/node-data/module.ts
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/shared/components/number-stepper/component.ts
- modules/web/src/app/shared/components/number-stepper/style.scss
- modules/web/src/app/shared/components/number-stepper/template.html
- modules/web/src/app/shared/entity/node.ts
- modules/web/src/app/shared/entity/provider/kubevirt.ts
Remove Pod Affinity/Anti-affinity settings and add support to configure topology spread constraints in KubeVirt provider.
**Cluster Wizard:**
**Cluster Summary:**
**Node List Details:**
Fixes #5067 
/kind feature
```release-note
Remove Pod Affinity/Anti-affinity settings and add support to configure topology spread constraints in KubeVirt provider.
```
```documentation
TBD
```
> Add support to configure topology spread constraints in KubeVirt

- modules/web/src/app/cluster/details/cluster/machine-deployment-list/component.ts
- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss
- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
Replaced text `Does not apply to external/imported cluster` with `Does not apply to external/imported clusters` (added `s` in the end).
Added details on hover to the quota widget
Fixes #5265
/kind bug
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Mini Quota Follow Up

- modules/api/pkg/handler/common/cluster.go
- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/wizard/step/cluster/component.ts
This PR adds minor fixes to the Expose Strategy and API Server Allowed IP ranges configuration for the cluster.
Fixes #5310
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix: Expose strategy not being set properly

- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/api/v1/types.go
- modules/api/pkg/handler/test/helper.go
- modules/api/pkg/handler/v1/admin/settings_test.go
- modules/api/pkg/handler/v2/application_installation/application_installation_test.go
- modules/api/pkg/provider/cloud/kubevirt/provider.go
- modules/api/pkg/provider/kubernetes/credentials.go
- modules/api/pkg/validation/cluster.go
Following the split of the KubeVirt CSI driver deployment between tenant (user) and infra cluster (https://github.com/kubermatic/kubermatic/pull/11370), this PR contains the dashboard changes needed.
Fixes #5149 
/kind feature
- https://github.com/kubermatic/kubermatic/pull/11362 -> enableWebTerminal is now optional, adjusting the unit tests
- https://github.com/kubermatic/kubermatic/pull/11359 -> Application Version is now a string.
```release-note
KubeVirt: split CSI driver deployment between user and infra cluster. …
```
> KubeVirt split csi driver deployment

- modules/web/src/app/cluster/details/cluster/share-kubeconfig/component.ts
- modules/web/src/app/cluster/details/cluster/share-kubeconfig/template.html
- modules/web/src/app/project/component.ts
- modules/web/src/app/project/template.html
- modules/web/src/app/settings/admin/interface/component.ts
- modules/web/src/app/settings/admin/interface/template.html
- modules/web/src/app/settings/user/component.ts
- modules/web/src/app/settings/user/template.html
- modules/web/src/app/shared/components/addon-list/component.ts
- modules/web/src/app/shared/components/addon-list/install-addon-dialog/component.ts
- modules/web/src/app/shared/components/addon-list/install-addon-dialog/template.html
- modules/web/src/app/shared/components/addon-list/template.html
- modules/web/src/app/shared/components/application-list/add-application-dialog/component.ts
- modules/web/src/app/shared/components/application-list/add-application-dialog/template.html
- modules/web/src/app/shared/components/application-list/component.ts
- modules/web/src/app/shared/components/application-list/template.html
- modules/web/src/app/shared/utils/common.ts
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
- modules/web/src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts
- modules/web/src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html
This PR adds abiltity to to use KKP Version in links to navigate that matches the KKP version that is currently being used.
**Examples:**
https://user-images.githubusercontent.com/17727069/203507367-91a9882f-4654-441e-afa4-6ce2f4a45535.mp4
https://user-images.githubusercontent.com/17727069/203507799-aac7e1da-adbf-4cd6-978c-ebc72b41422d.mp4
Fixes #4912 
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Use KKP version in links

- modules/api/pkg/handler/v1/admin/settings_test.go
- modules/api/pkg/provider/kubernetes/settings.go
updates the default/initial KubermaticSetting to have the resource filter minCPU option set from 1 to 2. This is done because we would like to display nodes with higher resource values by default, as they are more likely to be able to run a valid cluster (for example when integrating a cluster with MLA or OPA, 2 CPUs are minimum, and that is just KKP deployed resources).
This setting affects just the API/UI, the /size endpoints and the UI section where node sizes are chosen, and can be changed by admins in the admin settings.
It wont affect existing installations, as its only applied to the initial KubermaticSetting.
Fixes #5332 
/kind cleanup
**Does …
> updated default resource filter minCPU from 1 to 2

- modules/api/pkg/api/v2/types.go
- modules/api/pkg/ee/resource-quota/handler.go
- modules/api/pkg/ee/resource-quota/handler_test.go
- modules/api/pkg/handler/v2/resource_quota/resourequota.go
- modules/api/pkg/handler/v2/resource_quota/wrappers_ce.go
- modules/api/pkg/handler/v2/resource_quota/wrappers_ee.go
- modules/api/pkg/handler/v2/routes_v2.go
Adds endpoint for resource quota calculation, based on the current project quota + the chose node from a provider.
Fixes #5313 
/kind feature
```release-note
[EE] Added an resource quota endpoint which given a provider node size and replica count, returns the calculation of what the projects resource quota usage would be and a message if the quota is exceeded.
`POST /api/v2/projects/{project_id}/quotacalculation`
```
```documentation
TBD
```
> Resource quota calculation

- modules/api/pkg/api/v1/types.go
- modules/api/pkg/api/v1/types_test.go
- modules/api/pkg/machine/convert.go
- modules/api/pkg/resources/machine/common.go
Small cleanup after sig/virtualization did agree that all MD will require a **manual** migration (migration doc will be written part of https://github.com/kubermatic/docs/issues/1261).
Any existing MD that contains:
- Flavor
- PodAffinity/AntiAffinity/Preset
**will have to be manually migrated.**
We can then clean the code for KubeVirt GA and remove the handling of those fields.
Fixes #5311 
/kind cleanup
```release-note
Action required: KubeVirt- Manual migration of existing MD …
```
> KubeVirt cleanup Flavor and instancetype

- modules/api/pkg/resources/machine/common.go
This is needed for the machine-controller to set the new cluster labels. (see [#10923](https://github.com/kubermatic/kubermatic/issues/10923))
Sister PR of kubermatic/kubermatic#11453
```release-note
NONE
```
```documentation
TBD
```
We have a draft document including all KubeVirt changes and a migration guide for KKP 2.22. That document will include the documentation for this feature.
> New field ClusterName in kubevirt providerconfig

- modules/api/pkg/api/v1/types.go
Update `apiserverallowedIPRanges` to `apiServerAllowedIPRanges` to fix a typo.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix typo in the apiserverallowedIPRanges field

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/test/data/cluster.ts
This PR handles both points to display already configured IP ranges in existing cluster and allows to edit and send update payload to configure new/updated IP ranges.
https://user-images.githubusercontent.com/17727069/204507288-aff596d4-b0db-4b87-b18e-33953d306add.mp4
Fixes #5338 
/kind chore
Update DCO can be found [here](https://developercertificate.org/) or see "CONTRIBUTING.md" file in repo to find link.
Hold till this [PR](https://github.com/kubermatic/dashboard/pull/5355) is merged: 
```release-note
NONE
```
```documentation
NONE
```
> Allow to edit Allowed IP Ranges for apiserver in existing cluster

- modules/web/.husky/pre-commit
- modules/web/.husky/pre-push
This PR ensures that husky pre-commit and pre-push hooks exit early if there are no changes made to `modules/web`
/kind chore
There is one caveat to the current solution: Let's assume you have branch that has commits in the `modules/web` folder. If you are now making a new commit which does not change the folder, it will still run the pre-commit hook. The reason for this is because it compares your current ref with main.
There is a really weird reason though why we need to compare with main: Running `git diff --quiet` on a branch that has only new files staged, fails because new files cannot be diffed against event if they just have been added
Here's a full example
```sh
❯ touch …
```
> limit husky to fe in pre-commit hook

- hack/lib.sh
- modules/api/go.mod
- modules/api/go.sum
- modules/api/hack/reconciling.yaml
- modules/api/hack/update-codegen.sh
- modules/api/pkg/ee/metering/handler.go
- modules/api/pkg/handler/common/provider/kubevirt.go
- modules/api/pkg/handler/v2/application_installation/application_installation.go
- modules/api/pkg/provider/kubernetes/cluster.go
- modules/api/pkg/provider/kubernetes/credentials.go
- modules/api/pkg/provider/kubernetes/external_cluster.go
- modules/api/pkg/provider/kubernetes/seed.go
- modules/api/pkg/resources/reconciling/zz_generated_reconcile.go
This brings in the new reconciler framework. To lessen the dependency on KKP, I made it so that the dashboard just generates its own reconciling functions for kubevirt stuff.
This PR also removes a bunch of unused code from the hack/lib.sh.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> bump KKP to bd4abe02b7de

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v1/types.go
- modules/api/pkg/handler/common/machine.go
- modules/api/pkg/handler/v1/node/node.go
- modules/api/pkg/handler/v2/machine/machine.go
- modules/api/pkg/handler/v2/machine/machine_test.go
- modules/api/pkg/resources/machine/machinedeployment.go
- modules/api/pkg/test/e2e/utils/apiclient/models/node_deployment_spec.go
Adds option to set cluster autoscaler min/max replicas on the MachineDeployments through the API. 
revival of https://github.com/kubermatic/kubermatic/pull/6596
Fixes #5347 
/kind feature
```release-note
TBD
```
```documentation
TBD
```
> Add option to set cluster autoscaler annotation on MD through API

- modules/web/src/app/core/services/node-data/service.ts
- modules/web/src/app/shared/components/save-cluster-template/component.ts
Add `minReplicas` and `maxReplicas` in cluster template node data, which was missed in https://github.com/kubermatic/dashboard/pull/5369.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Add autoscaling config in cluster template node data

- modules/api/pkg/test/e2e/utils/client.go
This endpoint timing out again and again is a major pain, so I would like to increase it to 30 seconds (by default, it should be ten as far as I understand). This will also be backported to release branches in `kubermatic/kubermatic` as the api test failing because of this tends to delay release work.
Fixes #
/kind cleanup
/kind flake
```release-note
NONE
```
```documentation
NONE
```
> Increase timeout for e2e test API call to fetch Azure sizes

- modules/web/angular.json
This PR contains removal of karma configuration from `angular.json` and setting default prefix for selector in case component/directive is generate via `ng cli`. 
Fixes #
This change was not catered in this PR:
[Use Jest instead of karma #1896](https://github.com/kubermatic/dashboard/pull/1896)
/kind cleanup
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Remove karma testing config from angular configuration

- modules/api/hack/ci/sync-apiclient.sh
With the move of the API from KKP to dashboard, the go client generation was removed from kkp post-submits job and not added to the dashboard repo (https://github.com/kubermatic/infra/pull/1937)
This PR adds the sync script in dashboard and a infra PR is also raised for the prow job (https://github.com/kubermatic/infra/pull/1999)
Fixes kubermatic/go-kubermatic#
```release-note
NONE
```
```documentation
NONE
```
> add sync-client

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
This PR fix edit cluster as in patch request by default "apiServerAllowedIPRanges" was send in payload even thought expose strategy was not LB(Load balance) + Code Clean to use existing method.
This bug was introduced in this [PR](https://github.com/kubermatic/dashboard/pull/5356/files#diff-4cde679d28715ceee620ba265cb68ce799fdda1401908486688da58bff1a6416R367)
Fixes #
/kind bug
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Fix bug apiServerAllowedIPRanges is allowed for LB expose strategy

- hack/lib.sh
Step by step...
fixing this one:
https://public-prow.loodse.com/view/gs/prow-dev-public-data/logs/post-dashboard-sync-client/1603672583847284736
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> add ensure_github_host_pubkey for sync-client

- modules/web/src/app/cluster/details/cluster/node-list/template.html
- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
- modules/web/src/app/node-data/basic/provider/kubevirt/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/shared/entity/node.ts
This PR removes secondary disk section from "Initial nodes" wizard step
Hides all usage:
- Cluster summary page
- Edit MD dialog to edit secondary disks
- MD details page under Nodes list expansion panel
Wizard Initial Nodes step:
Fixes #5396 
/kind cleanup
/kind chore
```release-note
Removes configuring of optional secondary disks to mount nodes
```
```documentation
TBD
```
> Hide KubeVirt's secondary disks wizard and view

- modules/web/src/app/node-data/basic/provider/aws/component.ts
Add `io2` and `gp3` to AWS provider disk types list.
Fixes #5448 
/kind feature
```release-note
Add `io2` and `gp3` to AWS provider disk types list.
```
```documentation
NONE
```
> Add `io2` and `gp3` to AWS provider disk types list

- modules/web/src/app/core/services/external-cluster.ts
Redirect to KubeOne clusters list page after disconnect.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Redirect to KubeOne clusters list page after disconnect

- modules/api/pkg/machine/convert.go
Fixes issue where old `packet` machine spec is not recoginized as the current `equinix` one.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> convert packet machine provider spec as equinix

- modules/web/src/app/kubeone-wizard/module.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/gcp/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/gcp/template.html
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
- modules/web/src/app/kubeone-wizard/steps/provider/component.ts
- modules/web/src/app/kubeone-wizard/steps/summary/template.html
- modules/web/src/app/shared/entity/kubeone-cluster.ts
- modules/web/src/app/wizard/step/cluster/template.html
Add support to import GCP KubeOne cluster.
**Provider Step:**
**Credentials Step:**
Fixes #5456 
/kind feature
```release-note
Add support to import GCP KubeOne cluster.
```
```documentation
NONE
```
> Add support to import GCP KubeOne cluster

- modules/web/src/app/kubeone-wizard/module.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/azure/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/azure/template.html
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
- modules/web/src/app/kubeone-wizard/steps/provider/component.ts
- modules/web/src/app/kubeone-wizard/steps/summary/template.html
- modules/web/src/app/shared/entity/kubeone-cluster.ts
Add support to import Azure KubeOne cluster.
**Provider Step:**
**Credentials Step:**
Fixes #5471 
/kind feature
```release-note
Add support to import Azure KubeOne cluster.
```
```documentation
TBD
```
> Add support to import Azure KubeOne cluster

- modules/api/pkg/resources/machine/common.go
- modules/api/pkg/resources/machine/common_test.go
There is another mistake in our new disk config handling code that slipped through in kubermatic/kubermatic#10816 and kubermatic/kubermatic#11050 - this fixes that.
When having a `MachineDeployment` in a user cluster with only the new `disks` attribute set, API panics due to a nil-pointer dereference.
/kind bug
This is the [promised](https://github.com/kubermatic/kubermatic/pull/11602) PR for the new location of this code - maybe wait with reviewing until the linked PR is approved and merged, I will keep the changes in sync.
```release-note
Fix API error in the extended disk configuration for provider …
```
> Anexia: fix panic when configuring Node Pool with new Disks attribute

- modules/api/pkg/handler/v2/cluster_default/cluster_default.go
- modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
With the recent change in cluster defaulting in the UI, we now always default to dual-stack address family, which is not exactly what we want - we still want to default to IPv4 for all new clusters:
This PR fixes the cluster's IP family to IPv4 in the cluster default endpoint, after the standard cluster defaulting logic is applied. As discussed with @Waseem826 it probably makes more sense to fix it in the endpoint than in the UI.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Default to IPv4 address family in the cluster default endpoint

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/core/services/feature-gate.ts
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
Remove `konnectivityService` feature gate and make Konnectivity always available.
Fixes #5513 
/kind feature
```release-note
Make Konnectivity generally available without feature gate.
```
```documentation
TBD
```
> Make Konnectivity generally available without feature gate

- modules/api/pkg/handler/v2/cluster_default/cluster_default.go
- modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
Dashboard is always sending `TunnelingAgentIP` to the backend no matter which expose strategy is used, which can lead to errors like `TunnelingAgentIP: Forbidden: Tunneling agent IP can be configured only for Tunneling Expose strategy`.
The PR makes sure the default cluster endpoint returns `TunnelingAgentIP` only when the Tunneling expose strategy is set.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Default TunnelingAgentIP only when Tunneling expose strategy is set

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/hack/run-api.sh
- modules/api/pkg/api/v2/types.go
- modules/api/pkg/handler/v2/feature_gates/feature_gates_test.go
- modules/api/pkg/provider/kubernetes/featuregates.go
- modules/api/pkg/test/e2e/utils/apiclient/models/feature_gates.go
`KonnectivityService` feature gate has been removed in https://github.com/kubermatic/kubermatic/pull/11643 & https://github.com/kubermatic/dashboard/pull/5520 , this PR removes the last references of it in the API code.
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Remove references to the KonnectivityService feature gate

- modules/api/pkg/handler/v2/external_cluster/external_cluster.go
- modules/api/pkg/handler/v2/external_cluster/kubeone.go
- modules/api/pkg/provider/kubernetes/credentials.go
**What this PR does / why we need it**: Add External Cluster label to KubeOne secrets
Introducing this change to make it easy to list KubeOne Secrets.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Add External Cluster label to KubeOne secrets

- modules/web/src/app/cluster/list/external-cluster/component.spec.ts
- modules/web/src/app/cluster/list/kubeone/component.ts
- modules/web/src/app/cluster/list/kubeone/template.html
- modules/web/src/app/core/module.ts
- modules/web/src/app/core/services/external-cluster.ts
- modules/web/src/app/core/services/kubeone-wizard/kubeone-presets.ts
- modules/web/src/app/kubeone-wizard/module.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/preset/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/preset/style.scss
- modules/web/src/app/kubeone-wizard/steps/credentials/preset/template.html
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/aws/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/azure/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/gcp/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/template.html
- modules/web/src/app/kubeone-wizard/steps/summary/component.ts
- modules/web/src/app/kubeone-wizard/steps/summary/template.html
Add support to select preset in credentials step of KubeOne wizard.
**AWS:**
**GCP:**
**Azure:**
Fixes #5502 
/kind feature
```release-note
Add support to select preset in credentials step of KubeOne wizard.
```
```documentation
NONE
```
> Add support to select preset in credentials step of KubeOne wizard

- modules/web/src/app/core/services/cluster.ts
Remove `shareReplay` operator for `health` API request to fix polling issue.
Fixes #
/kind bug
This change was introduced in #5464 but since we call `health` method inside `combineLatest` operator so this causes old observable to be returned every time due to `shareReplay` operator.
```release-note
NONE
```
```documentation
NONE
```
> Fix health API request polling issue

- modules/web/src/app/cluster/details/kubeone/component.ts
- modules/web/src/app/cluster/details/kubeone/edit-cluster-dialog/component.ts
- modules/web/src/app/cluster/details/kubeone/edit-cluster-dialog/template.html
- modules/web/src/app/cluster/details/kubeone/template.html
- modules/web/src/app/cluster/module.ts
- modules/web/src/app/shared/entity/external-cluster.ts
- modules/web/src/app/shared/entity/kubeone-cluster.ts
Add support to migrate KubeOne cluster container runtime from `docker` to `containerd`.
- A new `Migrate Container Runtime` menu option has been added which is only enabled when cluster container runtime is `docker`.
**Migrate Container Runtime Dialog:**
Fixes #5490 
/kind feature
```release-note
Add support to migrate KubeOne cluster container runtime.
```
```documentation
TBD
```
> Add support to migrate KubeOne cluster container runtime

- modules/web/src/app/core/services/wizard/wizard.ts
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/wizard/component.ts
**What this PR does / why we need it**
fix displaying steps for wizard in case change provider after choosing kubeadm provider
Fixes #5505 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Changing Provider after choosing Kubeadm Break the wizard

- modules/web/src/app/project-overview/component.ts
- modules/web/src/app/shared/model/Config.ts
- modules/web/src/assets/config/userGroupConfig.json
fix the premonitions errors for wrong role user for project overview and groups tabs**Which issue(s) this PR fixes**:
Fixes #5281
/kind bug
so else than the error for service account in the project over view page we have that error when we navigate to groups tab so in this PR we disable groups tab because it's not suppose to be active in editor and viewer role.
```release-note
NONE
```
```documentation
NONE
```
> update premmisions for service accounts and groups

- modules/api/pkg/ee/resource-quota/handler.go
- modules/api/pkg/ee/resource-quota/handler_test.go
Fixes some calculation bugs:
- Openstack calculation used G instead of M
- Handle Anexia deprecated DiskSize field, it seems that its still used
- Format quota exceeded message with line breaks 
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Some fixes for RQ calculation

- modules/web/src/app/cluster/details/kubeone/template.html
- modules/web/src/app/shared/components/combobox/style.scss
- modules/web/src/assets/css/material/_main.scss
align drop down list to the left and remove the horizontal scrollbar 
**create cluster from template**:
Fixes #5299
/kind design
```release-note
NONE
```
```documentation
NONE
```
> fix style for combobox component

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/provider/cloud/kubevirt/provider.go
- modules/api/pkg/provider/cloud/kubevirt/storage_class.go
- modules/api/pkg/provider/cloud/provider.go
- modules/api/pkg/test/e2e/utils/apiclient/models/kube_virt_infra_storage_class.go
- modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
Last part to switch the configuration of StorageClasses to be deployed in the user  (tenant) cluster from infra cluster StorageClass annotations to proper DC configuration.
Fixes kubermatic/kubermatic#11689
/kind feature
```release-note
KubeVirt switch StorageClass config from annotation to DataCenter.
```
```documentation
TBD
```
> KubeVirt switch StorageClass config from annotation to DC

- modules/web/src/app/project-overview/create-resource-panel/component.ts
- modules/web/src/app/project-overview/create-resource-panel/template.html
hide create external cluster in the create resources button when external cluster disabled in the admin panel **Which issue(s) this PR fixes**:
Fixes #5570
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> hide create external cluster in the create resources button when external cluster disabled in the admin panel 

- modules/web/src/app/shared/entity/external-cluster.ts
Add missing external cluster error states in `ExternalClusterState`.
Fixes #
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Add missing external cluster error states in `ExternalClusterState`

- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
- modules/web/src/app/node-data/component.ts
- modules/web/src/app/project/edit-project/template.html
- modules/web/src/app/shared/entity/node.ts
- modules/web/src/app/shared/entity/provider/kubevirt.ts
- modules/web/src/app/shared/entity/quota.ts
This PR adds live update to quota depending on user action on each provider
e.g:
- Update of Replica count
- Select Instance type or manually giving cpu and memory
**Wizard:**
- Instance Type Selection
https://user-images.githubusercontent.com/17727069/213595547-e96f7677-4436-4065-b692-a0d9d0737d52.mp4
- On User Input
https://user-images.githubusercontent.com/17727069/213595751-edb202d0-19fb-41c5-8a31-f89cab2527a5.mp4
- Add MD
https://user-images.githubusercontent.com/17727069/213599353-8544f9d1-1703-48a6-9c31-97f74dfb3ebe.mp4
Fixes #5571 
/kind feature
```release-note …
```
> Add live quota functionality for KubeVirt

- modules/api/pkg/handler/common/cluster.go
- modules/api/pkg/handler/v2/cluster_template/cluster_template.go
Propagate InitialCNIValuesRequestAnnotation from API to backend
Fixes #
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Propagate InitialCNIValuesRequestAnnotation to backend

- modules/web/src/app/core/services/cluster-spec.ts
- modules/web/src/app/dynamic/enterprise/quotas/template.html
- modules/web/src/app/project/edit-project/template.html
- modules/web/src/app/shared/entity/cluster.ts
- modules/web/src/app/wizard/component.ts
- modules/web/src/app/wizard/module.ts
- modules/web/src/app/wizard/step/cluster/cilium-application-values-dialog/component.ts
- modules/web/src/app/wizard/step/cluster/cilium-application-values-dialog/style.scss
- modules/web/src/app/wizard/step/cluster/cilium-application-values-dialog/template.html
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
Add functionality to edit initial values of Cilium application when `Cilium` plugin is selected for cluster.
**Cluster Step:**
**Dialog:**
Fixes #5524 
/kind feature
```release-note
Add functionality to edit initial values of Cilium application when Cilium plugin is selected.
```
```documentation
NONE
```
> Add functionality to edit initial values of Cilium application

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v2/types.go
- modules/api/pkg/handler/v2/application_installation/conversion.go
- modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_spec.go
Pass `ReconciliationInterval` & `DeployOptions` between internal and API `ApplicationInstallation`. Without this, this config is lost when editing the ApplicationInstallation via UI.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Pass ReconciliationInterval & DeployOptions between internal and API ApplicationInstallation

- modules/web/src/app/settings/admin/presets/dialog/steps/preset/component.ts
- modules/web/src/app/settings/admin/presets/dialog/steps/preset/template.html
- modules/web/src/app/shared/components/select/component.ts
- modules/web/src/app/shared/components/select/template.html
- modules/web/src/app/shared/entity/preset.ts
on create preset first step (preset) Add an option under Optional Settings section to Restrict preset to projects
**Create Preset Dialog**:
Fixes #5580
/kind feature
```release-note
Add an option to Restrict preset to projects
```
```documentation
NONE
```
> add an option for restricting presets to projects

- modules/web/package-lock.json
- modules/web/package.json
Due to bump version in this [PR](https://github.com/kubermatic/dashboard/pull/5550) breaks resize inside webterminal. Therefore currently downgraded the version until that issue has been resolved
**with version 0.7.0**
https://user-images.githubusercontent.com/17727069/214832084-c559c82f-079e-4195-a8a9-fa41c1a87f0e.mp4
**with version 0.6.0**
https://user-images.githubusercontent.com/17727069/214832140-eda0411b-5317-44dc-9e1a-30cbf3d10e9c.mp4
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Downgrade version of xterm-addon-fit package

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go
- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
- modules/api/pkg/provider/kubernetes/operating_system_profile.go
- modules/api/pkg/provider/types.go
With https://github.com/kubermatic/kubermatic/issues/11585, OperatingSystemProfiles now exist in the user clusters and Custom OperatingSystemProfiles now belong to a new kind `CustomOperatingSystemProfile`. 
This PR takes care of those changes.
Fixes #5575
/kind chore
We don't need any release notes since only the internal implementation has changed. The request/response etc remain the same.
```release-note
NONE
```
```documentation
NONE
```
> Refactor endpoints to list OperatingSystemProfiles

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v2/types.go
- modules/api/pkg/handler/v2/application_installation/conversion.go
- modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_list_item.go
- modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_list_item_spec.go
Moves `Labels` in `ApplicationInstallationListItem` to the top level to match with `ApplicationInstallation`.
Pointed out to by @Waseem826 
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Move Labels in ApplicationInstallationListItem to the top level

- modules/web/src/app/node-data/extended/provider/vsphere/tag-categories/component.ts
Load category tags when new tag with category is added in Edit Machine Deployment dialog.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Load category tags when new tag with category is added

- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss
- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
- Fix font-size of "No qutas configured" message on MD list section.
- Hide extended progress bars if no quota configured.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix font-size and hide extended progress bars if no quota configured

- modules/web/src/app/cluster-template/component.ts
- modules/web/src/app/core/components/sidenav/component.spec.ts
- modules/web/src/app/core/components/sidenav/component.ts
- modules/web/src/app/node-data/component.ts
- modules/web/src/app/project-overview/component.ts
- modules/web/src/app/project-overview/create-resource-panel/component.ts
- modules/web/src/app/shared/components/add-cluster-from-template-dialog/component.ts
- modules/web/src/app/shared/components/side-nav-field/component.ts
- modules/web/src/app/wizard/component.ts
Use router state to communicate `mode` value to cluster wizard. Previously we were using query params for `mode` which is not ideal since that information is not important for end user.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Use router state to communicate `mode` value to cluster wizard

- modules/web/src/app/project/edit-project/component.ts
- modules/web/src/app/project/edit-project/template.html
in https://app.zenhub.com/workspaces/work-in-progress---the-a-team-5fa971db111c0d0018ce0008/issues/gh/kubermatic/dashboard/4913
point 4 
we suppose to show the edit quota in the edit project dialog only for admins 
so in this PR we fix this point since the edit quota is an admin feature 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> hide the quota in edit project dialog for non-admin users

- modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
this PR fix the error that occur on switching between different architecture types for EKS MD, which prevent the get request for the instance types.
**Add MD in EKD**:
Fixes #5658
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> add template reference variable for instance type

- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
- modules/web/src/app/node-data/basic/provider/kubevirt/template.html
Mark KubeVirt node affinity preset key and values as required.
Fixes #5650 
/kind bug
```release-note
Mark KubeVirt node affinity preset key and values as required.
```
```documentation
NONE
```
> Mark KubeVirt node affinity preset key and values as required

- modules/api/pkg/handler/v2/external_cluster/gke.go
**What this PR does / why we need it**: Fixes GKE zone and version list endpoint by removing duplicate type assertion
Fixes #5647
```release-note
NONE
```
```documentation
NONE
```
> Fixes GKE zone and version list endpoint

- modules/web/src/app/project/edit-project/component.ts
If a user has no projects and then edit their first project then a null value exception is thrown. This PR adds `undefined` value check on user `projects`.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Add `undefined` value check on user `projects`

- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
Reset OS image value if there are no matches in dropdown options.
Fixes #5671 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Reset OS image value if there are no matches in dropdown options

- modules/api/pkg/handler/common/cluster.go
This PR ensures we persist annotations when converting internal to external cluster. This should ensure that we persist annotations when upgrading a cluster. There are two critical use cases for this:
* Users might apply custom annotations on Cluster objects. For example, additional metadata related to ownership and billing (https://github.com/kubermatic/kubermatic/issues/11832)
* We apply CCM/CSI migration needed annotations which are not persisted. After upgrading Kubernetes version, migrated clusters might start misbehaving (https://github.com/kubermatic/kubermatic/issues/11688)
xref https://github.com/kubermatic/kubermatic/issues/11832
xref https://github.com/kubermatic/kubermatic/issues/11688 
**What type of PR …
> Persist annotations when upgrading a cluster

- modules/web/src/app/dynamic/enterprise/quotas/services/quota-calculation.ts
- modules/web/src/app/wizard/step/provider-settings/component.ts
this PR fix the issue that occur on provider change in the wizard from kubeadm to another provider on settings step the credentials are not displayed 
Fixes #5670
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Assign provider value on initialize ProviderSettingsStepComponent

- modules/api/pkg/api/v1/types.go
- modules/api/pkg/api/v1/types_test.go
Fixes marshalling error of KubeVirt node spec after upgrading from 2.21
Fixes [#11839](https://github.com/kubermatic/kubermatic/issues/11839)
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix KubeVirt Node marshalling error

- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
- modules/web/src/app/node-data/basic/provider/kubevirt/template.html
Mark KubeVirt Node Affinity Preset Values as optional. An error message is also added for Node Affinity Preset Key field.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Mark KubeVirt node affinity preset values as optional

- modules/web/src/app/cluster-template/component.ts
- modules/web/src/app/cluster-template/template.html
We need to show the cluster template creation date to stay consistent with our layouts. 
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Display creation date in cluster template list view

- modules/web/src/app/wizard/step/cluster/component.ts
When editing/customizing a template, if `Cilium` plugin is selected then Proxy Mode dropdown displays wrong options. This has been fixed by updating proxy mode options on page load.
**Before:**
**After:**
Found this while testing https://github.com/kubermatic/dashboard/issues/5343
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Update proxy mode options on initial page load

- modules/web/src/app/node-data/basic/provider/azure/component.ts
adjust the values of `osDiskSizeInMB` and `resourceDiskSizeInMB` in quota calculation for azure 
Fixes #5687 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> adjust Azure Node Size values in the quota calculation payload

- modules/web/src/app/node-data/component.ts
- modules/web/src/app/node-data/dialog/component.ts
- modules/web/src/app/node-data/dialog/template.html
- modules/web/src/app/node-data/template.html
Remove dynamic kubelet config setting and set it to always disabled. In Edit MD dialog, if a kubelet version of MD is less than `1.24` and `dynamicConfig` is enabled than a warning message is displayed about disabling this setting.
/kind bug
```release-note
Remove dynamic kubelet config setting and set it to always disabled.
```
```documentation
NONE
```
> Remove dynamic kubelet config setting and set it to always disabled

- modules/api/pkg/machine/convert.go
Fixes KubeVirt node marshaling after KKP upgrade.
Fixes https://github.com/kubermatic/kubermatic/issues/11839
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Restore flavor fields of KubeVirt node spec

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/handler/routes_v1_websocket.go
- modules/api/pkg/handler/websocket/terminal.go
This PR introduces a periodic (30s) ping message to the Web Terminal client via the websocket connection to avoid inactivity timeout.
Fixes #5683
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Add periodic "ping to client" to keep the Web Terminal connection alive

- modules/web/src/app/settings/admin/seed-configurations/seed-configurations-details/component.ts
This PR fixes sorting on Seed Configuration Overview table to sort data by `Provider, Datacenters, Clusters`
https://user-images.githubusercontent.com/17727069/217809327-8423c09e-5fdb-4c16-b334-0ef72c84aa58.mp4
Fixes #
https://github.com/kubermatic/dashboard/issues/5286#issuecomment-1409350941
/kind bug
Sorting is applied on overview table where all providers are listed for a particular seed.
```release-note
NONE
```
```documentation
NONE
```
> Fix sorting on provider overview table

- modules/web/src/app/settings/admin/presets/dialog/steps/preset/component.ts
fix initial value for projects in create preset to be an empty array instead of empty string.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix Initial Value for Projects in Create Preset 

- modules/web/src/app/dynamic/enterprise/quotas/service.ts
- modules/web/src/app/project/component.ts
- modules/web/src/app/project/template.html
Only take single subscription of project quota API request to prevent continuous polling even after a project's deletion. This issue was caused for non-admin users when they delete a project.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Only take single subscription of project quota API request

- modules/web/src/app/cluster/details/external-cluster/component.ts
- modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
- modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
- modules/web/src/app/cluster/details/external-cluster/template.html
Update the Conditions for Enable get kubeconfig and add MD Buttons
Fixes #5657
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Update the Conditions for Enable get kubeconfig and add MD Buttons

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v2/types.go
- modules/api/pkg/handler/test/helper.go
- modules/api/pkg/handler/v2/application_installation/application_installation_test.go
- modules/api/pkg/handler/v2/application_installation/conversion.go
- modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_list_item.go
- modules/web/src/app/core/services/application.ts
the namespace in the API called was the namespace where the workload is installed instead of the namespace of crd.
Fixes #5679
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix edit application 

- modules/web/src/app/shared/components/application-list/component.ts
Display unknown status for installed applications instead of marking them as "ready".
Fixes #5714
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Add unknown status for installed applications

- modules/web/src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/template.html
Hints are hidden for edit metering schedule dialog because the `mode` for that component is set to `errors`.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Display hints in edit schedule dialog for metering

- hack/images/web-terminal/Dockerfile
- hack/images/web-terminal/release.sh
- modules/api/pkg/handler/websocket/terminal.go
Add mult-arch support for web-terminal image and move it from https://github.com/kubermatic/kubermatic to dashboard. 
Fixes https://github.com/kubermatic/kubermatic/issues/11876 , https://github.com/kubermatic/kubermatic/issues/11884
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Add image for web-terminal

- src/app/project-overview/create-resource-panel/component.ts
- src/app/project-overview/create-resource-panel/template.html
Manual cherrypick of #5572 
also hide the import external cluster
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> cherrypick hide external cluster from project overview

- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/cluster/details/cluster/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/wizard/step/cluster/template.html
Single IP address cannot be configured in the "Allowed IP Ranges for apiserver". It is correctly guarded by a pattern, but the error message "Input has to be a valid IPv4 or IPv6 address" is wrong - it fact it cannot be an IP address, but must be an IP address CIDR:
This PR fixes it + makes "IP Range" plural "IP Ranges"
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix IP ranges pattern error message + labels

- modules/web/src/app/shared/components/terminal/component.ts
This PR keeps WS connection alive by exchange of messages from `be->fe ping` and `fe->be pong` to let backend . In order to avoid session get timeout.
Fixes #
Handle changes for
[PR#5696](https://github.com/kubermatic/dashboard/pull/5696)
[PR#5727](https://github.com/kubermatic/dashboard/pull/5727)
/kind bug
Previously WS connection was lost due to middleware proxy layer could be nginx or any reverse proxy so in order to let client/server that communication is still alive we need to keep web-terminal connection to alive
```release-note
NONE
``` …
> Keep WS connection alive by exchange of messages

- modules/web/src/app/cluster/details/cluster/edit-cluster/style.scss
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/shared/components/chip-list/template.html
- modules/web/src/app/wizard/step/cluster/style.scss
- modules/web/src/app/wizard/step/cluster/template.html
Display documentation link under `Allowed IP Ranges for API server` field.
**Cluster Wizard:**
**Edit Cluster Dialog:**
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Display documentation link under Allowed IP Ranges field

- modules/web/src/app/cluster/details/cluster/component.ts
- modules/web/src/app/cluster/details/cluster/template.html
- modules/web/src/app/shared/utils/health-status.ts
Disable Web Terminal Button when no Machine Deployment is on Running State
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Disable Web Terminal Button when no Machine Deployment is on Running State

- modules/web/src/app/cluster/details/kubeone/component.ts
- modules/web/src/app/cluster/details/kubeone/template.html
Update conditions to disable `Get Kubeconfig` button of KubeOne cluster.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Update conditions to disable download KubeOne kubeconfig button

- modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
- modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
This PR fetches resources required in Settings step of external clusters to in order to populate dropdown values
currently, it was not fetching when user manually entered credentials.
Fixes #5740 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix fetching of resources base on preset or manually entering credentials

- modules/web/src/app/cluster/details/external-cluster/component.ts
- modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
- modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
- modules/web/src/app/cluster/details/external-cluster/template.html
in AKS clusters with warning state the MD list is not shown and a loading spin is displayed while in the warning state we should consider the cluster as running cluster and show the MD list 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Consider AKS cluster with warning state as a running cluster.

- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/dynamic/enterprise/quotas/template.html
User should not be permitted to delete the default resource quotas for a particular project. This leads to inconsistency since the controller will try to recreate these resources anyways.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Disable deletion for default project quotas

- hack/lib.sh
This PR updates the way we calculate the git hash for KKP in CI. In most cases, we'd like to add a replacement for `k8c.io/kubermatic/v2` dependency so that we can pin it to a specific version. This PR would check if replacement is there and use it, if not, it would default to the original version.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Fix method to deduce the KKP git hash

- modules/api/pkg/resources/machine/common.go
Fixes kubermatic/kubermatic#11858
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> openstack annotion md: do not set security if c.Spec.Cloud.OpenstackSecurityGroups is empty

- modules/web/src/assets/config/changelog.json
I've extracted what I considered the most important end user (i.e. someone who uses the dashboard of a KKP instance) facing changes and updated the `changelog.json` with it. I assume it does not cover everything, but unless I've missed something crucial it's probably a solid amount of information for users. The UI links to the full changelog anyway as well.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Add changelog.json for end user facing changes in KKP 2.22.0

- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/handler/common/upgrade.go
Hopefully the last time we bump this before the release, but we had to given that we updated the defaulting logic for OpenStack clusters in https://github.com/kubermatic/kubermatic/commit/2ce03c27f21a543cadd08dd80a729ad397829a5f.
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Bump k8c.io/kubermatic/v2 dependency to Feb 22 commit

- modules/api/go.mod
- modules/api/go.sum
Updates the k8c.io/kubermatic/v2 dependency to https://github.com/kubermatic/kubermatic/commit/022ca1e74a2aec8636fb77079433daa97c8b7a25, which is planned to be the `v2.22.0` tag target.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update k8c.io/kubermatic/v2 dependency to latest

- hack/ci/setup-kind-cluster.sh
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Use registry.k8s.io for preloaded kube-controller-manager image

- modules/api/pkg/handler/common/filter.go
If you define some `MachineFlavorFilter` in the DC, it's was not used for the filtering.
Everywhere in the code, we call `DetermineMachineFlavorFilter` with:
- `filter := handlercommon.DetermineMachineFlavorFilter(datacenter.Spec.MachineFlavorFilter, settings.Spec.MachineDeploymentVMResourceQuota)`
--> first parameter is the DC, second the settings.
This inversion impact was that if you define `MachineFlavorFilter` in the DC, it was never taken into account.
Fixes #
/kind bug
```release-note
Fix Datacenter MachineFlavorFilter not used
``` …
> Fix DC MachineFlavorFilter not used

- modules/web/src/app/cluster/details/cluster/template.html
- modules/web/src/assets/css/global/_theme.scss
Add Tooltip and Remove Hover Effect for Disabled Button in Cluster Menu
Fixes #5406
/kind design
-->
```release-note
NONE
```
```documentation
NONE
```
> Add Tooltip for Disabled Button in Cluster Menu

- modules/web/src/app/cluster/details/cluster/template.html
- modules/web/src/app/project-overview/component.ts
- modules/web/src/app/project-overview/style.scss
- modules/web/src/app/project-overview/template.html
remove the welcome message that been add to inform users that they can make project overview page as there project landing page from user settings, the message been there for more than enough time. 
Fixes #5604 
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Remove Welcome Message for Projectview

- modules/web/src/app/core/components/sidenav/style.scss
- modules/web/src/app/settings/admin/presets/template.html
- modules/web/src/assets/css/global/_main.scss
change the the color and opacity for all providers in a disabled preset and add the disapled style for the disabled preset and adjust the tool tip for show and hide preset.
Fixes #5680
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Apply Disabled Style for the Disabled Preset 

- modules/web/src/app/settings/admin/presets/dialog/component.ts
- modules/web/src/app/settings/admin/presets/dialog/style.scss
- modules/web/src/app/settings/admin/presets/dialog/template.html
Add a back button to preset dialog to navigate between steps.
Fixes #5676 
/kind design
-->
```release-note
NONE
```
```documentation
NONE
```
> Add a Back Button to Preset Dialog

- modules/web/src/app/core/components/sidenav/component.ts
- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss
- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
- modules/web/src/app/settings/admin/customization/template.html
- modules/web/src/app/settings/admin/nav/component.ts
- modules/web/src/app/shared/constants/common.ts
- modules/web/src/assets/css/global/_main.scss
- Collapse sidenav at `1500px` screen width.
[screencast-localhost_8000-2023.03.07-15_50_45.webm](https://user-images.githubusercontent.com/13975988/223405670-f635c168-34ba-49ac-b24e-8b624e75257b.webm)
- Collapse Quota Widget at `1200px` screen width.
[screencast-localhost_8000-2023.03.07-15_48_16.webm](https://user-images.githubusercontent.com/13975988/223405615-d34f5221-b7e4-4d9d-ae2d-7b341bfb22d0.webm)
- Adjust misc spacing issues.
**Admin Settings Customization Page:**
**External Clusters List Page:**
Fixes #5732 
/kind design
```release-note
Improve page …
```
> Improve responsiveness for smaller screen sizes

- modules/api/pkg/handler/common/cluster.go
As documented in [KKP docs](https://docs.kubermatic.com/kubermatic/v2.21/tutorials-howtos/networking/cni-migration/#changing-the-kube-proxy-mode), under certain conditions, the `clusterNetwork.proxyMode` can be updated. This was not possible via the cluster PATCH API endpoint - this PR fixes it.
Fixes https://github.com/kubermatic/kubermatic/issues/11994
/kind bug
```release-note
Allow updating of the `clusterNetwork.proxyMode` via the KKP API (PATCH endpoint).
```
```documentation
NONE
```
> Allow updating of clusterNetwork.proxyMode via the KKP API

- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
- modules/web/src/app/project/component.ts
- modules/web/src/app/project/style.scss
- modules/web/src/app/project/template.html
**What this PR does / why we need it**
reduce the spacing in the bottom of the projects card and remove the no quota  widget.
**Project view:**
**Cluster Detail:**
Fixes #5608 
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Quota UI Adjustment

- modules/api/pkg/handler/common/kubeconfig.go
- modules/api/pkg/handler/test/helper.go
- modules/api/pkg/handler/v1/cluster/kubeconfig_test.go
- modules/api/pkg/handler/v2/cluster/kubeconfig.go
- modules/api/pkg/handler/v2/cluster/kubeconfig_test.go
- modules/api/pkg/handler/v2/routes_v2.go
Assign a unique identifier i.e. cluster ID for the `context` specified in the OIDC kubeconfig. Having it set as `default` makes it difficult to differentiate and switch context between multiple clusters.
Fixes #5745
/kind feature
```release-note
The context name for OIDC Kubeconfig has been changed to the cluster ID from `default`.
```
```documentation
NONE
```
> Change kubeconfig context name from default to cluster ID

- .prow/api.yaml
- modules/api/.golangci.yml
`golangci-lint` keeps timing out every now and then. Since we are already assigning it 10 Gigs of memory it makes sense to run the tests concurrently.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Enable concurrency for golangci-lint

- Dockerfile
- hack/images/web-terminal/Dockerfile
Sister PR to https://github.com/kubermatic/kubermatic/pull/12007, bumping all Alpine versions found to 3.17.
Fixes #
/kind cleanup
```release-note
Use Alpine Linux 3.17 for container images
```
```documentation
NONE
```
> Use Alpine Linux 3.17

- modules/web/src/app/shared/utils/health-status.ts
When a MachineDeployment has zero replicas, the returned status does not contain any information about replica health (since the value is zero and is omitted by the backend's struct definition) and thus, the dashboard shows it as "Updating".
Since we cannot change the backend code (it uses the cluster-api definition of MachineDeployment status), I tried fixing this in the frontend; I couldn't think of a better way to handle this than including a "special case" in the if condition. If there's a way to simplify it that I've missed, I'm very open to suggestions.
Fixes #5834 …
> Correctly handle MD health if no replicas are configured

- modules/api/go.mod
- modules/api/go.sum
This bumps the `k8c.io/kubermatic/v2` dependency so Cilium 1.13.1 is available from the frontend (https://github.com/kubermatic/kubermatic/commit/890805d15997d5269dfb6411f0087baa45a2587a).
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Bump k8c.io/kubermatic/v2 dependency

- modules/api/cmd/kubermatic-api/main.go
quick fix for logger error formating mismatch, some calls were using `log.Fatalw` but included formatting 'verbs' instead key/val args.
```
$ grep . -nre 'Fatalw.*%'
./modules/api/cmd/kubermatic-api/main.go:157:           log.Fatalw("failed to add index on Event involvedObject name: %w", err)
./modules/api/cmd/kubermatic-api/main.go:365:           log.Fatalw("failed to create an openid authenticator - issuer: %q, oidcClientID: %q: %v", options.oidcURL, options.oidcAuthenticatorClientID, err)
```
none, stumbled upon it when testing https://docs.kubermatic.com/kubermatic/v2.22/installation/install-kkp-ce/ and accidentally misconfigured `values.yaml` to observe `kubermatic-api` in `CrashLoopBackOff` with:
``` …
```
> api: fix logger error fmt mismatch

- modules/web/src/app/node-data/basic/provider/openstack/component.ts
- modules/web/src/app/node-data/basic/provider/openstack/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/shared/entity/cluster.ts
- modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts
- modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
- modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
- modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/template.html
Allow configuration of `enableIngressHostname` and `ingressHostnameSuffix` settings of OpenStack provider.
Additionally 2 more issues are fixed:
- Load security group, network and subnet pool dropdown options only when cluster credentials are updated.
- Visually mark Disk Size field (on Initial Nodes step) as required when form control is marked as required.
Fixes #5856 
/kind feature
```release-note
Configure Ingress Hostname cluster settings of OpenStack provider.
```
```documentation
https://docs.kubermatic.com/kubermatic/main/references/crds/#openstackcloudspec
```
> Configure OpenStack ingress cluster settings

- src/app/node-data/basic/provider/openstack/component.ts
- src/app/node-data/basic/provider/openstack/template.html
- src/app/shared/components/cluster-summary/template.html
- src/app/shared/entity/cluster.ts
- src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts
- src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
- src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
- src/app/wizard/step/provider-settings/provider/extended/openstack/template.html
This is a manual cherry-pick of https://github.com/kubermatic/dashboard/pull/5861.
/kind feature
```release-note
Configure Ingress Hostname cluster settings of OpenStack provider.
```
```documentation
https://docs.kubermatic.com/kubermatic/v2.21/references/crds/#openstackcloudspec
```
> [release/v2.21] Configure OpenStack ingress cluster settings

- modules/web/src/app/core/services/auth/service.ts
There is a desire for DNS-less KKP installation without TLS certificates for the KKP dashboard. This ensures the cookie storage works over HTTP as well as HTTPS.
relevant for: https://github.com/kubermatic/kubermatic/issues/12023
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> dashboard: allow http for cookie store

- modules/web/src/app/wizard/step/cluster/component.ts
The frontend code made the assumption that there will always be a `v` prefix for versions. That is however not the case, for example when you configure versions on your own in `KubermaticConfiguration`. This PR makes sure we remove a `v` string from the version instead, so it doesn't do anything if the version is not set.
Technically, versions could have a string suffix that could include `v`, but this is not the case for Kubernetes versions and I couldn't get a regex to work here. So if you're from the future stumbling into this PR, I'm sorry I made an incorrect assumption. Otherwise, feel free to discard this comment.
Fixes #5871
/kind bug
**Does …
> Fix 'v' prefix removal by removing character instead of slicing string

- modules/api/pkg/handler/v2/provider/aws.go
When we added project-scoped API endpoints for AWS in #5441, we apparently forgot to also fetch the VPC id from the header `VPC` if it was set. This meant that not using presets was broken for AWS user cluster setups. See linked issue for details.
Fixes #5882
/kind bug
```release-note
AWS subnets are fetched correctly if credentials are provided directly instead of using a preset
```
```documentation
NONE
```
> Fetch AWS VPC id from request header

- Makefile
- package-lock.json
- package.json
- src/assets/config/changelog.json
This bumps the dashboard version to v2.21.8 n preparation of April patch releases.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.21] Bump version to v2.21.8

- modules/web/src/app/dynamic/enterprise/metering/schedule-config/add-dialog/component.ts
- modules/web/src/app/dynamic/enterprise/metering/schedule-config/add-dialog/template.html
- modules/web/src/app/dynamic/enterprise/metering/schedule-config/component.spec.ts
- modules/web/src/app/dynamic/enterprise/metering/schedule-config/component.ts
- modules/web/src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/component.ts
- modules/web/src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/template.html
- modules/web/src/app/dynamic/enterprise/metering/schedule-config/template.html
- modules/web/src/app/dynamic/enterprise/metering/service/metering.ts
- modules/web/src/app/shared/entity/datacenter.ts
- modules/web/src/test/data/metering.ts
Add functionality to configure report types in metering schedule configuration:
- **Schedules List:**
- **Create Schedule Dialog**
- **Edit Schedule Dialog:**
Fixes #4871 
/kind feature
```release-note
Configure report types in schedule configuration.
```
```documentation
TBD
```
> Add functionality to configure metering schedule report types

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/api/v2/types.go
- modules/api/pkg/handler/v1/admin/settings.go
- modules/api/pkg/test/e2e/utils/apiclient/models/global_settings.go
- modules/web/src/app/core/components/help-panel/component.ts
- modules/web/src/app/core/components/help-panel/template.html
- modules/web/src/app/settings/admin/customization/component.ts
- modules/web/src/app/settings/admin/customization/template.html
- modules/web/src/app/shared/entity/settings.ts
Add support to disable changelog (What's new) popup. When this setting (`disableChangelogPopup`) is set, it will also hide the `What's New` option from Help menu.
[screencast-localhost_8000-2023.04.17-14_30_02.webm](https://user-images.githubusercontent.com/13975988/232464616-9651fb59-b05c-4182-8d89-7eb05191fc52.webm)
Fixes #4751 
/kind feature
```release-note
Add support to disable changelog popup.
```
```documentation
TBD
```
> Add support to disable changelog popup

- modules/web/src/app/project/style.scss
- modules/web/src/app/project/template.html
Fix spacing between placeholder text and `Add Project` button for Firefox.
xref #5511 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Add margin between placeholder text and `Add Project` button

- modules/web/src/assets/css/global/_theme.scss
add a cut off shadow to indelicate the action area in dialog
Fixes #5202 
**light mode dialog**:
**dark mode dialog**:
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Add cut off shadow to dialogs

- modules/web/src/app/node-data/component.ts
- modules/web/src/app/node-data/template.html
- modules/web/src/app/shared/model/NodeProviderConstants.ts
Hide the show advanced settings option in the MD dialog for the providers that don't have a advanced settings 
**Hetzner MD dialog**:
before :
after:
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Hide the show advanced settings option

- modules/api/pkg/handler/v2/external_cluster/kubeone.go
We are missing credentials processing/configuration for KubeOne clusters on Hetzner and Digital Ocean.
Required to unblock:
- https://github.com/kubermatic/dashboard/pull/5830
- https://github.com/kubermatic/dashboard/pull/5827
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Credentials configuration for KubeOne clusters on Hetzner and Digital Ocean

- modules/web/src/app/kubeone-wizard/module.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/digitalocean/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/digitalocean/template.html
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
- modules/web/src/app/kubeone-wizard/steps/provider/component.ts
- modules/web/src/app/kubeone-wizard/steps/summary/template.html
- modules/web/src/app/shared/entity/kubeone-cluster.ts
Add support to import digitalocean KubeOne cluster.
**Provider Step:**
**Credentials Step:**
Fixes #5820
/kind feature
```release-note
Add support to import digitalocean KubeOne cluster
```
```documentation
NONE
```
> Add support to import digitalocean kubeone cluster

- modules/web/src/app/kubeone-wizard/module.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/hetzner/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/hetzner/template.html
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
- modules/web/src/app/kubeone-wizard/steps/provider/component.ts
- modules/web/src/app/kubeone-wizard/steps/summary/template.html
- modules/web/src/app/shared/entity/kubeone-cluster.ts
Add support to import hetzner KubeOne cluster.
**Provider Step:**
**Credentials Step:**
Fixes #5819
/kind feature
```release-note
Add support to import hetzner KubeOne cluster
```
```documentation
NONE
```
> Add support to import hetzner kubeone cluster

- modules/web/src/app/shared/components/application-list/style.scss
- modules/web/src/app/shared/components/application-list/template.html
Make applications table span full width of the card.
xref: https://github.com/kubermatic/dashboard/issues/4914
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Span applications table to full width

- modules/web/src/assets/css/material/_theme.scss
Add secondary color to required indicator of untouched and empty required form fields.
Fixes #5297 
/kind design
```release-note
Add color to required indicator of untouched and empty required form fields.
```
```documentation
NONE
```
> Add secondary color to form field required indicator

- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
- modules/web/src/app/node-data/component.ts
the `autoupdateEnable` option in the admin panel shouldn't apply on the edit dialog that's why we see the warning for recreate nodes for all provider .
for kubevirt there was an issue with setting some `null` values in case there is no value for that field, while the value for them in the MD object that come from the api is `""` (empty string), so that cause the warning to show cause the initial data that been add to the editdialog come from the api 
Fixes #5932 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix recreate nodes warning on edit MD dialog 

- modules/web/src/app/component.ts
- modules/web/src/app/dynamic/enterprise/theming/services/manager.ts
Since theme files (`dark.scss`, `light.scss`, `custom.scss`) don't have any hash in their names (like `styles.*.scss`) and we have to load them manually on the basis of selected theme, these files are cached by browser and sometimes lead to unexpected behaviour.
This PR adds current release `tag` inside the file URL to bust the cache and load latest version of these files.
For example (note file size):
**v2.22.0:**
**v2.22.2:**
Fixes #5583 
/kind bug
```release-note
Add cache busting mechanism for theme styles.
```
```documentation
NONE
```
> Use version as query param to cache bust theme styles

- modules/api/pkg/handler/v2/external_cluster/kubeone.go
- modules/web/src/app/kubeone-wizard/module.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/openstack/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/openstack/template.html
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
- modules/web/src/app/kubeone-wizard/steps/provider/component.ts
- modules/web/src/app/kubeone-wizard/steps/summary/template.html
- modules/web/src/app/shared/entity/kubeone-cluster.ts
add openstack provider to the kubeone import wizard and set the credentials in the api    
Fixes #5804 
**Provider Step**:
**Credentials Step**:
**Summary Step**:
/kind feature
```release-note
Add support to import openstack kubeone cluster
```
```documentation
NONE
```
> Add support to import openstack kubeone cluster

- modules/web/src/app/wizard/step/provider-settings/provider/basic/vsphere/template.html
Change the checkbox label in Vspher settings(Credentials) step to a better description. 
Fixes #5952
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Clarify vSphere credentials

- modules/web/src/app/cluster/details/cluster/edit-provider-settings/vsphere-provider-settings/component.ts
- modules/web/src/app/cluster/details/cluster/edit-provider-settings/vsphere-provider-settings/template.html
- modules/web/src/app/wizard/step/provider-settings/provider/basic/vsphere/component.ts
- modules/web/src/app/wizard/step/provider-settings/provider/basic/vsphere/template.html
Through https://github.com/kubermatic/dashboard/issues/5952, we found two major issues with the credentials handling for vSphere:
1. The difference is ambiguous and needs more coherence
2. By default we are setting the credentials for `infra management user` and by additionally specifying "dedicated credentials" we configure the username/password for vSphere. In reality, this is completely the opposite of how it should work. 
This PR fixes both of these issues and tries to improve the UX as well.
Fixes #5952
/kind cleanup
/kind bug
```release-note
* UI/UX improvements …
```
> Rework vSphere credentials UI/UX

- modules/api/pkg/handler/v1/admin/seed.go
- modules/web/src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts
handle update backup destination when the value is empty string (remove default backup destination)
Fixes #5950
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix update default backup destination

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/settings/admin/opa/default-constraints/template.html
- modules/web/src/app/shared/components/label-form/component.ts
- modules/web/src/app/shared/components/label-form/template.html
- modules/web/src/app/shared/utils/cluster.ts
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
Add functionality to delete disabled label especially when `PodNodeSelector` admission plugin and `clusterDefaultNodeSelector` namespace is set.
Fixes #5979 
/kind bug
```release-note
Allow removing cluster label when PodNodeSelector admission plugin and clusterDefaultNodeSelector namespace are set.
```
```documentation
TBD
```
> Add functionality to delete disabled label

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/shared/components/label-form/component.ts
- modules/web/src/app/shared/components/label-form/template.html
- modules/web/src/app/shared/utils/cluster.ts
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
This is a manual cherry pick of #5981 
Fixes #
/kind bug
```release-note
Allow removing cluster label when PodNodeSelector admission plugin and clusterDefaultNodeSelector namespace are set.
```
```documentation
NONE
```
> [release/v2.22] Add functionality to delete disabled label

- modules/web/src/app/core/components/notification/component.ts
- modules/web/src/app/core/services/cluster.spec.ts
- modules/web/src/app/core/services/node.spec.ts
- modules/web/src/app/core/services/notification.ts
- modules/web/src/app/shared/components/terminal/component.spec.ts
- modules/web/src/app/shared/module.ts
- modules/web/src/assets/css/_variables.scss
- modules/web/src/assets/css/global/_main.scss
- modules/web/src/assets/css/global/_theme.scss
- modules/web/src/assets/css/material/_theme.scss
This PR migrates Angular Material `Snackbar` component from legacy to v15.
xref #5864 
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Migrate Angular Material Snackbar component from legacy to v15

- modules/web/src/app/core/components/notification-panel/component.ts
- modules/web/src/app/core/components/notification-panel/template.html
There was an issue with notification panel where it would immediately close the panel because of outside click handler hence making it look like that click event is ignored. This PR fixes it by ignoring the outside click event if target element is notification toggle button.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Ignore notification outside click if target element is toggle button

- modules/api/go.mod
- modules/api/pkg/handler/v2/external_cluster/kubeone.go
- modules/web/src/app/kubeone-wizard/module.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/vsphere/component.ts
- modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/vsphere/template.html
- modules/web/src/app/kubeone-wizard/steps/provider/component.ts
- modules/web/src/app/kubeone-wizard/steps/summary/template.html
- modules/web/src/app/shared/entity/kubeone-cluster.ts
add VSphere provider to the kubeone import wizard and set the credentials in the api
**Provider Step**:
**Credentials Step**:
**Summary Step**:
Fixes #5806 
/kind feature
```release-note
Add support to import VSphere kubeone cluster
```
```documentation
NONE
```
> Add support to import a vsphere kubeone cluster

- modules/web/src/app/node-data/basic/provider/aws/component.ts
This PR fixes an issue in AWS provider where if there are subnets available and then a new new API request has no subnets then subnets dropdown was not cleared.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Clear AWS subnets dropdown when there are no subnets available

- modules/web/src/app/node-data/basic/provider/azure/component.ts
Fix the  accelerated networking filter for azure is not working when the user select the accelerated networking while  the VM sizes list still not ready.
Fixes #6036
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix the filter for accelerated networking for azure 

- modules/web/src/app/node-data/basic/provider/azure/component.ts
there is an issue that in azure md dialog (add/edit), the availability zones still show `zone loading` label even though the assign availability set is not enabled and it keep like that for more than 30 seconds cause the label wait for the api response, so we shouldn't even do that api request if the field already disabled .
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Prevent calling availability zone api request if assign availability set

- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
- modules/web/src/app/node-data/dialog/component.ts
- modules/web/src/app/node-data/dialog/template.html
This PR fixes a small issue in Add/Edit machine deployment dialog where the Save Changes button remains disabled even after quota calculation API request is complete. This was caused by change detection not running.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Use `async` pipe to handle quota calculation observable in template

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This bumps the repository to Go 1.19.10.
/kind chore
```release-note
Update to Go 1.19.10.
```
```documentation
NONE
```
> Update to Go 1.19.10

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This ensures that the dashboard uses the same image as KKP itself. There are no changes in this image compared to the -7 variant, it's just a rebuild to make 100000% sure we get the bookworm-based golang image.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Bump kubermatic/build image

- modules/web/src/app/cluster/details/cluster/component.ts
- modules/web/src/app/cluster/details/cluster/template.html
disables (Get Kubeconfig, Open Dashboard, Web Terminal) buttons in cluster details page, when the cluster on deleting state
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> disable all button in cluster detail page on cluster deletion

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v1/types.go
- modules/api/pkg/api/v1/types_test.go
- modules/api/pkg/machine/convert.go
- modules/api/pkg/resources/machine/common.go
- modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere_node_spec.go
- modules/web/src/app/cluster/details/cluster/node-list/template.html
- modules/web/src/app/node-data/extended/provider/vsphere/component.ts
- modules/web/src/app/node-data/extended/provider/vsphere/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/shared/entity/node.ts
This PR adds support to configure `vmAntiAffinity` setting for vSphere Machine Deployments.
**Create Cluster Wizard:**
**Add Machine Deployment Dialog:**
**Cluster Summary Page:**
Fixes #6050 
/kind feature
```release-note
Add VM anti-affinity setting for vSphere machine deployments.
```
```documentation
TBD
```
> Add VM anti-affinity setting for vSphere machine deployments

- modules/api/pkg/handler/v2/provider/gcp.go
With https://github.com/kubermatic/dashboard/pull/5330, we introduced project-scoped endpoints for GCP and later on we switched to using those endpoints instead of the default ones in the UI. Although this broke the usage of these endpoints with `credentials` instead of `presets`. 
The following endpoints were affected:
* `/projects/{project_id}/providers/gcp/disktypes`
* `/projects/{project_id}/providers/gcp/sizes`
* `/projects/{project_id}/providers/gcp/{dc}/zones`
* `/projects/{project_id}/providers/gcp/networks`
* `/projects/{project_id}/providers/gcp/{dc}/subnetworks`
Fixes #
/kind bug
**Does this PR introduce a user-facing change? Then add your …
> Fix project scoped endpoints for GCP

- Makefile
This was forgotten in #6106 (cc @pkprzekwas for awareness).
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.23] Bump root Makefile to v2.23.1

- Makefile
This was forgotten in #6107 (cc @pkprzekwas for awareness).
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.22] Bump root Makefile to v2.22.5

- modules/web/src/assets/config/changelog.json
This updates the changelog.json. I would consider some of the changes in the changelog to be of no consequence for users, so I removed them (what is a KKP _user_ supposed to do with the info that we now use buildx?).
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.22] update changelog.json, remove some non-user-facing changes from it

- modules/web/src/app/shared/components/cluster-from-template/content/style.scss
- modules/web/src/app/shared/components/cluster-from-template/content/template.html
- modules/web/src/assets/css/material/_main.scss
This PR fixes an issue where dialogs with material horizontal stepper would not display vertical scrollbar if content was long.
Fixes #6093 
/kind bug
```release-note
Add vertical scroll to the install Addon dialog.
```
```documentation
NONE
```
> Add vertical scroll in dialogs with material horizontal stepper

- modules/web/src/app/project/style.scss
- modules/web/src/app/project/template.html
the current case is that when user is admin and don't have any project he can't see other projects if the `show all project` toggle is unchecked and at the same time he can't see the toggle so he can't check it to see all projects,
in this PR we kkeep the toggle shown always if the user is admin.
Fixes #6039
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Keep the show all projects toggel displayed when the user is admin

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v1/types.go
- modules/api/pkg/api/v1/types_test.go
- modules/api/pkg/machine/convert.go
- modules/api/pkg/resources/machine/common.go
- modules/api/pkg/test/e2e/utils/apiclient/models/a_w_s_node_spec.go
- modules/web/src/app/cluster/details/cluster/node-list/template.html
- modules/web/src/app/node-data/extended/provider/aws/component.ts
- modules/web/src/app/node-data/extended/provider/aws/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/shared/entity/node.ts
This PR adds support to configure EBS Volume Encryption for AWS provider:
**Create Cluster Wizard:**
**Cluster Summary:**
**Nodes List:**
Fixes #5357 
/kind feature
```release-note
Add support for encrypted root volumes in AWS.
```
```documentation
TBD
```
> Add support for encrypted root volumes in AWS

- modules/web/src/app/core/services/auth/service.ts
- modules/web/src/app/project/template.html
- modules/web/src/app/shared/model/Config.ts
Starting from Keycloak 18, [RP initiated logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout) was introduced in keycloak. `post_logout_redirect_uri` and `id_token_hint` parameters are required now for logging a user out. 
To support this special case, we are now adding a new configuration named `oidc_provider` which will allow us to manage OIDC provider specific configurations.
Fixes #6127
/kind bug
```release-note
Fix support for keycloak OIDC logout. New field `oidc_provider` was introduced to support OIDC provider specific configurations. Configuring `oidc_provider` as …
```
> Fix the redirect url for keycloak logout

- modules/web/src/app/core/services/auth/service.ts
- modules/web/src/app/shared/model/Config.ts
manual backporting to v2.23
xref #6144  #6127
```release-note
Fix support for keycloak OIDC logout. New field `oidc_provider` was introduced to support OIDC provider specific configurations. Configuring `oidc_provider` as `keycloak` will properly configure the logout workflow.
```
> [release/v2.23] Fix the redirect URI for keycloak

- modules/api/pkg/handler/common/cluster.go
- modules/api/pkg/handler/common/machine.go
- modules/api/pkg/handler/v2/machine/machine_test.go
- modules/web/src/app/cluster/details/cluster/component.ts
Currently, we are fetching metrics as soon as the control plane components for the user cluster are up. This won't work since the metrics depend on the metric-server being up and available. Metric-server is not a control plane component and is installed on the user cluster in the form of a /pod. Hence, without having worker nodes available for that pod to be scheduled we end up getting bombarded with the following error after every 10 seconds because of polling.
```
failed to get API group resources: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```
Fixes #
/kind bug …
> Skip fetching metrics if metric-server is not available

- modules/web/src/app/node-data/basic/provider/hetzner/component.ts
- modules/web/src/app/node-data/basic/provider/nutanix/component.ts
- modules/web/src/app/node-data/basic/provider/vsphere/component.ts
This PR fixes a bug where a wrong filter for EE stopped the values being configured for node resources to be propagated from the forms to the persistence layer. 
Fixes #6165
/kind bug
```release-note
Fix a bug, for Community Edition, where the values configured for vSphere, Hetzner, and Nutanix nodes were not being persisted.  
```
```documentation
NONE
```
> Fix filter for quota calculation

- modules/web/src/app/shared/components/cluster-summary/component.ts
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
UI support against https://github.com/kubermatic/kubermatic/issues/9442; instead of a single IP CIDR allow users to specify a list of IPv4 and IPv6 IP CIDRs for node ports.
Fixes #
/kind feature
```release-note
Support multiple NodePort allowed IP ranges
```
```documentation
NONE
```
> Support multiple NodePort allowed IP ranges

- modules/api/pkg/provider/kubernetes/preset.go
Fixes an issue where the API Token from preset was not being sourced to the cluster.
Fixes #6195
/kind bug
```release-note
VMware Cloud Director: fix an issue where the API Token from preset was not being sourced to the cluster
```
```documentation
NONE
```
> Fix preset to cluster mapping for VMware Cloud Director

- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
- modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go
Bumps `k8c.io/kubermatic/v2` to https://github.com/kubermatic/kubermatic/commit/5aa989ae987063c6965769baaca970d0980e8a50. This pulls in newer Cilium versions and Kubernetes 1.28.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update k8c.io/kubermatic/v2 to `5aa989ae9870`

- modules/api/pkg/provider/cloud/openstack/helper.go
- modules/api/pkg/provider/cloud/openstack/provider.go
If openstack user configured in credentials is an admin, our API lists all the networks, security groups and subnet pools that user has access to without filtering by provided ProjectID/ProjectName. This PR introduces additional filtering for networks, security groups and subnet pools listings.
/kind bug
```release-note
openstack: take `TenantID` into account while listing networks, security groups and subnet pools.
```
```documentation
NONE
```
> openstack client: include TenantID in list options

- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
Manual backport for https://github.com/kubermatic/dashboard/pull/5941 to v2.22.
ref #5932
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> replace null values to empty values for kubevirt

- Makefile
- modules/api/Makefile
- modules/api/go.mod
- modules/api/go.sum
- modules/web/Makefile
- modules/web/package-lock.json
- modules/web/package.json
- modules/web/src/assets/config/changelog.json
I [introduced](https://github.com/kubermatic/kubermatic/pull/12635) a [regression](https://github.com/kubermatic/kubermatic/issues/12662) in KKP v2.23.3 that made KKP offer Cilium 1.14.1 via the API and subsequently from the dashboard when creating a new cluster with Cilium. That version doesn't exist in KKP v2.23.
This PR bumps to https://github.com/kubermatic/kubermatic/commit/218aec21ed486418b079681e9755fd4c8052e3a8 to undo the damage and remove Cilium 1.14.1 from the list of supported versions. It also prepares an out-of-band patch release for it.
Fixes #
/kind bug
**Does this PR introduce a user-facing change? Then add your …
> [release/v2.23] Prepare v2.23.4 out-of-band patch release

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v2/types.go
- modules/api/pkg/handler/v2/cniversion/cniversion.go
- modules/api/pkg/test/e2e/utils/apiclient/models/c_n_i_versions.go
- modules/web/src/app/shared/entity/cluster.ts
- modules/web/src/app/wizard/step/cluster/component.ts
use `cni.GetDefaultCNIPluginVersion` to get the default value for cni Plugin version .
Fixes #6233 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Set default value for cni plugin version 

- modules/web/src/app/core/services/node.ts
- modules/web/src/app/node-data/component.ts
- modules/web/src/app/shared/entity/machine-deployment.ts
add the `'k8c.io/operating-system-profile'` annotation to the patch object for editing a machine deployment .
Fixes #6255
/kind bug
```release-note
Add operating system profile to the machine deployment patch object.
```
```documentation
NONE
```
> Add OSP to the MD patch object

- src/app/core/services/node.ts
- src/app/shared/entity/machine-deployment.ts
This is a manual cherry-pick of #6255
```release-note
Add operating system profile to the machine deployment patch object.
```
> [release/v2.21] Add OSP to the MD patch object

- docs/proposals/testing.md
- modules/api/pkg/api/v1/types.go
- modules/api/pkg/handler/common/kubeconfig.go
- modules/api/pkg/handler/v2/cluster/kubeconfig_test.go
- modules/api/pkg/handler/v2/constraint/constraint.go
- modules/api/pkg/provider/cloud/aws/client_test.go
- modules/api/pkg/test/e2e/utils/oidc.go
- modules/web/version.js
Fixing spelling issues in the codebase to satisfy `pre-dashboard-common-verify` CI job.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Spelling-fixes

- modules/web/src/app/core/services/node.ts
- modules/web/src/app/shared/entity/machine-deployment.ts
This is a manual cherry-pick of #6264 .
/kind bug
```release-note
Add operating system profile to the machine deployment patch object.
```
> [release/v2.23] Add OSP to the MD patch object

- modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/component.ts
- modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/shared/entity/cluster.ts
- modules/web/src/app/shared/entity/preset.ts
- modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
- modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
Add functionality to configure `basePath` in preset and cluster for vSphere.
**Add Preset Dialog:**
**Create Cluster Wizard:**
xref https://github.com/kubermatic/kubermatic/issues/12632
/kind feature
```release-note
Add functionality to configure `basePath` in preset and cluster for vSphere.
```
```documentation
TBD
```
> Add functionality to configure `basePath` in preset and cluster for vSphere

- modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/template.html
- modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
- modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
Replace base folder path dropdown with an input field for vSphere. Also update field description in both preset dialog and cluster wizard.
**Preset Dialog:**
**Create Cluster Wizard:**
xref https://github.com/kubermatic/kubermatic/issues/12632
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Replace base folder path dropdown with an input field

- modules/api/pkg/handler/websocket/terminal.go
Follow-up to #6283, bumping the image version after @xrstf has built the `0.7.0` tag of the image.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update to `quay.io/kubermatic/web-terminal:0.7.0`

- modules/api/pkg/handler/websocket/terminal.go
Follow-up PR to #6284, bumping the image version to `0.6.2` after @xrstf has built them. Apparently we never released 0.6.1 although it was bumped at some point, but alas.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.23] Update to `quay.io/kubermatic/web-terminal:0.6.2`

- hack/images/web-terminal/Dockerfile
- hack/images/web-terminal/release.sh
- hack/lib.sh
- modules/api/pkg/handler/websocket/terminal.go
Update dependencies in web-termial docker image and bump util version
/kind chore
```release-note
Update web-terminal image to kubectl 1.25.14, Helm 3.12.3 and curl 8.4.0
```
```documentation
NONE
```
> [release/v2.22] Update dependencies in web-termial docker image and bump util version

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v1/types.go
- modules/api/pkg/handler/common/cluster.go
- modules/api/pkg/test/e2e/utils/apiclient/models/cluster_health.go
Followup to https://github.com/kubermatic/dashboard/pull/6256, the kubelb status is not displayed on the dashboard, I think it might be due to a missing translation from the API.
```
$ k get cluster kdph8trwp7 -o json | jq '.status.extendedHealth.kubelb'
"HealthStatusUp"
```
see also: https://github.com/kubermatic/kubermatic/issues/12676
/kind cleanup
I am not sure how to test this locally as the instructions seem to be out of date https://github.com/kubermatic/dashboard/blob/v2.23.4/Development.md
```release-note
NONE
```
```documentation
NONE
```
> Propagate KubeLB cluster status to dashboard

- modules/web/src/app/wizard/step/cluster/component.ts
There was error thrown during edit/customize cluster template due to invalid value of Allowed IP Ranges for NodesPorts. This has been fixed by reading value from `cidrBlocks` property.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix issue caused by invalid value of allowed IP ranges for NodePorts

- modules/web/src/app/cluster/details/cluster/cni-version/component.ts
Fixes a bug where available version upgrades for CNI plugins were not being properly deduced.
Fixes #
/kind bug
```release-note
Fixes a bug where available version upgrades for CNI plugins were not being properly deduced
```
```documentation
NONE
```
> Fix for determining available CNI version upgrades

- modules/web/src/app/node-data/component.ts
There was an issue where a custom OSP value was not selected when editing/customizing cluster template. This has been fixed by avoiding unnecessary trigger of `valueChanges` event.
Fixes #6316 
Close #6309 
/kind bug
```release-note
Fix an issue where a custom OSP value was not selected when editing/customizing cluster template.
```
```documentation
NONE
```
> Set default OS value only when it's different from selected OS value

- modules/web/src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
This PR fixes an issue where label of Floating IP Pools (in Openstack provider settings step) would keep displaying `Loading...` when there were no pools available.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Set Floating IP Pools label to empty if there are no pools available

- modules/api/pkg/handler/common/cluster.go
- modules/api/pkg/handler/v2/external_cluster/external_cluster.go
Since controller-runtime introduced the new caching config, we had to explicitly enable caches per namespace. Looking at our dev system, I spotted
> {"level":"error","time":"2023-10-26T06:36:58.837Z","caller":"handler/routing.go:153","msg":"unable to list: default because of unknown namespace for the cache","request":"/api/v2/projects/wt8bxznl97/kubernetes/clusters/2g6zd8vwkw/events"}
Looking deeper, it seemed that we accidentally specified a namespace when ExternalClusters are not namespaced.
Fixes #6331
We can backport this, even though the error should only surface with controller-runtime 0.16, i.e. KKP 2.24.
/kind bug
```release-note …
```
> fix listing events for external clusters

- modules/web/src/app/cluster/details/external-cluster/template.html
- modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/template.html
- modules/web/src/app/shared/components/external-cluster-credentials/provider/gke/component.ts
- modules/web/src/app/shared/components/external-cluster-credentials/provider/gke/template.html
- modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
* send the encode value of service Account instead of the string value
* remove the `cluster version`  property from the external cluster detail since it's control plan version already show the version 
Fixes #6333
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix GKE Credentials validation

- modules/web/src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/component.ts
- modules/web/src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html
disable the deletion button on the delete external cluster dialog for EKS in case there is any nodegroup 
Fixes #6335 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Add disableDeletion method in EKS 

- modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
remove the disable method for the vmsizes form control when fetching VMs
Fixes #6347 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Remove the disable method for vmsizes

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.spec.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
Since OpenVPN support is now deprecated, Konnectivity is enabled and enforced by default.
Ref: https://github.com/kubermatic/kubermatic/pull/12691
Fixes #
/kind feature
```release-note
Enforce Konnectivity value because OpenVPN support is now deprecated.
```
```documentation
NONE
```
> Enforce Konnectivity value because OpenVPN support is deprecated

- modules/web/src/app/shared/components/event-rate-limit/component.ts
Set `eventRateLimitConfig` to `null` instead of deleting service getter method. This fixes an issue where unselecting `Event Rate Limit` option from Admission Plugins doesn't remove `eventRateLimitConfig` from the cluster spec object.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Set `eventRateLimitConfig` to `null` instead of calling `delete` on service getter method

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
Prevent `clusterDefaultNodeSelector` label from being added on opening of edit cluster dialog if those labels are not present in cluster object.
Fixes #5979 
/kind bug
```release-note
Fix an issue where `clusterDefaultNodeSelector` label was being added back on opening of edit cluster dialog.
```
```documentation
NONE
```
> Prevent `clusterDefaultNodeSelector` label from being added on opening of edit cluster dialog

- modules/api/pkg/handler/middleware/middleware.go
- modules/api/pkg/handler/v1/cluster/cluster.go
- modules/api/pkg/handler/v1/project/project.go
- modules/api/pkg/handler/v2/cluster/cluster.go
- modules/api/pkg/handler/v2/preset/preset.go
- modules/api/pkg/handler/v2/seedoverview/seedoverview.go
- modules/api/pkg/provider/kubernetes/etcdbackupconfig.go
- modules/api/pkg/provider/kubernetes/etcdrestore.go
- modules/web/src/app/core/services/cluster.ts
in case of error come when fetching clusters from seed don't return the error and keep fetching clusters from other seeds 
Fixes #6056
/kind bug
```release-note
Fix issue with managing clusters if some seeds are down. 
```
```documentation
NONE
```
> Don't return error in case one of a seed down

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere.go
- modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere_cloud_spec.go
- modules/web/src/assets/config/changelog.json
This bumps the `k8c.io/kubermatic/v2` dependency and adds a changelog entry for partial cluster listing, added in #6374.
This is the last PR planned for 2.24.0-rc.0.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Bump `k8c.io/kubermatic/v2` and add changelog entry for partial cluster  list

- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go
- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
- modules/web/src/app/node-data/component.ts
As followup to https://github.com/kubermatic/operating-system-manager/pull/330 this PR makes flatcar selectable with VMWare Cloud director and also sets the default osp
Addresses the UI Part for https://github.com/kubermatic/kubermatic/issues/12576 
/kind feature
```release-note
VMware-cloud-director: Added Flatcar as supported os
```
```documentation
NONE
```
> Added flatcar for VMWare Cloud Director to the UI

- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go
- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
- modules/web/src/app/node-data/component.ts
Add flatcar as supported OS for GCE.
Fixes https://github.com/kubermatic/kubermatic/issues/12728
/kind feature
```release-note
Flatcar is now supported on GCE
```
```documentation
NONE
```
> Add flatcar as supported OS for GCE

- modules/web/src/app/wizard/step/applications/component.ts
This PR fixes following issues of applications when editing cluster template:
- Not possible to edit the name, namespace and version of pre-selected applications. 
- Not possible to add new applications if cluster template didn't have any application.
- Delete an application would delete all pre-selected applications of cluster tempalte.
Fixes #6413 
/kind bug
```release-note
Fix issue in editing and updating applications of cluster template.
```
```documentation
NONE
```
> Fix issue in editing and updating applications of cluster template

- modules/web/src/app/shared/components/editor/component.ts
There was an issue with cursor position inside Monaco Editor which was caused by inconsistent rendered size of `Inconsolata` font. This PR removes the usage of `Inconsolata` font for Monaco editor and uses the default font with some reduced font size.
Fixes #6412 
/kind bug
```release-note
Fix issue with cursor position inside YAML editor.
```
```documentation
NONE
```
> Use default font to fix cursor position issue in monaco editor

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
This bumps the build images and scripts to Go 1.20.12. Prow jobs are updated in https://github.com/kubermatic/infra/pull/2508.
Towards https://github.com/kubermatic/release/issues/22
/kind chore
```release-note
KKP Dashboard is now built with Go 1.20.12
```
```documentation
NONE
```
> [release/v2.23] Update to Go 1.20.12

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/chrome-headless/release.sh
- modules/web/containers/custom-dashboard/Dockerfile
This bumps the build images and scripts to Go 1.21.5. Prow jobs are updated in https://github.com/kubermatic/infra/pull/2508.
Towards https://github.com/kubermatic/release/issues/22
/kind chore
```release-note
KKP Dashboard is now built with Go 1.21.5
```
```documentation
NONE
```
> Update Go to 1.21.5

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/custom-dashboard/Dockerfile
This bumps the build images, scripts and Dockerfiles to Go 1.21.5. Prow jobs are updated in https://github.com/kubermatic/infra/pull/2508.
Towards https://github.com/kubermatic/release/issues/22
/kind chore
```release-note
KKP Dashboard is now built with Go 1.21.5
```
```documentation
NONE
```
> [release/v2.24] Update Go to 1.21.5

- modules/web/src/app/node-data/component.ts
In KKP we have support for GCP i.e. Google Cloud Platform. Similarly, machine-controller also supports creating machines on Google Cloud using the Google Compute Engine. Hence the drift in the name; GCP and GCE for KKP and machines respectively.
This PR fixes an issue where Operating System Profiles for GCP were not being listed properly because of this drift.
Fixes #
/kind bug
```release-note
Fix a bug where Operating System Profiles were not being listed for GCP
```
```documentation
NONE
```
> Fix operating system profile filter for GCP

- modules/web/src/app/node-data/component.ts
This is a manual cherry-pick of #6453
/kind bug
```release-note
Fix a bug where Operating System Profiles were not being listed for GCP
```
> [release/v2.22] Fix operating system profile filter for GCE 

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
- modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go
- modules/api/pkg/provider/cloud/aws/client.go
Kubernetes 1.29 support has been merged into k8c.io/kubermatic, this updates the dependency. In addition, we are building the dashboard with Go 1.21, so this updates the `go.mod` file accordingly.
cc @xrstf for awareness.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update k8c.io/kubermatic/v2 dependency to `223a5c1`

- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/style.scss
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/template.html
- modules/web/src/app/shared/entity/backup.ts
add new field in the add backup/schedule to chose whether pod volume file system backup should be used for all volumes by default.
also for changing the default value of BSL and removing the destinations.
In an upcoming PR, the list of BSL will be added.
```release-note
NONE
```
```documentation
NONE
```
> Add new option for default volumes file system 

- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
For details: https://github.com/kubermatic/kubermatic/issues/12920
Fixes https://github.com/kubermatic/kubermatic/issues/12920
/kind feature
```release-note
Option to enable Cilium Ingress capabilities for user clusters
```
```documentation
NONE
```
> Option to enable Cilium Ingress for user clusters

- modules/api/pkg/provider/kubernetes/preset.go
Looks like the preset-to-spec logic never set the load balancer SKU. I'm surprised to see this, but there are no other references to those fields in the dashboard code.
This PR sets the field from the preset. If it's empty, there is still defaulting code in KKP that will put `basic` as value.
Fixes https://github.com/kubermatic/kubermatic/issues/13063
/kind bug
```release-note
Set LoadBalancerSKU on Azure clusters if the field is set in the preset
```
```documentation
NONE
```
> Set LoadBalancerSKU from Azure preset

- modules/api/go.mod
- modules/api/go.sum
After I cleaned out non-versioned container images, we need to bump the dashboard to one KKP commit that does have images available again.
```release-note
NONE
```
```documentation
NONE
```
> bump to latest KKP 2.23 commit

- modules/api/pkg/handler/websocket/terminal.go
The security context is redundant in this case. It's used to configure the group and user for the web-terminal. Although we now already configure this in the container image https://github.com/kubermatic/dashboard/blob/main/hack/images/web-terminal/Dockerfile#L31-L40
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Drop additional configuration for web-terminal pod

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/delete-dialog/template.html
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
fix an issue with choosing BSL in the cluster creation wizard and show the `displayName` for the user instead of the `name`
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix select BSL on cluster creation

- modules/api/pkg/provider/kubernetes/cluster.go
Machine controller health check must be excluded when the edge cloud provider is used. This PR guarantees that no check for machine controller is present when the edge provider used. Another PR will be open in KKP to mitigate that abstract machine controller health check over there.  
Fixes #
/kind bug
```release-note
None
```
```documentation
None
```
> Exclude machine controller health check when edge provider is used

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
Hide cluster backup feature in cluster creation and in edit cluster if the feature is disabled from the admin.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Hide cluster backup feature for user cluster

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v2/types.go
- modules/api/pkg/handler/test/helper.go
- modules/api/pkg/handler/v2/application_definition/application_definition.go
- modules/api/pkg/handler/v2/application_definition/application_definition_test.go
- modules/api/pkg/handler/v2/application_definition/conversion.go
- modules/api/pkg/handler/v2/application_installation/application_installation.go
- modules/api/pkg/handler/v2/application_installation/application_installation_test.go
- modules/api/pkg/handler/v2/application_installation/conversion.go
- modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_spec.go
This PR adds makes the new fields valuesBlock and defaultValuesBlock of AppInstalls and AppDefs available in the api. In addition on POST & PUT requests for AppInstalls/AppDefs the values/defaultValues fields are being converted to their valuesBlock/defaultValuesBlock equivalent.
Fixes https://github.com/kubermatic/kubermatic/issues/12941
/kind feature
```release-note
valuesBlock and defaultValuesBlock fields are now available via the api
```
```documentation
NONE
```
> Add valuesBlock and defaultValuesBlock and their conversion

- modules/web/src/app/cluster/details/cluster/edit-provider-settings/vsphere-provider-settings/component.ts
- modules/web/src/app/cluster/details/cluster/edit-provider-settings/vsphere-provider-settings/template.html
Infra management credentials should not be "required" as they are optional credentials. 
Fixes #6550
/kind bug
```release-note
vSphere: fix a bug where dedicated credentials were incorrectly being required as mandatory input when editing provider settings for a cluster
```
```documentation
NONE
```
> Fix handling of cloud credentials for vSphere when editting provider

- modules/web/src/app/core/services/wizard/provider/nutanix.ts
Fix invalid project ID in API requests for Nutanix provider.
Fixes #6571 
/kind bug
```release-note
Fix invalid project ID in API requests for Nutanix provider.
```
```documentation
NONE
```
> Fix invalid project ID in API requests for Nutanix provider

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/images/web-terminal/Dockerfile
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/chrome-headless/release.sh
- modules/web/containers/custom-dashboard/Dockerfile
This bumps KKP to Go 1.22.1, which comes with some important fixes: https://groups.google.com/g/golang-announce/c/Fm51GRLNRvM/m/F5bwBlXMAQAJ
/kind chore
```release-note
Update to Go 1.22.1
```
```documentation
NONE
```
> update to Go 1.22.1

- Makefile
- modules/api/Makefile
- modules/api/go.mod
- modules/api/go.sum
- modules/web/Makefile
- modules/web/package-lock.json
- modules/web/package.json
This bumps KKP to the version I'm going to tag as beta.3 after this PR got merged.
```release-note
Bump KKP for v2.25.0-beta.3
```
```documentation
NONE
```
> bump to future KKP 2.25.0-beta.3

- modules/api/pkg/resources/machine/machinedeployment.go
The edge provider is not supported by machine controller by design since it doesn't play any role in the node lifecycle. Thus the replica should be set to 1 and the status should be also updated.
Fixes #
/kind bug
```release-note
None
```
```documentation
None
```
> Set replicas to 1 when edge provider is used

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v1/types.go
- modules/api/pkg/test/e2e/utils/apiclient/models/application_spec.go
Fixes an issue where the valuesBlock field did not get rendered in the clusters' `kubermatic.io/initial-application-installations-request` annotation.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> add valuesblock to api type used by cluster generation

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This updates all references to Go to version 1.21.8, released 2 days ago.
/kind chore
```release-note
Update to Go 1.21.8
```
```documentation
NONE
```
> [release/v2.24] Bump to Go 1.21.8

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This updates all references to Go to version 1.20.13.
/kind chore
```release-note
Update to Go 1.20.13
```
```documentation
NONE
```
> [release/v2.23] Bump to Go 1.20.13

- modules/web/src/app/cluster/details/cluster/component.ts
Enable web terminal button when at least one MD replica is ready.
Fixes #6601 
/kind bug
```release-note
Enable web terminal button when at least one MD replica is ready.
```
```documentation
NONE
```
> Enable web terminal button when at least one MD replica is ready

- modules/api/pkg/handler/common/machine.go
- modules/api/pkg/resources/machine/machinedeployment.go
For the edge provider, the machine deployment replicas should be ignored as it plays no role at all. This PR remove the update of the machine deployment status replicas.  
Fixes #
```release-note
None
```
```documentation
None
```
> Revert the machine deployment status

- modules/api/cmd/kubermatic-api/main.go
- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/cmd/kubermatic-api/wrappers_ce.go
- modules/api/cmd/kubermatic-api/wrappers_ee.go
- modules/api/pkg/ee/clusterbackup/storage-location/handler.go
- modules/api/pkg/ee/clusterbackup/storage-location/provider.go
- modules/api/pkg/ee/cmd/kubermatic-api/wrappers.go
- modules/api/pkg/handler/v2/clusterbackup/storage-location/cbsl.go
- modules/api/pkg/handler/v2/clusterbackup/storage-location/wrappers_ce.go
- modules/api/pkg/handler/v2/clusterbackup/storage-location/wrappers_ee.go
- modules/api/pkg/provider/types.go
Allow non admin users to manage backup storage location.
Fixes #6563 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Allow non admin users to manage BSL

- modules/web/src/app/cluster/details/cluster/machine-deployment-list/template.html
- modules/web/src/app/cluster/details/shared/version-change-dialog/component.ts
- modules/web/src/app/cluster/details/shared/version-change-dialog/template.html
- modules/web/src/app/cluster/details/shared/version-picker/component.ts
- modules/web/src/app/wizard/step/cluster/component.ts
In cluster version change dialog, sort the versions list in descending order and hide the update available icon when there is no updates.
Fixes #6524 
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Hide the update available icon when there is no updates

- Makefile
- modules/api/Makefile
- modules/api/go.mod
- modules/api/go.sum
- modules/web/Makefile
- modules/web/package-lock.json
- modules/web/package.json
Bumps the KKP dependency to the latest 2.23 revision.
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.23] bump for 2.23.12

- modules/web/angular.json
`defaultProject` is obsolete and not used anymore
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Remove defaultProject from angular.json

- modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/gke/style.scss
- modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
- modules/web/src/app/shared/directives/value-changed-indicator.ts
- modules/web/src/assets/css/global/_main.scss
- modules/web/src/assets/css/global/_theme.scss
- modules/web/src/assets/css/material/_main.scss
- modules/web/src/assets/css/material/_theme.scss
migrates Angular Material Radio components from legacy to v15.
xref #5864 
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> migrate mat-radio component to v15

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/.golangci.yml
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
Fixes #
/kind chore
```release-note
Update to Go 1.22.2
```
```documentation
NONE
```
> [release/v2.25] Upgrade golang to 1.22.2 for v2.25 release branch

- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/cluster/details/cluster/node-list/style.scss
- modules/web/src/app/cluster/details/cluster/node-list/template.html
- modules/web/src/app/cluster/details/external-cluster/external-node-list/style.scss
- modules/web/src/app/cluster/details/external-cluster/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/style.scss
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/style.scss
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/schedule/style.scss
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/schedule/template.html
- modules/web/src/app/dynamic/enterprise/metering/legacy-reports/card/style.scss
- modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss
- modules/web/src/app/external-cluster-wizard/style.scss
- modules/web/src/app/kubeone-wizard/style.scss
- modules/web/src/app/settings/admin/defaults/style.scss
- modules/web/src/app/settings/admin/defaults/template.html
- modules/web/src/app/shared/components/chip/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/shared/components/event-card/style.scss
- modules/web/src/app/shared/components/labels/component.ts
- modules/web/src/app/shared/components/labels/style.scss
- modules/web/src/app/shared/components/labels/template.html
- modules/web/src/app/shared/components/taints/template.html
- modules/web/src/app/wizard/step/cluster/template.html
- modules/web/src/app/wizard/style.scss
- modules/web/src/assets/css/material/_main.scss
- modules/web/src/assets/css/material/_theme.scss
migrates Angular Material card and chip components from legacy to v15.
xref #5864
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Migrate card-chip component version 15

- modules/web/src/app/settings/admin/defaults/style.scss
- modules/web/src/app/settings/admin/defaults/template.html
Better wording to make the OIDC/admin Kubeconfig settings more coherent.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Improve wording for OIDC Kubeconfig settings

- modules/api/pkg/handler/common/upgrade.go
It looks like the API code never used the logic provided by KKP to determine conditions that are used in decision-making on possible upgrade paths. This was changed in https://github.com/kubermatic/kubermatic/pull/13046, but the old logic was also not called (its logic seemed to be copy-pasted into the API code though), so the drift wasn't detected.
This PR removes the logic to determine conditions from the API code and instead just re-uses `k8c.io/kubermatic/v2/pkg/version/clusterGetVersionConditions`, as the KKP code does.
Fixes #
/kind bug …
> api: don't construct upgrade conditions, use KKP logic instead

- modules/web/src/app/core/module.ts
- modules/web/src/app/hotfix-mat-select.ts
- modules/web/src/app/shared/module.ts
Hotfix to mitigate a bug in new releases of chromium that causes a browser crash on `mat-select` component.
- https://issuetracker.google.com/issues/335553723
- https://github.com/angular/components/issues/28905
Fixes #
/kind bug
```release-note
Hotfix to mitigate a bug in new releases of chromium that causes browser crashes on `mat-select` component. For more details: https://issuetracker.google.com/issues/335553723
```
```documentation
NONE
```
> [release/2.24] hotfix: browser crashes on mat-select

- modules/web/src/app/core/module.ts
- modules/web/src/app/hotfix-mat-select.ts
- modules/web/src/app/shared/module.ts
Hotfix to mitigate a bug in new releases of chromium that causes a browser crash on `mat-select` component.
- https://issuetracker.google.com/issues/335553723
- https://github.com/angular/components/issues/28905
Fixes #
/kind bug
```release-note
Hotfix to mitigate a bug in new releases of chromium that causes browser crashes on `mat-select` component. For more details: https://issuetracker.google.com/issues/335553723
```
```documentation
NONE
```
> [release/2.23] hotfix: browser crashes on mat-select

- modules/web/src/app/node-data/basic/provider/vsphere/component.ts
Fixes #6400 #6643
/kind bug
```release-note
Fix template value for machine deployments in edit mode
```
```documentation
NONE
```
> Fix vSphere default template value

- modules/web/src/app/cluster/details/cluster/cni-version/style.scss
- modules/web/src/app/cluster/details/cluster/cni-version/template.html
- modules/web/src/app/cluster/details/cluster/cni-version/theme.scss
- modules/web/src/app/cluster/details/shared/version-picker/style.scss
- modules/web/src/app/cluster/details/shared/version-picker/theme.scss
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/style.scss
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/style.scss
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/schedule/style.scss
- modules/web/src/assets/css/global/_main.scss
- modules/web/src/assets/css/global/_theme.scss
- modules/web/src/assets/css/material/_main.scss
- modules/web/src/assets/css/material/_theme.scss
- modules/web/src/assets/themes/dark.scss
- modules/web/src/assets/themes/light.scss
migrates Angular Material tool-tip, form-field, mat-option and mat-select components from legacy to v15.
**Add MachineDeployment**
**wizard**
xref #5864
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Migrate form-field and tool-tip component version 15 (#6655)

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/cluster/details/cluster/template.html
- modules/web/src/app/node-data/component.ts
- modules/web/src/app/node-data/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/shared/components/save-cluster-template/component.ts
- modules/web/src/app/shared/entity/cluster.ts
- modules/web/src/app/wizard/component.ts
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
- modules/web/src/app/wizard/step/summary/component.ts
The user-data plugins from machine-controller [have been removed](https://github.com/kubermatic/machine-controller/pull/1789). OSM is mandatory now to create a functional cluster since we can't fall back to user-data generated by machine-controller anymore.
Fixes #
/kind cleanup
```release-note
The option to disable the operating system manager on cluster creation has been removed.
```
```documentation
NONE
```
> OSM is always enabled

- modules/api/pkg/provider/cloud/vmwareclouddirector/provider.go
We have placement policies without a description, which causes the requests to fail. This PR just adds a nil check
```2024/05/24 11:36:17 http: panic serving 10.244.0.53:58594: runtime error: invalid memory address or nil pointer dereference
goroutine 2216644 [running]:
net/http.(*conn).serve.func1()
net/http/server.go:1898 +0xbe
panic({0x487dc60?, 0xc096cc0?})
runtime/panic.go:770 +0x132
k8c.io/dashboard/v2/pkg/provider/cloud/vmwareclouddirector.ListComputePolicies({0x30?, 0xc0016d7808?}, {{0x0, 0x0}, {0x0, 0x0}, {0xc002bd2420, 0x20}, {0xc000ce565c, 0x4}, ...})
k8c.io/dashboard/v2/pkg/provider/cloud/vmwareclouddirector/provider.go:220 +0x2c2
k8c.io/dashboard/v2/pkg/handler/v2.Routing.listVMwareCloudDirectorComputePoliciesNoCredentials.VMwareCloudDir …
```
> fix: Added nil check to prevent exception on policy load

- modules/api/go.mod
- modules/api/go.sum
Fixes issue of prematurely cancelled context when reading response from openstack
See more: https://github.com/gophercloud/gophercloud/issues/2969
```release-note
Update github.com/gophercloud/gophercloud to 1.11.0
```
```documentation
NONE
```
> [release/v2.25] Update github.com/gophercloud/gophercloud to 1.11.0

- Makefile
Now that `spec.api.dockerTag` is a thing, it also needs to be set explicitly when deploying to dev.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> fix dev deployment

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/handler/v2/preset/preset.go
- modules/api/pkg/test/e2e/utils/apiclient/client/preset/list_presets_parameters.go
- modules/api/pkg/test/e2e/utils/apiclient/client/preset/list_project_presets_parameters.go
- modules/api/pkg/test/e2e/utils/apiclient/client/preset/list_project_provider_presets_parameters.go
- modules/api/pkg/test/e2e/utils/apiclient/client/preset/list_provider_presets_parameters.go
- modules/web/src/app/cluster/details/cluster/component.spec.ts
- modules/web/src/app/cluster/details/cluster/component.ts
- modules/web/src/app/cluster/details/cluster/template.html
- modules/web/src/app/core/services/wizard/presets.ts
- modules/web/src/app/shared/utils/health-status.ts
- modules/web/src/test/services/preset-mock.ts
Display the name of the preset used when creating the cluster on the cluster detail page.
Fixes #5656 
/kind feature
```release-note
Display the used preset name on the cluster detail page.
```
```documentation
NONE
```
> Display the used preset in cluster page

- modules/web/src/app/wizard/step/cluster/component.ts
Fixes a bug where CNI was always being defaulted to cilium irrespective of what was configured in the cluster template or default cluster template.
Fixes #
/kind bug
```release-note
Fix a bug where CNI was always being defaulted to cilium irrespective of what was configured in the cluster template or default cluster template
```
```documentation
NONE
```
/cherry-pick release/v2.25
> Fix defaulting for CNI

- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/schedule/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/schedule/template.html
- modules/web/src/app/shared/entity/backup.ts
add a check box to select all namespaces, and show the name of the `CBSL`  that was used during cluster creation.
Fixes #6700 
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Add a "Backup All Namespaces" Checkbox

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- docs/proposals/testing.md
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This PR is to update Go version to 1.22.4.
Related to https://github.com/kubermatic/infra/pull/2707
Fixes #
/kind chore
```release-note
Update Go version to 1.22.4
```
```documentation
NONE
```
> Bump Go version to 1.22.4

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- docs/proposals/testing.md
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This PR is to update Go version to 1.21.11
Related to https://github.com/kubermatic/infra/pull/2707
Fixes #
/kind chore
```release-note
Update Go version to 1.21.11
```
```documentation
NONE
```
> [release/v2.24] Updated Go version to 1.21.11

- modules/web/src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html
- modules/web/src/app/settings/admin/presets/dialog/steps/preset/template.html
- modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vmware-cloud-director/template.html
- modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/template.html
- modules/web/src/app/shared/components/chip-list/component.ts
- modules/web/src/app/wizard/step/cluster/style.scss
- modules/web/src/app/wizard/step/cluster/template.html
Adjust the km-chip-list component so that the user can add multiple values separated by commas or spaces all at once.
Fixes #6684
/kind cleanup
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Adjust chip list component to have multiple values at once

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This PR is to update the Go version to 1.22.5
Related to https://github.com/kubermatic/infra/pull/2765
Fixes #
/kind chore
```release-note
Update Go version to 1.22.5
```
```documentation
NONE
```
> Bump Go version to 1.22.5

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This PR is to update the Go version to 1.21.12
Related to https://github.com/kubermatic/infra/pull/2765
Fixes #
/kind chore
```release-note
Update Go version to 1.21.12
```
```documentation
NONE
```
> [release/v2.24] Bump Go version to 1.21.12

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This PR is to update the Go version to 1.22.5
Related to https://github.com/kubermatic/infra/pull/2765
Fixes #
/kind chore
```release-note
Update Go version to 1.22.5
```
```documentation
NONE
```
> [release/v2.25] Bump Go version to 1.22.5

- modules/api/cmd/kubermatic-api/main.go
- modules/api/cmd/kubermatic-api/swagger.json
While technically correct, the warning about the API stability is causing uncertainty with integrators. In practice the KKP REST API is not going away anytime soon, especially not in KKP 2.x, given KKP's architecture and inherent limitations.
CRDs are still the way to go for "simple" setups or setups where a singular entity is managing KKP (like when you have a GitOps pipeline and only scripts modify KKP directly, instead of all members in a team individually connecting to KKP). But I can see how my strong stance on deprecating and de-emphasizing the REST API might have caused more friction than I intended.
/cc @moadqassem 
/kind cleanup …
> remove scary deprecation warning

- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/style.scss
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/template.html
add a yaml editor in the backup storage location dialog to configure the BSL  config.
Fixes #6732 
/kind feature
```release-note
Add a `yaml` block field to add additional parameters to the `config` for the backup storage location 
```
```documentation
NONE
```
> Add YAML editor to configure CBSL config

- modules/web/src/app/wizard/step/cluster/component.ts
Support for eBPF proxy mode when the CNI plugin is none.
Fixes #6755
/kind bug
```release-note
Support for eBPF proxy mode when the CNI plugin is none.
```
```documentation
NONE
```
> Allow eBPF proxy mode when cni is none

- modules/api/pkg/provider/kubernetes/preset.go
This PR will fix nil pointer issue because we're copying kubeconfig from kubevirt when baremetal provider is enabled 
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Fix setBaremetal Credential 

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/shared/directives/value-changed-indicator.ts
- modules/web/src/app/shared/model/NodeProviderConstants.ts
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/assets/css/global/_main.scss
add new option to edit the allowed ip ranges in the edit cluster dialog for the supported providers.
**edit cluster dialog**
Fixes #6772
/kind feature
```release-note
Enable editing allowed IP ranges for NodePorts 
```
```documentation
NONE
```
> Enable editing allowed IP ranges for NodePorts

- modules/api/.golangci.yml
```
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
```
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
/assign
/cc @Waseem826
> Remove deprecated linter exportloopref

- modules/web/src/app/core/components/help-panel/component.ts
- modules/web/src/app/core/components/help-panel/template.html
update the user settings after opening the release notes page.
Fixes #6819 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix the "What's new" notification

- hack/images/web-terminal/.bashrc
Since Helm 3.3.3, warning messages are displayed when the KUBECONFIG permissions are group/world readable. https://github.com/helm/helm/pull/8779 writes them to stderr.
The warnings are displayed when opening the web terminal, as 'helm completion' execs when the .bashrc is sourced:
... this confuses unexperienced users.
/kind enhancement
```release-note
Fix: remove 'WARNING: Kubernetes configuration file is {group,world}-readable' when launching the Web Terminal.
```
```documentation
NONE
```
> Web terminal: fix warning when sourcing .bashrc

- modules/web/src/app/cluster/details/cluster/edit-provider-settings/vsphere-provider-settings/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/wizard/step/provider-settings/provider/basic/vsphere/template.html
This PR changes the labels for the vSphere InfraManagement credentials to reflect that these credentials are used to manage and provision the infrastructure.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> correct labels for vSphere InfraManagement credentials

- Makefile
- modules/api/Makefile
- modules/api/go.mod
- modules/api/go.sum
- modules/web/Makefile
- modules/web/package-lock.json
- modules/web/package.json
- modules/web/src/assets/config/changelog.json
An upgrade issue in KKP was identified and we will most likely release another out-of-bands release for 2.25.x only very soon.
cf. https://github.com/kubermatic/kubermatic/issues/13734
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.25] prepare 2.25.10

- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/add-dialog/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/add-dialog/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/template.html
- modules/web/src/app/shared/entity/backup.ts
- modules/web/src/app/shared/utils/health-status.ts
- modules/web/src/app/shared/validators/cron.validator.ts
- modules/web/src/app/shared/validators/others.ts
Fix bugs and implement some enhancements for the cluster backup feature.
* Backup storage location page
* Validation for units of backup sync period
* cluster backup expires in validation
* for now we don't have a message for backup errors we agree to have this message for 2.26 and in the next release will add the message 
* download backup or create restore will not be enable if the backup not in running state 
* create schedule validation
*  create schedule text overflow fixed
Fixes #6864
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Cluster backup enhancements

- modules/web/src/app/node-data/basic/provider/vsphere/component.ts
This PR fixes an issue where selected value of vSphere VMGroup was not shown in edit MD dialog.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Show selected value of vSphere VMGroup in edit MD dialog

- modules/api/pkg/handler/v2/cluster_default/cluster_default.go
Manual backport of https://github.com/kubermatic/dashboard/pull/6878
Fixes #
/kind bug
```release-note
Fix CNI plugin defaulting for Edge cloud provider
```
```documentation
NONE
```
> [release/v2.25] Fix CNI plugin defaulting for Edge cloud provider

- modules/web/src/app/wizard/step/cluster/cilium-application-values-dialog/component.ts
- modules/web/src/app/wizard/step/cluster/component.ts
This PR fixes an issue where default values of CNI application were not loading in "Edit CNI Values" dialog. Also, now the initial CNI values are only sent to backend if user interacts with them (Enable Ingress or Save Initial CNI values).
Fixes #6859 
/kind bug
```release-note
Fix default CNI application values in cluster wizard.
```
```documentation
NONE
```
> Fix default CNI application values in cluster wizard

- modules/web/src/app/shared/components/annotation-form/template.html
- modules/web/src/app/wizard/step/cluster/component.ts
- Shorten annotation value error messages to fit in places with less space.
- Sync cluster annotations with annotation form value to handle external changes (e.g. initial CNI values).
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Annotations form improvements

- modules/web/src/app/wizard/step/cluster/cilium-application-values-dialog/component.ts
- modules/web/src/app/wizard/step/cluster/component.ts
Manual backport of https://github.com/kubermatic/dashboard/pull/6884
Fixes #
/kind bug
```release-note
Fix default CNI application values in cluster wizard.
```
```documentation
NONE
```
> [release/v2.25] Fix default CNI application values in cluster wizard

- modules/web/src/app/shared/components/labels/style.scss
- modules/web/src/app/shared/components/labels/template.html
Fix alignment of long label keys and values.
**Before**
**After**
Fixes #
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Fix alignment of long label keys and values

- hack/images/web-terminal/.bashrc
This reverts commit 5d1ec10fcd21ceaa602d316725d86f4472b2c40d.
After testing #6848, I realised the `kubeconfig` would be R/O and `0777` (https://github.com/kubernetes/kubernetes/issues/125876) since it's mounted from a secret inside the web-terminal pod. This would result on an extra error on the web-terminal startup: 
```
chmod: /etc/kubernetes/kubeconfig: Read-only file system
```
... rather than solving the warnings from Helm that #6848 intended to fix. This would require a more complex solution involving `fsGroup` + `initContainers` probably.
CC/ @ahmedwaleedmalik @Waseem826 as you took care of the previous PR. Sorry for the noise! 
**Which issue(s) this PR fixes**: N/A
/kind bug …
> Revert "Web terminal: fix warning when sourcing .bashrc (#6848)"

- modules/web/src/app/settings/admin/presets/dialog/steps/settings/template.html
- modules/web/src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
- modules/web/src/app/wizard/step/provider-settings/provider/basic/openstack/template.html
- Display preset floating IP pool value if dropdown options are empty
- Move customizable preset checkbox outside optional restrictions section
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Customizable openstack preset fixes

- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/component.ts
fix adding `config` to cluster backup storage location.
Fixes #6902 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix add config to CBSL

- modules/web/src/app/shared/components/labels/component.ts
- modules/web/src/app/shared/components/labels/style.scss
This PR fixes the issue where the "SHOW MORE" button is displayed even when there are no more labels to show.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix `SHOW MORE` labels button

- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go
- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
This is PR will add baremetal to OSP, in order to generate OSP for baremetal nodes and execute cloud-init scripts
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Add baremetal to SupportedCloudProviders list in OSP

- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go
- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
- modules/api/pkg/resources/machine/machinedeployment.go
This PR adds the baremetal provider to the SupportedCloudProviders list of Ubuntu and add Baremetal provider to the node deployment Validate function
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.26] Add baremetal to osp-ubuntu

- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go
- modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
- modules/api/pkg/resources/machine/machinedeployment.go
This PR will allow ubuntu OSP only for baremetal provider add Baremetal provider to the node deployment Validate function
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Allow Ubuntu OSP only for baremetal provider

- modules/web/src/app/project/component.ts
- modules/web/src/app/project/edit-project/component.spec.ts
- modules/web/src/app/project/edit-project/component.ts
- modules/web/src/app/project/edit-project/template.html
- modules/web/src/app/shared/components/add-project-dialog/component.spec.ts
- modules/web/src/app/shared/components/add-project-dialog/component.ts
- modules/web/src/app/shared/components/add-project-dialog/template.html
Only operating systems allowed by the admin will be displayed in the add/edit dialog.
**Admin panel:**
**Edit project dialog:**
**Add project dialog:**
Fixes #6952 
/kind design
```release-note
Display only the admin-allowed OS's on project add/edit dialog.
```
```documentation
NONE
```
> Display only the admin-allowed OS on project add/edit dialog

- modules/api/pkg/ee/clusterbackup/backup/handler.go
- modules/api/pkg/ee/clusterbackup/restore/handler.go
- modules/api/pkg/ee/clusterbackup/schedule/handler.go
- modules/api/pkg/kubernetes/helper.go
This ensures empty label selectors are removed in order to not confuse Velero.
Fixes #6970
/kind bug
```release-note
[EE] Fix Cluster Backups failing because of empty label selectors.
```
```documentation
NONE
```
> remove empty LabelSelector in Velero objects

- modules/api/cmd/kubermatic-api/main.go
- modules/api/cmd/kubermatic-api/swagger.json
This PR is to bump the KKP API version in the swagger.json.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.26] Bump KKP API version to 2.26

- modules/web/src/app/cluster/details/cluster/style.scss
- modules/web/src/app/cluster/details/cluster/template.html
- modules/web/src/app/settings/admin/defaults/style.scss
- modules/web/src/app/settings/admin/defaults/template.html
- modules/web/src/app/settings/admin/opa/component.ts
- modules/web/src/app/settings/admin/opa/style.scss
- modules/web/src/app/settings/admin/opa/template.html
- modules/web/src/app/wizard/step/cluster/style.scss
- modules/web/src/app/wizard/step/cluster/template.html
add a warning message for the kkp users that OPA will be deprecated in favor of kyverno.
**create cluster wizard:**
**Cluster details page:**
The warning message will be displayed if the OPA integration is enabled for the cluster.
**Admin settings:**
Default page:
OPA page:
Fixes #6988
/kind feature
```release-note
OPA (Open Policy Agent) will be deprecated in KKP 2.28, Kyverno will replace it as an EE-only feature for policy management.
```
```documentation
NONE
```
> Add OPA deprecated warning message

- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/component.ts
- modules/web/src/app/shared/components/cluster-summary/template.html
Remove the `includedNamespaces` property when select all namespaces in the create backup/schedule 
Fixes #7032 
/kind bug
```release-note
Fix backing up all namespaces.
```
```documentation
NONE
```
> Remove the `includedNamespaces` property when select all namespaces

- modules/web/src/app/cluster/details/cluster/machine-deployment-list/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/component.ts
backport of #7032 
/kind bug
```release-note
Fixed an issue where selecting "Backup All Namespaces" in the create backup/schedule dialog for cluster backups caused new namespaces to be excluded.
```
```documentation
NONE
```
> [release/v2.25] Remove includedNamespaces when select all namespaces

- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/component.ts
backport of #7032 
/kind bug
```release-note
Fixed an issue where selecting "Backup All Namespaces" in the create backup/schedule dialog for cluster backups caused new namespaces to be excluded.
```
```documentation
NONE
```
> [release/v2.26] Remove includedNamespaces when select all namespaces (#7034)

- modules/web/src/app/wizard/step/cluster/component.ts
For cluster creation, the default value for EnableGatewayAPI and UseLoadbalancerClass will be picked from datacenter configuration.
Fixes #
/kind feature
```release-note
KubeLB: enable gateway API and use load balancer class values will now be picked from the datacenter configuration during cluster creation
```
```documentation
NONE
```
> Pick default value for KubeLB Gateway API from datacenter

- modules/web/src/app/shared/components/autocomplete/component.ts
- modules/web/src/app/shared/components/autocomplete/style.scss
- modules/web/src/app/shared/components/autocomplete/template.html
Add a new search field in options dropdown of km-autocomplete instead of using the value for filtering.
https://github.com/user-attachments/assets/1392fc94-5d60-4ad2-b68a-a62c13e79010
Fixes #7038
/kind design
```release-note
Add search field in options dropdown of autocomplete element.
```
```documentation
NONE
```
> Add search field in autocomplete options dropdown

- modules/api/pkg/handler/common/provider/baremetal.go
- modules/api/pkg/handler/common/provider/kubevirt.go
- modules/api/pkg/resources/machine/common.go
This PR fixes listing images Tinkerbell and Kubevirt functionality. 
* Code would panic if OperatingSystems[os] was nil.
* Listing Kubevirt and Tinkerbell functionality is not working anymore, because of nil sub-maps of Supported Operating systems
* In the original implementation, the code directly attempted to assign values to a sub-map within `res.Standard.OperatingSystems[os]` without verifying if the sub-map was initialized.
/kind bug
```release-note
Fix list images in kubevirt and tinkerbell 
```
```documentation
NONE
```
> Fix list images in kubevirt and tinkerbell

- modules/api/go.mod
- modules/api/go.sum
Bump KKP dependencies to the commit da427bca5c36f5840385175798bc20023e18dfb7 to support 1.32 k8s version .
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Bump KKP dependencies to the commit da427bc

- modules/web/src/app/node-data/component.ts
- modules/web/src/app/node-data/template.html
- modules/web/src/app/shared/entity/application.ts
- modules/web/src/app/shared/model/NodeSpecChange.ts
- modules/web/src/app/wizard/step/applications/component.ts
This PR adds an option to install `cluster-autoscaler` application when configuring cluster autoscaling in cluster creation wizard.
**Initial Nodes Step:**
**Applications Step:**
**Add/Edit MD Dialog:**
Fixes #6699
/kind feature
```release-note
Add new option for cluster autoscaling in initial nodes step of cluster wizard to add cluster autoscaler application.
```
```documentation
TBD
```
> Add option to install cluster autoscaling application 

- modules/api/pkg/handler/common/provider/kubevirt.go
For Kubevirt there are some storage classes that can be used for VM disk images and PVs in the tenant cluster, in addition there are other storage classes that can be used only for PVs in the tenant cluster, This PR make sure that the api would only retrieve storage classes that can be used by CDI to create VM image disks instead of fetching all the storage classes and show them in the UI. 
Fixes #
/kind feature
```release-note
Filter out KubeVirt storage classes in the API/UI based on the the volume provisioner field. 
```
```documentation
None
```
> Filter KubeVirt Storage Casses based on volume Provisioner

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This is the cousin to https://github.com/kubermatic/kubermatic/pull/14124.
/kind chore
```release-note
Update to Go 1.23.6
```
```documentation
NONE
```
> bump to Go 1.23.6

- modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
Check credentials type when evaluating required credentials for Openstack settings.
Fixes #7045 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Check credentials type when evaluating required credentials for Openstack settings

- modules/web/src/app/core/components/help-panel/component.ts
- modules/web/src/app/settings/admin/announcements/announcement-dialog/component.ts
- modules/web/src/app/settings/admin/announcements/announcement-dialog/template.html
- modules/web/src/app/settings/admin/announcements/component.ts
- modules/web/src/app/settings/admin/announcements/template.html
- modules/web/src/app/shared/components/announcement-banner/component.ts
- modules/web/src/app/shared/components/announcement-banner/style.scss
- modules/web/src/app/shared/components/announcement-banner/template.html
- modules/web/src/app/shared/components/announcements-dialog/component.ts
- modules/web/src/app/shared/components/announcements-dialog/style.scss
- modules/web/src/app/shared/components/announcements-dialog/template.html
- modules/web/src/app/shared/components/announcements-dialog/theme.scss
- modules/web/src/app/shared/module.ts
- modules/web/src/assets/css/_images.scss
- modules/web/src/assets/css/global/_main.scss
- modules/web/src/assets/css/theme/_component.scss
- modules/web/src/assets/images/icons/announcement.svg
UX and UI improvements for admin announcements.
**Announcement Banner:**
- Updated the background color.
- Change "See All" to a button instead of anchor link.
- Maximum text limit set to 3 rows.
**Announcements Dialog:**
- Increased dialog width to `1000px`.
- Added "Created" column.
- Added a different background color to unread announcements.
- Removed the redundant "Close" button in dialog footer.
**Admin Announcements Page:**
- Swapped Edit/Delete buttons.
- Added Confirmation Dialog for deleting announcement.
**Add/Edit Announcements Dialog:**
- Increased rows for announcements message.
- Updated action button text.
- Updated notification messages of adding/updating announcements.
Fixes #
**What type of PR is …
> UX and UI improvements for admin announcements

- modules/web/src/app/backup/list/automatic-backup/add-dialog/template.html
- modules/web/src/app/backup/list/component.ts
- modules/web/src/app/backup/list/snapshot/add-dialog/template.html
add errors messages  for the add dialogs,
fix etcd backup components (automatic backups, snapshot, restore) are not displayed on refresh page.
Fixes #7119 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Small enhancements for etcd 

- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/style.scss
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/add-dialog/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/add-dialog/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/style.scss
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/template.html
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/schedule/template.html
- modules/web/src/app/settings/admin/defaults/template.html
- modules/web/src/app/shared/entity/backup.ts
- modules/web/src/app/wizard/step/cluster/template.html
- modules/web/src/assets/css/global/_theme.scss
add select all namespaces for restore dialog, small enhancements, and remove the experimental tag 
Fixes #7125
/kind bug
```release-note
In the cluster backup feature, fix the issue with restoring a backup that includes all namespaces and add the option to restore all namespaces from a backup.
```
```documentation
NONE
```
> Add select all namespaces to restore and few enhancements

- modules/api/pkg/machine/convert.go
This PR covers the external cloud provider for converting the machine deployment spec into node spec. Otherwise an error such as `unknown cloud provider external: failed to get node cloud spec from machine deployment` will keep showing up in the UI. 
Fixes #
/kind bug
```release-note
None
```
```documentation
None
```
> Cover the External Cloud Spec in the API

- modules/web/package.json
Since we don't explicitly set the value for `CYPRESS_MOCK` in the npm script, it was being set as `false` in case of mock tests through https://github.com/kubermatic/dashboard/blob/main/modules/web/package.json#L27
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix `e2e:mock` script

- modules/web/jest.config.cjs
- modules/web/package-lock.json
- modules/web/package.json
- modules/web/src/app/shared/module.ts
Bring back `ngx-charts` package which is used for displaying cluster distribution pie chart on project overview page.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Bring back `ngx-charts` package

- modules/api/cmd/kubermatic-api/main.go
- modules/api/pkg/handler/auth/oidc.go
- modules/web/src/app/config.ts
- modules/web/src/app/core/services/auth/service.ts
- modules/web/src/app/core/services/token.ts
Fix the issue when the user tries to log in and is a member of many groups/roles, which results in a huge token
Fixes #7182 
/kind bug
```release-note
Fix KKP login issue when the ID token is too large to be saved in a cookie, by splitting the token into multiple cookies.
```
```documentation
TBD
```
> Split large token to multi cookies

- modules/api/go.mod
- modules/api/go.sum
This PR is to bump KKP dependency for KKP Dashboard patch release 2.27.1
previous PR https://github.com/kubermatic/dashboard/pull/7185 takes care of version bump.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.27] Bump KKP dependency for KKP Dashboard patch release 2.27.1

- modules/api/pkg/resources/machine/machinedeployment.go
This PR updates `getOperatingSystemProfile` helper to parse Node annotations instead of relying on the dc spec, which needs to be used as a default, not as an enforced OSP
Fixes https://github.com/kubermatic/kubermatic/issues/14028
/kind bug
```release-note
Updated Dashboard API to use correct OSP which is selected while creating a cluster.
```
```documentation
NONE
```
> (fix): use OSP from node instead of default OSP from dc

- Makefile
- modules/api/Makefile
- modules/api/go.mod
- modules/api/go.sum
- modules/web/Makefile
- modules/web/package-lock.json
- modules/web/package.json
- modules/web/src/assets/config/changelog.json
This PR is to bump KKP dashboard version to 2.25.15 and update KKP dependencies. 
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.25] Bump KKP dashboard version and update dependencies

- modules/web/src/app/shared/utils/member.ts
Updated the `getGroupInProject` method to return the highest-priority group role for a member within a specific project.
Fixes #7270
/kind bug
```release-note
Add role prioritization: Update logic to return the highest-priority role for members with multiple roles.
```
```documentation
NONE
```
> Add logic to select the highest priority role

- modules/web/src/app/node-data/component.ts
- modules/web/src/app/node-data/template.html
Prevent users from enabling the Cluster Autoscaler option if the corresponding application is not defined in the application definitions.
Fixes #7216 
/kind bug
```release-note
Disable the Cluster Autoscaler option when the cluster autoscaler application is not defined in applications catalog.
```
```documentation
NONE
```
> Prevent installing autoscaler if not defined in app definitions.

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v1/types.go
- modules/api/pkg/api/v1/types_test.go
- modules/api/pkg/machine/convert.go
- modules/api/pkg/resources/machine/common.go
- modules/api/pkg/test/e2e/utils/apiclient/models/openstack_node_spec.go
This PR fixes a logic where configDrive is set to null during updates; which causes extra machines to rollout since the JSON patch detects difference between `null` and boolean value.
Fixes https://github.com/kubermatic/kubermatic/issues/14215
/kind bug
```release-note
Pass ConfigDrive value to JSON patch during machine updates  for OpenStack
```
```documentation
NONE
```
> (fix): OpenStack - pass ConfigDrive value to JSON patch during machine updates

- Makefile
- modules/api/Makefile
- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/handler/test/helper.go
- modules/web/Makefile
- modules/web/package-lock.json
- modules/web/package.json
- modules/web/src/assets/config/changelog.json
This PR is to bump KKP Dashboard version and dependencies for KKP patch release v2.25.17 May 2025. 
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.25] Bump KKP Dashboard version and dependencies for May 2025

- modules/web/containers/chrome-headless/release.sh
This PR is to update the image tag for chrome-headless image to use build image 1.24
Fixes #
/kind chore
```release-note
NONE 
```
```documentation
NONE
```
> Bump the image tag for chrome-headless image to use build image 1.24

- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/handler/middleware/middleware.go
- modules/api/pkg/handler/v1/project/project.go
- modules/api/pkg/provider/kubernetes/member.go
- modules/api/pkg/provider/types.go
- modules/api/pkg/provider/userinfo.go
- Adds support for the `globalViewer` role in Kubermatic.
- Users with `globalViewer: true` in their User CR are automatically granted read-only access to all projects and clusters. This is achieved through dynamic group and role injection in the API middleware, without the need for explicit UserProjectBinding resources.
Fixes #
/kind feature
- Global viewers are now resolved dynamically in the `UserInfo` middleware layer.
- `isGlobalViewer` and `isAdmin` are mutually exclusive, validated by webhook.
```release-note
Users marked with globalViewer: true now receive …
```
> Add support for global viewer role in middleware

- modules/api/go.sum
- modules/api/pkg/handler/common/provider/kubevirt.go
This PR disables the automatic listing of the default kubevirt instance types and preferences based on the new field introduced in `datacenter.spec.Kubevirt` (`DisableDefaultInstanceTypes` and `DisableDefaultPreferences`) 
This PR is part of the implementation of https://github.com/kubermatic/kubermatic/pull/14426 that addresses the issue https://github.com/kubermatic/kubermatic/issues/14415
Fixes #
/kind feature
```release-note
Add the ability to disable the automatic installation of default kubevirt instance types and preferences
```
```documentation …
```
> feat: disable default kubevirt instance types and preferences

- modules/api/pkg/handler/v1/user/user.go
- Fixes a permission issue where users with globalViewer access were unable to retrieve members for a project.
- For more info, ref: https://github.com/kubermatic/dashboard/issues/7325#issuecomment-2886864590
Fixes 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> fix(global-viewer): fix users api for global viewer use

- modules/web/src/app-config.ts
- modules/web/src/app/module.ts
Hide selection indicator from button toggle.
**Before**
**After**
Fixes #
/kind design
```release-note
NONE
```
```documentation
NONE
```
> Hide selection indicator from button toggle

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/pkg/api/v1/types.go
- modules/api/pkg/handler/v1/admin/admin.go
- modules/api/pkg/provider/kubernetes/admin.go
- modules/api/pkg/provider/types.go
- modules/api/pkg/test/e2e/utils/apiclient/models/admin.go
- modules/api/pkg/test/e2e/utils/apiclient/models/user.go
- modules/web/src/app/project/template.html
- modules/web/src/app/settings/admin/global-viewer/add-global-viewer-dialog/component.ts
- modules/web/src/app/settings/admin/global-viewer/add-global-viewer-dialog/template.html
- modules/web/src/app/settings/admin/global-viewer/component.ts
- modules/web/src/app/settings/admin/global-viewer/module.ts
- modules/web/src/app/settings/admin/global-viewer/style.scss
- modules/web/src/app/settings/admin/global-viewer/template.html
- modules/web/src/app/settings/admin/nav/template.html
- modules/web/src/app/settings/admin/routing.ts
- modules/web/src/app/shared/components/side-nav-field/component.ts
- modules/web/src/app/shared/entity/common.ts
- modules/web/src/app/shared/entity/member.ts
- modules/web/src/app/shared/utils/member.ts
Adding a new role called Global Viewer to the dashboard, where the admin can manage global viewers from the new `obalviewers` page in the admin panel.
Fixes #7313 
/kind feature
```release-note
New page in the admin panel to manage the Global Viewer role.
```
```documentation
TBD
```
> Add global viewer role to the dashboard

- modules/api/pkg/ee/clusterbackup/backup/handler.go
This PR adds `spec.labels` to ClusterBackup objects created via the KKP controllers. These labels help identify and distinguish controller-initiated backups from those manually uploaded via the UI. 
Ref #7343 
/kind feature
```release-note
Cluster backups created by KKP controllers now include spec.labels to distinguish controller-initiated backups from those manually uploaded via the UI. 
```
```documentation
NONE
```
> fix(7343): add labels for backup objects

- modules/api/pkg/ee/clusterbackup/backup/handler.go
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/component.ts
- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/template.html
- modules/web/src/app/shared/entity/backup.ts
This PR adds a new column in backups table to display source of cluster backups based on value of `system/backup-origin` label.
Fixes #7343 
/kind feature
```release-note
Display source of cluster backups.
```
```documentation
TBD
```
> Display source of cluster backups

- modules/api/cmd/kubermatic-api/swagger.json
- modules/api/go.mod
- modules/api/go.sum
- modules/api/pkg/api/v2/types.go
- modules/api/pkg/handler/common/provider/kubevirt.go
- modules/api/pkg/handler/v2/provider/kubevirt.go
- modules/api/pkg/provider/cloud/kubevirt/networks.go
- modules/api/pkg/test/e2e/utils/apiclient/models/kube_virt_subnet.go
- modules/api/pkg/test/e2e/utils/apiclient/models/subnet.go
- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
- modules/web/src/app/node-data/basic/provider/kubevirt/template.html
- modules/web/src/app/shared/entity/provider/kubevirt.ts
This PR supports showing the kubevirt subnets CIDR in the UI. 
Fixes #
/kind feature
```release-note
Display KubeVirt Subnet CIDRs in UI
```
```documentation
None
```
> Display KubeVirt Subnet CIDRs in UI

- modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
in the case of using a preset that have vpcs then user need to chose a subnet (if they are exist)
**Which issue(s) this PR fixes:**
Fixes #7329
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Make subnets as required on kubevirt

- modules/web/src/app/shared/components/application-list/component.ts
- modules/web/src/app/shared/components/application-list/style.scss
- modules/web/src/app/shared/components/application-list/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- Display system applications in cluster creation wizard.
- Fix application type label for system applications.
- Make all application type labels look consistent.
**Cards View:**
**Table View:**
Fixes #
/kind bug
```release-note
Display system applications in cluster creation wizard and fix application type label for system applications.
```
```documentation
NONE
```
> UI fixes for system applications

- modules/web/src/app/core/services/auth/service.ts
The `path` argument was missing while calling cookie delete method due to which token cookie was not being deleted. This would result in application using an invalid token hence rendering the dashboard useless until token cookie was deleted manually.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix token cookie cleaning by passing path argument to delete method

- modules/api/pkg/ee/kyverno/policy-template/handler.go
- modules/web/src/app/dynamic/enterprise/kyverno-policies/cluster-policies/add-policy-dialog/component.ts
- modules/web/src/app/dynamic/enterprise/kyverno-policies/cluster-policies/component.ts
- modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/component.ts
- modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/template.html
- modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/component.ts
- modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/template.html
this PR fix: 
- Project scope policies should not be visible on the admin panel. By default admins can only add “Global” level policies.
- Policies on project level page limit usability because all policies are disabled. showing the status of policies
- Unable to add policy on a cluster because the “Add Policy” dialog doesn’t display any policies.
- Cluster scoped policy (using cluster label selector) is not visible on the cluster details page.
- Cluster and project label selector keys are not removed when editing a policy.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Kyverno bug fixes and enhancements

- modules/api/pkg/ee/clusterbackup/backup/handler.go
- modules/api/pkg/ee/clusterbackup/schedule/handler.go
This PR adds `backupSpec.labels` to Schedule objects created via the KKP controllers. These labels help identify and distinguish controller-initiated backups from those manually uploaded via the UI. 
Fixes #
/kind bug
```release-note
Cluster backup schedules created by KKP controllers now include backupSpec.labels to distinguish controller-initiated backups from those manually uploaded via the UI. 
```
```documentation
NONE
```
> Fix: Add labels to backup objects created by a schedule.

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
It should be possible to "uninstall" KubeLB from a cluster even if the KubeLB integration is disabled for the data center or the seed. 
xref https://github.com/kubermatic/dashboard/issues/7342#issuecomment-2937260429
/kind bug
These are mostly changes against https://github.com/kubermatic/dashboard/issues/7341, which is new feature for 2.28.
```release-note
NONE
```
```documentation
NONE
```
> Rework KubeLB validation

- modules/api/go.mod
- modules/api/go.sum
This PR bumps KKP Go Dependency to prepare 2.28.0-rc.1
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Bump kkp go dependency for 2.28.0-rc.1

- modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/template.html
- modules/web/src/app/settings/admin/nav/style.scss
- modules/web/src/app/settings/admin/nav/template.html
Change `Experimental` to `Beta` label.
```release-note
NONE
```
```documentation
NONE
```
> Change `Experimental` to Beta label

- modules/web/src/app/shared/components/application-list/add-application-dialog/component.ts
- modules/web/src/app/shared/components/application-list/component.ts
- modules/web/src/app/shared/entity/application.ts
This PR adds functionality to allow manually installing system applications except with type `cni`. This is useful especially for installing cluster autoscaler application after cluster creation.
Fixes #
/kind feature
```release-note
Allow manual installation of system applications except with type `cni`.
```
```documentation
NONE
```
> Allow manual installation of system applications except with type `cni`

- modules/api/pkg/provider/cloud/openstack/provider.go
Remove the TenantID filter to get all the floating IP pools, including the shared ones.
Fixes #7436
/kind bug
```release-note
List all OpenStack networks in the UI wizard during cluster creation.
```
```documentation
NONE
```
> Removing TenantID filter for listing openstack networks

- modules/api/go.mod
- modules/api/go.sum
This PR bump KKP GO dependency to prepare for 2.28.0rc.1
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> prepare for 2.28.0-rc.1

- modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/component.ts
This PR sets the default backupSyncPeriod to null if the form value is an empty string.
Fixes #7222 
/kind bug
```release-note
Unset backup sync period if value is empty.
```
```documentation
NONE
```
> Set default backup sync period to null if value is empty

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/wizard/step/cluster/component.ts
When KubeLB was enforced for a datacenter, we were not "enabling" KubeLB which results in it not being deployed for the cluster and users can't change it afterwards as well since it's a disabled control in the UI.
Fixes #
/kind bug
```release-note
KubeLB: Fix a bug where enforcement on a datacenter was not enabling KubeLB for the user clusters in the dashboard.
```
```documentation
NONE
```
> KubeLB: Fix a bug with kubelb enforcement

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This PR is to bump Go version to 1.23.10.
[CVE-2025-4673](https://github.com/advisories/GHSA-62jj-gr2r-5c34): net/http: sensitive headers not cleared on cross-origin redirect
[CVE-2025-0913](https://github.com/advisories/GHSA-jw54-c8rr-pjpq): os: inconsistent handling of O_CREATE|O_EXCL on Unix and Windows
[CVE-2025-22874](https://github.com/advisories/GHSA-6f52-wpx2-hvf2): crypto/x509: usage of ExtKeyUsageAny disables policy validation
Fixes #
/kind chore
```release-note
Update to Go 1.23.10
```
```documentation
NONE
```
> [release/v2.27] Bump Go version to 1.23.10

- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
This PR fixes KubeLB checkbox state when switching datacenters, improves tooltip visibility on disabled elements, and eliminates UI flickering caused by delayed API responses.
Wizard
Dialog
Fixes #
/kind bug
```release-note
Fixed KubeLB checkbox state management and UI flickering issues in cluster creation wizard/edit cluster dialog
```
```documentation
NONE
```
> Fix KubeLB checkbox state tooltip and rendering issues

- modules/api/pkg/handler/v2/cluster_template/cluster_template.go
- modules/api/pkg/handler/v2/cluster_template/cluster_template_test.go
- modules/api/pkg/provider/kubernetes/cluster_template.go
- modules/web/src/app/cluster-template/component.ts
- modules/web/src/app/cluster-template/template.html
- modules/web/src/assets/config/userGroupConfig.json
This PR prevents users with the Project Viewer role from creating cluster templates. Viewers will now only have read-only access.
Fixes #7409 
/kind bug
In the video, the Edit/Delete buttons on the cluster template list page are enabled based on existing permissions defined by the template scope.
See Template Scope  Permission  [here](https://github.com/kubermatic/dashboard/pull/7446/files#diff-e2469aa9f9189ca73cb2aae2f33b0f6e493ae82de9e58a81dd8ad8688cb3834bR274)
```release-note
Project viewers can now only view cluster templates and can no longer create them on Viewer …
```
> Prevent project viewer from creating cluster templates

- modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
- modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
- modules/web/src/app/shared/components/annotation-form/component.ts
- modules/web/src/app/shared/entity/cluster.ts
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
Add a checkbox in the cluster settings to enable or disable skipping router reconciliation for OpenStack clusters via the reconciliation.kubermatic.k8c.io/skip-router annotation.reconciliation.
ref: https://github.com/kubermatic/kubermatic/pull/14771
Fixes #7476 
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> Add skip router reconciliation option for OpenStack clusters

- Makefile
- modules/api/Makefile
- modules/api/go.mod
- modules/api/go.sum
- modules/web/Makefile
- modules/web/package-lock.json
- modules/web/package.json
This PR is to bump KKP and OSM dependencies for KKP patch release 2.27.6
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.27] Bump KKP and OSM dependencies for KKP patch release 2.27.6

- Makefile
- modules/api/Makefile
- modules/api/go.mod
- modules/api/go.sum
- modules/web/Makefile
- modules/web/package-lock.json
- modules/web/package.json
This PR is to bump KKP and OSM dependencies for KKP patch release 2.26.10.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.26] Bump KKP and OSM dependencies for KKP patch release 2.26.10

- hack/images/web-terminal/Dockerfile
- hack/images/web-terminal/release.sh
- modules/api/pkg/handler/websocket/terminal.go
Updated the web-terminal image with:
- Latest kubectl, helm, and k8sgpt versions
- Install k9s, krew, and krew plugins ns, ctx, and oidc-login
Fixes #
/kind feature
```release-note
- Update web-terminal image to v0.11.0
- web-terminal: k9s, krew, and krew plugins ns, ctx, and oidc-login are available to use in the web-terminal image
```
```documentation
NONE
```
> Install k9s, krew, and oidc-login in terminal image

- modules/api/pkg/provider/cloud/openstack/helper.go
- modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
- modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/template.html
This PR resolves issues with unnamed OpenStack networks by displaying their ID in the dropdown and properly loading associated subnets.
**Before**
**After**
**Network**
**Subnets**
Fixes #7099 
/kind bug
API Provides a fallback mechanism in case it fails to list by name it search network with network ID which is always generated by openstack network provider.
```release-note
Fixes network selection to display network ID when name is missing in OpenStack.
```
```documentation
tbd
```
> Fix OpenStack network selection to handle networks without name

- modules/web/src/app/node-data/basic/provider/openstack/component.ts
- modules/web/src/app/node-data/basic/provider/openstack/style.scss
- modules/web/src/app/node-data/basic/provider/openstack/template.html
- modules/web/src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/component.ts
- modules/web/src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html
- modules/web/src/app/shared/components/cluster-summary/template.html
- modules/web/src/app/shared/entity/datacenter.ts
- modules/web/src/app/shared/entity/node.ts
Add a new checkbox to enable the config drive for MD in the OpenStack provider, and also add an option at the datacenter level to enforce enabling it on all MDs.
Fixes #6733 
/kind feature
```release-note
Added a new option to enable the config drive on the OpenStack provider for machine deployments, along with a datacenter-level option to enforce it for all machine deployments.
```
```documentation
TBD
```
> Enable of config drive for open stack

- Makefile
- modules/api/Makefile
- modules/api/go.mod
- modules/api/go.sum
- modules/web/Makefile
- modules/web/package-lock.json
- modules/web/package.json
This PR is to bump KKP dependencies for KKP patch release v2.26.12
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v2.26] Bump KKP dependencies for KKP patch release v2.26.12

- modules/api/.gitignore
- modules/api/pkg/handler/auth/oidc.go
- modules/api/pkg/handler/common/kubeconfig.go
- modules/api/pkg/handler/middleware/middleware.go
- modules/api/pkg/handler/routes_v1_websocket.go
- modules/api/pkg/handler/test/fake_auth.go
- modules/api/pkg/handler/websocket/terminal.go
- modules/api/pkg/provider/auth/types/types.go
- modules/api/pkg/watcher/types.go
- modules/web/.gitignore
- modules/web/src/app/shared/components/terminal/component.ts
- modules/web/src/app/shared/components/terminal/template.html
- modules/web/src/app/shared/components/terminal/terminal-status-bar/component.ts
- modules/web/src/app/shared/components/terminal/terminal-status-bar/template.html
Refresh the token for the web terminal kubeconfig when it has expired. If the refresh fails, prompt the user to authenticate again.
Fixes #7271
/kind bug
```release-note
Fix web terminal token expiration by refreshing expired tokens automatically.
```
```documentation
TBD
```
> Refresh and update token for webterminal kubeconfig when token is expired

- modules/api/pkg/handler/routes_v1_websocket.go
- modules/api/pkg/handler/websocket/terminal.go
- modules/api/pkg/watcher/types.go
This is a cherry-pick of #7451
```release-note
Move web-terminal cleanup job to seed to fix cleanup not working when the token is expired.
```
> [release/v2.26] Moving web-terminal clean job to seed

- modules/api/.gitignore
- modules/api/pkg/handler/auth/oidc.go
- modules/api/pkg/handler/common/kubeconfig.go
- modules/api/pkg/handler/middleware/middleware.go
- modules/api/pkg/handler/routes_v1_websocket.go
- modules/api/pkg/handler/test/fake_auth.go
- modules/api/pkg/handler/websocket/terminal.go
- modules/api/pkg/provider/auth/types/types.go
- modules/api/pkg/watcher/types.go
- modules/web/.gitignore
- modules/web/src/app/shared/components/terminal/component.ts
- modules/web/src/app/shared/components/terminal/template.html
- modules/web/src/app/shared/components/terminal/terminal-status-bar/component.ts
- modules/web/src/app/shared/components/terminal/terminal-status-bar/template.html
This is a cherry-pick of #7508 
```release-note
Fix web terminal token expiration by refreshing expired tokens automatically.
```
```documentation
NONE
```
> [release/v2.27] Refresh and update token for webterminal kubeconfig when token is expired

- modules/api/.gitignore
- modules/api/pkg/handler/auth/oidc.go
- modules/api/pkg/handler/common/kubeconfig.go
- modules/api/pkg/handler/middleware/middleware.go
- modules/api/pkg/handler/routes_v1_websocket.go
- modules/api/pkg/handler/test/fake_auth.go
- modules/api/pkg/handler/websocket/terminal.go
- modules/api/pkg/provider/auth/types/types.go
- modules/api/pkg/watcher/types.go
- modules/web/.gitignore
- modules/web/src/app/shared/components/terminal/component.ts
- modules/web/src/app/shared/components/terminal/template.html
- modules/web/src/app/shared/components/terminal/terminal-status-bar/component.ts
- modules/web/src/app/shared/components/terminal/terminal-status-bar/template.html
This is a cherry-pick of #7508
```release-note
Fix web terminal token expiration by refreshing expired tokens automatically.
```
> [release/v2.28] Refresh and update token for webterminal kubeconfig when token is expired

- modules/api/.gitignore
- modules/api/pkg/handler/auth/oidc.go
- modules/api/pkg/handler/common/kubeconfig.go
- modules/api/pkg/handler/middleware/middleware.go
- modules/api/pkg/handler/routes_v1_websocket.go
- modules/api/pkg/handler/test/fake_auth.go
- modules/api/pkg/handler/websocket/terminal.go
- modules/api/pkg/provider/auth/types/types.go
- modules/api/pkg/watcher/types.go
- modules/web/.gitignore
- modules/web/src/app/shared/components/terminal/component.ts
- modules/web/src/app/shared/components/terminal/template.html
- modules/web/src/app/shared/components/terminal/terminal-status-bar/component.ts
- modules/web/src/app/shared/components/terminal/terminal-status-bar/template.html
This is a cherry-pick of #7508 
```release-note
Fix web terminal token expiration by refreshing expired tokens automatically.
```
```documentation
NONE
```
> [release/v2.26] Refresh and update token for webterminal kubeconfig when token is expired

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/go.mod
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/custom-dashboard/Dockerfile
This PR is to bump Go version to v1.23.12 which includes few CVE fixes.
Fixes #
/kind chore
```release-note
Update Go version to v1.23.12
```
```documentation
NONE
```
> [release/v2.26] Bump Go version to v1.23.12

- .prow/api.yaml
- .prow/common.yaml
- .prow/frontend.yaml
- hack/verify-spelling.sh
- modules/api/go.mod
- modules/api/hack/gen-api-client.sh
- modules/api/hack/update-swagger.sh
- modules/api/hack/verify-licenses.sh
- modules/web/containers/chrome-headless/Dockerfile
- modules/web/containers/chrome-headless/release.sh
- modules/web/containers/custom-dashboard/Dockerfile
- modules/web/go.mod
This PR is to bump Go version to v1.25.1 which includes [CVE-2025-47910](https://github.com/golang/go/issues/75054#issuecomment-3229430998) fix. Also bump the chrome-headless image to v1.9.1
Fixes #
/kind chore
```release-note
Update Go version to v1.25.1
```
```documentation
NONE
```
> Bump Go version to v1.25.1

- modules/web/src/app/node-data/basic/provider/gcp/component.ts
- modules/web/src/app/wizard/step/cluster/component.ts
- modules/web/src/app/wizard/step/cluster/template.html
* fix disk types and machine types values are not loaded in cluster template
* fix "Skip Router Reconciliation " checkbox state is not persisted in cluster template
Fixes #7632 
/kind bug
```release-note
Fix disk types and machine types values are not loaded in cluster template for Google Cloud Provider
```
```documentation
NONE
```
> Fix cluster template bugs
