hack/e2e/ci-setup-kubermatic-in-kind.sh
=> Fix E2E tests

src/app/core/services/datacenter/datacenter.service.ts
Remove circular dependency for datacenterService <> index
Copy of https://github.com/kubermatic/dashboard/pull/2383, because of broken fork
Fixes #2376
/
```release-note
NONE
```
=> Remove circular dependency for datacenterService <> index

src/app/app.config.ts, src/app/core/components/footer/footer.component.html, src/app/core/components/footer/footer.component.ts, src/app/core/components/user-panel/user-panel.component.ts, src/app/core/core.module.ts, src/app/core/services/auth/auth.service.spec.ts, src/app/core/services/auth/auth.service.ts, src/app/core/services/project/project.service.ts, src/app/core/services/token/token.service.ts, src/app/core/services/user/user.service.spec.ts, src/app/core/services/user/user.service.ts, src/app/pages/frontpage/frontpage.component.html, src/app/pages/frontpage/frontpage.component.ts, src/app/project/project.component.ts, src/app/testing/services/auth-mock.service.ts
Related to https://github.com/kubermatic/kubermatic/pull/5540
```release-note
NONE
```
=> Add logout endpoint support

src/app/core/components/footer/footer.component.html
**Special notes for your reviewer**: Do we want to change it in a different way?
```release-note
NONE
```
=> Update company name and webpage in the footer

.prow.yaml, cypress/integration/stories/edition.spec.ts, cypress/pages/login.po.ts, cypress/pages/user-panel.po.ts, cypress/pages/user-settings.po.ts, cypress/utils/auth.ts, cypress/utils/condition.ts, hack/e2e/ci-e2e.sh, src/app/core/components/footer/footer.component.html, src/app/core/components/user-panel/user-panel.component.html, src/app/dynamic/enterprise/theming/picker/template.html
Fixes https://github.com/kubermatic/dashboard/issues/2409
```release-note
NONE
```
=> Add e2e tests for community edition and remove redundant prow jobs

src/app/node-data-new/template.html, src/app/node-data/node-data.component.html, src/app/wizard-new/step/cluster/template.html, src/app/wizard/set-cluster-spec/set-cluster-spec.component.html
Disable name generation on enter
Fixes #2425
/
```release-note
NONE
```
=> Disable name generation on enter

src/app/cluster/cluster-details/cluster-details.component.ts, src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/add-cluster-sshkeys.component.ts, src/app/cluster/cluster-details/edit-sshkeys/edit-sshkeys.component.ts, src/app/core/components/sidenav/sidenav.component.html, src/app/core/components/sidenav/sidenav.component.ts, src/app/core/core.module.ts, src/app/core/services/auth/auth.guard.ts, src/app/core/services/page-title/page-title.service.ts, src/app/core/services/params/params.service.ts, src/app/kubermatic.component.ts, src/app/shared/entity/common.ts, src/app/shared/model/Config.ts, src/app/sshkey/sshkey.component.ts, src/app/testing/fake-data/userGroupConfig.fake.ts, src/app/wizard-new/step/provider-settings/ssh-keys/component.ts, src/app/wizard/set-settings/ssh-keys/cluster-ssh-keys.component.ts, src/assets/config/userGroupConfig.json
Set page title according to view e.g. `members in project 'xyz'` and  `cluster 'frosty-pare' in project 'xyz'`. 
Updated version of #2377, which is from my old broken fork.
Fixes #2062
/
```release-note
NONE
```
=> Set page title according to view

src/app/cluster/cluster-details/cluster-details.component.ts, src/app/cluster/cluster-details/revoke-token/revoke-token.component.ts, src/app/cluster/cluster-list/cluster-list.component.ts, src/app/core/components/sidenav/sidenav.component.ts, src/app/member/member.component.ts, src/app/project/project.component.ts
Use View enum that was introduced in https://github.com/kubermatic/dashboard/pull/2410
/
```release-note
NONE
```
=> Use View enum

src/app/node-data-new/component.ts, src/app/node-data/node-data.component.ts
Enable flatcar for openstack
cc @kdomanski 
```release-note
Enable Flatcar Linux for Openstack
```
=> Enable flatcar for openstack

.prow.yaml, Makefile, cypress/integration/stories/edition.spec.ts, cypress/pages/login.po.ts, cypress/pages/user-panel.po.ts, cypress/pages/user-settings.po.ts, cypress/utils/auth.ts, cypress/utils/condition.ts, hack/e2e/ci-e2e.sh, hack/e2e/ci-setup-kubermatic-in-kind.sh, package.json, src/app/core/components/footer/footer.component.html, src/app/core/components/navigation/navigation.component.html, src/app/theming/picker/template.html
=> Cherry-pick CI/CD changes into v2.14 release branch

src/app/cluster/cluster-details/node-list/node-list.component.html, src/app/core/services/api/api.service.ts, src/app/core/services/wizard/provider/openstack.ts, src/app/node-data-new/basic/provider/openstack/component.ts, src/app/node-data-new/basic/provider/openstack/template.html, src/app/node-data-new/service/provider/openstack.ts, src/app/node-data/node-data.component.spec.ts, src/app/node-data/openstack-node-data/openstack-node-data.component.html, src/app/node-data/openstack-node-data/openstack-node-data.component.spec.ts, src/app/node-data/openstack-node-data/openstack-node-data.component.ts, src/app/shared/entity/node.ts, src/app/shared/entity/provider/openstack.ts, src/app/testing/fake-data/addNodeModal.fake.ts, src/app/wizard-new/step/summary/template.html, src/app/wizard/summary/summary.component.html
Add Availability Zones for Openstack
Fixes #2390
https://github.com/kubermatic/kubermatic/pull/5535 needs to get merged first
/hold 
```release-note
Added possibility to specify Availability Zones for Openstack via UI
```
=> Add Availability Zones for Openstack

src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.ts, src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.ts, src/app/shared/model/NodeProviderConstants.ts
=> Fix provider names display

src/app/node-data-new/component.ts, src/app/node-data/node-data.component.ts
Enable flatcar for openstack
Cherrypicked from https://github.com/kubermatic/dashboard/pull/2430
cc @kdomanski 
```release-note
Enable Flatcar Linux for Openstack
```
=> [release/2.14] Enable flatcar for openstack

src/app/core/components/notification-panel/notification-panel.component.html
Fixes https://github.com/kubermatic/dashboard/issues/2442
```release-note
Fixed notification display in the notification panel.
```
=> Fix notification display in the panel

src/app/dynamic/enterprise/theming/picker/component.ts, src/app/dynamic/enterprise/theming/services/manager.ts
=> Monitor theme changes globally and fix system theme option

src/assets/css/_theme.scss
Fixes #
```release-note
Aligned color of the icons in the footer with the text.
```
=> Align footer icon color with the text

src/app/settings/admin/admin-settings.component.html, src/app/shared/entity/settings.ts, src/app/testing/services/settings-mock.service.ts, tsconfig.json
Fixes https://github.com/kubermatic/dashboard/issues/2458
```release-note
Added option to set project limit for users from the admin panel.
```
=> Add user project limit to the admin panel

src/app/core/services/datacenter/datacenter.service.ts, src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.ts, src/app/shared/entity/datacenter.ts, src/app/testing/fake-data/datacenter.fake.ts, src/app/wizard-new/step/provider-datacenter/component.ts, src/app/wizard/set-datacenter/set-datacenter.component.ts, src/app/wizard/set-provider/set-provider.component.ts
Fixes https://github.com/kubermatic/dashboard/issues/2468
```release-note
NONE
```
=> Do not filter seeds from datacenters as API does no longer mix them

src/app/cluster/cluster-list/cluster-list.component.ts
Fixes #
```release-note
NONE
```
=> Fix status and deletion in the cluster list

src/app/cluster/cluster-details/rbac/rbac.component.html, src/app/shared/components/event-list/event-list.component.html, src/assets/css/_theme.scss, src/assets/themes/dark.scss
Fixes #
```release-note
NONE
```
=> Improve the styling

src/app/node-data/basic/provider/aws/component.ts
There was an error while trying to add/edit ND for AWS
```release-note
NONE
```
=> Fix add/edit ND for AWS

cypress/pages/clusters.po.ts, cypress/pages/projects.po.ts, cypress/utils/endpoint.ts, cypress/utils/monitor.ts, hack/e2e/ci-setup-kubermatic-in-kind.sh
Small refactoring and e2e improvements.
```release-note
NONE
```
=> Improve e2e

src/app/node-data/basic/provider/openstack/component.ts, src/app/node-data/component.ts, src/app/node-data/extended/provider/vsphere/component.ts, src/app/wizard/step/cluster/component.ts, src/app/wizard/step/provider-datacenter/component.ts, src/app/wizard/step/provider-datacenter/template.html, src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts, src/app/wizard/step/summary/component.ts
Fix issue with auto form reset when using Openstack provider
```release-note
NONE
```
=> Fix issue with Openstack provider in the wizard

.prow.yaml
Renamed prow jobs to be globally unique.
```release-note
NONE
```
=> Rename prow jobs

src/app/core/services/project/project.service.ts, src/app/project/project.component.ts
As in the title :slightly_smiling_face: 
Fixes #2546
```release-note
NONE
```
=> Fix pagination on projects view when switching layout

src/app/node-data/dialog/component.ts, src/app/node-data/extended/provider/aws/component.ts, src/app/node-data/extended/provider/azure/component.ts, src/app/node-data/extended/provider/vsphere/component.ts, src/app/node-data/service/service.ts
As in the title
Fixes #2549 
```release-note
NONE
```
=> Fix add/edit mode text

src/app/project/project.component.html, src/app/project/project.component.scss, src/app/project/project.component.ts, src/app/settings/user/user-settings.component.html, src/assets/css/_theme.scss
Move show all projects toggle back to the project list view.
```release-note
Moved "Show All Projects" toggle back to the project list.
```
=> Move show all projects to the project list view

src/app/cluster/cluster-details/cluster-details.component.html, src/app/cluster/cluster-details/cluster-details.component.spec.ts, src/app/cluster/cluster-details/cluster-details.component.ts, src/app/core/services/cluster/cluster.service.ts
Fixes #
```release-note
Remove list of orphaned nodes from cluster view as only deployments are used right now.
```
=> Remove list of orphaned nodes from cluster view

src/app/core/services/api/api.service.ts
Fixes https://github.com/kubermatic/dashboard/issues/2606
```release-note
NONE
```
=> Remove token param from kubeconfig query

src/app/cluster/cluster-details/share-kubeconfig/share-kubeconfig.component.html, src/app/dynamic/enterprise/LICENSE, src/app/pages/terms-of-service/terms-of-service.component.html
Update company name
Fixes #2591
/
```release-note
NONE
```
=> Update company name

src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.html, src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.html, src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.html, src/app/cluster/cluster-details/node-list/node-list.component.html, src/app/node-data/basic/provider/openstack/template.html, src/app/settings/admin/admin-settings.component.html, src/app/settings/admin/custom-link-form/custom-links-form.component.ts, src/app/settings/user/user-settings.component.html, src/app/wizard/step/cluster/template.html
Fixed issues:
Fixes 2 issues mentioned in https://github.com/kubermatic/dashboard/issues/2615
```release-note
NONE
```
=> Fix custom links and missing info icon

angular.json, package-lock.json, package.json, src/app/pages/api-docs/api-docs.component.ts
Fixes #2623
```release-note
NONE
```
=> Fix swagger and build warning

src/app/settings/user/user-settings.component.html, src/app/settings/user/user-settings.component.ts
Fixes https://github.com/kubermatic/dashboard/issues/2602
```release-note
Non-existing default projects will be now unchecked in the settings.
```
=> Remove non-existing default project selections

hack/e2e/ci-e2e.sh, hack/e2e/ci-setup-kubermatic-in-kind.sh
=> [release/v2.15] Fix e2e

src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.html, src/app/shared/components/combobox/style.scss, src/app/shared/components/combobox/template.html, src/app/wizard/step/provider-settings/preset/template.html, src/assets/css/global/_main.scss
Fixes #2601
```release-note
NONE
```
=> Fix text overlapping clear button in our custom combobox

src/app/cluster/cluster-details/version-picker/template.html, src/app/shared/components/combobox/template.html, src/app/wizard/step/provider-settings/preset/template.html, src/assets/css/material/_main.scss
Fixes https://github.com/kubermatic/dashboard/issues/2589
**Special notes for your reviewer**: 
```release-note
NONE
```
=> Fix selection panel positioning

src/app/cluster/cluster-details/add-machine-network/add-machine-network.component.spec.ts, src/app/cluster/cluster-details/add-machine-network/add-machine-network.component.ts, src/app/cluster/cluster-details/change-cluster-version/change-cluster-version.component.ts, src/app/cluster/cluster-details/cluster-delete-confirmation/cluster-delete-confirmation.component.ts, src/app/cluster/cluster-details/cluster-details.component.ts, src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.ts, src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.ts, src/app/cluster/cluster-details/machine-networks-display/machine-networks-display.component.ts, src/app/cluster/cluster-list/cluster-list.component.ts, src/app/core/services/cluster/cluster.service.ts, src/app/core/services/page-title/page-title.service.ts, src/app/core/services/params/params.service.ts, src/app/wizard/component.ts
Related to https://github.com/kubermatic/dashboard/issues/2438
```release-note
Switched to new cluster endpoints.
```
=> Switch to new cluster endpoints without seed param

src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.html, src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.ts, src/app/shared/components/addon-list/install-addon-dialog/install-addon-dialog.component.html, src/app/shared/components/addon-list/install-addon-dialog/install-addon-dialog.component.ts, src/app/shared/entity/addon.ts
Add flag continuouslyReconcile to addons
Fixes #2540
/
```release-note
Added flag "continuouslyReconcile" to addons
```
=> Add flag continuouslyReconcile to addons

src/app/sshkey/sshkey.component.ts
Fixes https://github.com/kubermatic/dashboard/issues/2564
```release-note
Fix loading of the access rights in the SSH keys view.
```
=> Fix call order in the SSH key view

src/app/shared/services/cluster.service.ts, src/app/wizard/step/cluster/component.ts
Fixes #2653
```release-note
NONE
```
=> Fix admission plugin selection in wizard

src/app/wizard/step/cluster/template.html
Fixes https://github.com/kubermatic/dashboard/issues/2647
```release-note
Fix wizard rendering in Safari.
```
=> Fix wizard rendering in Safari

src/assets/css/root.scss
Fixes https://github.com/kubermatic/dashboard/issues/2670
```release-note
NONE
```
=> Change flag icons default ratio to 4x3

src/app/shared/components/event-list/event-list.component.scss, src/app/sshkey/sshkey.component.scss
=> Fix styling issues

src/app/shared/components/addon-list/addon-list.component.html, src/app/shared/components/addon-list/addon-list.component.scss, src/app/shared/components/addon-list/addon-list.component.ts, src/app/shared/components/dialog-title/dialog-title.component.html, src/assets/css/global/_main.scss, src/assets/css/global/_theme.scss, src/assets/themes/dark.scss
Fixes https://github.com/kubermatic/dashboard/issues/2650
```release-note
Display deletion state of accessible addons.
```
=> Mark addons in deletion

src/app/dynamic/enterprise/theming/picker/style.scss, src/app/settings/admin/admin-settings.component.html, src/app/settings/admin/admin-settings.component.scss, src/app/settings/user/user-settings.component.html, src/app/settings/user/user-settings.component.scss
Fixes https://github.com/kubermatic/dashboard/issues/2657
```release-note
NONE
```
=> Fix settings UI

src/app/cluster/cluster-list/cluster-list.component.html, src/app/cluster/cluster-list/cluster-list.component.ts
Fixes https://github.com/kubermatic/dashboard/issues/2722
```release-note
NONE
```
=> Fix cluster search

src/app/cluster/cluster-details/rbac/rbac.component.scss, src/app/node-data/template.html, src/app/shared/components/editor/component.ts, src/app/shared/components/editor/style.scss, src/app/shared/components/event-list/event-list.component.scss, src/app/wizard/step/cluster/style.scss, src/app/wizard/step/cluster/template.html, src/app/wizard/step/provider-datacenter/template.html, src/app/wizard/step/provider-settings/ssh-keys/template.html, src/assets/css/global/_main.scss, src/assets/css/global/_theme.scss, src/assets/css/material/_main.scss, src/assets/css/material/_theme.scss
Fixes https://github.com/kubermatic/dashboard/issues/2698
```release-note
NONE
```
=> Improve UI/UX

src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.html, src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.html, src/app/cluster/cluster-details/node-list/node-list.component.html, src/app/cluster/cluster-list/cluster-list.component.html, src/app/node-data/template.html, src/app/wizard/step/summary/template.html
**What this PR does / why we need it**: 
**Special notes for your reviewer**: https://coreos.com/os/docs/latest/
```release-note
NONE
```
=> Update Container Linux EOL messages

src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.html, src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.ts, src/app/shared/components/addon-list/install-addon-dialog/install-addon-dialog.component.ts, src/app/shared/entity/addon.ts
Fixes https://github.com/kubermatic/dashboard/issues/2727
```release-note
Fixed addon variables edit.
```
=> Fix addon edit dialog

cypress/integration/stories/machine-deployments.spec.ts, cypress/utils/endpoint.ts, src/app/cluster/cluster-details/change-cluster-version/component.ts, src/app/cluster/cluster-details/component.ts, src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/component.ts, src/app/cluster/cluster-details/edit-sshkeys/component.ts, src/app/cluster/cluster-details/node-list/component.ts, src/app/cluster/cluster-list/component.ts, src/app/cluster/services/node.service.ts, src/app/core/services/api/service.ts, src/app/core/services/cluster/service.ts, src/app/wizard/component.ts
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Related to https://github.com/kubermatic/dashboard/issues/2438.
```release-note
NONE
```
=> Use the new endpoints

src/app/cluster/cluster-list/template.html
Fixes https://github.com/kubermatic/dashboard/issues/2729
```release-note
NONE
```
=> Change create cluster button label

src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.html, src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.scss, src/app/shared/components/addon-list/install-addon-dialog/install-addon-dialog.component.html, src/app/shared/components/addon-list/install-addon-dialog/install-addon-dialog.component.scss, src/app/shared/entity/addon.ts
Related to https://github.com/kubermatic/dashboard/issues/2728
Addon config for tests:
```yaml
apiVersion: kubermatic.k8s.io/v1
kind: AddonConfig
metadata:
name: node-exporter
spec:
description: "The Prometheus Node Exporter exposes a wide variety of hardware- and kernel-related metrics."
logoFormat: "svg+xml"
logo: |+
PHN2ZyB3aWR0aD0iMTY2IiBoZWlnaHQ9IjQwIiB2aWV3Qm94PSIwIDAgMTY2IDQwIiBmaWxsPSJub25lIiB4bWxucz0iaHR0
cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgo8cGF0aCBkPSJNMTkuOTEyNCA1LjE3NTU0QzExLjY3NjggNS4xNzU1NCA1IDEx …
```
=> Add help text to addon forms

src/app/cluster/cluster-details/cluster-details.component.html, src/app/cluster/cluster-details/cluster-details.component.spec.ts, src/app/cluster/cluster-details/cluster-details.component.ts, src/app/core/services/cluster/cluster.service.ts
This reverts commit 73aa2226
Fixes #
/assign @floreks 
```release-note
Restore list of nodes in the cluster view.
```
=> [v2.15] Revert "Remove list of orphaned nodes from cluster view (#2574)"

src/app/cluster/cluster-details/version-picker/style.scss, src/app/config.service.ts, src/app/shared/components/chip/theme.scss, src/app/shared/components/eol/theme.scss, src/assets/css/theme/_component.scss
Updated styles that were not migrated to new theming approach.
Fixes #2829
```release-note
Fix end of life chip/badge styling
```
=> Update chip and eol badge styling

src/app/wizard/step/cluster/component.ts
It was using the old logic based on app config instead of settings. Updated to use new logic.
Fixes #2836
```release-note
Displayed distributions in the wizard are now correctly shown based on admin settings.
```
=> Update displayed distributions logic to use admin settings

src/assets/images/branding/bg.svg
Fixes https://github.com/kubermatic/dashboard/issues/2817
I'll replace Dex image too in the core repo.
```release-note
Updated login page background.
```
=> Update login page background

src/app/project/project.component.ts
Fixes https://github.com/kubermatic/dashboard/issues/2826
```release-note
Fixed issue with listing all projects if one of them had no owner set.
```
=> Fix listing all projects

src/app/shared/utils/member-utils/member-utils.ts
Fixes #2803 
```release-note
Fix missing group name on Service Account list.
```
=> Fix group display name logic

src/app/cluster/cluster-details/rbac/add-binding/style.scss, src/app/cluster/cluster-details/rbac/add-binding/template.html, src/app/cluster/cluster-details/rbac/add-binding/theme.scss, src/assets/css/theme/_component.scss
Fixes #2830 
```release-note
Fixed styling of 'Add RBAC Binding' dialog.
```
=> Fix add rbac dialog styling

.github/ISSUE_TEMPLATE/bug-report.md
Fixes https://github.com/kubermatic/dashboard/issues/2806
```release-note
NONE
```
=> Remove list of internal domains from bug template

src/app/wizard/step/cluster/style.scss, src/app/wizard/step/cluster/theme.scss, src/assets/css/_images.scss, src/assets/css/_mixins.scss, src/assets/themes/dark.scss
The issue was only present in the dark theme as the order of applying styles was different.
Fixes #2805
Fixes #2857 
```release-note
NONE
```
=> Fix dark theme provider logo centering

src/app/wizard/step/cluster/theme.scss
**What this PR does / why we need it**: Icons (all in the toolbar for example) were transparent due to generic selector. Made it more specific.
```release-note
NONE
```
=> Fix icon colors

src/app/dynamic/enterprise/theming/picker/component.ts, src/app/dynamic/enterprise/theming/picker/style.scss, src/app/dynamic/enterprise/theming/picker/template.html
Fixes https://github.com/kubermatic/dashboard/issues/2875
```release-note
NONE
```
=> Fix theme save status indicator

src/app/cluster/cluster-details/node-list/template.html, src/app/cluster/cluster-details/rbac/template.html, src/assets/css/_variables.scss, src/assets/css/material/_main.scss
- Rbac column: renamed "Name" to "User/Group"
- Adjusted box-shadows and reduced border-radius from 5 to 3
- Fixed node list, as some missing checks on azure let the list crash & browser console explode for all other providers
Related to #2881
```release-note
NONE
```
=> UI/UX Fixes

src/app/core/services/api/service.ts, src/app/settings/admin/module.ts, src/app/settings/admin/opa/component.ts, src/app/settings/admin/opa/template.html, src/app/shared/entity/opa.ts
Add OPA table to admin view
Fixes #2968
/
```release-note
NONE
```
=> Add OPA table to admin view

src/app/core/services/wizard/provider/azure.ts, src/app/shared/entity/provider/azure.ts, src/app/wizard/step/provider-settings/provider/extended/azure/component.ts, src/app/wizard/step/provider-settings/provider/extended/azure/template.html
Fixes https://github.com/kubermatic/dashboard/issues/2919
```release-note
Use endpoint to load Azure subnets autocompletions.
```
=> Use endpoint to load Azure subnets 

src/app/cluster/cluster-details/edit-cluster/component.ts, src/app/cluster/cluster-details/edit-cluster/style.scss, src/app/cluster/cluster-details/edit-cluster/template.html, src/app/shared/entity/cluster.ts, src/app/shared/model/ClusterForm.ts, src/app/wizard/step/cluster/component.ts, src/app/wizard/step/cluster/style.scss, src/app/wizard/step/cluster/template.html, src/app/wizard/step/summary/template.html
OPA - Added options to enable/disable OPA Integration in Wizard & Edit Cluster Dialog
Fixes #2995
Fixes #2996
```release-note
NONE
```
=> OPA - Added options to enable/disable OPA Integration

src/app/settings/admin/admins/component.ts, src/app/settings/admin/admins/style.scss, src/app/settings/admin/admins/template.html, src/app/settings/admin/dynamic-datacenters/template.html, src/app/settings/admin/presets/style.scss, src/app/settings/admin/presets/template.html, src/app/settings/admin/template.html
Moves mentioned lists to a group of tabs.
Fixes #3002
```release-note
NONE
```
=> Move dataceneters/administrator/presets to tabs in admin settings

src/app/core/services/wizard/provider/vsphere.ts, src/app/shared/entity/provider/vsphere.ts, src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts, src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
Fixes https://github.com/kubermatic/dashboard/issues/2917
Fixes https://github.com/kubermatic/dashboard/issues/2916
**Special notes for your reviewer**: Backend implementation: https://github.com/kubermatic/kubermatic/pull/6442
```release-note
Added autocompletions for vSphere datastores.
```
=> Add autocompletions for vSphere datastores

src/app/cluster/cluster-details/template.html, src/app/shared/entity/cluster.ts, src/app/wizard/step/cluster/component.ts, src/app/wizard/step/cluster/style.scss, src/app/wizard/step/cluster/template.html, src/app/wizard/step/summary/template.html
Fixes https://github.com/kubermatic/dashboard/issues/2986
Fixes https://github.com/kubermatic/kubermatic/issues/6383
```release-note
Added option to disable User SSH Key Agent from the cluster wizard.
```
=> Add option to disable User SSH Key Agent from the cluster wizard

src/app/cluster/cluster-details/edit-cluster/template.html, src/app/wizard/step/cluster/template.html
Fixes https://github.com/kubermatic/dashboard/issues/3032
```release-note
NONE
```
=> Update pod security policy warning

src/app/core/services/cluster/service.ts
Fixes important memory leak caused by building up subscriptions on cluster details view.
/cherry-pick release/v2.16
```release-note
NONE
```
=> Fix subscription memory leak

.editorconfig, hack/e2e/fixtures/seed.yaml, hack/run-in-docker.sh, src/app/cluster/cluster-details/machine-deployment-details/template.html, src/app/cluster/cluster-details/node-list/template.html, src/app/cluster/cluster-list/component.ts, src/app/cluster/cluster-list/template.html, src/app/cluster/services/node.service.ts, src/app/node-data/basic/provider/openstack/component.ts, src/app/node-data/basic/provider/vsphere/component.ts, src/app/node-data/component.ts, src/app/node-data/template.html, src/app/shared/entity/datacenter.ts, src/app/shared/entity/node.ts, src/app/shared/model/NodeProviderConstants.ts, src/app/shared/model/NodeSpecChange.ts, src/app/testing/fake-data/datacenter.fake.ts, src/app/testing/fake-data/node.fake.ts, src/app/wizard/service/wizard.ts, src/app/wizard/step/summary/template.html
Fixes https://github.com/kubermatic/kubermatic/issues/6378
```release-note
Remove CoreOS
```
=> Remove CoreOS

src/app/cluster/cluster-details/component.spec.ts, src/app/cluster/cluster-details/component.ts, src/app/cluster/cluster-details/constraints/component.ts, src/app/cluster/cluster-details/constraints/constraint-dialog/component.ts, src/app/cluster/cluster-details/constraints/constraint-dialog/style.scss, src/app/cluster/cluster-details/constraints/constraint-dialog/template.html, src/app/cluster/cluster-details/constraints/style.scss, src/app/cluster/cluster-details/constraints/template.html, src/app/cluster/cluster-details/constraints/violation-details/component.ts, src/app/cluster/cluster-details/constraints/violation-details/style.scss, src/app/cluster/cluster-details/constraints/violation-details/template.html, src/app/cluster/module.ts, src/app/core/services/opa/service.ts, src/app/shared/entity/opa.ts
OPA - Add Constraints table to cluster details view
Fixes #2969
Fixes #2989
Fixes #2966
Fixes #2967
/
```release-note
NONE
```
=> OPA - Add Constraints table to cluster details view

src/app/cluster/cluster-details/component.ts
Check if OPA is enabled, before calling endpoints
```release-note
NONE
```
=> Check if OPA is enabled, before calling endpoints

src/app/cluster/cluster-details/constraints/component.ts, src/app/cluster/cluster-details/constraints/style.scss, src/app/cluster/cluster-details/constraints/template.html
Filter constraints by constraint template
Fixes #3088
/
```release-note
NONE
```
=> OPA- filter constraints by constraint template

src/app/cluster/cluster-details/cluster-secrets/component.ts, src/app/cluster/cluster-details/cluster-secrets/template.html, src/app/shared/entity/health.ts
Adds gatekeeper status to cluster details view
Fixes #2997
/
```release-note
NONE
```
=> OPA - Add gatekeeper status to cluster details view

src/app/node-data/basic/provider/alibaba/component.ts, src/app/node-data/basic/provider/alibaba/template.html, src/app/shared/entity/provider/alibaba.ts, src/app/testing/fake-data/alibaba.fake.ts
Fixes https://github.com/kubermatic/dashboard/issues/3094
```release-note
Added GPU count display for Alibaba instance types.
```
=> Display GPU count for Alibaba instance types

src/app/cluster/cluster-details/machine-deployment-list/template.html, src/app/node-data/component.ts
The admin settings will be respected now when creating/editing clusters.
Fixes #2992
```release-note
NONE
```
=> Use global settings for initial replicas fields in wizard/edit md dialog

license-checker-config.json, src/app/dynamic/enterprise/theming/module.ts, src/app/dynamic/enterprise/theming/picker/component.ts, src/app/dynamic/enterprise/theming/picker/style.scss, src/app/dynamic/enterprise/theming/picker/template.html, src/app/dynamic/enterprise/theming/services/color-scheme.ts, src/app/dynamic/enterprise/theming/services/manager.ts, src/app/dynamic/enterprise/theming/services/theme.ts, src/index.html
I have also removed apache headers from enterprise directories and added all files to the ignored list.
Fixes #2799
```release-note
NONE
```
=> Remove apache license from index.html and enterprise files

src/app/settings/admin/constraint-templates/component.ts, src/app/settings/admin/constraint-templates/constraint-template-dialog/component.ts, src/app/settings/admin/constraint-templates/constraint-template-dialog/template.html, src/app/settings/admin/constraint-templates/style.scss, src/app/settings/admin/constraint-templates/template.html
Due to the tab implementation, the template of constraint templates needed to be changed. 
Also the name field has been removed, as it can be read from the provided spec (in lowercase).
Fixes #3071
/
```release-note
NONE
```
=> OPA - Constraint Templates improvements

src/app/node-data/basic/provider/azure/component.ts, src/app/node-data/basic/provider/azure/template.html, src/app/shared/entity/provider/azure.ts, src/app/testing/fake-data/addNodeModal.fake.ts
Fixes https://github.com/kubermatic/dashboard/issues/3135
```release-note
Added info about GPU count for Azure instances.
```
=> Add GPU count for Azure instances

src/app/cluster/cluster-details/constraints/component.spec.ts, src/app/cluster/cluster-details/constraints/component.ts, src/app/cluster/cluster-details/constraints/constraint-dialog/component.spec.ts, src/app/cluster/cluster-details/constraints/constraint-dialog/template.html, src/app/cluster/cluster-details/constraints/violation-details/component.spec.ts, src/app/cluster/cluster-details/edit-cluster/template.html, src/app/cluster/cluster-details/gatekeeper-config/component.spec.ts, src/app/cluster/cluster-details/gatekeeper-config/component.ts, src/app/cluster/cluster-details/gatekeeper-config/gatekeeper-config-dialog/component.spec.ts, src/app/cluster/cluster-details/gatekeeper-config/gatekeeper-config-dialog/template.html, src/app/cluster/cluster-details/gatekeeper-config/template.html, src/app/cluster/cluster-details/template.html, src/app/settings/admin/component.spec.ts, src/app/settings/admin/constraint-templates/component.spec.ts, src/app/settings/admin/constraint-templates/constraint-template-dialog/component.spec.ts, src/app/settings/admin/constraint-templates/constraint-template-dialog/template.html, src/app/settings/admin/template.html, src/app/shared/entity/opa.ts, src/app/testing/fake-data/opa.fake.ts, src/app/wizard/step/cluster/template.html, src/app/wizard/step/summary/template.html
Enable all components that are related to OPA and add unit tests
Fixes #2970
Fixes #3001
/
```release-note
Added support for OPA to UI
```
=> OPA - enable and test

src/app/node-data/basic/provider/hetzner/component.ts, src/app/shared/entity/cluster.ts, src/app/shared/entity/datacenter.ts, src/app/shared/entity/node.ts, src/app/wizard/module.ts, src/app/wizard/step/provider-settings/component.ts, src/app/wizard/step/provider-settings/provider/extended/hetzner/component.ts, src/app/wizard/step/provider-settings/provider/extended/hetzner/template.html, src/app/wizard/step/provider-settings/provider/extended/template.html, src/app/wizard/step/summary/template.html
Added network to Hetzner
Fixes #3124
FYI: Networks should only be available during cluster creation, but not during cluster edit. The machine deployment needs the exact same network as the cluster, therefor it is copied over.
```release-note
Added network to Hetzner
```
=> Added network to Hetzner

src/app/dynamic/enterprise/theming/picker/component.ts
Fixes #
```release-note
Fixed bug with changing the theme based on the color scheme if enforced_theme was set.
```
=> Do not change the theme based on the color scheme if enforced_theme is set

src/app/node-data/component.ts, src/app/wizard/step/summary/template.html
Changing the provider did not correctly update the node data provider structure. A new provider structure was added and updated, but the old one was not deleted.
Fixes #3148
```release-note
NONE
```
=> Fix switching provider issue in wizard

src/app/node-data/component.ts, src/app/wizard/step/summary/template.html
Backport of the https://github.com/kubermatic/dashboard/pull/3165
```release-note
NONE
```
=> [release/v2.16] Fix switching provider issue in wizard

src/app/core/interceptors/error-notifications/interceptor.ts
Add missing space to error notification
Fixes #3138
/
```release-note
NONE
```
=> Add missing space to error notification

cypress/integration/providers/azure.spec.ts, cypress/utils/preset.ts, cypress/utils/provider.ts, hack/e2e/setup-kubermatic-in-kind.sh
Fixes #2944
```release-note
NONE
```
=> Add e2e tests for the azure provider

src/app/shared/components/tab-card/style.scss
Increase speed of tab animation
Fixes #3061
```release-note
NONE
```
=> Increase speed of tab animation

.prow.yaml, cypress/integration/providers/anexia.spec.ts, cypress/integration/providers/aws.spec.ts, cypress/integration/providers/digitalocean.spec.ts, cypress/integration/providers/gcp.spec.ts, cypress/integration/providers/hetzner.spec.ts, cypress/integration/providers/openstack.spec.ts, cypress/integration/stories/basic.spec.ts, cypress/utils/preset.ts, cypress/utils/provider.ts, hack/e2e/setup-kubermatic-in-kind.sh
Fixes #2946
```release-note
NONE
```
=> Add e2e for hetzner

src/app/cluster/cluster-details/constraints/template.html, src/app/node-data/style.scss, src/app/node-data/template.html, src/app/settings/admin/dynamic-datacenters/template.html, src/app/settings/admin/presets/template.html, src/app/shared/components/combobox/template.html, src/app/wizard/step/cluster/style.scss, src/app/wizard/step/cluster/template.html, src/app/wizard/step/cluster/theme.scss, src/app/wizard/step/provider-settings/preset/template.html, src/assets/css/global/_main.scss, src/assets/css/global/_theme.scss, src/assets/css/material/_main.scss, src/assets/css/material/_theme.scss
Changes and fixes related to dropdowns, such as hovers and sizes
Fixes #3129
/
```release-note
NONE
```
=> Improve dropdown styling

cypress/integration/stories/user-settings.spec.ts, cypress/pages/projects.po.ts, cypress/pages/user-settings.po.ts, src/app/dynamic/enterprise/theming/picker/template.html, src/app/settings/user/user-settings.component.html
Fixes https://github.com/kubermatic/dashboard/issues/2954
```release-note
NONE
```
=> Add E2E tests for user settings

src/app/cluster/cluster-details/cluster-secrets/component.ts, src/app/cluster/cluster-details/cluster-secrets/template.html, src/app/cluster/cluster-details/constraints/component.spec.ts, src/app/cluster/cluster-details/constraints/component.ts, src/app/cluster/cluster-details/constraints/constraint-dialog/component.ts, src/app/cluster/cluster-details/constraints/template.html, src/app/cluster/cluster-details/constraints/violation-details/component.spec.ts, src/app/cluster/cluster-details/constraints/violation-details/component.ts, src/app/cluster/cluster-details/constraints/violation-details/template.html, src/app/cluster/cluster-details/template.html, src/app/core/services/opa/service.ts, src/app/settings/admin/template.html, src/app/wizard/step/cluster/style.scss, src/app/wizard/step/cluster/template.html
Added OPA prefix to all components
Fixed position of checkbox in cluster step in wizard
Added paginators
/
```release-note
NONE
```
=> OPA - Improvements

src/app/cluster/cluster-details/edit-cluster/component.spec.ts, src/app/cluster/cluster-details/edit-cluster/component.ts, src/app/cluster/cluster-details/edit-cluster/style.scss, src/app/cluster/cluster-details/edit-cluster/template.html, src/app/settings/admin/template.html, src/app/shared/entity/settings.ts, src/app/testing/services/settings-mock.service.ts, src/app/wizard/step/cluster/component.ts, src/app/wizard/step/cluster/template.html
Added `enable` & `enforce` OPA options to Admin Settings and select `OPA Integration` checkboxes in cluster creation & edit cluster dialog accordingly.
Fixes #3200
/hold
https://github.com/kubermatic/kubermatic/pull/6787 needs to get merged first
```release-note
Added `enable` & `enforce` OPA options to Admin Settings
```
=> Add OPA Options to Admin Settings

Makefile
Fixes #
```release-note
NONE
```
=> fix EE build

.prow.yaml, hack/e2e/fixtures/kubermatic.yaml, hack/e2e/setup-kubermatic-in-kind.sh
This ensures this branch can be built on the new CI cluster.
Fixes #
```release-note
NONE
```
=> [release/v2.16] use KUBERMATIC_DOMAIN

.prow.yaml, hack/e2e/ci-setup-kubermatic-in-kind.sh
This ensures this branch can be built on the new CI cluster.
Fixes #
```release-note
NONE
```
=> [release/v2.15] use KUBERMATIC_DOMAIN

.github/ISSUE_TEMPLATE/cleanup.md, .github/ISSUE_TEMPLATE/design-change.md, .github/ISSUE_TEMPLATE/design.md, .github/ISSUE_TEMPLATE/failing-test.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/pre-release.md, .github/ISSUE_TEMPLATE/release.md, .github/PULL_REQUEST_TEMPLATE/general.md, .github/PULL_REQUEST_TEMPLATE/release.md, cypress/integration/stories/ssh-keys.spec.ts
Should fix broken issue/PR templates.
```release-note
NONE
```
=> Cleanup and fix release templates

package-lock.json, package.json
Update version in `package.json` and `package-lock.json` for `v2.17.0-alpha.0` release.
```release-note
NONE
```
=> Update version for v2.17.0-alpha.0 release

src/app/core/services/api/service.ts, src/app/core/services/wizard/provider/alibaba.ts, src/app/node-data/basic/provider/alibaba/component.ts, src/app/node-data/basic/provider/alibaba/template.html, src/app/node-data/service/provider/alibaba.ts, src/app/shared/entity/provider/alibaba.ts, src/app/testing/fake-data/alibaba.fake.ts, src/app/testing/services/api-mock.service.ts
Added option to select Alibaba VSwitch from list
```release-note
NONE
```
=> Added Alibaba VSwitch

src/app/node-data/basic/provider/vsphere/component.ts
Previously Ubuntu was used as default even if it wasn't configured for the chosen datacenter. Right now, the datacenter configuration is taken under consideration.
Fixes https://github.com/kubermatic/dashboard/issues/3207
```release-note
Set default VM template based on the available operating systems.
```
=> Set default template based on the available operating systems

cypress/integration/providers/anexia.spec.ts, cypress/pages/wizard.po.ts, src/app/core/services/api/service.ts, src/app/core/services/wizard/presets.service.ts, src/app/core/services/wizard/provider/anexia.ts, src/app/node-data/basic/provider/anexia/component.ts, src/app/node-data/basic/provider/anexia/template.html, src/app/node-data/dialog/component.ts, src/app/node-data/service/provider/anexia.ts, src/app/node-data/service/service.ts, src/app/shared/entity/cluster.ts, src/app/shared/entity/datacenter.ts, src/app/shared/entity/node.ts, src/app/shared/entity/provider/anexia.ts, src/app/testing/fake-data/anexia.fake.ts, src/app/testing/services/api-mock.service.ts
Use endpoints to fetch anexia vlans & templates
Fixes #3261
Fixes #3263
```release-note
NONE
```
=> Use endpoints to fetch anexia vlans & templates

src/app/node-data/component.ts
Fixes https://github.com/kubermatic/dashboard/issues/3323.
```release-note
Disabled CentOS for GCP.
```
=> Disable CentOS for GCP

src/app/core/services/api/service.ts, src/app/core/services/wizard/provider/aws.ts
Extend endpoints to filter AWS sizes
Fixes #3283
```release-note
NONE
```
=> Extend endpoints to filter AWS sizes

src/app/core/components/sidenav/style.scss
Fixes https://github.com/kubermatic/dashboard/issues/3334.
```release-note
Fixed sidenav background behaviour.
```
=> Fix sidenav background behaviour

.github/dependabot.yml
=> Upgrade to GitHub-native dependabot

cypress/integration/stories/admin-settings/dynamic-datacenters.spec.ts, cypress/pages/admin-settings.po.ts, cypress/utils/provider.ts, hack/e2e/run-tests.sh, package.json, src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html, src/app/settings/admin/dynamic-datacenters/template.html
Fixes https://github.com/kubermatic/dashboard/issues/3305.
```release-note
NONE
```
=> Add e2e tests for dynamic datacenters

src/app/wizard/step/provider-datacenter/component.ts, src/app/wizard/step/provider-datacenter/style.scss, src/app/wizard/step/provider-datacenter/template.html
Fixes https://github.com/kubermatic/dashboard/issues/3294.
```release-note
Added warning in the wizard when there is no configured seed.
```
=> Add warning in the wizard when there is no configured seed

cypress/integration/stories/admin-settings/administrators.spec.ts, cypress/integration/stories/admin-settings/custom-links.spec.ts, cypress/integration/stories/admin-settings/presets.spec.ts, cypress/pages/admin-settings.po.ts, cypress/pages/wizard.po.ts, src/app/settings/admin/presets/dialog/steps/preset/template.html, src/app/settings/admin/presets/dialog/steps/provider/template.html, src/app/settings/admin/presets/dialog/steps/settings/provider/digitalocean/template.html, src/app/settings/admin/presets/dialog/template.html, src/app/settings/admin/presets/template.html
Closes #3307
```release-note
NONE
```
=> Add e2e test for preset

src/app/cluster/cluster-details/constraints/style.scss, src/app/cluster/cluster-details/constraints/template.html, src/app/cluster/cluster-details/gatekeeper-config/template.html, src/app/cluster/cluster-details/machine-deployment-details/style.scss, src/app/cluster/cluster-details/machine-deployment-details/template.html, src/app/cluster/cluster-details/rbac/style.scss, src/app/cluster/cluster-details/rbac/template.html, src/app/cluster/cluster-details/style.scss, src/app/cluster/cluster-details/template.html, src/app/cluster/external-cluster-details/style.scss, src/app/cluster/external-cluster-details/template.html, src/app/serviceaccount/token/style.scss, src/app/serviceaccount/token/template.html, src/app/settings/admin/admins/style.scss, src/app/settings/admin/admins/template.html, src/app/settings/admin/constraint-templates/template.html, src/app/settings/admin/dynamic-datacenters/style.scss, src/app/settings/admin/dynamic-datacenters/template.html, src/app/settings/admin/presets/style.scss, src/app/settings/admin/presets/template.html, src/app/shared/components/addon-list/component.ts, src/app/shared/components/addon-list/style.scss, src/app/shared/components/addon-list/template.html, src/app/shared/components/addon-list/theme.scss, src/assets/css/global/_main.scss, src/assets/css/material/_main.scss, src/assets/css/material/_theme.scss
Fixes https://github.com/kubermatic/dashboard/issues/3372.
At the moment all buttons in the admin settings card at the bottom are aligned to the top to keep them in the same place. I've removed the constant height for all headers as I had the feeling that too much space is empty. @cschieder what do you think, how should we proceed?
You can compare it to what we have at dev environment.
```release-note
NONE
```
=> Update button styling

src/app/cluster/cluster-details/edit-cluster/template.html, src/app/cluster/cluster-details/edit-sshkeys/component.ts, src/app/shared/components/add-ssh-key-dialog/component.ts, src/app/shared/components/add-ssh-key-dialog/template.html, src/app/shared/components/addon-list/template.html, src/app/wizard/step/cluster/template.html, src/assets/css/material/_main.scss
Fixes https://github.com/kubermatic/dashboard/issues/3395.
```release-note
NONE
```
=> Update text in some places

src/app/node-data/component.ts
Fix replica count, as it was automatically reset to default after a few seconds. 
```release-note
Fixed replica count, as it was automatically reset to default after a few seconds.
```
=> Fix replica count

src/app/serviceaccount/component.ts, src/app/settings/admin/presets/dialog/steps/preset/component.ts, src/app/settings/admin/presets/dialog/steps/preset/template.html, src/app/settings/admin/presets/dialog/steps/service.ts, src/app/settings/admin/presets/dialog/steps/settings/component.ts, src/app/settings/admin/presets/dialog/steps/settings/template.html
- Add regex validation for the domain restriction
- Add datacenter name auto-completion to the preset provider
Fixes https://github.com/kubermatic/kubermatic/issues/6480
```release-note
NONE
```
=> Presets improvements

src/assets/css/material/_main.scss
Fixes https://github.com/kubermatic/dashboard/issues/3430.
```release-note
NONE
```
=> Fix button styling

src/app/cluster/cluster-details/node-list/component.ts, src/app/cluster/cluster-details/node-list/template.html
Fixed #3428
```release-note
NONE
```
=> Fix sorting on node list

src/app/cluster/cluster-list/template.html, src/app/project/component.ts, src/app/project/template.html
Fixes https://github.com/kubermatic/dashboard/issues/3420.
```release-note
NONE
```
=> Add search for projects

src/app/settings/admin/presets/dialog/steps/settings/provider/azure/component.ts, src/app/settings/admin/presets/dialog/steps/settings/provider/azure/template.html, src/app/shared/entity/cluster.ts, src/app/shared/entity/preset.ts, src/app/testing/fake-data/cluster.ts, src/app/wizard/step/provider-settings/provider/extended/azure/component.ts, src/app/wizard/step/provider-settings/provider/extended/azure/template.html, src/app/wizard/step/summary/template.html
Add Azure LoadBalancer SKU
Fixes #3424
```release-note
Added option to select Azure LoadBalancer SKU in cluster creation
```
=> Add Azure LoadBalancer SKU

src/app/settings/admin/presets/dialog/steps/settings/provider/azure/component.ts, src/app/settings/admin/presets/dialog/steps/settings/provider/azure/template.html, src/app/shared/entity/cluster.ts, src/app/shared/entity/preset.ts, src/app/testing/fake-data/cluster.fake.ts, src/app/wizard/step/provider-settings/provider/extended/azure/component.ts, src/app/wizard/step/provider-settings/provider/extended/azure/template.html, src/app/wizard/step/summary/template.html
Add Azure LoadBalancer SKU
cherry-picked from https://github.com/kubermatic/dashboard/pull/3455
```release-note
Added option to select Azure LoadBalancer SKU in cluster creation
```
=> [release/v2.17] Add Azure LoadBalancer SKU

src/app/shared/entity/cluster.ts, src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts, src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html, src/app/wizard/step/summary/template.html
Closes https://github.com/kubermatic/kubermatic/issues/7283.
```release-note
Added option to specify vSphere resource pool.
```
=> Add vSphere resource pool

src/app/shared/components/tab-card/style.scss
Fixes https://github.com/kubermatic/dashboard/issues/3452.
```release-note
NONE
```
=> Reduce minimum tab width

src/app/project/component.ts, src/app/project/template.html, src/assets/css/global/_main.scss
Fixes https://github.com/kubermatic/dashboard/issues/3443.
```release-note
NONE
```
=> Project page improvements

src/app/cluster/cluster-details/component.spec.ts, src/app/cluster/cluster-details/component.ts, src/app/cluster/cluster-details/edit-cluster/template.html, src/app/cluster/cluster-details/rule-groups/component.spec.ts, src/app/cluster/cluster-details/rule-groups/component.ts, src/app/cluster/cluster-details/rule-groups/rule-group-dialog/component.spec.ts, src/app/cluster/cluster-details/rule-groups/rule-group-dialog/component.ts, src/app/cluster/cluster-details/rule-groups/rule-group-dialog/style.scss, src/app/cluster/cluster-details/rule-groups/rule-group-dialog/template.html, src/app/cluster/cluster-details/rule-groups/style.scss, src/app/cluster/cluster-details/rule-groups/template.html, src/app/cluster/cluster-details/template.html, src/app/cluster/module.ts, src/app/core/services/mla.ts, src/app/settings/admin/defaults/template.html, src/app/shared/utils/mla-utils.ts, src/app/testing/fake-data/mla.ts, src/app/wizard/step/cluster/template.html, src/app/wizard/step/summary/template.html
Extend cluster details view by tab User Cluster Alert Rules
Fixes #3422
Fixes #3426
```release-note
Extend cluster details view by tab User Cluster Alert Rules for MLA
```
=> Extend cluster details view by tab User Cluster Alert Rules

src/app/core/services/wizard/provider/openstack.ts, src/app/core/services/wizard/provider/provider.ts, src/app/node-data/service/provider/openstack.ts, src/app/shared/entity/cluster.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/template.html, src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
Cherry-pick of https://github.com/kubermatic/dashboard/pull/3480
```release-note
Added support for Application Credentials to the Openstack provider
```
=> [v2.17] Add support for openstack app credentials

Makefile, package-lock.json, package.json
Bump the Dashboard version to v2.17.2.
```release-note
NONE
```
/assign @floreks
=> Bump the Dashboard version to v2.17.2

src/app/shared/components/cidr-form/component.ts, src/app/shared/validators/others.ts, src/app/wizard/step/cluster/component.ts, src/app/wizard/step/cluster/template.html
=> Allow only one CIDR for pods and services

src/app/core/services/cluster-spec.ts, src/app/core/services/wizard/provider/openstack.ts, src/app/node-data/basic/provider/hetzner/component.ts, src/app/node-data/basic/provider/openstack/template.html, src/app/wizard/module.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/application/component.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/application/template.html, src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/default/component.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/default/template.html, src/app/wizard/step/provider-settings/provider/basic/openstack/style.scss, src/app/wizard/step/provider-settings/provider/basic/openstack/template.html, src/app/wizard/step/provider-settings/provider/basic/openstack/theme.scss, src/app/wizard/step/provider-settings/provider/extended/azure/component.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/application/template.html, src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/default/template.html, src/app/wizard/step/provider-settings/provider/extended/openstack/service.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/template.html, src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts, src/assets/css/theme/_component.scss
- Added credentials type selector to switch between the user/application credentials
- Updated credentials handling and additional data resolving
Fixes #3521
```release-note
Redesign Openstack provider settings step to better support different type of credentials
```
=> Fix Openstack credentials support

src/app/core/services/wizard/provider/openstack.ts, src/app/node-data/basic/provider/openstack/template.html, src/app/shared/services/cluster.service.ts, src/app/wizard/module.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/application/component.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/application/template.html, src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/default/component.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/default/template.html, src/app/wizard/step/provider-settings/provider/basic/openstack/style.scss, src/app/wizard/step/provider-settings/provider/basic/openstack/template.html, src/app/wizard/step/provider-settings/provider/basic/openstack/theme.scss, src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/application/template.html, src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/default/template.html, src/app/wizard/step/provider-settings/provider/extended/openstack/service.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/template.html, src/assets/css/theme/_component.scss
- Added credentials type selector to switch between the user/application credentials
- Updated credentials handling and additional data resolving
```release-note
Redesign Openstack provider settings step to better support different types of credentials
```
=> [v2.17] Fix Openstack credentials support

src/app/cluster/cluster-details/component.ts, src/app/cluster/cluster-details/template.html, src/app/core/services/cluster.ts, src/app/shared/entity/cluster.ts, src/app/testing/fake-data/cluster-with-machine-networks.ts, src/app/testing/fake-data/cluster.ts, src/assets/css/global/_theme.scss
Closes https://github.com/kubermatic/dashboard/issues/3159.
```release-note
Added support for external CCM migration.
```
=> Support external CCM migration

src/app/serviceaccount/component.spec.ts, src/app/serviceaccount/component.ts, src/app/serviceaccount/template.html
Remove status indicator from service account view
Fixes #2804
```release-note
NONE
```
=> Remove status indicator from service account view

src/app/core/components/notification-panel/component.ts, src/app/core/interceptors/error-notifications.ts, src/app/core/services/node-data/provider/alibaba.ts, src/app/core/services/notification.ts, src/app/node-data/basic/provider/alibaba/component.ts, src/assets/css/global/_main.scss, src/assets/css/global/_theme.scss
- Added option to get unread notifications count (logic only for now)
- Improved error interceptor and added error notification mapping for alibaba
- Added small debounce to the alibaba form
- Fixed an issue with notification box styling when error message was too short
Closes #3569
```release-note
NONE
```
=> Improve aliababa wizard form handling

src/app/core/interceptors/error-notifications.ts, src/app/core/services/node-data/provider/anexia.ts
- Added error notification mapping for anexia
- Added small debounce to the anexia form
Closes #3570
```release-note
NONE
```
=> Improve anexia wizard form handling

src/app/core/interceptors/error-notifications.ts, src/app/core/services/node-data/provider/aws.ts, src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
- Added error notification mapping for aws
- Added small debounce to the aws form
Closes #3571
```release-note
NONE
```
=> Improve AWS wizard form handling

src/app/core/interceptors/error-notifications.ts, src/app/core/services/node-data/provider/digitalocean.ts, src/app/core/services/node-data/provider/gcp.ts, src/app/core/services/node-data/provider/hetzner.ts, src/app/wizard/step/provider-settings/provider/extended/azure/component.ts, src/app/wizard/step/provider-settings/provider/extended/gcp/component.ts, src/app/wizard/step/provider-settings/provider/extended/hetzner/component.ts
- Added error notification mapping for new providers
- Added small debounce to the provider forms
Closes #3573
Closes #3574
Closes #3575
```release-note
NONE
```
=> Improve DigitalOcean/GCP/Hetzner wizard form handling

src/app/core/components/notification-panel/component.ts, src/app/core/interceptors/error-notifications.ts, src/app/core/services/node-data/provider/azure.ts, src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
- Added error notification mapping for azure
- Added small debounce to the azure form
- Fixed an issue with newest notifications not being shown on the top
Closes #3572
```release-note
NONE
```
=> Improve Azure wizard form handling

src/app/cluster/cluster-details/template.html
This PR renames `User Cluster Alert Rules` to `User Cluster Recording & Alerting Rules`
```release-note
NONE
```
=> [MLA] Rename User Cluster Alert Rules to User Cluster Recording & Alerting Rules

src/app/dynamic/common.ts, src/app/dynamic/community/allowed-registries/module.ts, src/app/dynamic/enterprise/allowed-registries/allowed-registry-dialog/component.ts, src/app/dynamic/enterprise/allowed-registries/allowed-registry-dialog/template.html, src/app/dynamic/enterprise/allowed-registries/component.ts, src/app/dynamic/enterprise/allowed-registries/entity.ts, src/app/dynamic/enterprise/allowed-registries/module.ts, src/app/dynamic/enterprise/allowed-registries/service.ts, src/app/dynamic/enterprise/allowed-registries/style.scss, src/app/dynamic/enterprise/allowed-registries/template.html, src/app/dynamic/module-registry.ce.ts, src/app/dynamic/module-registry.ts, src/app/settings/admin/opa/component.ts, src/app/settings/admin/opa/routing.ts, src/app/settings/admin/opa/template.html, src/app/shared/components/tab-card/component.ts, src/app/shared/components/tab-card/dynamic-tab/component.ts, src/app/shared/components/tab-card/dynamic-tab/template.html, src/app/shared/components/tab-card/template.html, src/app/shared/model/dynamic-tab.ts, src/app/shared/module.ts
Adds Allowed Registries to UI. Note that this is **only** an ee feature.
Fixes #3518
```release-note
EE: Added Allowed Registries
```
=> Add Allowed Registries

Makefile
Right now the version on dev says its "2.17.0-dev", even though it's 2.18-dev. This PR fixes that.
```release-note
NONE
```
=> fix dev versions

hack/e2e/setup-kubermatic-in-kind.sh
Disable telemetry in ci
```release-note
NONE
```
=> Disable telemetry in ci

src/app/core/services/page-title.ts
It was causing consistent notification error popup on the login screen.
```release-note
NONE
```
=> Avoid setting custom page title when user is not logged in

src/app/shared/components/cluster-from-template/component.ts, src/app/shared/components/cluster-from-template/template.html, src/app/shared/components/cluster-summary/component.ts, src/app/shared/components/cluster-summary/template.html, src/app/shared/components/save-cluster-template/component.ts, src/app/shared/components/save-cluster-template/template.html, src/app/shared/entity/cluster-template.ts, src/app/wizard/component.ts, src/app/wizard/step/summary/component.ts, src/app/wizard/step/summary/template.html
Closes https://github.com/kubermatic/dashboard/issues/3634.
```release-note
NONE
```
=> Add SSH keys for cluster templates

src/app/cluster/cluster-details/mla/alertmanager-config/component.ts
Fix grafana link
```release-note
NONE
```
=> Fix grafana link

src/app/core/services/node-data/provider/azure.ts, src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
Fixes NPE found during testing.
```release-note
NONE
```
=> Fix Azure cluster creation

src/app/node-data/extended/provider/digitalocean/template.html, src/app/wizard/step/provider-settings/provider/basic/aws/component.ts, src/app/wizard/step/provider-settings/provider/basic/aws/template.html, src/app/wizard/step/provider-settings/provider/basic/openstack/application/component.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/application/template.html, src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/default/component.ts, src/app/wizard/step/provider-settings/provider/basic/openstack/default/template.html, src/app/wizard/step/provider-settings/provider/basic/openstack/template.html, src/app/wizard/step/provider-settings/provider/basic/vsphere/template.html, src/app/wizard/step/provider-settings/provider/extended/gcp/component.ts, src/app/wizard/step/provider-settings/provider/extended/gcp/template.html, src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/application/template.html, src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts, src/app/wizard/step/provider-settings/provider/extended/openstack/default/template.html, src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts, src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
Fixes https://github.com/kubermatic/dashboard/issues/3663.
```release-note
Disable provider-specific fields if preset was selected.
```
=> Disable comboboxes if preset was selected

src/app/cluster/cluster-details/change-cluster-version/component.ts, src/app/cluster/cluster-details/change-cluster-version/style.scss, src/app/cluster/cluster-details/change-cluster-version/template.html
Fixes https://github.com/kubermatic/dashboard/issues/3665.
```release-note
NONE
```
=> Fix change version dialog

src/app/core/services/node-data/provider/alibaba.ts
Fixes https://github.com/kubermatic/dashboard/issues/3683.
```release-note
NONE
```
=> Do not send requests in wizard before Alibaba datacenter is picked

src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/component.ts, src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/template.html, src/app/shared/entity/preset.ts
UI part for https://github.com/kubermatic/kubermatic/pull/7796.
```release-note
NONE
```
=> Add vSphere resource pool to the preset 

src/app/settings/admin/bucket-settings/edit-credentials-dialog/component.ts, src/app/shared/entity/backup.ts
Updated object structure to match the API.
#3687
```release-note
NONE
```
=> Update backup credentials object

.github/ISSUE_TEMPLATE/pre-release.md
It adds new features to the checklist and also adds a few improvements to it.
```release-note
NONE
```
=> Update pre-release procedure

package-lock.json, package.json
Update version in related files to `v2.18`.
Closes #3698
```release-note
NONE
```
=> [v2.18] Version bump

src/assets/config/changelog.json
As in the title
```release-note
NONE
```
=> Add changelog for v2.18

.prow.yaml, containers/chrome-headless/Dockerfile, containers/chrome-headless/release.sh, containers/e2e-kind-cypress/Dockerfile, containers/e2e-kind-cypress/release.sh, cypress/integration/providers/openstack.spec.ts, cypress/integration/providers/vsphere.spec.ts, cypress/integration/stories/admin-settings/administrators.spec.ts, cypress/integration/stories/machine-deployment.spec.ts, cypress/plugins/index.ts, hack/e2e/setup-kubermatic-in-kind.sh, package.json
Closes https://github.com/kubermatic/dashboard/issues/3713.
```release-note
NONE
```
=> Skip provider tests in community edition and update the images

src/assets/css/material/_main.scss
Fixed labels view, as long labels were a problem
Fixes #3716
```release-note
NONE
```
=> Fix labels view

src/app/settings/admin/bucket-settings/edit-bucket-setting-dialog/component.ts, src/app/settings/admin/bucket-settings/edit-bucket-setting-dialog/template.html
Remove default endpoint hint + make it required
Fixes #3703
```release-note
NONE
```
=> Remove default endpoint hint

src/app/cluster/cluster-details/template.html
@shaase-ctrl 
Close https://github.com/kubermatic/dashboard/issues/3745.
```release-note
NONE
```
=> Add seed info to cluster details view

src/app/core/components/notification-panel/style.scss, src/app/core/components/notification-panel/template.html
Fixes #3744 
```release-note
NONE
```
=> Fix filter icon alignment

hack/check-licenses.sh, hack/development/run-npm-in-docker.sh, hack/e2e/run-tests.sh, hack/e2e/setup-kind-cluster.sh, hack/e2e/setup-kubermatic-in-kind.sh, hack/extract-themes.sh, hack/run-dashboard.sh, hack/run-in-docker.sh, hack/run-local-dashboard.sh, hack/upload-coverage.sh, src/app/core/components/notification/component.ts, src/app/core/interceptors/error-notifications.ts, src/app/wizard/step/provider-settings/provider/extended/azure/component.ts, src/assets/css/global/_main.scss
- Add error mapping entry for the resource group related errors. It will now display a single error notification instead.
- Restore a shebang line in our bash scripts
- Improve the notification overlay area not to block visible elements that were placed below the notification element
- Slightly increase the debounce time to increase the chance of avoiding multiple overlapping calls that might result in error notification
Fixes #3756
```release-note
NONE
```
=> Improve azure error handling and more

cypress/fixtures/projects.json, cypress/integration/stories/admin-settings/administrators.spec.ts, cypress/integration/stories/multi-owner.spec.ts, cypress/integration/stories/user-settings.spec.ts, cypress/pages/clusters.po.ts, cypress/pages/projects.po.ts, cypress/pages/service-accounts.po.ts, cypress/pages/ssh-keys.po.ts, cypress/utils/auth.ts, cypress/utils/mocks.ts, cypress/utils/monitor.ts
Closes https://github.com/kubermatic/dashboard/issues/3710.
```release-note
NONE
```
=> Traffic monitor improvements

src/app/cluster/cluster-details/edit-sshkeys/component.ts, src/app/shared/components/relativetime/component.spec.ts, src/app/shared/components/relativetime/component.ts, src/app/shared/pipes/relativetime.ts, src/app/testing/services/app-config-mock.ts
Fixes https://github.com/kubermatic/dashboard/issues/3619.
```release-note
NONE
```
=> Fix relative time display

src/app/cluster/cluster-details/constraints/template.html, src/app/cluster/cluster-details/mla/rule-groups/template.html, src/app/cluster/cluster-details/version-picker/style.scss, src/app/dynamic/enterprise/theming/picker/style.scss, src/app/settings/admin/defaults/style.scss, src/app/settings/admin/defaults/template.html, src/app/settings/admin/dynamic-datacenters/template.html, src/app/settings/admin/opa/default-constraints/template.html, src/app/settings/admin/presets/template.html, src/app/shared/components/cidr-form/style.scss, src/app/shared/components/combobox/template.html, src/app/shared/components/label-form/style.scss, src/app/shared/components/taint-form/style.scss, src/app/wizard/step/provider-settings/preset/template.html, src/assets/css/global/_main.scss, src/assets/css/material/_main.scss
Reduce height of formfields
Fixes #3385
```release-note
NONE
```
=> Reduce height of formfields

.prow.yaml, cypress/integration/providers/kubevirt.spec.ts, cypress/integration/providers/vsphere.spec.ts, cypress/integration/stories/ssh-keys.spec.ts, cypress/pages/clusters.po.ts, cypress/pages/projects.po.ts, cypress/plugins/index.ts, cypress/utils/preset.ts, cypress/utils/provider.ts, package.json, src/app/shared/entity/cluster.spec.ts
Fixes https://github.com/kubermatic/dashboard/issues/3459.
```release-note
NONE
```
=> Enable disabled E2E tests 

src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/style.scss, src/app/cluster/cluster-details/rbac/add-binding/style.scss, src/app/core/components/sidenav/style.scss, src/app/dynamic/enterprise/allowed-registries/style.scss, src/app/dynamic/enterprise/metering/config/style.scss, src/app/dynamic/enterprise/theming/picker/style.scss, src/app/machine-networks/style.scss, src/app/node-data/style.scss, src/app/project/style.scss, src/app/settings/admin/admins/style.scss, src/app/settings/admin/bucket-settings/style.scss, src/app/settings/admin/dynamic-datacenters/style.scss, src/app/settings/admin/nav/style.scss, src/app/settings/admin/opa/constraint-templates/style.scss, src/app/settings/admin/opa/default-constraints/style.scss, src/app/settings/admin/presets/style.scss, src/app/wizard/step/cluster/style.scss, src/app/wizard/step/provider-settings/provider/basic/openstack/style.scss, src/assets/css/global/_main.scss, src/assets/css/material/_main.scss
Adjust button height to 45px so that they are aligned to the new formfield height.
Fixes #3861
```release-note
NONE
```
=> Adjust button height

src/app/core/components/footer/theme.scss, src/app/pages/api-docs/theme.scss, src/app/wizard/step/cluster/template.html, src/assets/css/theme/_main.scss, src/assets/themes/dark.scss, src/assets/themes/light.scss
Fixes https://github.com/kubermatic/dashboard/issues/3692.
```release-note
NONE
```
=> Adjust Swagger dark theme

src/app/component.ts, src/app/core/components/footer/style.scss, src/app/settings/admin/nav/style.scss, src/app/style.scss, src/app/template.html, src/assets/css/_variables.scss
The scrollbar will be now part of the page content (on the right of the side nav).
Fixes #3850
```release-note
NONE
```
=> Make footer a part of the content and fix styling on admin settings

src/app/cluster/cluster-details/mla/alertmanager-config/component.ts, src/app/shared/entity/datacenter.ts
Add seed dns overwrite option to mla links
Fixes https://github.com/kubermatic/kubermatic/issues/7964
```release-note
NONE
```
=> Add seed dns overwrite option to mla links

src/app/core/interceptors/error-notifications.ts, src/app/shared/validators/async-credentials.validator.ts
Typo in API endpoint name was fixed in https://github.com/kubermatic/kubermatic/pull/8354. This change adjusts UI to work with it.
```release-note
NONE
```
=> Adjust endpoint name

src/app/core/components/navigation/component.ts
Small sidenav logic update to fully rely on the API when showing/hiding the sidenav.
Closes #3900 
```release-note
NONE
```
=> Small sidenav logic update

src/app/cluster/cluster-details/cluster-secrets/component.spec.ts, src/app/cluster/cluster-details/cluster-secrets/component.ts, src/app/cluster/cluster-details/cluster-secrets/template.html, src/app/shared/entity/health.ts
Add health status for mla
Fixes #3279
```release-note
NONE
```
=> Add health status for mla

src/app/cluster/cluster-details/cni-version/cni-version-dialog/component.ts, src/app/cluster/cluster-details/cni-version/component.ts, src/app/cluster/cluster-details/cni-version/template.html
Only display cni versions greater than current one in dialog
```release-note
NONE
```
=> Only display cni versions greater than current one

src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/component.ts, src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/template.html, src/app/cluster/cluster-details/machine-deployment-details/component.ts, src/app/cluster/cluster-details/machine-deployment-details/template.html, src/app/cluster/cluster-details/machine-deployment-list/component.ts, src/app/cluster/cluster-details/machine-deployment-list/template.html, src/app/cluster/cluster-details/node-list/component.ts, src/app/cluster/cluster-details/node-list/template.html, src/app/cluster/cluster-details/version-picker/component.ts, src/app/cluster/cluster-details/version-picker/template.html, src/app/cluster/cluster-list/component.ts, src/app/cluster/external-cluster-details/component.ts, src/app/cluster/external-cluster-details/style.scss, src/app/cluster/external-cluster-details/template.html, src/app/core/services/cluster.ts, src/app/core/services/page-title.ts, src/app/node-data/kubelet-version/component.ts, src/app/node-data/kubelet-version/template.html, src/app/shared/components/add-external-cluster-dialog/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/cluster/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/eks/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/gke/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/credentials/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/provider/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/service.ts, src/app/shared/components/external-cluster-data-dialog/component.ts, src/app/shared/entity/cluster.spec.ts, src/app/shared/entity/cluster.ts, src/app/shared/entity/external-cluster-model.ts
Closes https://github.com/kubermatic/dashboard/issues/3897.
```release-note
NONE
```
=> Display more external cluster details

src/app/settings/admin/presets/dialog/steps/settings/provider/aws/template.html, src/app/settings/admin/presets/dialog/steps/settings/provider/eks/component.ts, src/app/settings/admin/presets/dialog/steps/settings/provider/eks/template.html, src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/template.html, src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/aks/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/aks/template.html, src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/eks/template.html, src/app/shared/components/add-external-cluster-dialog/steps/credentials/template.html, src/app/shared/components/add-external-cluster-dialog/steps/service.ts, src/app/shared/entity/external-cluster-model.ts, src/app/shared/entity/preset.ts
Closes https://github.com/kubermatic/dashboard/issues/3945.
https://github.com/kubermatic/kubermatic/pull/8460 is required for AKS presets to work.
```release-note
NONE
```
=> Enable presets for AKS and EKS

src/app/backup/details/automatic-backup/backups/component.ts, src/app/backup/details/automatic-backup/template.html
Add missing destination to etcd restore
```release-note
NONE
```
=> Add destination to etcd restore

src/app/shared/entity/cluster.ts
Updates supported Cilium version to 1.11 to align with https://github.com/kubermatic/kubermatic/pull/8450
```release-note
NONE
```
=> Update supported Cilium version to 1.11

src/app/wizard/step/cluster/component.ts
Enable konnectivity by default
Fixes https://github.com/kubermatic/kubermatic/issues/8129
```release-note
NONE
```
=> Enable konnectivity by default

src/app/core/services/project.ts, src/app/project/style.scss
#3865 changed default size of icon buttons to 45px x 45px and this made the project card buttons too big for the card itself. It reverts mentioned buttons size back to 40px x 40px.
Fixes https://github.com/kubermatic/dashboard/issues/3944.
```release-note
NONE
```
=> Fix project card buttons styling

Makefile, package-lock.json, package.json
Bumps the version to 2.18.4.
Towards #3968
```release-note
NONE
```
=> [release/v2.18] Version bump for 2.18.4

src/assets/css/material/_main.scss
Closes https://github.com/kubermatic/dashboard/issues/3930.
```release-note
NONE
```
=> Fix icon button borders

src/assets/css/material/_main.scss
Pointers will be used only over clickable part of the checboxes.
Fixes https://github.com/kubermatic/dashboard/issues/3901.
```release-note
NONE
```
=> Fix checkbox cursor

src/app/backup/list/snapshot/restore-dialog/component.ts
Use destination in restore dialog
```release-note
NONE
```
=> Use destination in restore dialog

src/app/shared/entity/cluster.ts
Update the list of supported Canal version to align with https://github.com/kubermatic/kubermatic/pull/8510 and https://github.com/kubermatic/kubermatic/pull/8527
```release-note
NONE
```
=> Update Canal supported versions - add v3.21, remove v3.8

src/app/core/services/backup.ts, src/app/settings/admin/bucket-settings/destinations/component.ts
Use delete endpoint for backup destinations
Fixes #3992
```release-note
NONE
```
=> Use delete endpoint for backup destinations

src/app/shared/entity/cluster.ts, src/app/wizard/step/cluster/component.ts
Do not allow ebpf proxy mode if konnectivity is disabled
Fixes https://github.com/kubermatic/kubermatic/issues/8496
```release-note
NONE
```
=> Do not allow ebpf proxy mode if konnectivity is disabled

src/app/cluster/details/external-cluster/component.ts, src/app/cluster/details/external-cluster/template.html
- hide version picker if API is not returning version
- refactor subscriptions on details page to improve load times
```release-note
NONE
```
=> External clusters improvements

src/app/cluster/details/shared/version-change-dialog/template.html
=> Do not show updates available badge if there are none

src/app/cluster/details/external-cluster/component.ts
=> Update subscriptions to improve data load

.github/ISSUE_TEMPLATE/pre-release.md
Just to keep our pre-release checklist up-to-date with latest features.
```release-note
NONE
```
=> Update pre-release steps

src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts, src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html, src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts, src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html, src/app/cluster/details/external-cluster/replicas-dialog/component.ts, src/app/cluster/details/external-cluster/replicas-dialog/template.html, src/app/cluster/module.ts, src/app/core/services/cluster.ts, src/app/shared/entity/external-machine-deployment.ts
Closes https://github.com/kubermatic/dashboard/issues/4015.
```release-note
NONE
```
=> Allow editing replica count for external clusters

src/app/core/services/node.ts, src/app/node-data/component.ts, src/app/node-data/dialog/component.ts, src/app/node-data/dialog/template.html
Fix https://github.com/kubermatic/dashboard/issues/4029.
```release-note
NONE
```
=> Fix MD edit

src/app/cluster/details/cluster/cluster-delete-confirmation/template.html, src/app/cluster/details/cluster/component.ts, src/app/cluster/details/cluster/edit-cluster/template.html, src/app/cluster/details/cluster/machine-deployment-list/component.ts, src/app/cluster/details/cluster/rbac/add-binding/template.html, src/app/cluster/details/cluster/template.html, src/app/cluster/details/external-cluster/component.ts, src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts, src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html, src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts, src/app/cluster/details/external-cluster/external-node-list/component.ts, src/app/cluster/details/external-cluster/replicas-dialog/component.ts, src/app/cluster/details/external-cluster/template.html, src/app/project/edit-project/template.html, src/app/settings/admin/admins/add-admin-dialog/template.html, src/app/shared/components/add-project-dialog/template.html, src/app/shared/entity/external-cluster.ts
Closes https://github.com/kubermatic/dashboard/issues/4033.
Closes https://github.com/kubermatic/dashboard/issues/4032.
```release-note
NONE
```
=> Handle new external cluster statuses and few other improvements

src/app/cluster/details/cluster/machine-deployment-details/style.scss, src/app/cluster/details/cluster/machine-deployment-details/template.html, src/app/cluster/details/cluster/mla/alertmanager-config/component.ts, src/app/cluster/details/cluster/rbac/add-binding/component.ts
Fixes https://github.com/kubermatic/dashboard/issues/4049.
Fixes https://github.com/kubermatic/dashboard/issues/4046.
Fixes https://github.com/kubermatic/dashboard/issues/4048.
```release-note
NONE
```
=> Multiple fixes

src/app/cluster/list/external-cluster/component.ts, src/app/cluster/list/external-cluster/template.html
Closes https://github.com/kubermatic/dashboard/issues/4060.
```release-note
NONE
```
=> Block access to custom external clusters in error state

src/app/shared/components/event-card/component.ts, src/app/shared/components/event-card/template.html, src/app/shared/components/event-list/component.ts, src/assets/css/_images.scss, src/assets/images/icons/warning-event.svg
Closes https://github.com/kubermatic/dashboard/issues/4068.
```release-note
NONE
```
=> Update event icons

src/app/cluster/details/cluster/machine-deployment-list/component.ts, src/app/cluster/details/cluster/machine-deployment-list/template.html
Closes https://github.com/kubermatic/dashboard/issues/4031.
```release-note
NONE
```
=> Display operating system logos in machine deployment list

src/app/cluster/details/cluster/component.ts, src/app/cluster/details/cluster/style.scss, src/app/cluster/details/cluster/template.html, src/app/cluster/details/shared/version-picker/style.scss, src/app/shared/components/property-boolean/template.html, src/app/shared/components/property-health/template.html, src/app/shared/components/property-usage/style.scss, src/app/shared/components/property-usage/template.html, src/app/shared/components/property/component.ts, src/app/shared/components/property/style.scss, src/app/shared/components/property/template.html, src/assets/css/global/_main.scss, src/assets/css/global/_theme.scss
Updated the styling to match the new design.
Closes #4061
```release-note
Redesigned the cluster details additional information section.
```
=> Update cluster additional details style

src/app/cluster/details/cluster/edit-cluster/component.ts, src/app/cluster/details/cluster/edit-cluster/template.html, src/app/wizard/step/cluster/component.ts, src/app/wizard/step/cluster/template.html
Fixes https://github.com/kubermatic/dashboard/issues/4063.
```release-note
NONE
```
=> Update OPA enforcement message

Makefile, package-lock.json, package.json
=> bump version to 2.18.5

src/app/shared/components/number-stepper/component.ts
Fixes #4058
```release-note
NONE
```
=> Get rid of the NaN warning in the console

src/app/settings/admin/bucket-settings/destinations/template.html
Fixes https://github.com/kubermatic/dashboard/issues/4041.
```release-note
NONE
```
=> Fix icon styling

Makefile, package-lock.json, package.json
cut off release v2.19.0-alpha.9
```release-note
NONE
```
=> release v2.19.0-alpha.9

Makefile, package-lock.json, package.json
cut off release v2.19.0-alpha.10
```release-note
NONE
```
=> release v2.19.0-alpha.10

src/app/cluster/details/cluster/edit-cluster/template.html, src/app/cluster/details/external-cluster/external-node-list/template.html, src/app/dynamic/enterprise/metering/config/config-dialog/template.html, src/app/dynamic/enterprise/metering/config/credentials-dialog/template.html, src/app/project/edit-project/template.html, src/app/serviceaccount/edit-dialog/template.html, src/app/serviceaccount/template.html, src/app/settings/admin/admins/add-admin-dialog/template.html, src/app/settings/admin/bucket-settings/destinations/component.ts, src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts, src/app/settings/admin/bucket-settings/destinations/destination-dialog/template.html, src/app/settings/admin/bucket-settings/destinations/edit-credentials-dialog/template.html, src/app/shared/components/cluster-summary/template.html, src/app/shared/components/event-rate-limit/template.html, src/app/wizard/step/cluster/template.html
Closes https://github.com/kubermatic/dashboard/issues/4092.
```release-note
NONE
```
=> Update button labels

src/app/backup/list/automatic-backup/add-dialog/template.html, src/app/backup/list/snapshot/add-dialog/template.html, src/app/cluster/details/cluster/cluster-delete-confirmation/component.ts, src/app/cluster/details/cluster/cluster-delete-confirmation/template.html, src/app/cluster/details/cluster/cni-version/style.scss, src/app/cluster/details/cluster/cni-version/template.html, src/app/cluster/details/cluster/cni-version/theme.scss, src/app/cluster/details/cluster/style.scss, src/app/cluster/details/cluster/template.html, src/app/cluster/details/shared/version-change-dialog/component.ts, src/app/cluster/details/shared/version-change-dialog/style.scss, src/app/cluster/details/shared/version-picker/style.scss, src/app/cluster/details/shared/version-picker/template.html, src/app/cluster/details/shared/version-picker/theme.scss, src/app/settings/admin/custom-link-form/style.scss, src/app/settings/admin/presets/template.html, src/app/shared/components/expansion-panel/style.scss, src/app/shared/components/expansion-panel/template.html, src/app/shared/utils/common-utils.ts
Fixes https://github.com/kubermatic/dashboard/issues/4094.
```release-note
NONE
```
=> Multiple UI/UX improvements

Makefile, package-lock.json, package.json
cut off release  v2.19.0-alpha.11
```release-note
NONE
```
=> release v2.19.0-alpha.11

Makefile, cypress/utils/endpoint.ts, cypress/utils/mocks.ts, package-lock.json, package.json, src/app/core/components/changelog/theme.scss, src/assets/config/changelog.json
- Bump version to `v2.19.0`
- Update changelog
- Fix small issue with the changelog styling
Please read the changelog and comment if there is anything important missing there or it should be updated in any way.
@xrstf @shaase-ctrl @maciaszczykm @kgroschoff @cschieder 
Hold until all the other PRs before the release get merged.
/hold
Closes #4023
```release-note
NONE
```
=> Bump version to v2.19 and update changelog

cypress/integration/stories/admin-settings/cluster-settings.spec.ts
As in the title.
Related to the https://github.com/kubermatic/dashboard/issues/4152
```release-note
NONE
```
=> Fix the e2e tests

.prow.yaml, containers/chrome-headless/Dockerfile, containers/chrome-headless/release.sh, package-lock.json, package.json
=> Fix unit test and update headless Chrome image

src/app/settings/admin/presets/dialog/steps/settings/component.ts, src/app/settings/admin/presets/dialog/steps/settings/style.scss, src/app/settings/admin/presets/dialog/steps/settings/template.html, src/app/settings/admin/presets/dialog/template.html, src/assets/css/global/_main.scss
Fix ui in edit provider dialog. Informations + Scrollbar were misplaced
Fixes #4159
```release-note
NONE
```
=> Fix ui in edit provider dialog

Makefile, package-lock.json, package.json
Same as #4208, just for v2.19.
```release-note
NONE
```
Signed-off-by: Marvin Beckers <marvin@kubermatic.com>
=> [release/v2.19] Bump release version to v2.19.2

src/app/settings/admin/defaults/template.html, src/app/settings/admin/rule-groups/template.html
Fixes https://github.com/kubermatic/dashboard/issues/4186.
```release-note
NONE
```
=> Fix UI/UX issues

src/app/settings/admin/presets/dialog/component.ts, src/app/settings/admin/presets/dialog/template.html
Fixes https://github.com/kubermatic/dashboard/issues/4217.
```release-note
NONE
```
=> Update preset dialog button labels

src/app/node-data/extended/provider/gcp/component.ts
Tags input passed to the component was uninitialized
Fixes #4226
```release-note
NONE
```
=> Fix GCP tag input

src/app/cluster/list/cluster/template.html, src/app/shared/components/add-cluster-from-template-dialog/template.html, src/app/shared/components/add-ssh-key-dialog/template.html, src/app/wizard/step/cluster/ssh-keys/template.html
insure that all buttons text use title case 
"closes #4235"
```release-note
NONE
```
=> use title case where needed

src/app/backup/details/snapshot/template.html
Addition of the destination field when restoring from a snapshot.
#4147 
```release-note
NONE
```
=> Backup destination added to snapshot backup-list

src/app/settings/admin/presets/dialog/steps/settings/provider/nutanix/component.ts, src/app/settings/admin/presets/dialog/steps/settings/provider/nutanix/template.html, src/app/shared/components/cluster-summary/template.html, src/app/shared/components/number-stepper/component.ts, src/app/shared/entity/cluster.ts, src/app/shared/entity/preset.ts, src/app/wizard/step/provider-settings/provider/basic/nutanix/component.ts, src/app/wizard/step/provider-settings/provider/basic/nutanix/template.html, src/app/wizard/step/provider-settings/provider/extended/nutanix/component.ts, src/app/wizard/step/provider-settings/provider/extended/nutanix/template.html
Closes https://github.com/kubermatic/dashboard/issues/4213.
```release-note
Added Nutanix CSI Configuration.
```
=> Add Nutanix CSI properties

src/app/cluster/details/cluster/component.ts, src/app/cluster/details/cluster/edit-cluster/component.ts, src/app/shared/components/cluster-summary/component.ts, src/app/shared/entity/datacenter.ts, src/app/wizard/step/cluster/component.ts, src/app/wizard/step/cluster/template.html, src/test/data/datacenter.ts
- fix an issue with the wrong variable name in MLA spec
- fix an issue with the MLA settings not being shown in the wizard until after the mouse hovered some element
Fixes #4254
```release-note
NONE
```
=> Fix the MLA settings

src/app/core/services/project.ts, src/app/project/component.ts, src/app/project/style.scss, src/app/project/template.html, src/app/shared/entity/project.ts, src/test/data/project.ts
Closes https://github.com/kubermatic/dashboard/issues/4230.
Closes https://github.com/kubermatic/dashboard/issues/4263.
```release-note
NONE
```
=> Project improvements

src/app/cluster/details/cluster/machine-deployment-list/style.scss, src/app/shared/components/event-list/style.scss, src/app/shared/components/number-stepper/style.scss, src/app/shared/components/number-stepper/template.html, src/app/shared/model/NodeProviderConstants.ts, src/assets/css/global/_main.scss
Add "Nutanix" on the Provider Settings side of (4) Initial Nodes in Cluster Create,
Adjust number input styling,
Force icons to stay in one line in machine deployments card,
Fix Event table line breaks width 
“closes #4249 ”
```release-note
NONE
```
=>  UI/UX adjustments

src/app/cluster/list/external-cluster/style.scss, src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/eks/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/gke/component.ts, src/app/shared/components/add-external-cluster-dialog/steps/cluster/style.scss, src/app/shared/components/add-external-cluster-dialog/steps/credentials/style.scss, src/app/shared/components/add-external-cluster-dialog/steps/provider/style.scss, src/app/shared/components/add-external-cluster-dialog/steps/service.ts, src/app/shared/entity/external-cluster.ts, src/app/shared/entity/provider/aks.ts, src/app/shared/entity/provider/eks.ts, src/app/shared/entity/provider/gke.ts
This change is mostly about UI changes and updates in GKE types. The rest will be done once we will clarify external cluster types.
Closes https://github.com/kubermatic/dashboard/issues/4294.
Related to https://github.com/kubermatic/dashboard/issues/4247.
```release-note
NONE
```
=> External cluster improvements

src/assets/config/changelog.json
Related to the #4293
```release-note
NONE
```
=> Update changelog for the v2.20 release

src/app/shared/components/cluster-summary/template.html, src/app/shared/entity/cluster.ts, src/app/wizard/step/provider-settings/provider/basic/nutanix/component.ts, src/app/wizard/step/provider-settings/provider/extended/nutanix/component.ts, src/app/wizard/step/provider-settings/provider/extended/nutanix/template.html
- Removes `Segmented Iscsi Network` property
- Add list of possible options for `Fstype` property
- Allow setting storage class properties even if preset is selected
```release-note
NONE
```
=> Nutanix improvements

package-lock.json, package.json, src/polyfills.ts
Closes https://github.com/kubermatic/dashboard/issues/4346.
```release-note
NONE
```
=> Fix Swagger UI

Makefile, hack/e2e/setup-kubermatic-in-kind.sh, package-lock.json, package.json
Since the last release v2.18.7, there was no changes related to KKP in the dashboard. 
```release-note
NONE
```
=> [release/v2.18] Bump to v2.18.8 version

src/app/dynamic/enterprise/metering/list/component.ts, src/app/dynamic/enterprise/metering/list/template.html
Fixes https://github.com/kubermatic/dashboard/issues/4345.
```release-note
Fixed sorting metering reports by modification date.
```
=> Fix metering sort

Makefile, package-lock.json, package.json
Bump KKP dashboard to 2.19.3
```release-note
NONE
```
=> Bump to 2.19.3 version

Makefile, package-lock.json, package.json
We need to cut another set of KKP patch releases. This creates the dashboard version for that.
```release-note
NONE
```
=> [release/v2.19] Bump version to 2.19.4

Makefile, package-lock.json, package.json
We need to cut another set of KKP patch releases. This creates the dashboard version for that.
```release-note
NONE
```
=> [release/v2.18] Bump version to 2.18.9

Makefile, package-lock.json, package.json
We need to cut another set of KKP patch releases. This creates the dashboard version for that.
```release-note
NONE
```
=> [release/v2.20] Bump version to 2.20.1

.github/ISSUE_TEMPLATE/bug-report.md
Added "Current workaround", "Affected user persona", "Business goal to be improved" and "Metric to be improved" as bug report parameter requirements
Standardised existing parameters with other repositories
```release-note
NONE
```
=> Parameters extended for bug report

Makefile, package-lock.json, package.json
Time to prepare a new patch release.
```release-note
NONE
```
=> Bump version to 2.20.2

Makefile, package-lock.json, package.json
Time to prepare a new patch release.
```release-note
NONE
```
=> Bump version to 2.19.5

Makefile, package-lock.json, package.json
Time to prepare a new patch release.
```release-note
NONE
```
=> Bump version to 2.18.10

Development.md, src/app/cluster/details/cluster/mla/alertmanager-config/component.ts
- fixed alertmanager config edit
Fixes #4400 
```release-note
NONE
```
=> Fix alertmanager config edit

src/app/node-data/basic/provider/kubevirt/component.ts
=> Fix KubeVirt wizard

src/app/node-data/basic/provider/kubevirt/component.ts
=> Fix KubeVirt secondary disks wizard

package-lock.json, src/app/cluster-template/style.scss, src/app/cluster/details/cluster/style.scss, src/app/cluster/list/cluster/style.scss, src/app/cluster/list/external-cluster/style.scss, src/app/settings/admin/dynamic-datacenters/style.scss, src/app/settings/admin/dynamic-datacenters/template.html, src/app/settings/admin/presets/component.ts, src/app/settings/admin/presets/edit-dialog/style.scss, src/app/settings/admin/presets/edit-dialog/template.html, src/app/settings/admin/presets/style.scss, src/app/settings/admin/presets/template.html, src/app/shared/components/add-external-cluster-dialog/steps/cluster/style.scss, src/app/shared/components/add-external-cluster-dialog/steps/credentials/style.scss, src/app/shared/components/add-external-cluster-dialog/steps/provider/style.scss, src/app/shared/components/cluster-summary/style.scss, src/assets/css/_images.scss, src/assets/css/_mixins.scss, src/assets/css/global/_main.scss, src/assets/css/material/_main.scss
It reduces number of places where logo styling is modified, so it's easier to make it look similar across the app.
Closes https://github.com/kubermatic/dashboard/issues/4427.
```release-note
NONE
```
=> Provider logos adjustments

cypress/integration/v2/stories/admin-settings/defaults.spec.ts, cypress/integration/v2/stories/members.spec.ts, cypress/integration/v2/stories/service-accounts.spec.ts, cypress/integration/v2/stories/ssh-keys.spec.ts, cypress/intercept/clusters.ts, cypress/pages/v2/clusters/list/page.ts, cypress/pages/v2/projects/page.ts, cypress/types/endpoints.ts, cypress/types/pages.ts, cypress/types/view.ts, src/app/core/components/sidenav/component.spec.ts, src/app/core/components/sidenav/template.html, src/app/core/services/cluster.ts, src/app/core/services/project.ts, src/app/project-overview/clusters-overview/component.ts, src/app/project-overview/clusters-overview/template.html, src/app/project-overview/component.ts, src/app/shared/entity/cluster.ts, src/app/shared/entity/common.ts
Closes https://github.com/kubermatic/dashboard/issues/4383.
```release-note
NONE
```
=> Register project overview

package-lock.json, package.json
Fixes https://github.com/kubermatic/dashboard/issues/4470.
```release-note
NONE
```
=> Revert Swagger version to the last one that is working

src/assets/images/cni/cilium-dark.svg, src/assets/themes/dark.scss
Fixes https://github.com/kubermatic/dashboard/issues/4486.
```release-note
NONE
```
=> Fix Cilium and KubeVirt logos in the dark UI

Makefile, package-lock.json, package.json
=> Bump version to 2.19.6

Makefile, package-lock.json, package.json
What it says on the tin.
```release-note
NONE
```
=> Bump version to 2.20.4

src/app/cluster/details/shared/version-change-dialog/component.ts
fixing upgrade external cluster dialog 
"closes #4616 "
```release-note
NONE
```
=> Fixing upgrade external cluster

src/app/node-data/basic/provider/alibaba/component.ts, src/app/node-data/basic/provider/anexia/component.ts, src/app/node-data/basic/provider/aws/component.ts, src/app/node-data/basic/provider/gcp/component.ts, src/app/node-data/basic/provider/openstack/component.ts
Manual cherry pick for #4496 because it couldn't be created automatically: https://github.com/kubermatic/dashboard/pull/4496#issuecomment-1169852457
```release-note
NONE
```
=> [release/v2.20] Show updated config instead of default values in edit machine deployment dialog

Makefile, package-lock.json, package.json
What it says on the tin.
```release-note
NONE
```
=> Bump version to 2.20.5

src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
This PR fixes minor code issues such as 
- Adding a new Pattern validator
- Adding Types for static checking 
- Control binding issues
minor code fixes and validations
```release-note
NONE
```
=> Fix control bindings and add typings

src/app/core/services/external-cluster.ts, src/app/external-cluster-wizard/component.ts, src/app/external-cluster-wizard/module.ts, src/app/external-cluster-wizard/steps/external-cluster/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html, src/app/external-cluster-wizard/steps/external-cluster/template.html, src/app/shared/entity/external-cluster.ts, src/app/shared/entity/provider/gke.ts
add the option to create GKE external cluster
Fixes #4570 
```release-note
NONE
```
=> Create external cluster GKE

Makefile, package-lock.json, package.json
Fixes #
```release-note
NONE
```
=> Bump version to 2.19.7

Makefile, package-lock.json, package.json
Fixes #
```release-note
NONE
```
=> Bump version to 2.18.11

src/app/wizard/step/cluster/component.ts
Fixes #
```release-note
NONE
```
=> Temporarily disable OSM by default

.gitignore, .npmrc, .prow/build-image.yaml, .prow/tests-e2e.yaml, .prow/tests-unit.yaml, .prow/verify.yaml, Development.md, Makefile, containers/chrome-headless/Dockerfile, containers/chrome-headless/release.sh, containers/custom-dashboard/Dockerfile, go.mod, go.sum, hack/e2e/fixtures/seed.yaml, hack/e2e/run-tests.sh, hack/e2e/setup-kubermatic-in-kind.sh, package-lock.json, package.json
Fixes #
```release-note
NONE
```
=> Fix peer dependencies and `full` E2E tests

src/app/wizard/step/cluster/component.ts
Disallow `ipvs` proxy mode when `Cilium` CNI is selected.
Fixes #4687 
```release-note
Disallow IPVS proxy mode when `Cilium` CNI is selected.
```
=> Disallow IPVS proxy mode for Cilium CNI

cypress/integration/stories/admin-settings/custom-links.spec.ts, cypress/pages/v2/root/page.ts, cypress/pages/v2/settings/admin/page.ts, docs/manuals/customizing.md, docs/proposals/testing.md, src/app/cluster/details/cluster/gatekeeper-config/component.ts, src/app/cluster/details/cluster/gatekeeper-config/template.html, src/app/core/services/node-data/provider/kubevirt.ts, src/app/dynamic/enterprise/metering/schedule-config/add-dialog/component.ts, src/app/settings/admin/bucket-settings/destinations/style.scss, src/app/shared/components/event-rate-limit/component.ts, src/app/shared/components/property-health/component.ts, src/app/shared/entity/external-cluster.ts, src/app/shared/utils/health-status.ts, src/assets/css/global/_main.scss, src/assets/css/material/_theme.scss
https://github.com/crate-ci/typos found a lot of false positives, but also lots of actual typos. :-)
Fixes #
```release-note
NONE
```
=> fix a bunch of typos

src/assets/css/global/_main.scss, src/assets/css/material/_theme.scss
Use separate negation pseudo-class selector instead of list arguments.
Fixes #
```release-note
NONE
```
=> Use separate negation pseudo-class selector instead of list arguments

src/app/core/services/cluster-spec.ts, src/app/node-data/basic/provider/kubevirt/template.html, src/app/shared/components/cluster-summary/template.html, src/app/shared/entity/cluster.ts, src/app/wizard/module.ts, src/app/wizard/step/provider-settings/component.ts, src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts, src/app/wizard/step/provider-settings/provider/extended/kubevirt/style.scss, src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html, src/app/wizard/step/provider-settings/provider/extended/template.html
Add support for KubeVirt pre-allocated data volumes.
Fixes #4413 
```release-note
Add support for KubeVirt pre-allocated data volumes.
```
=> Add support for KubeVirt pre-allocated data volumes

src/app/wizard/step/cluster/component.ts
Fixes #
```release-note
NONE
```
/hold
=> Enable OSM by default during cluster creation

cypress/fixtures/feature-gates.json, cypress/utils/endpoint.ts, cypress/utils/mocks.ts
Fixes #
```release-note
NONE
```
=> Add mock request for `featuregates` API endpoint

src/app/shared/components/select-external-cluster-provider/style.scss
**Before:**
**After:**
Fixes #
```release-note
NONE
```
=> Update external provider tile size

src/app/cluster/details/cluster/edit-cluster/component.ts, src/app/cluster/details/cluster/edit-cluster/template.html, src/app/cluster/details/cluster/template.html, src/app/core/module.ts, src/app/core/services/operating-system-manager.ts, src/app/node-data/basic/provider/kubevirt/template.html, src/app/node-data/component.ts, src/app/node-data/template.html, src/app/settings/admin/interface/template.html, src/app/shared/components/application-list/template.html, src/app/shared/entity/operating-system-profile.ts
Fixes #
```release-note
NONE
```
=> List custom operating system profiles

src/app/shared/components/application-list/add-application-dialog/component.ts, src/app/shared/components/application-list/edit-application-dialog/component.ts
`values` are parsed from YAML and sent as `JSON` format to backend. Similarly, when editing, `values` are parsed from JSON to YAML.
Fixes #
```release-note
NONE
```
=> Handle application `values`

Makefile, package-lock.json, package.json
Fixes #
```release-note
NONE
```
=> Bump version to 2.20.6

src/app/cluster/details/cluster/component.ts
We were trying to use a function that didn't exist.
Fixes #
```release-note
NONE
```
=> Fix health check for dashboard

Makefile, package-lock.json, package.json
Fixes #
```release-note
NONE
```
=> Bump version to 2.19.8

Makefile, package-lock.json, package.json
Fixes #
```release-note
NONE
```
=> Bump version to 2.21.0

src/app/cluster/details/cluster/share-kubeconfig/template.html, src/app/settings/admin/interface/template.html
Fixes #
```release-note
NONE
```
=> Update docs URL to new pattern

.github/pull_request_template.md
Unified PR template with emphasising documentation
Fixes #
```release-note
NONE
```
=> Unified PR template update

src/app/node-data/component.ts
Update OS compatibility matrix.
Fixes #4791
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Update OS compatibility matrix

main.go
Fixes kubermatic/edgematic#117
/kind bug
```release-note
Add additional header to prevent being shown in an iframe
```
```documentation
NONE
```
=> Add additional header to webserver serving dashboard

src/app/core/services/application.ts, src/app/shared/components/addon-list/install-addon-dialog/style.scss, src/app/shared/components/addon-list/install-addon-dialog/template.html, src/app/shared/components/addon-list/template.html, src/app/shared/components/application-list/add-application-dialog/component.ts, src/app/shared/components/application-list/add-application-dialog/style.scss, src/app/shared/components/application-list/add-application-dialog/template.html, src/app/shared/components/application-list/component.ts, src/app/shared/components/application-list/edit-application-dialog/style.scss, src/app/shared/components/application-list/edit-application-dialog/template.html, src/app/shared/components/application-list/style.scss, src/app/shared/components/application-list/template.html, src/assets/css/global/_main.scss
- Descriptions about Applications and Addons:
- Adjust applications search field
- Separate step for Values
Fixes #4756
Fixes #4757  
Fixes #4758 
Fixes #4761 
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Applications UI/UX improvements

src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts, src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html, src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts, src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html, src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts, src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/template.html, src/app/shared/entity/external-machine-deployment.ts
This PR fix status icon and message for external cluster machine deployment based on which current `phase` of MD.
Fixes #4746 
```release-note
NONE
```
=> Fix external cluster machine deployment health status icons and status

src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html
Update KubeVirt docs link
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Update KubeVirt docs link

src/app/cluster/details/external-cluster/template.html, src/app/cluster/list/external-cluster/template.html, src/app/core/services/external-cluster.ts, src/app/core/services/external-machine-deployment.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts, src/app/shared/entity/provider/aks.ts
This PR adds UI fixes and display issues based on backend PR updates previously, it was returning strings[] but now it is returning an array of objects.
Fixes #4787 
```release-note
None
```
=> External cluster bug fixes

src/app/shared/components/property-usage/style.scss, src/app/shared/components/property-usage/template.html
Fix alignment of progress bar and static value in `property-usage` component.
Fixes #4493 
/kind design
```release-note
Fix alignment of CPU/Memory usage on cluster details
```
```documentation
NONE
```
=> Fix alignment of CPU/Memory usage on cluster details

src/app/project-overview/template.html
Fix alignment of project overview details and remove empty space after project name.
**Main issue**
**After**
https://user-images.githubusercontent.com/13975988/184863828-e2f9185d-19f2-4183-bf58-c77c49e8ccb5.mov
**Before**
https://user-images.githubusercontent.com/13975988/184863853-c30b38fb-8bfb-4dca-8bf6-c747bd782ab3.mov
Fixes #
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Fix alignment of project overview details

src/app/cluster/details/cluster/edit-cluster/template.html, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/style.scss, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html, src/app/shared/components/select/component.ts, src/app/shared/components/select/template.html, src/app/shared/module.ts
change the autocomplete component in some field that just need to show a list to km-select component and fix the  issue for trimming .patch (except .0 ))
Fixes #4774 #4821
/kind bug
-->
```release-note
NONE
```
```documentation
NONE
```
=> Change autocomplete to km select

src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/component.ts, src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/style.scss, src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html, src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts, src/app/core/services/external-cluster.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html, src/app/project-overview/providers-overview/component.ts, src/app/shared/components/autocomplete/component.ts, src/app/shared/components/chip-autocomplete/component.ts, src/assets/css/global/_main.scss
This PR fixes multiple issues related to external cluster.
Fixes #4818 
Fixes #4769  
Fixes #4829 
FIxes: **Color code** for EKS cluster as AWS had same color code in dashboard pie chart distribution.
/kind bug
/kind design
```release-note
None
```
```documentation
NONE
```
=> External cluster UI improvements and bug fixes

src/app/core/services/project.ts, src/app/dynamic/enterprise/quotas/service.ts
Fix indefinite quotas API requests.
Fixes #4839 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix indefinite quotas API requests

src/app/cluster/details/external-cluster/component.ts, src/app/cluster/details/external-cluster/template.html, src/app/core/services/external-cluster.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html, src/app/shared/components/external-cluster-credentials/preset/template.html, src/app/shared/components/external-cluster-credentials/provider/eks/component.ts, src/app/shared/components/external-cluster-credentials/provider/eks/template.html, src/app/shared/entity/external-cluster.ts, src/app/shared/entity/provider/aks.ts
Add list dropdown for AKS and EKS locations
Fixes #4815
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> add location list aks eks

src/app/dynamic/enterprise/metering/legacy-reports/list/template.html
Fix legacy reports table sorting and action buttons
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
=> Fix legacy reports table sorting and action buttons

src/app/node-data/basic/provider/kubevirt/component.ts
Update node affinity preset values in node data service so that its up to date in the payload.
Fixes #4859 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Update node affinity preset values in node data service

src/app/cluster/details/cluster/edit-provider-settings/openstack-provider-settings/component.ts, src/app/cluster/details/cluster/edit-provider-settings/openstack-provider-settings/style.scss, src/app/cluster/details/cluster/edit-provider-settings/openstack-provider-settings/template.html, src/app/shared/entity/cluster.ts
Update openstack configuration in edit provider dialog.
Since we don't have an API endpoint to determine current credentials type so I've added a warning message when project is updated.
Fixes #4702 
/kind bug
```release-note
Update openstack configuration in edit provider dialog
```
```documentation
NONE
```
=> Update openstack configuration in edit provider dialog

src/app/core/services/external-cluster.ts, src/app/core/services/external-machine-deployment.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html, src/app/shared/components/combobox/component.ts, src/app/shared/components/combobox/template.html, src/app/shared/entity/provider/eks.ts
This PR updates external cluster EKS/AKS fields to combobox and update error handling of API call in catchError
Fixes #4834
Fixes #4842 
/kind bug
/kind design
```release-note
None
```
```documentation
None
```
=> External Cluster EKS/AKS fields update and Error handling

src/app/cluster/details/external-cluster/external-cluster-add-machine-deployment/template.html
This PR updates title to provider specific term for MD dialog
https://user-images.githubusercontent.com/17727069/185615746-ea0f1610-44c7-4713-a5dc-12bc4980e212.mp4
Fixes #
/kind design
```release-note
None
```
```documentation
None
```
=> Rename title for MD dialog specific to cloud provider term

src/app/shared/components/application-list/add-application-dialog/template.html, src/app/shared/components/application-list/template.html
Update applications documentation link
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Update applications documentation link

src/app/project/component.ts, src/app/project/template.html
Add project `trackBy` function to avoid unnecessary re-rendering of DOM especially resource quotas.
https://user-images.githubusercontent.com/13975988/185604192-1c335169-72c0-4287-94b7-e47792589fcc.mov
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Add project `trackBy` function to avoid unnecessary re-rendering of DOM

src/app/shared/components/application-list/add-application-dialog/component.ts, src/app/shared/entity/application.ts
Set default values of selected application in YAML editor.
Fixes #
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> Set default values of selected application in YAML editor

src/app/dynamic/enterprise/quotas/component.ts
Update delete project quota success message.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Update delete project quota success message

src/app/dynamic/enterprise/quotas/module.ts, src/app/dynamic/enterprise/quotas/quota-widget/component.ts, src/app/dynamic/enterprise/quotas/quota-widget/style.scss, src/app/dynamic/enterprise/quotas/quota-widget/template.html, src/app/dynamic/enterprise/quotas/service.ts, src/app/project-overview/component.ts, src/app/project-overview/routing.ts, src/app/project-overview/template.html, src/app/project/component.ts, src/app/project/style.scss, src/app/project/template.html
- Added placeholder text when no quotas are found
- Added quota widget to project overview page
Fixes #4753 
Fixes #4468
```release-note
Add quota widget to project overview page
```
```documentation
NONE
```
=> Extra space in project tiles with no resource quotas

src/app/project/component.ts
On project cards, quota widgets are being rendered with a lot of delay, this PR fixes this issue.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fixed rendering delay of quota widgets on project cards.

src/app/dynamic/enterprise/quotas/quota-widget/style.scss, src/app/dynamic/enterprise/quotas/quota-widget/template.html, src/assets/css/_images.scss, src/assets/css/global/_main.scss
Minor UI fixes for quota widget
/kind bug
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
=> Quota UI fixes

src/app/cluster/details/cluster/mla/alertmanager-config/alertmanager-config-dialog/template.html, src/app/cluster/details/cluster/mla/rule-groups/rule-group-dialog/template.html, src/app/cluster/details/cluster/revoke-token/component.ts, src/app/serviceaccount/edit-dialog/component.ts
This PR fixes some issues found during testing of `km-button` migration.
Fixes #4674 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix issues in km-button migration

src/app/shared/components/application-list/edit-application-dialog/component.ts
Fixes #4880
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Parse application values as YAML for patch requests

src/app/wizard/step/cluster/component.ts
Dual-stack not allowed on Canal CNI version lower than 3.22.
Fixes #4874
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Dual-stack not allowed on Canal CNI version lower than 3.22

src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html, src/app/core/services/external-cluster.ts, src/app/core/services/external-machine-deployment.ts, src/app/external-cluster-wizard/component.ts, src/app/external-cluster-wizard/steps/external-cluster/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html, src/app/external-cluster-wizard/template.html, src/app/shared/components/external-cluster-credentials/preset/component.ts, src/app/shared/components/external-cluster-credentials/provider/aks/template.html, src/app/shared/components/external-cluster-credentials/provider/eks/template.html, src/app/shared/components/external-cluster-credentials/provider/gke/template.html, src/app/shared/entity/provider/gke.ts
This PR adds 
- UI fixes (hint fixes) along with this adds payload fixes for GKE cluster. 
- It also handles state for fields which has network call dependency to update user some actions is been done.
- Updates text for dialogs (Disconnect/Delete)
Fixes #4876 
/kind bug
/kind cleanup
```release-note
None
```
```documentation
None
```
=> External Cluster Fixes

src/app/cluster/list/cluster/component.ts, src/app/dynamic/enterprise/quotas/quota-widget/component.ts, src/app/dynamic/enterprise/quotas/quota-widget/template.html, src/app/project-overview/component.ts, src/app/project-overview/template.html
Fixed quota widget not being rendered when `CPU` is not set on project overview page and Initial nodes cluster step.
Fixes #4892
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> fixed quota widget logic

src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
This PR updates placeholder states in case of async operations are executed
Fixes #4886 
/kind design
No major UI change just addition of third state for placeholder to make it consistent with other pages e.g KKP Clusters
```release-note
None
```
```documentation
None
```
=> Add third state or AKS/EKS dropdown fields

src/app/core/services/external-cluster.ts, src/app/core/services/external-machine-deployment.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/style.scss, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
refactor the input fields and add the machine and disk types for GKE cluster creation
Fixes #4786
/kind feature
```release-note
add the machine types and disk types fields for GKE cluster creation 
```
```documentation
NONE
```
=> Improvement gke cluster creation

src/app/external-cluster-wizard/component.ts, src/app/external-cluster-wizard/config.ts, src/app/external-cluster-wizard/module.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts, src/app/external-cluster-wizard/steps/summary/component.ts, src/app/external-cluster-wizard/steps/summary/external-cluster-details/component.ts, src/app/external-cluster-wizard/steps/summary/external-cluster-details/provider/aks/component.ts, src/app/external-cluster-wizard/steps/summary/external-cluster-details/provider/aks/template.html, src/app/external-cluster-wizard/steps/summary/external-cluster-details/provider/eks/component.ts, src/app/external-cluster-wizard/steps/summary/external-cluster-details/provider/eks/style.scss, src/app/external-cluster-wizard/steps/summary/external-cluster-details/provider/eks/template.html, src/app/external-cluster-wizard/steps/summary/external-cluster-details/provider/gke/component.ts, src/app/external-cluster-wizard/steps/summary/external-cluster-details/provider/gke/template.html, src/app/external-cluster-wizard/steps/summary/external-cluster-details/template.html, src/app/external-cluster-wizard/steps/summary/style.scss, src/app/external-cluster-wizard/steps/summary/template.html, src/app/external-cluster-wizard/template.html, src/app/shared/entity/external-machine-deployment.ts, src/app/shared/entity/provider/gke.ts
also changed step's heading from `Settings` to `Credentials`
Fixes #4903
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> Added summary page to external cluster wizard

src/app/dynamic/enterprise/quotas/service.ts
A delay was observed in the resource quota widget while navigating between different routes, this PR fixes it.
Fixes #4902 
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
=> Refactor resource quota polling logic

package.json
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
=> Postinstall script shouldn't fail if cypress config doesn't exist

src/app/external-cluster-wizard/steps/summary/external-cluster-details/provider/eks/template.html
Fixes `security groups` on EKS external cluster summary step
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> External cluster EKS summary step `security groups` shows incorrect data

src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts, src/app/shared/entity/external-cluster.ts, src/app/shared/entity/external-machine-deployment.ts, src/app/shared/entity/provider/eks.ts, src/app/shared/utils/health-status.ts, src/assets/css/_images.scss
adding the new health status (Warning, Stoped), and set a default values for subnets in the eks external cluster wizard
Fixes #4937 
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> Update existing and new states for external clusters

src/app/core/services/external-cluster.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html, src/app/shared/entity/provider/aks.ts
Signed-off-by: khizerrehan <khizerrehan92@gmail.com>**What this PR does / why we need it**:
This PR updates the UI fields in order to allow filtering and clear the existing value. 
Previously it was a dropdown and user can only select value but **neither** allows clearing and filtering in case of large list is returned.
**EKS Wizard -> VPC field**
**GKE Wizard -> Zone field**
**AKS Wizard -> Location field**
**AKS MD dialog -> Kubernetes Version**
Fixes #4893 
Fixes #4768 
/kind cleanup
/kind design
```release-note
None
```
```documentation
None
```
=> Update control for AKS/GKE cluster settings page

.github/pull_request_template.md
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> Add kind/chore to PR template

package-lock.json, package.json
Upgrade `typescript` to latest version.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Upgrade Typescript to latest version

package-lock.json, package.json, src/app/pages/api-docs/component.ts
Upgrade `swagger-ui` to latest version.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Upgrade `swagger-ui` to latest version

Makefile, package-lock.json, package.json
/kind chore
```release-note
NONE
```
=> Bump version to 2.20.7

Makefile, package-lock.json, package.json
/kind chore
```release-note
NONE
```
=> Bump version to 2.19.9

src/app/backup/details/automatic-backup/template.html, src/app/cluster-template/component.ts, src/app/cluster/details/cluster/machine-deployment-details/cluster-panel/template.html, src/app/cluster/details/cluster/template.html, src/app/cluster/details/external-cluster/template.html, src/app/cluster/list/cluster/component.spec.ts, src/app/cluster/list/cluster/component.ts, src/app/cluster/list/cluster/template.html, src/app/core/components/help-panel/template.html, src/app/core/components/navigation/project/template.html, src/app/core/components/user-panel/template.html, src/app/dynamic/enterprise/metering/schedule-config/report-list/template.html, src/app/project-overview/create-resource-panel/component.ts, src/app/project-overview/create-resource-panel/template.html, src/app/project-overview/members-overview/style.scss, src/app/project-overview/members-overview/template.html, src/app/project-overview/template.html, src/app/shared/components/add-cluster-from-template-dialog/steps/template/component.ts, src/app/shared/components/add-cluster-from-template-dialog/steps/template/template.html, src/app/shared/components/combobox/template.html, src/app/shared/components/event-card/style.scss, src/app/shared/components/event-card/template.html, src/assets/css/_images.scss, src/assets/css/global/_main.scss, src/assets/css/global/_theme.scss, src/assets/css/material/_main.scss, src/assets/css/theme/_main.scss, src/assets/themes/dark.scss, src/assets/themes/light.scss, src/test/services/cluster-template-mock.ts
Dark mode UI UX fixes.
Fixes #4637 
/kind bug
/kind design
```release-note
Dark mode and general UI UX fixes.
```
```documentation
NONE
```
=> Dark mode UI UX fixes

src/app/core/services/external-cluster.ts, src/app/core/services/external-machine-deployment.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html, src/app/shared/entity/provider/eks.ts
This PR integrates new endpoint to show Node I AM role as dropdown list.
Fixes #4961 
/kind design
/kind chore
It allows user to select value from dropdown + filtering instead typing by user itself
```release-note
Allow user to select Node IAM role from dropdown list
```
```documentation
NONE
```
=> Add NodeServiceRole dropdown for EKS Node Role MD

src/app/cluster/details/cluster/template.html, src/app/external-cluster-wizard/steps/summary/style.scss, src/app/node-data/template.html, src/app/project-overview/template.html, src/app/shared/components/autocomplete/component.ts, src/app/shared/components/autocomplete/style.scss, src/app/shared/components/autocomplete/template.html, src/app/shared/components/cluster-summary/style.scss, src/app/shared/components/property/style.scss, src/assets/css/_images.scss, src/assets/css/global/_main.scss
This PR fixes various UI UX issues.
Fixes #4924 
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> UI UX Improvements

.github/dependabot.yml
Add documentation label in dependabot PR.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Add documentation label in dependabot PR

src/app/core/services/external-machine-deployment.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/style.scss, src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html, src/app/shared/entity/external-machine-deployment.ts, src/app/shared/entity/provider/aws.ts, src/app/shared/entity/provider/eks.ts
add the instance types in add machine deployment in EKS 
Fixes #4826
/kind feature
```release-note
add new field to enter the instance types when add new MD
```
```documentation
NONE
```
=> Add Instance type for eks MD

src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html, src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts, src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html, src/app/cluster/details/external-cluster/template.html, src/app/shared/entity/external-cluster.ts, src/app/shared/entity/external-machine-deployment.ts
add provisioning state and power state for aks cluster and MD
Fixes #4960
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> Add provisioning and power states for aks

Makefile, package-lock.json, package.json
Bumps the version to v2.19.10 so we can release an out-of-band set of patches for KKP.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.19] Bump version to 2.19.10

Makefile, package-lock.json, package.json
Bumps version to v2.20.9 in preparation for upcoming KKP releases.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.20] Bump version to 2.20.9

Makefile, package-lock.json, package.json
Bumps version to v2.19.11 in preparation for upcoming KKP releases.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.19] Bump version to v2.19.11

license-checker-config.json
Add `pkg`, `cmd` and `certs` directories to ignored list for license checker.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Add `pkg`, `cmd` and `certs` directories to ignored list for license checker

Makefile
Determining the correct repository to build and push for was broken, this should fix it.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> Fix Makefile not producing the right image repository

src/app/shared/components/terminal/style.scss, src/app/shared/components/terminal/template.html
Fix Web terminal placeholder styles
Fixes #
/kind design
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Fix web terminal placeholder styles

src/app/shared/components/terminal/template.html
Fix styles for toolbar and status bar once terminal is initialized
Fixes #
```release-note
None
```
```documentation
None
```
=> Fix web terminal styles

src/app/core/services/node-data/provider/alibaba.ts, src/app/core/services/node-data/provider/aws.ts, src/app/core/services/node-data/provider/azure.ts, src/app/core/services/node-data/provider/digitalocean.ts, src/app/core/services/node-data/provider/equinix.ts, src/app/core/services/node-data/provider/gcp.ts, src/app/core/services/node-data/provider/hetzner.ts, src/app/core/services/node-data/provider/kubevirt.ts, src/app/core/services/wizard/provider/alibaba.ts, src/app/core/services/wizard/provider/aws.ts, src/app/core/services/wizard/provider/azure.ts, src/app/core/services/wizard/provider/digitalocean.ts, src/app/core/services/wizard/provider/equinix.ts, src/app/core/services/wizard/provider/gcp.ts, src/app/core/services/wizard/provider/hetzner.ts, src/app/core/services/wizard/provider/kubevirt.ts, src/app/settings/admin/defaults/component.ts, src/app/settings/admin/defaults/template.html, src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/component.ts, src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/style.scss, src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html, src/app/shared/components/machine-flavor-filter/component.ts, src/app/shared/components/machine-flavor-filter/template.html, src/app/shared/entity/datacenter.ts, src/app/shared/module.ts
This PR adds support for configuring machine flavor filter at datacenter level. Summary of changes:
1. Propagate DatacenterName to the endpoints that list VM flavors.
2. Create `MachineFlavorFilterComponent` that can be used in create/edit datacenter dialog and in the defaults/limits section in the admin panel.
3. Display units for RAM
Fixes #5047 
xref https://github.com/kubermatic/kubermatic/issues/10207
/kind feature
I have intentionally opted out of re-using the component for the defaults/limits section in the admin panel at the moment. The parent component would need significant refactoring because of the way everything has been working …
=> Support to filter machines based on resources per datacenter

pkg/handler/v1/dc/datacenter.go, src/app/settings/admin/defaults/template.html, src/app/shared/components/machine-flavor-filter/template.html
Update the tooltip for the resource filter and update the API response for list seeds.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update tooltip for resource filter

.gitignore
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> add .envrc to gititnore

.prow/api.yaml, .prow/verify.yaml, containers/chrome-headless/Dockerfile, containers/custom-dashboard/Dockerfile, hack/gen-api-client.sh
Upgrade to Go 1.19.3.
Fixes #
/kind feature
```release-note
Upgrade to Go 1.19.3
```
```documentation
NONE
```
=> Upgrade to Go 1.19.3

src/app/cluster/details/cluster/component.ts, src/app/cluster/details/cluster/template.html, src/app/settings/admin/interface/component.ts, src/app/settings/admin/interface/template.html, src/app/shared/entity/settings.ts, src/test/services/settings-mock.ts
This PR adds new interface option to enable/disable the web terminal from cluster details page
https://user-images.githubusercontent.com/17727069/199467727-1d41b566-05e5-4c85-8e4d-2dfb10fbaffa.mp4
Fixes #5014 
/kind feature
/kind design
/kind chore
```release-note
Adds new option under admin/interface page to enable/disable web terminal from cluster details page.
```
```documentation
TBD
```
=> Add interface option to enable/disable the web terminal 

pkg/handler/v1/admission-plugin/admission_plugin.go
Kubernetes v1.25 doesn't support Pod Security Policy.
Fixes #5210
/kind chore
This PR only targets the API and UI. This removal should be properly implemented in KKP with https://github.com/kubermatic/kubermatic/issues/6854
```release-note
Remove support for Pod Security Policy Admission Plugin with k8s v1.25
```
```documentation
NONE
```
=> Kubernetes v1.25 doesn't support Pod Security Policy

src/app/cluster/details/cluster/machine-deployment-list/component.ts, src/app/cluster/details/cluster/machine-deployment-list/template.html, src/app/cluster/list/cluster/component.ts, src/app/cluster/list/cluster/template.html, src/app/cluster/list/external-cluster/component.ts, src/app/cluster/list/external-cluster/template.html
https://user-images.githubusercontent.com/17727069/200272300-051d6e92-a731-4ef3-8fb6-9ca98750b9df.mp4
**AWS Provider Note: => (Displays Extra Column "Availaibitly Zone")**
**Other Providers:**
Fixes #5086 #4819 
/kind design
/kind chore
In case Kubernetes version is not displayed for External clusters see this https://github.com/kubermatic/dashboard/issues/4819#issuecomment-1220711126
```release-note
NONE
```
```documentation
TBD
```
=> Remove Labels from Table Views

src/app/node-data/basic/provider/alibaba/component.ts, src/app/node-data/basic/provider/alibaba/template.html, src/app/node-data/basic/provider/aws/component.ts, src/app/node-data/basic/provider/aws/template.html, src/app/node-data/basic/provider/gcp/component.ts, src/app/node-data/basic/provider/gcp/template.html, src/app/node-data/component.ts, src/app/node-data/dialog/component.ts, src/app/node-data/dialog/template.html, src/app/node-data/template.html, src/assets/css/material/_main.scss
Enhancement for machine deployment edit dialog 
Fixes #5085
**Special notes for your reviewer:**
show disk type and disk size in one row is only for following providers
-  AWS, 
- GCP 
- Alibaba
/kind design
```release-note
change the showing advance settings button to expanding arrow in the edit md dialog  and rearrange some fields in it.
```
```documentation
NONE
```
=> Edit MD Dialog Enhancements

src/app/node-data/basic/provider/aws/template.html
Move architecture radio button outside `form`.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Move architecture radio button outside `form`

Makefile, package-lock.json, package.json
Bumps version to v2.19.12 in preparation of November releases.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.19] Bump version to v2.19.12

Makefile, package-lock.json, package.json
Bumps version to v2.20.10 in preparation of November releases.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.20] Bump version to v2.20.10

Makefile, package-lock.json, package.json
Bumps version to v2.21.3 in preparation of November releases.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Bump version to v2.21.3

src/app/cluster/details/cluster/template.html, src/app/core/services/application.ts, src/app/shared/components/application-list/add-application-dialog/component.ts, src/app/shared/components/application-list/add-application-dialog/template.html, src/app/shared/components/application-list/component.ts, src/app/shared/components/application-list/edit-application-dialog/component.ts, src/app/shared/components/application-list/edit-application-dialog/template.html
Load application definition and installation details in add/edit application dialogs to support limited data from applications API.
Fixes #5012 
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> Support limited data from applications API

fixtures/db.json
Sync json-server datacenter mock data with cypress fixtures data (`cypress/fixtures/datacenters.json`). This prevents datacenter E2E tests to fail because of mismatch between table data.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Sync json-server datacenter mock data with cypress fixtures data

pkg/handler/v1/user/user.go
**What this PR does / why we need it**: Handle resource not found for missing user for a user-project binding by logging the error instead of ignoring the error.
This will fix the "resource not found" in kkp dashboard for project's member users.
Fixes https://github.com/kubermatic/kubermatic/issues/8289
```release-note
NONE
```
```documentation
NONE
```
=> Handle resource not found for missing user

.prow/api.yaml, .prow/frontend.yaml
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update trigger conditions for prow jobs

modules/web/package.json
This PR install husky commit inside `modules/web` repo in order to run pre/post husky commit for web repo.
Note: After investigation it was found by default husky installation is occurred at root level where **.git** folder resides. So in order to install husky inside nested folder structure a workaround is added to move up into directory and then installing inside repo. 
Fixes #
/kind bug
This change was introduced due to #5227 
```release-note
NONE
```
```documentation
NONE
```
=> Revert prepare script to install husky dependency

modules/api/cmd/kubermatic-api/swagger.json, modules/api/hack/gen-api-client.sh, modules/api/hack/update-swagger.sh, modules/api/hack/verify-api-client.sh, modules/api/hack/verify-import-order.sh, modules/api/hack/verify-licenses.sh, modules/api/hack/verify-swagger.sh, modules/api/pkg/handler/v2/provider/kubevirt.go, modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_preferences_parameters.go, modules/api/pkg/test/e2e/utils/apiclient/models/application_ref.go, modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_node_spec.go
Fix some missing parameter in the swagger for:
`/api/v2/providers/kubevirt/preferences`
Fixes #5277 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> KubeVirt fix swagger list preferences missing parameter

modules/web/Makefile, modules/web/cmd/dashboard/main.go
One of the pending things from https://github.com/kubermatic/dashboard/pull/5257. I'm not sure if the version and edition are actually used anywhere though 🤷‍♂️ 
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Fix versioning for dashboard metrics wrapper

modules/web/license-checker-config.json
This PR adds "OWNERS"  files to ignore list.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Ignore OWNERS files to add license

Makefile, package-lock.json, package.json
Bumps version to v2.21.4 in preparation of a KKP release.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Bump version to 2.21.4

modules/web/license-checker-config.json, modules/web/license-header.txt, modules/web/src/app/dynamic/enterprise/LICENSE
The regex was invalid.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix license checker

Makefile, package-lock.json, package.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.19] Bump version to 2.19.13

Makefile, package-lock.json, package.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.20] Bump version to 2.20.11

modules/web/src/app/cluster/details/cluster/node-list/template.html, modules/web/src/app/project-overview/create-resource-panel/template.html, modules/web/src/app/serviceaccount/component.ts, modules/web/src/app/serviceaccount/template.html, modules/web/src/app/settings/admin/bucket-settings/component.ts, modules/web/src/app/settings/admin/bucket-settings/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/aks/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/alibaba/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/anexia/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/aws/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/azure/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/digitalocean/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/eks/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/equinix/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/gcp/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/gke/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/hetzner/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/kubevirt/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/template.html, modules/web/src/app/shared/components/editor/component.ts, modules/web/src/app/shared/components/loader/component.ts, modules/web/src/app/shared/components/loader/template.html, modules/web/src/assets/css/_mixins.scss, modules/web/src/assets/css/global/_main.scss
This PR adds UI adjustments and enhancements
Fixes #5095 
Adding some of the screenshot
**header icons alignment**
**Fix error icon:**
**Default Loading spinner**
https://user-images.githubusercontent.com/17727069/203315282-6e7ec1eb-dd89-45b8-a9f1-83427855203c.mp4
**Add Token/Add Destination**
https://user-images.githubusercontent.com/17727069/203768726-2e652e7d-ba15-4c9f-8aa7-ed41217cdb3f.mp4
**Reducing Layout gap between children's provider presets settings**
https://user-images.githubusercontent.com/17727069/203768249-643c805d-81ca-4d99-88d1-f681489c6684.mp4
/kind design
/kind cleanup
/kind chore
This things are already confirmed from **chiara** …
=> UI Adjustment and enhancements

CONTRIBUTING.md, DCO
This PR update "Developer Certificate of Origin" content.
Fixes #
/kind chore
Update DCO can be found [here](https://developercertificate.org/) or see "CONTRIBUTING.md" file in repo to find link.
```release-note
NONE
```
```documentation
NONE
```
=> Update developer certificate origin

modules/web/src/app/cluster/details/cluster/template.html, modules/web/src/app/shared/components/cluster-summary/template.html
This PR displays Configured IP ranges in Cluster step to show in cluster summary step and cluster details steps under "Additional Cluster Information"
Fixes #5337 
e.g **IPv4**
e.g  **IPv6**
**Details Page:**
/kind design
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Display Allowed IP ranges in summary and details page

modules/api/go.mod, modules/api/go.sum
Finally one of those simple "bump and commit" PRs without having to change tons of code :grin: 
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> bump KKP to dd5fd6c6fbc5

modules/web/src/app/backup/list/automatic-backup/template.html, modules/web/src/app/backup/list/restore/template.html, modules/web/src/app/backup/list/snapshot/template.html, modules/web/src/app/cluster-template/template.html, modules/web/src/app/cluster/list/cluster/template.html, modules/web/src/app/cluster/list/external-cluster/template.html, modules/web/src/app/dynamic/enterprise/group/template.html, modules/web/src/app/member/template.html, modules/web/src/app/serviceaccount/template.html, modules/web/src/app/sshkey/template.html
add titles to the cards for the new sections in project side bar
Fixes #5371
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Add headings to cards

modules/api/pkg/handler/v2/external_cluster/external_cluster.go
**What this PR does / why we need it**: Fix nil pointer for version
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> Fix nil pointer for version

modules/web/src/app/backup/list/automatic-backup/template.html, modules/web/src/app/backup/list/snapshot/template.html, modules/web/src/app/dynamic/enterprise/group/template.html, modules/web/src/app/member/template.html, modules/web/src/app/node-data/component.ts, modules/web/src/app/node-data/extended/provider/aws/template.html, modules/web/src/app/node-data/extended/provider/azure/template.html, modules/web/src/app/node-data/extended/provider/openstack/template.html, modules/web/src/app/node-data/extended/provider/vsphere/template.html, modules/web/src/app/node-data/template.html, modules/web/src/app/serviceaccount/template.html, modules/web/src/app/sshkey/template.html
remove validators from provider tags for machine deployment
Fixes #5364
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> remove validators from provider tags for MD

modules/web/src/app/node-data/component.ts
This PR fixes the creation of Machine Deployment creation. In Case of "Add Machine Deployment" default OS is not selected but now based on provider it will select default OS.
[Source of truth for OS Support matrix](https://github.com/kubermatic/machine-controller/blob/main/docs/operating-system.md)
**Anexia:**
Other Providers "Defaults' Ubuntu:
Fixes #5366 
/kind bug
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Fix Add Machine Deployment creation

modules/web/src/app/cluster/details/cluster/machine-deployment-details/template.html, modules/web/src/app/core/services/node.ts, modules/web/src/app/node-data/component.ts, modules/web/src/app/node-data/style.scss, modules/web/src/app/node-data/template.html, modules/web/src/app/shared/components/cluster-summary/template.html, modules/web/src/app/shared/entity/machine-deployment.ts, modules/web/src/app/shared/model/NodeSpecChange.ts, modules/web/src/app/wizard/component.ts, modules/web/src/app/wizard/step/summary/component.ts
Provide options for autoscaling nodes.
Fixes #5347 
/kind feature
```release-note
Provide options for autoscaling nodes.
```
```documentation
NONE
```
=> Provide option for autoscaling nodes

src/assets/config/changelog.json
Updates the changelog visible from the dashboard for users.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.19] Add changelog for KKP 2.19.13

src/assets/config/changelog.json
Updates the changelog visible from the dashboard for users.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.20] Add changelog for KKP 2.20.11

src/assets/config/changelog.json
Updates the changelog visible from the dashboard for users.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Add changelog for KKP 2.21.4

modules/api/pkg/resources/machine/common.go
Fixes kubermatic/kubermatic#11557
**No back port needed.**
Only exists since the move of API to dashboard repo.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> KubeVirt fix broken custom local disk

modules/api/cmd/kubermatic-api/swagger.json, modules/api/hack/tools.go, modules/api/hack/update-codegen.sh, modules/api/pkg/handler/v2/routes_v2.go, modules/api/pkg/test/e2e/utils/apiclient/client/default_cluster/default_cluster_client.go, modules/api/pkg/test/e2e/utils/apiclient/client/default_cluster/get_default_cluster_responses.go, modules/api/pkg/test/e2e/utils/apiclient/client/networkdefaults/get_network_defaults_responses.go, modules/api/pkg/test/e2e/utils/apiclient/client/networkdefaults/networkdefaults_client.go, modules/api/pkg/test/e2e/utils/apiclient/client/operatingsystemprofile/list_operating_system_profiles_for_cluster_responses.go, modules/api/pkg/test/e2e/utils/apiclient/client/operatingsystemprofile/operatingsystemprofile_client.go
Fix `./hack/update-codegen.sh` script along with adding missing `/api/v2` prefix in swagger spec for endpoints.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Fix code generation

modules/web/src/app/shared/components/number-stepper/component.ts
Add strict check on `max` and `min` values in number-stepper.
Fixes #5416 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Add strict check on `max` and `min` values in number-stepper

modules/web/src/app/shared/components/application-list/edit-application-dialog/component.ts, modules/web/src/app/shared/components/application-list/edit-application-dialog/template.html
This PR allows o update/downgrade the version of an already deployed Application. 
https://user-images.githubusercontent.com/17727069/207828132-2afd358a-a8c6-4e12-bfc0-54e4de96d8e0.mp4
Fixes #5251 
/kind design
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Allow editing version for installed application

modules/api/hack/ci/sync-apiclient.sh
Step by step ....
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> fix paths for sync-client

modules/api/pkg/handler/common/upgrade.go, modules/api/pkg/handler/test/fake_provider.go, modules/api/pkg/handler/v2/external_cluster/aks.go, modules/api/pkg/handler/v2/external_cluster/eks.go, modules/api/pkg/handler/v2/external_cluster/external_cluster.go, modules/api/pkg/handler/v2/external_cluster/gke.go, modules/api/pkg/handler/v2/external_cluster/kubeone.go, modules/api/pkg/handler/v2/external_cluster/node.go, modules/api/pkg/handler/v2/external_cluster/upgrade.go, modules/api/pkg/kubernetes/helper.go, modules/api/pkg/provider/cloud/eks/provider.go, modules/api/pkg/provider/kubernetes/credentials.go, modules/api/pkg/provider/kubernetes/external_cluster.go, modules/api/pkg/provider/types.go
**What this PR does / why we need it**: Add method to get user based MasterClient checking if the user is admin
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> Add method to get user based MasterClient

src/app/node-data/component.ts, src/app/node-data/extended/provider/aws/template.html, src/app/node-data/extended/provider/azure/template.html, src/app/node-data/extended/provider/openstack/template.html, src/app/node-data/template.html
Cherry picked from #5459 .
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Remove validators from provider tags for MD (#5383) (#5459)

modules/web/src/app/project-overview/members-overview/component.ts, modules/web/src/app/project-overview/members-overview/template.html, modules/web/src/app/project-overview/providers-overview/template.html, modules/web/src/app/project-overview/template.html, modules/web/src/app/project/component.ts, modules/web/src/app/project/template.html, modules/web/src/app/shared/components/labels/component.ts, modules/web/src/app/shared/components/labels/style.scss, modules/web/src/app/shared/components/labels/template.html
**Remove tab styling from Cluster Distribution and add labels to project overview** :
**remove labels from the projects table and only show the number of labels**:
Fixes #5323
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Modify Project Overview

modules/web/src/app/node-data/component.ts
Update minimum replicas count value to `0`.
Fixes #5463 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Update minimum replicas count value to `0`

modules/api/cmd/kubermatic-api/swagger.json, modules/api/pkg/api/v2/types.go, modules/api/pkg/ee/resource-quota/handler.go, modules/api/pkg/ee/resource-quota/handler_test.go, modules/api/pkg/test/e2e/utils/apiclient/models/resource_quota.go
Adds handling for default resource quotas:
- info if the quota is default
- on update remove the default label
Fixes #5431
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> Handle default resource quotas

modules/web/package.json
Update **Copyright** Year 
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update Copyright Year

modules/web/src/app/shared/components/application-list/add-application-dialog/component.ts, modules/web/src/app/shared/components/application-list/component.ts, modules/web/src/app/shared/components/application-list/style.scss, modules/web/src/app/shared/components/application-list/template.html, modules/web/src/app/shared/entity/application.ts
- Hide KKP managed system applications from add application dialog.
- Add toggle for admin to view KKP managed system applications.
- Prevent KKP managed system applications from being deleted.
Fixes #5440 
/kind feature
```release-note
Hide KKP managed applications from add application dialog and only allow admin to view them.
```
```documentation
NONE
```
=> Hide KKP managed applications

modules/web/src/app/cluster/list/cluster/component.ts, modules/web/src/app/cluster/list/cluster/template.html, modules/web/src/app/dynamic/enterprise/quotas/component.ts, modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts, modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss, modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html, modules/web/src/app/dynamic/enterprise/quotas/service.ts, modules/web/src/app/dynamic/enterprise/quotas/style.scss, modules/web/src/app/dynamic/enterprise/quotas/template.html, modules/web/src/app/dynamic/enterprise/quotas/utils/common.ts, modules/web/src/app/project-overview/component.ts, modules/web/src/app/project/component.ts, modules/web/src/app/project/edit-project/component.spec.ts, modules/web/src/app/project/edit-project/component.ts, modules/web/src/app/project/edit-project/template.html, modules/web/src/app/project/style.scss, modules/web/src/app/project/template.html, modules/web/src/app/shared/components/number-stepper/style.scss, modules/web/src/app/wizard/step/cluster/template.html, modules/web/src/assets/css/global/_main.scss, modules/web/src/assets/css/global/_theme.scss
Quota UI design enhancement .
**Project View Card :**
**Edit Project :**
**Project Quota :**
**Cluster List :**
Fixes #4913
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Quota UI follow ups

modules/web/src/app/core/components/user-panel/component.spec.ts, modules/web/src/app/core/components/user-panel/component.ts, modules/web/src/app/core/services/auth/service.ts, modules/web/src/app/shared/model/Config.ts, modules/web/src/test/services/auth-mock.ts
Add support for OIDC provider logout URL.
Fixes #5465 
/kind feature
```release-note
Add support for OIDC provider logout URL.
```
```documentation
TBD
```
=> Add support for OIDC provider logout URL

modules/web/src/app/cluster-template/component.ts, modules/web/src/app/core/components/sidenav/component.spec.ts, modules/web/src/app/core/components/sidenav/component.ts, modules/web/src/app/shared/components/add-cluster-from-template-dialog/component.ts, modules/web/src/app/shared/components/add-cluster-from-template-dialog/steps/template/component.ts, modules/web/src/app/shared/components/add-cluster-from-template-dialog/template.html, modules/web/src/app/wizard/component.ts, modules/web/src/app/wizard/template.html, modules/web/src/app/wizard/types/wizard-mode.ts
Cluster Template (Creation, Edit and Customize) UX enhancement 
**customize Cluster Template Wizard buttons**:
**Edit wizard buttons**:
**Create wizard buttons**:
Fixes #5026
/kind design
```release-note
Cluster Template (Creation, Edit and Customize) UX enhancement 
```
```documentation
NONE
```
=> Cluster Template Creation, Edit and Customize UX

src/assets/config/changelog.json
Updates changelog.json for 2.21.5 patch release.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] changelog update 2.21.5

src/assets/config/changelog.json
Updates changelog.json for 2.19.14 patch release.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.19] changelog update 2.19.14

modules/web/src/app/project-overview/component.ts, modules/web/src/app/project-overview/create-resource-panel/template.html, modules/web/src/app/project-overview/style.scss, modules/web/src/app/project-overview/template.html, modules/web/src/app/shared/components/labels/style.scss, modules/web/src/app/shared/components/labels/template.html
enhancement for the project overview page 
**create resources list**:
**project overview card**:
Fixes #5506
/kind design
```release-note
add edit product button in project overview page,  rearrangement for the create resource list
```
```documentation
NONE
```
=> project overview follow up

Makefile, package-lock.json, package.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.19] Bump version v2.19.14

Makefile, package-lock.json, package.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.20] Bump version v2.20.12

Makefile, package-lock.json, package.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Bump version v2.21.5

modules/api/pkg/handler/v2/provider/gcp.go
Fix a typo in the credential handling for GCP.
Fixes #5542
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix credentials handing for GCP

modules/web/src/app/cluster/details/kubeone/machine-deployment-details/component.ts, modules/web/src/app/cluster/details/kubeone/machine-deployment-details/template.html, modules/web/src/app/cluster/details/kubeone/machine-deployment-dialog/component.ts, modules/web/src/app/cluster/details/kubeone/machine-deployment-dialog/style.scss, modules/web/src/app/cluster/details/kubeone/machine-deployment-dialog/template.html, modules/web/src/app/cluster/details/kubeone/machine-deployment-list/component.ts, modules/web/src/app/cluster/details/kubeone/machine-deployment-list/template.html, modules/web/src/app/cluster/details/kubeone/template.html, modules/web/src/app/cluster/module.ts, modules/web/src/app/shared/entity/external-cluster.ts
Add support to upgrade KubeOne machine deployment version.
**MD Dialog:**
Additionally, warning messages are also added when MD version is less than cluster version or if cluster container runtime is `docker`.
https://user-images.githubusercontent.com/13975988/213246273-05800f73-0362-4481-a791-2d71bfa3e6f5.mov
Fixes #5560 
/kind feature
```release-note
Add support to upgrade KubeOne machine deployment version.
```
```documentation
NONE
```
=> Upgrade KubeOne MD version

modules/api/pkg/ee/resource-quota/handler.go, modules/api/pkg/ee/resource-quota/handler_test.go
Small fix for mismatched scale.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix vsphere resource calculation

modules/web/src/app/dynamic/enterprise/quotas/component.ts, modules/web/src/app/dynamic/enterprise/quotas/default-project-quota/component.ts, modules/web/src/app/dynamic/enterprise/quotas/default-project-quota/style.scss, modules/web/src/app/dynamic/enterprise/quotas/default-project-quota/template.html, modules/web/src/app/dynamic/enterprise/quotas/module.ts, modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts, modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss, modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html, modules/web/src/app/dynamic/enterprise/quotas/style.scss, modules/web/src/app/dynamic/enterprise/quotas/template.html, modules/web/src/app/project/edit-project/component.ts, modules/web/src/app/project/edit-project/template.html, modules/web/src/app/project/style.scss, modules/web/src/app/shared/entity/settings.ts
Add functionality to configure default project quota.
https://user-images.githubusercontent.com/13975988/213157287-537ed1dc-06b5-43db-bd9f-e12308aafce3.mov
Fixes #4860 
/kind feature
```release-note
Add functionality to configure default project quota.
```
```documentation
NONE
```
=> Add functionality to configure default project quota

modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts, modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html, modules/web/src/app/dynamic/enterprise/quotas/template.html
This PR cover couple of scenarios:
- Case when no quotas configured
-  Case when explicit quotas configured
- Case when defaulting quotas configured
**Explicit:**
https://user-images.githubusercontent.com/17727069/214517759-45dc7869-c554-431a-8701-3f31525188c4.mp4
**Defaulting Quotas:**
https://user-images.githubusercontent.com/17727069/214517813-202ae717-c292-4c12-991b-59c57a988c68.mp4
Fixes #5594 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Show progress bars when defaulting is applied to projects

modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
This PR adds a  validation check to prevent calculation of live quota calculation when no quota is being returned.
Note:
- Quota is not returned for non-configured projects
Fixes #5593 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Prevent blockage when quota resources is not configured to any project

modules/web/src/app/dynamic/enterprise/quotas/template.html
Display tooltip message on default project quota label.
Fixes #
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Display tooltip message on default project quota label

modules/api/pkg/handler/common/upgrade.go
For the reasons described in https://github.com/kubermatic/kubermatic/pull/11765 the update condition `nonAMD64WithCanalAndIPVS` should not be set anymore and was removed in https://github.com/kubermatic/kubermatic/pull/11765
Fixes #
/kind bug
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
=> Do not set nonAMD64WithCanalAndIPVS condition on upgrade

modules/web/src/app/shared/components/application-list/add-application-dialog/template.html, modules/web/src/app/shared/components/application-list/component.ts, modules/web/src/app/shared/components/application-list/edit-application-dialog/component.ts, modules/web/src/app/shared/components/application-list/edit-application-dialog/template.html, modules/web/src/app/shared/entity/application.ts
- Prevent version upgrade for system applications.
- Update version dropdown hint message.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Prevent version upgrade for system applications

modules/web/src/app/shared/entity/opa.ts
In kubermatic/kubermatic#11723 we allow to define enforcementAction in kubermatic 's constraint. This  PR updates UI so user can edit enforcementAction on constraints and default constraints.
Fixes #
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> opa constraint: handle enforcementAction in UI

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.19] Bump version to 2.19.15

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.20] Bump version to 2.20.13

modules/web/src/app/core/services/application.ts, modules/web/src/app/shared/components/application-list/component.ts
Load application definition details to display method and source icons.
Fixes #5598, Fixes #5223, Fixes #5222 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Load application definition details to display method and source icons

modules/web/src/app/cluster/details/shared/version-change-dialog/component.ts, modules/web/src/app/cluster/details/shared/version-change-dialog/template.html, modules/web/src/app/shared/entity/cluster.ts
This PR disable Control plane version to update to 1.25 or greater due to [PodSecurityPolicy Deprecation](https://kubernetes.io/docs/concepts/security/pod-security-policy/)
**Case: PSP is enabled and Upgrade >= 1.25**
- It shows warning and allowed upgrade to > version but it will **disable** PSP policy
**Case: PSP is **NOT** enabled and Upgrade >= 1.25**
**Note:** by mistake UI ticket was not there used below ticket reference
Fixes [Kubermatic#11763](https://github.com/kubermatic/kubermatic/issues/11763)
/kind bug
```release-note
NONE
``` …
=> Forbid upgrading to Kubernetes v1.25 if Pod Security Policy are enabled

modules/web/src/app/dynamic/enterprise/quotas/services/quota-calculation.ts, modules/web/src/app/node-data/component.ts, modules/web/src/app/node-data/template.html, modules/web/src/app/wizard/component.ts, modules/web/src/app/wizard/template.html
Fixes #5606
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Allow User to Go Through the Cluster Template Wizard When Quota Exceeded 

modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html, modules/web/src/app/settings/admin/presets/dialog/steps/preset/component.ts, modules/web/src/app/settings/admin/presets/dialog/steps/preset/template.html
fix projects in the payload for create preset
Fixes #5632
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix Restrict Preset to Projects

modules/web/src/app/core/services/node.ts, modules/web/src/app/dynamic/enterprise/quotas/services/quota-calculation.ts, modules/web/src/app/node-data/basic/provider/alibaba/component.ts, modules/web/src/app/node-data/basic/provider/anexia/component.ts, modules/web/src/app/node-data/basic/provider/aws/component.ts, modules/web/src/app/node-data/basic/provider/azure/component.ts, modules/web/src/app/node-data/basic/provider/digitalocean/component.ts, modules/web/src/app/node-data/basic/provider/equinix/component.ts, modules/web/src/app/node-data/basic/provider/gcp/component.ts, modules/web/src/app/node-data/basic/provider/hetzner/component.ts, modules/web/src/app/node-data/basic/provider/kubevirt/component.ts, modules/web/src/app/node-data/basic/provider/nutanix/component.ts, modules/web/src/app/node-data/basic/provider/openstack/component.ts, modules/web/src/app/node-data/basic/provider/vmware-cloud-director/component.ts, modules/web/src/app/node-data/basic/provider/vsphere/component.ts, modules/web/src/app/node-data/component.ts, modules/web/src/app/node-data/dialog/component.ts, modules/web/src/app/node-data/dialog/template.html, modules/web/src/app/shared/entity/quota.ts, modules/web/src/app/shared/model/NodeSpecChange.ts
This PR fixes live quota calculation for Add/Edit MD dialog
Add MD
https://user-images.githubusercontent.com/17727069/217036791-41eff4f5-7083-4e2e-9f80-15b72a7fd48f.mp4
Edit MD:
https://user-images.githubusercontent.com/17727069/217037033-250ffab0-3924-4eed-9376-833da02e8e76.mp4
Note:
Added checks to prevent API call triggering on CE edition as this Widget feature is EE feature
Note: No Ticket
Fixes # 
/kind bug
There was a bug where user tries to edit MD dialog the Replica count was sent 1 to backend on initial load and backend assumed that user is trying to add 1 more replica where backend "Adds" up calculation to existing resource quota which …
=> Fix resource quota calculation for Edit MD

src/app/node-data/basic/provider/kubevirt/component.ts, src/app/node-data/basic/provider/kubevirt/template.html, src/app/shared/components/chip-list/component.ts, src/app/shared/components/chip-list/template.html
Manual cherrypick of https://github.com/kubermatic/dashboard/pull/5662.
Fixes #
/kind bug
```release-note
Mark KubeVirt node affinity preset key and values as required.
```
```documentation
NONE
```
=> Mark KubeVirt node affinity preset key and values as required

modules/api/pkg/provider/cloud/kubevirt/client.go
Signed-off-by: Marcin Franczyk <marcin0franczyk@gmail.com>
Fix KubeVirt client scheme creation
Fixes https://github.com/kubermatic/dashboard/issues/5660
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix KubeVirt client scheme creation

modules/api/cmd/kubermatic-api/swagger.json, modules/api/pkg/handler/v2/external_cluster/external_cluster.go, modules/api/pkg/handler/v2/provider/aws.go, modules/api/pkg/handler/v2/provider/gcp.go, modules/api/pkg/handler/v2/routes_v2.go, modules/api/pkg/test/e2e/utils/apiclient/client/gcp/gcp_client.go, modules/api/pkg/test/e2e/utils/apiclient/client/gcp/list_project_g_c_p_subnetworks_parameters.go, modules/api/pkg/test/e2e/utils/apiclient/client/gcp/list_project_g_c_p_subnetworks_responses.go, modules/api/pkg/test/e2e/utils/apiclient/client/gke/gke_client.go, modules/api/pkg/test/e2e/utils/apiclient/client/gke/list_project_g_c_p_zones_parameters.go, modules/api/pkg/test/e2e/utils/apiclient/client/gke/list_project_g_c_p_zones_responses.go
This PR fixes parameters parsing of some routes after they were migrated to introduce project id parameter.
Fixes kubermatic/kubermatic#11807
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fixes after introducing project id to routes

modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
Bumps version information to v2.22.0-alpha.1.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update version to v2.22.0-alpha.1

modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
fix the quota calculation payload in edit MD for kubevirt  
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix Quota Calculation for Kubevirt Edit MD

src/app/node-data/basic/provider/kubevirt/component.ts, src/app/node-data/basic/provider/kubevirt/template.html
This is manual cherrypick of https://github.com/kubermatic/dashboard/pull/5685.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Mark KubeVirt node affinity preset values as optional

modules/web/src/app/backup/list/automatic-backup/add-dialog/template.html, modules/web/src/app/dynamic/enterprise/metering/schedule-config/add-dialog/template.html, modules/web/src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/template.html, modules/web/src/app/shared/validators/cron.validator.ts
This PR fixes the cron validation which in it's current state is broken and unusable.
Fixes #5674
/kind bug
```release-note
Fixes validation for cron expressions for Etcd backups and metering schedule
```
```documentation
NONE
```
=> Hotfix: Validation for cron expressions for etcd backups and metering schedule

modules/api/pkg/handler/websocket/terminal.go
Update to the latest image for web-terminal.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update image for web terminal

modules/web/src/app/dynamic/enterprise/quotas/default-project-quota/template.html
Update default project quota layout to better align with other Admin Settings.
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Update default project quota layout

modules/api/pkg/handler/v1/project/project.go
Fix user info and error checking for list projects API endpoint.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Hotfix: project list for inactive projects

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Bump patch version & update changelog for 2.21.6

modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts, modules/web/src/app/cluster/details/cluster/edit-cluster/template.html, modules/web/src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html, modules/web/src/app/wizard/step/cluster/component.ts, modules/web/src/app/wizard/step/cluster/template.html
This PR introduces the following changes:
1. Remove docker as the supported container runtime
2. Tooltips/hints to inform users that using Pod Security Policies is not recommended.
Fixes #
/kind chore
Since we are pretty close to the actual release I'd request for the reviewer to run these changes locally and verify them again as well.
```release-note
NONE
```
```documentation
NONE
```
=> Minor UI/UX improvements

modules/web/cypress/types/endpoints.ts, modules/web/cypress/utils/endpoint.ts, modules/web/src/app/core/services/provider/equinix.ts, modules/web/src/app/core/services/wizard/provider/equinix.ts, modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
Rename `packet` to `equinixmetal` in `sizes` endpoint of Equinix provider.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Update `sizes` endpoint of Equinix provider

modules/api/cmd/kubermatic-api/swagger.json, modules/api/pkg/api/v2/types.go, modules/api/pkg/handler/common/machine.go, modules/api/pkg/handler/v2/cluster_template/cluster_template.go, modules/api/pkg/test/e2e/utils/apiclient/models/cluster_template_node_deployment.go
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Include annotations for nodeDeployments in get cluster templates response

modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
**PreReq**
**kubevirt** cluster template saved with **instance** type selected
This bug was catched when customizing kubevirt cluster template as it was triggering API call with default values first and meanwhile when instance type was fetched it send payload to backend with OLD replaced resource field which was a mismatch to get correct quota calculation from backend.
It should select correct `replaced` resource in case of Edit MD when user tries to update instance type instead of default values of cpu/memory.
[Cater this comment](https://github.com/kubermatic/dashboard/issues/5584#issuecomment-1424039969)
Fixes #
/kind bug
There is still one bug …
=> Fix payload for Kubevirt quota calculation

modules/api/pkg/handler/websocket/terminal.go
This PR adds a missing part for the web terminal bug fix for inactivity timeout: now it is able to handle the "ping-pong" reply from the client.
Fixes #5683
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Handle "pong" messages from web terminal client

modules/web/src/app/core/services/wizard/provider/equinix.ts
Update header names for Equinix provider endpoints.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Update header names for Equinix provider endpoints

modules/api/pkg/handler/v2/routes_v2.go, modules/web/src/app/shared/components/external-cluster-credentials/provider/eks/component.ts
This PR does the following things:
- Fix API endpoint to validate credentials for EKS
- Fix an issue with assume role where the values were being set to null and forwarded to backend incorrectly.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fixes for EKS clusters

modules/api/pkg/handler/v2/external_cluster/node.go
**What this PR does / why we need it**: List AKS machinedeployments for Warning state
Fixes #5734
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> List AKS machinedeployments for Warning state

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
Bumping version to `v2.22.0-rc.0` so we can cut a first RC release in the near future.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Bump version to v2.22.0-rc.0

modules/web/src/app/cluster/details/cluster/edit-cluster/template.html, modules/web/src/app/node-data/basic/provider/gcp/component.ts
prevent sending the quota calculation post request until the machine type is been set 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix Quota Calculation for Edit MD in GCP cluster

modules/web/src/assets/config/changelog.json
Fix changelog JSON syntax error.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix changelog JSON syntax error

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
Just preparing this PR in case we want to cut a second RC, which seems likely at the moment.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Bump version to v2.22.0-rc.1

modules/api/cmd/kubermatic-api/main.go, modules/api/cmd/kubermatic-api/swagger.json
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> Extend swagger doc mentioning API as being internal

modules/web/package-lock.json, modules/web/package.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update dependencies for dashboard

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Bump version to v2.22.0

modules/web/cypress/pages/v2/projects/page.ts, modules/web/cypress/pages/v2/settings/admin/dynamic-datacenters/page.ts
Add assertion for delete project button to exist in DOM and be enabled.
```release-note
NONE
```
```documentation
NONE
```
=> Add assertion for delete project button

modules/api/hack/ci/update-docs.sh
We are going to use this scrip in prow's postsubmit jobs in order to refresh swagger in kubermatic/docs repo.
Fixes #
/kind bug
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Add script for updating swagger in kubermatic/docs

modules/web/src/app/cluster/details/cluster/machine-deployment-details/template.html, modules/web/src/app/core/components/navigation/project/template.html, modules/web/src/app/settings/admin/custom-link-form/style.scss, modules/web/src/app/settings/admin/customization/style.scss, modules/web/src/app/shared/components/side-nav-field/style.scss, modules/web/src/app/shared/components/side-nav-field/theme.scss, modules/web/src/app/shared/components/spinner-with-confirmation/style.scss, modules/web/src/assets/css/global/_main.scss, modules/web/src/assets/css/material/_main.scss, modules/web/src/assets/themes/dark.scss, modules/web/src/assets/themes/light.scss
- Adjust spacing and styles of collapsed side-nav:
- Increase project selector dropdown to make more projects visible:
- Fix spacing between confirmation spinner and input fields:
- Fix spacing between action buttons on machine deployment details page:
Fixes #5755 
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> UI fixes and improvements

modules/api/pkg/api/v1/types.go, modules/api/pkg/api/v1/types_test.go
Fixes kubermatic/kubermatic#11847
/kind bug
No backport needed.
```release-note
NONE
```
```documentation
NONE
```
=> KubeVirt prevent marshalling of resources both in instancetype and NodeSpec

modules/api/go.mod, modules/api/go.sum, modules/api/pkg/handler/test/helper.go
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> API: Bump dependency for KKP

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Bump version v2.21.7

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.20] Bump version v2.20.14

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
- Update KKP version in Dashboard API
- Bump versions to v2.22.1
- Update `changelog.json`
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Bump version v2.22.1

modules/web/src/app/pages/frontpage/style.scss, modules/web/src/app/pages/frontpage/template.html, modules/web/src/assets/images/branding/bg.svg
This PR updates login page visual changes
Fixes #5790 
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Login page visual changes

modules/web/package-lock.json, modules/web/package.json
Update xterm to `5.1.0`.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update xterm to latest version

src/app/shared/utils/health-status.ts
A manual cherry-pick of #5837.
Fixes #5834
/kind bug
```release-note
Show correct health information for Machine Deployments with no replicas
```
```documentation
NONE
```
=> [release/v2.21] Correctly handle MD health if no replicas are configured

hack/lib.sh
Required because GitHub rotated their RSA SSH key: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update GitHub SSH key

.prow/api.yaml, .prow/common.yaml, .prow/frontend.yaml, hack/verify-spelling.sh, modules/api/hack/gen-api-client.sh, modules/api/hack/update-swagger.sh, modules/api/hack/verify-licenses.sh, modules/api/pkg/handler/v1/user/user_test.go, modules/api/pkg/handler/v2/cluster/binding_test.go, modules/web/containers/chrome-headless/Dockerfile, modules/web/containers/custom-dashboard/Dockerfile
Fixes https://github.com/kubermatic/release/issues/11
/kind chore
```release-note
Bump golang version to 1.19.8.
```
```documentation
NONE
```
=> [release/v2.22] Upgrade to Go 1.19.8

.prow/api.yaml, .prow/common.yaml, .prow/frontend.yaml, hack/images/web-terminal/Dockerfile, hack/verify-spelling.sh, modules/api/.golangci.yml, modules/api/hack/gen-api-client.sh, modules/api/hack/update-swagger.sh, modules/api/hack/verify-licenses.sh, modules/api/pkg/handler/v1/user/user_test.go, modules/api/pkg/handler/v2/cluster/binding_test.go, modules/api/pkg/provider/cloud/nutanix/client.go, modules/web/containers/chrome-headless/Dockerfile, modules/web/containers/chrome-headless/release.sh, modules/web/containers/custom-dashboard/Dockerfile
Use docker image with go 1.20.4 version.
xref https://github.com/kubermatic/release/issues/11
/kind chore
```release-note
Update golang version to 1.20.4.
```
```documentation
NONE
```
=> Upgrade to Go 1.20.3

modules/api/go.mod, modules/api/go.sum, modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go, modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
=> Update k8c.io/kubermatic/v2 to 8243a5d86430

modules/web/src/app/cluster/details/cluster/component.ts
When there are 0 MD replicas it takes more time to load MD list because `metrics` API request takes extra time for some reason and we wait for all API requests to finish before initializing cluster details. This PR initializes MD list without waiting for other cluster details to finish loading.
https://user-images.githubusercontent.com/13975988/234661678-37208eee-227e-4efd-a2bf-82366118002c.mov
Fixes #5833 
/kind bug
```release-note
Machine Deployments are initialized without waiting for all cluster details to finish loading.
```
```documentation
NONE …
```
=> Initialize machine deployments before other cluster details are loaded

modules/web/src/app/backup/list/automatic-backup/add-dialog/template.html, modules/web/src/app/backup/list/snapshot/add-dialog/template.html, modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts, modules/web/src/app/cluster/details/cluster/edit-cluster/template.html, modules/web/src/app/cluster/details/cluster/edit-provider-settings/aws-provider-settings/template.html, modules/web/src/app/cluster/details/cluster/machine-deployment-list/template.html, modules/web/src/app/cluster/details/cluster/mla/alertmanager-config/template.html, modules/web/src/app/cluster/details/cluster/share-kubeconfig/template.html, modules/web/src/app/cluster/details/cluster/template.html, modules/web/src/app/cluster/details/shared/version-change-dialog/template.html, modules/web/src/app/dynamic/enterprise/metering/schedule-config/add-dialog/template.html, modules/web/src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/template.html, modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html, modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html, modules/web/src/app/project/template.html, modules/web/src/app/settings/admin/defaults/template.html, modules/web/src/app/settings/user/template.html, modules/web/src/app/shared/components/addon-list/install-addon-dialog/template.html, modules/web/src/app/shared/components/addon-list/template.html, modules/web/src/app/shared/components/application-list/add-application-dialog/template.html, modules/web/src/app/shared/components/application-list/template.html, modules/web/src/app/shared/components/external-cluster-credentials/provider/aks/template.html, modules/web/src/app/shared/components/external-cluster-credentials/provider/eks/template.html, modules/web/src/app/wizard/step/cluster/template.html, modules/web/src/app/wizard/step/provider-settings/provider/basic/aws/template.html, modules/web/src/assets/css/_images.scss, modules/web/src/assets/css/global/_main.scss, modules/web/src/assets/css/global/_theme.scss, modules/web/src/assets/css/material/_main.scss
Add external link icon inside all links which open in new tab.
**Inside Form Field Hints:**
**Normal Text:**
Fixes #5511 
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Add external link icon

modules/web/src/app/cluster/details/cluster/edit-cluster/template.html, modules/web/src/app/wizard/step/cluster/template.html, modules/web/src/assets/css/global/_main.scss
add a fixed height to all elements in the `km-content-wrap` component 
Fixes #5024
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Fix vertical space between label and value for km-property

modules/web/src/app/settings/admin/presets/dialog/style.scss, modules/web/src/app/settings/admin/presets/edit-dialog/template.html
Fix spacing in edit preset dialog:
**Before:**
**After:**
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix spacing in edit preset dialog

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Bump version to v2.21.9 && add new changelog

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
Bump version to v2.20.16 && add new changelog
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.20] Bump version to v2.20.16 && add new changelog

modules/web/src/app/settings/admin/opa/default-constraints/component.ts, modules/web/src/app/settings/admin/opa/default-constraints/style.scss, modules/web/src/app/settings/admin/opa/default-constraints/template.html
add fold/unfold functionality to the applies  on column when the providers are more than 3 
Fixes #3644
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Add toggele option to default constraints

README.md
Based on consensus in sig-ui. 
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
=> Remove code coverage report from description

modules/web/src/app/cluster/list/cluster/component.spec.ts, modules/web/src/app/cluster/list/cluster/component.ts, modules/web/src/app/cluster/list/cluster/style.scss, modules/web/src/app/cluster/list/cluster/template.html, modules/web/src/app/shared/entity/cluster.ts
Add warnning message in the cluster list page in case some seeds are not reachable .
**Cluster list**:
Fixes #5913 
/kind design
```release-note
Add warning message in the cluster list page in case some seeds are not reachable.
```
```documentation
NONE
```
=> Add warnning message in case some seed are not reachable

modules/web/src/app/node-data/basic/provider/azure/component.ts, modules/web/src/app/node-data/basic/provider/azure/template.html
Set Azure data disk size default value to `0`.
Fixes #5973 
/kind feature
```release-note
NONE
```
```documentation
TBD
```
=> Set Azure data disk size default value to 0

.prow/api.yaml, .prow/common.yaml, .prow/frontend.yaml, hack/images/web-terminal/Dockerfile, hack/images/web-terminal/release.sh, hack/verify-spelling.sh, modules/api/hack/gen-api-client.sh, modules/api/hack/update-swagger.sh, modules/api/hack/verify-licenses.sh, modules/web/containers/chrome-headless/Dockerfile, modules/web/containers/chrome-headless/release.sh, modules/web/containers/custom-dashboard/Dockerfile
Update Golang veresion to 1.20.5
/kind chore
```release-note
Update to Go 1.20.5
```
```documentation
NONE
```
=> Update Golang veresion to 1.20.5

modules/web/package-lock.json, modules/web/src/app/cluster/details/cluster/template.html, modules/web/src/app/member/add-member/component.ts, modules/web/src/app/settings/admin/admins/add-admin-dialog/component.ts, modules/web/src/app/shared/components/application-list/add-application-dialog/template.html, modules/web/src/app/shared/components/cluster-summary/template.html
Fixes against https://github.com/kubermatic/dashboard/issues/6017#issuecomment-1589135106
xref #6017
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Minor improvements for UI/UX

modules/web/src/app/node-data/dialog/component.ts, modules/web/src/app/node-data/dialog/template.html, modules/web/src/assets/css/_images.scss
Disable Add/Save machine deployment button during quota estimation:
https://github.com/kubermatic/dashboard/assets/13975988/f6e45451-9dbf-43fa-a99c-87bb064842a3
xref https://github.com/kubermatic/dashboard/issues/6017#issuecomment-1586950444
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Disable Add/Save machine deployment button during quota estimation

modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts, modules/web/src/app/dynamic/enterprise/quotas/service.ts, modules/web/src/app/shared/components/add-cluster-from-template-dialog/component.ts, modules/web/src/app/shared/components/add-cluster-from-template-dialog/style.scss, modules/web/src/app/shared/components/add-cluster-from-template-dialog/template.html
disable creating cluster button in the create cluster from template dialog quota is exceeded 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Prevent creating cluster from template if quota exceeded

.dockerignore, .github/ISSUE_TEMPLATE/pre-release.md, .github/ISSUE_TEMPLATE/release.md, docs/manuals/release.md, modules/web/tsconfig.json
Just some documentation and random improvements. Nothing code related.
Fixes #
/kind cleanup
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Minor improvements

package-lock.json, package.json, src/assets/config/changelog.json
Bump version to 2.21.10 and update changelog.json
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Bump version to 2.21.10 and update changelog.json

modules/api/Makefile, modules/api/cmd/kubermatic-api/swagger.json, modules/api/go.mod, modules/api/go.sum, modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go, modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go, modules/api/pkg/test/e2e/utils/apiclient/models/datacenter_spec_kubevirt.go, modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Bump version for v2.22.4
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Bump version to v2.22.4 and update changelog.json

.github/dependabot.yml
Updating dependabot configuration to group angular updates together in a single PR.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Dependabot: group Angular updates

modules/web/src/app/node-data/component.ts
Ubuntu should be the default OS for all the cloud providers, if it's available and allowed to be used. The behaviour seems to have changed after https://github.com/kubermatic/dashboard/pull/6070.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> Default OS for vSphere to Ubuntu, if template exists

modules/web/src/app/node-data/basic/provider/vmware-cloud-director/template.html
With https://github.com/kubermatic/dashboard/pull/6094, we made sizing and placement policy required fields for machine deployments on VMware Cloud Director. This is not required since the VCD admins/operators might already define default policies at the ORG VDC level.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Mark sizing and placement policy as optional fields for VMware Cloud Director

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
Bump version to v2.21.11.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Bump version to v2.21.11

src/assets/config/changelog.json
This updates the changelog.json
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] mention MC update in changelog

modules/web/src/assets/config/changelog.json
This updates the changelog.json. I would consider some of the changes in the changelog to be of no consequence for users, so I removed them.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] update changelog.json, remove some non-user-facing changes from it

modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts, modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
This PR is continuation of https://github.com/kubermatic/dashboard/pull/6120 and it fixes the same issue when using Application Credentials.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix network and subnet pool dropdowns of Openstack provider

modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts, modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
This is a manual cherry-pick of https://github.com/kubermatic/dashboard/pull/6128.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Fix network and subnet pool dropdowns of Openstack provider

modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts, modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
This is a manual cherry-pick of https://github.com/kubermatic/dashboard/pull/6128.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] Fix network and subnet pool dropdowns of Openstack provider

modules/web/src/app/shared/components/application-list/style.scss, modules/web/src/app/shared/module.ts, modules/web/src/assets/css/global/_main.scss, modules/web/src/assets/css/material/_main.scss, modules/web/src/assets/css/material/_theme.scss, modules/web/src/assets/themes/dark.scss, modules/web/src/assets/themes/light.scss
Migrate material `slide-toggle` component from legacy to latest version.
xref #5864 
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Migrate material slide-toggle component from legacy to latest version

modules/web/hack/extract-themes.sh
Fixes the npm script to build custom themes.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix script for building themes

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Prepare dashboard for 2.22.6 patch release.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Update web for v2.22.6 patch release

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
Updates for v2.21.12 patch release
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Updates for v2.21.12 patch release

modules/web/src/app/node-data/extended/provider/vsphere/tag-categories/component.ts
Fix a bug where tags specified at the cluster level were not being properly synced to the state of the machines(node data). 
Fixes #
/kind bug
```release-note
Fix: vSphere tags for initial machine deployments
```
```documentation
NONE
```
=> Fix: vSphere tags for initial machine deployments

modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
Update `tooltip` shown in the provider settings for vSphere for Cluster Tags.
Fixes #6169
```release-note
NONE
```
```documentation
NONE
```
=> Update tooltip to document vSphere folder tags support

modules/web/src/app/settings/user/template.html
Fix docs link about OIDC groups on user settings page.
Fixes #6207 
/kind bug
```release-note
Fix docs link about OIDC groups on user settings page.
```
```documentation
NONE
```
=> Fix docs link about OIDC groups

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Prepares the upcoming v2.22.7 patch release, bumping the version references and adding user-visible changelog entries.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Prepare v2.22.7

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Prepares the upcoming v2.23.3 patch release, bumping the version references and adding user-visible changelog entries.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] Prepare v2.23.3

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Patch release version bump

Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Patch release version bump, KKP update

modules/web/src/assets/config/changelog.json
Adding information about security patch in web-terminal.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Changelog update

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Bump versions and update changelog.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Patch release 2.22.9

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
Version bump and changelog update.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Patch release 2.21.14

modules/web/src/app/shared/components/cluster-summary/template.html
Fix typo in `KubeLB` label.
Fixes #
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Fix typo in `KubeLB` label

modules/web/src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/component.ts
This improves the wording a tiny bit.
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
=> re-word warning message about deleting external clusters

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
This prepares `v2.24.0-beta.1`. I won't cut it right away, but at least we'll have the relevant files bumped already.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Prepare v2.24.0-beta.1 release

modules/web/src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts
in eks we shouldn't send the patch version for updating the machinedeployment
Fixes #6334 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Remove the patch version in edit MD for EKS

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
This PR prepares the first 2.24.0 release candidate where we need to bump version. In addition, I've started drafting the changelog.json content (based on https://github.com/kubermatic/kubermatic/pull/12758/), which should be more or less complete now but might see a few changes before the final release.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Prepare 2.24.0 Release Candidate 0 and update changelog.json

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
This prepares the v2.22.10 release scheduled for next Tuesday.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Prepare v2.22.10 release

Makefile, package-lock.json, package.json, src/assets/config/changelog.json
This prepares the v2.21.15 release scheduled for next Tuesday.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.21] Prepare v2.21.15 release

modules/web/Makefile
Oversight in #6371, caught by @Waseem826.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Update web Makefile to v2.22.10

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
This prepares the v2.23.7 release scheduled for next Tuesday.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] Prepare v2.23.7 release

modules/web/src/assets/config/changelog.json
Adds changelog entry for #6381.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] Add changelog entry for partial cluster list

modules/api/pkg/handler/v1/project/project.go
We added a check for context timeout in https://github.com/kubermatic/dashboard/pull/6374 which caused the API request to timeout if it takes more than 10 seconds to list clusters of a project. This PR reverts that change.
Fixes #6384 
/kind bug
```release-note
Fix a bug where API call to list projects was failing due to slowness.
```
```documentation
NONE
```
=> Remove context timeout check from listing clusters of project

modules/api/pkg/handler/v1/project/project.go
This is a manual cherry-pick of https://github.com/kubermatic/dashboard/pull/6385
Fixes #
/kind bug
```release-note
Fix a bug where API call to list projects was failing due to slowness.
```
```documentation
NONE
```
=> [release/v2.23] Remove context timeout check from listing clusters of project

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
This prepares the repository for the upcoming 2.23.8.
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] Update to 2.23.8

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Last PR for v2.24.0. This bumps the version to the final release.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Prepare 2.24.0

modules/api/cmd/kubermatic-api/swagger.json, modules/api/go.mod, modules/api/go.sum, modules/api/pkg/api/v1/types.go, modules/api/pkg/handler/common/cluster.go, modules/api/pkg/handler/v1/dc/datacenter.go, modules/api/pkg/handler/v2/cluster_default/cluster_default.go, modules/api/pkg/handler/v2/cluster_template/cluster_template.go, modules/api/pkg/resources/cluster/cluster.go, modules/api/pkg/test/e2e/utils/apiclient/models/cluster_spec.go, modules/api/pkg/test/e2e/utils/apiclient/models/datacenter_spec.go, modules/api/pkg/test/e2e/utils/apiclient/models/metering_configuration.go, modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts, modules/web/src/app/cluster/details/cluster/edit-cluster/template.html, modules/web/src/app/cluster/details/cluster/template.html, modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/vsphere/template.html, modules/web/src/app/shared/components/cluster-summary/template.html, modules/web/src/app/shared/entity/cluster.ts, modules/web/src/app/shared/entity/datacenter.ts, modules/web/src/app/wizard/step/cluster/component.ts, modules/web/src/app/wizard/step/cluster/template.html, modules/web/src/app/wizard/step/provider-settings/provider/extended/vmware-cloud-director/component.ts, modules/web/src/app/wizard/step/provider-settings/provider/extended/vmware-cloud-director/template.html
This PR adds the required changes in API and UI to support disabling CSI drivers for user clusters.
Fixes #6206
/kind feature
```release-note
Support for disabling CSI driver for user clusters
```
```documentation
NONE
```
=> Option to disable CSI drivers

modules/web/src/assets/config/changelog.json
Follow-up to #6430. Adds missing changelog entries.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Add changelog entries for v2.22.11 dashboard fixes

modules/web/src/assets/config/changelog.json
Follow-up to #6431. Adds missing changelog entries.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] Add changelog entries for v2.23.9 dashboard fixes

modules/web/src/app/node-data/component.ts
This is a manual cherry-pick of #6453
/kind bug
```release-note
Fix a bug where Operating System Profiles were not being listed for GCP
```
=> [release/v2.23] Fix operating system profile filter for GCE 

Makefile, modules/api/Makefile, modules/api/cmd/kubermatic-api/swagger.json, modules/api/go.mod, modules/api/go.sum, modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go, modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go, modules/api/pkg/resources/reconciling/zz_generated_reconcile.go, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
This bumps the version to v2.22.12 (January 2024 patch release).
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.22] Bump version to v2.22.12

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go, modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] Bump version to v2.23.10

modules/web/src/app/node-data/basic/provider/vmware-cloud-director/template.html
Just a small adjustment to the title for VM Placement settings.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> VCD: Change title to VM placement settings

Dockerfile, hack/images/web-terminal/Dockerfile
Fixes #
/kind chore
Not updating/releasing a new image for `web-terminal` yet since https://github.com/kubermatic/dashboard/pull/6501 is also going to add some enhancements for web-terminal.
```release-note
Upgrade to alpine 3.19(latest available) version for container images 
```
```documentation
NONE
```
=> Upgrade to alpine 3.19 for container images

modules/api/cmd/kubermatic-api/swagger.json, modules/api/pkg/api/v2/types.go, modules/api/pkg/handler/v2/application_definition/conversion.go, modules/api/pkg/test/e2e/utils/apiclient/models/application_definition_list_item_spec.go, modules/web/src/app/core/services/application.ts, modules/web/src/app/shared/components/application-list/add-application-dialog/style.scss, modules/web/src/app/shared/components/application-list/add-application-dialog/template.html, modules/web/src/app/shared/components/application-list/component.ts, modules/web/src/app/shared/components/application-list/edit-application-dialog/style.scss, modules/web/src/app/shared/components/application-list/edit-application-dialog/template.html, modules/web/src/app/shared/components/application-list/style.scss, modules/web/src/app/shared/components/application-list/template.html, modules/web/src/app/shared/entity/application.ts, modules/web/src/assets/themes/dark.scss
Display source URL, documentation URL and logo of applications.
**Add Application Dialog:**
**Edit Application Dialog:**
**Applications List:**
_Cards View:_
_Table View:_
Fixes #6444 
/kind feature
```release-note
Display source URL, documentation URL and logo of applications.
```
```documentation
TBD
```
=> Display source URL, documentation URL and logo of applications

.prow/api.yaml, .prow/common.yaml, .prow/frontend.yaml, hack/verify-spelling.sh, modules/api/hack/gen-api-client.sh, modules/api/hack/update-swagger.sh, modules/api/hack/verify-licenses.sh, modules/web/containers/chrome-headless/Dockerfile, modules/web/containers/custom-dashboard/Dockerfile
What it says on the tin.
/kind chore
```release-note
Update to Go 1.22.0
```
```documentation
NONE
```
=> Update to Go 1.22

modules/api/pkg/handler/websocket/terminal.go
Fixes Wrong Group & UID of Webshell User
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Adjust Group and User for Webshell Terminal

modules/web/src/app/shared/components/application-list/add-application-dialog/style.scss, modules/web/src/app/shared/components/application-list/add-application-dialog/template.html, modules/web/src/app/shared/components/application-list/application-definition-card/component.ts, modules/web/src/app/shared/components/application-list/application-definition-card/style.scss, modules/web/src/app/shared/components/application-list/application-definition-card/template.html, modules/web/src/app/shared/components/application-list/application-definition-card/theme.scss, modules/web/src/app/shared/components/application-list/edit-application-dialog/template.html, modules/web/src/app/shared/module.ts, modules/web/src/assets/css/_images.scss, modules/web/src/assets/css/global/_theme.scss, modules/web/src/assets/css/theme/_component.scss, modules/web/src/assets/images/icons/code.svg, modules/web/src/assets/images/icons/docs.svg, modules/web/src/assets/themes/dark.scss
Update design of add/edit application dialog.
**Add Application Dialog:**
**Edit Application Dialog:**
Fixes #
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Update design of add/edit application dialog

modules/api/pkg/api/v1/types.go, modules/api/pkg/handler/common/machine.go
This PR adds a response to the edge provider get node endpoint. This is needed as we expect a marshalled response.
Fixes #
```release-note
None
```
```documentation
None
```
=> Add description field to the edge spec

Makefile, modules/api/Makefile, modules/api/cmd/kubermatic-api/swagger.json, modules/api/go.mod, modules/api/go.sum, modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go, modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go, modules/api/pkg/test/e2e/utils/apiclient/models/application_definition_spec.go, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
Prepares v2.25.0-beta.1 to be cut.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Prepare v2.25.0-beta.1

modules/web/src/app/wizard/step/cluster/template.html
With the ever-increasing cluster settings options, the placement of items in the list seems out of place. Having them in an alphabetic order makes more sense.
Fixes #
/kind design 
```release-note
NONE
```
```documentation
NONE
```
=> Sort cluster settings options in an alphabetic order

modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/component.ts, modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/template.html, modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/add-dialog/template.html
Add hint for CBSL field in the add backup dialog.
fix the title for the edit backup storage location dialog. 
Add one of the following kinds:
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Add hint for CBSL field

modules/web/src/app/shared/components/application-list/component.ts
There was an exception being thrown in application list component because of delay in loading of application definitions. This PR fixes that error by adding a safety check.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Add safety check for undefined value exception in application list card

Makefile, modules/api/Makefile, modules/api/cmd/kubermatic-api/swagger.json, modules/api/go.mod, modules/api/go.sum, modules/api/pkg/test/e2e/utils/apiclient/models/application_definition_spec.go, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
Prepares a new v2.25.0-beta.2 release to roll out to QA.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Bump version to v2.25.0-beta.2

modules/web/src/app/cluster/details/cluster/component.ts, modules/web/src/app/core/services/wizard/wizard.ts
- Skip machine controller health check when loading upgrade versions.
- Show Node Settings step in create cluster wizard.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix edge provider issues

modules/web/src/assets/css/material/_theme.scss, modules/web/src/assets/themes/dark.scss
- Fix icon color issues in dark theme.
**Before:**
**After:**
**Before:**
**After:**
- Fix left border color for _checked_ toggle button.
**Before:**
**After:**
Fixes #
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Fix icon and toggle button border color issues

modules/web/src/app/shared/components/application-list/component.ts
Fix application status message.
Fixes #6582 
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Fix application status message

modules/api/pkg/test/e2e/utils/http_test.go
Soo... I admit I don't fully understand the original code and its intent. The tests were introduced in kubermatic/kubermatic#6184.
In general the tests try to induce timeouts and see if the client respects timeouts and error codes accordingly. For this it's important to know that the HandlerFunc that is created by `iterateHandlerFuncs` will be called in individual goroutines, because that's how Go's httptest server works. This means even though we test multiple handles "in sequence", they still race when they attempt to use `funcs` directly. So the channel for the funcs is necessary to coordinate this.
However, I don't understand the WaitGroup. Everytime the HandlerFunc is called, it takes the next func, calls it and then _waits_. This means all …
=> fix race condition in unit tests

modules/web/src/app/backup/details/automatic-backup/backups/component.ts, modules/web/src/app/backup/details/automatic-backup/component.ts, modules/web/src/app/backup/details/automatic-backup/style.scss, modules/web/src/app/backup/details/automatic-backup/template.html, modules/web/src/app/backup/details/snapshot/component.ts, modules/web/src/app/backup/details/snapshot/style.scss, modules/web/src/app/backup/details/snapshot/template.html, modules/web/src/app/backup/list/snapshot/template.html
Disable restore backup button if snabshot/automatic are on deletion status, and fix the status column for the snapshot table.
Fixes #6580 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Disable restore backup button if snabshot/automatic are on deletion

modules/web/src/app/node-data/component.ts
Fixes #
/kind bug
```release-note
Fix a bug where OSPs were not being listed for VMware Cloud Director
```
```documentation
NONE
```
=> Fix OSP list for VMware Cloud Director

modules/web/src/app/cluster/details/cluster/machine-deployment-list/template.html, modules/web/src/app/wizard/step/cluster/component.ts, modules/web/src/app/wizard/step/cluster/template.html, modules/web/src/assets/css/_images.scss
- Hide `Cilium` CNI plugin.
- Add instructions for interacting with cluster pods.
Fixes #
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> Edge provider improvements

modules/web/src/assets/themes/dark.scss
This PR fixes wrong color for some icons in dark mode.
Fixes #6595 
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Fix wrong color for some icons in dark mode

modules/web/src/app/node-data/component.ts
Set Replica count to `0` for Edge provider.
Fixes #
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> Set Replica count to `0` for Edge provider

modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go, modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Include Edge provider in the OSP list

modules/web/src/assets/config/changelog.json
This updates the link to the changelog.
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] update changelog.json

modules/web/src/assets/config/changelog.json
This updates the link to the changelog.
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.24] update changelog.json

modules/api/cmd/kubermatic-api/swagger.json, modules/api/pkg/handler/v1/common/conversion.go, modules/web/src/app/cluster/details/cluster/mla/alertmanager-config/component.spec.ts, modules/web/src/app/cluster/details/cluster/mla/alertmanager-config/component.ts, modules/web/src/app/shared/entity/project.ts, modules/web/src/test/data/project.ts
Add the grafana organization id parameter to Grafana UI link in dashboard
Fixes #6167 
/kind feature
```release-note
Add the grafana orgId parameter to Grafana UI link in dashboard
```
```documentation
NONE
```
=> Append grafana organization id parameter

modules/web/cypress/pages/admin-settings.po.ts, modules/web/cypress/pages/clusters.po.ts, modules/web/cypress/pages/v2/clusters/list/page.ts, modules/web/src/app/cluster/details/cluster/cni-version/theme.scss, modules/web/src/app/cluster/details/shared/version-picker/theme.scss, modules/web/src/app/shared/components/tab-card/style.scss, modules/web/src/app/shared/components/tab-card/theme.scss, modules/web/src/assets/css/global/_main.scss, modules/web/src/assets/css/global/_theme.scss, modules/web/src/assets/css/material/_main.scss, modules/web/src/assets/css/material/_theme.scss
Removing legacy classes in favor of MDC, where applicable.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Migrate to MDC classes

modules/web/src/app/settings/admin/defaults/style.scss, modules/web/src/app/settings/admin/defaults/template.html
Manual cherry-pick of https://github.com/kubermatic/dashboard/pull/6656
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] Improve wording for OIDC kubeconfig settings

modules/web/src/app/settings/admin/defaults/style.scss, modules/web/src/app/settings/admin/defaults/template.html
Manual cherry-pick of https://github.com/kubermatic/dashboard/pull/6656
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.24] Improve wording for OIDC kubeconfig settings

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Time for yet another out-of-band release...
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> prepare 2.25.3

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Time for yet another out-of-band release...
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> prepare 2.24.8

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Time for yet another out-of-band release...
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> prepare 2.23.15

modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/component.ts, modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/template.html, modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/template.html, modules/web/src/app/shared/entity/backup.ts
For the Cluster backups feature, adding options to configure CA Certificates and prefix for the backup storage locations.
Fixes #
/kind feature
```release-note
Cluster Backup: CA bundle and Prefix configuration for backup storage
```
```documentation
NONE
```
=> Cluster Backup: CA bundle and Prefix configuration for backup storage

modules/web/src/app/cluster/details/cluster/style.scss, modules/web/src/app/cluster/details/external-cluster/style.scss, modules/web/src/app/cluster/details/kubeone/style.scss, modules/web/src/app/project-overview/style.scss, modules/web/src/assets/css/global/_main.scss, modules/web/src/assets/css/material/_main.scss
general style enhancement.
* project overview:
* chip-list
* hints:
* card-header
* hide/show button
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> General style enhancement

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
This PR is for Bump version and add changelog for KKP patch release 2.25.4
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.25] Bump version and add changelog for KKP patch release 2.25.4

modules/web/src/app/settings/admin/presets/dialog/steps/preset/component.ts, modules/web/src/app/settings/admin/presets/dialog/steps/preset/template.html, modules/web/src/app/shared/validators/others.ts, modules/web/src/assets/css/material/_main.scss
adjust the domain field to accept emails in the create preset dialog 
* create preset dialog:
Fixes #6686
/kind bug
```release-note
Adjust the preset domain field to accept emails.
```
```documentation
NONE
```
=> Adjust the preset domain field to accept emails

modules/web/hack/development/Dockerfile, modules/web/hack/run-in-docker.sh
Bump node version in the local development scripts. 
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> Bump node version in local run scripts

modules/api/pkg/handler/common/provider/azure.go
Azure API returns location names in a mix of small-letter names and CamelCase names, while it accepts small-letter names consistently. This caused some issues while processing some locations, e.g.: `germanywestcentral`.
This PR allows the user to provide the location name in both formats with no issues.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix Azure location bug

modules/web/src/app/cluster/details/cluster/constraints/style.scss, modules/web/src/app/cluster/details/cluster/mla/rule-groups/style.scss, modules/web/src/app/project/style.scss, modules/web/src/app/settings/admin/dynamic-datacenters/style.scss, modules/web/src/app/settings/admin/dynamic-datacenters/template.html, modules/web/src/app/settings/admin/opa/default-constraints/style.scss, modules/web/src/app/settings/admin/presets/style.scss, modules/web/src/app/settings/admin/presets/template.html, modules/web/src/app/settings/admin/rule-groups/style.scss, modules/web/src/app/settings/admin/rule-groups/template.html, modules/web/src/app/shared/components/application-list/style.scss, modules/web/src/assets/css/global/_main.scss
This PR fixes the styling for the "Filter By" section and ensures the buttons in the action section of tables always appear.
Fixes #6702
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Small ui enhancement

.prow/api.yaml, .prow/common.yaml, .prow/frontend.yaml, docs/proposals/testing.md, hack/verify-spelling.sh, modules/api/hack/gen-api-client.sh, modules/api/hack/update-swagger.sh, modules/api/hack/verify-licenses.sh, modules/web/containers/chrome-headless/Dockerfile, modules/web/containers/custom-dashboard/Dockerfile
This PR is to update Go version to 1.22.4.
Related to https://github.com/kubermatic/infra/pull/2707
Fixes #
/kind chore
```release-note
Update Go version to 1.22.4
```
```documentation
NONE
```
=> [release/v2.25] Updated Go version to 1.22.4

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Time for a new patch release!
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.24] Prepare v2.24.10

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Time for a new patch release!
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.25] Prepare v2.25.6

modules/web/src/app/member/component.ts
fix the pagination for the project member table 
**member page:**
Fixes #6737
/kind bug
/kind cleanup
```release-note
Fix the pagination in project members table.
```
```documentation
NONE
```
=> Fix the pagination in project members table

Makefile, modules/api/Makefile, modules/api/cmd/kubermatic-api/swagger.json, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Preparing a new release.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] Prepare 2.23.17

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Preparing a new release.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.24] Prepare 2.24.11

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Preparing the repo for the upcoming patch releases.
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.25] Prepare 2.25.7

modules/api/pkg/ee/metering/report_handler.go
This PR ensures that the API will fetch the CA bundle on the target seed in order to securely connect to the metering obect store. KKP's operator copies the CA bundle onto ever seed, because it is meant to potentially deviate per seed, so this patch purposefully does not use the CA bundle the API loaded on startup (via --ca-bundle), but fetches it from the seed instead.
Fixes #6751
/kind bug
```release-note
Fix TLS errors in the admin page when using a custom CA for the metering object store.
```
```documentation
NONE
```
=> fetch seed's CA bundle before connecting with metering Minio

modules/api/pkg/handler/v1/user/user.go, modules/api/pkg/provider/kubernetes/member.go
Grant admin all owner Privileges on all projects.
Fixes #6753
/kind bug
/kind feature
```release-note
Grant admin all owner Privileges on all projects.
```
```documentation
TBD
```
=> Give admin owner role to all projects

.gitignore
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> Add applypatch-msg to .gitignore

modules/api/pkg/test/e2e/utils/client.go
This PR changes the Hetzner instance size to fix the e2e tests
Fixes #6784 
```release-note
NONE
```
```documentation
NONE
```
=> Fix: Change hetzner machine size e2e tests

modules/api/pkg/handler/common/provider/packet.go, modules/api/pkg/provider/cloud/packet/provider.go
https://github.com/kubermatic/kubermatic/pull/13629 but for KKP API.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Add Kubermatic/api to packngo User-Agent

Development.md
Update development docs with updated depedency matrix.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update development docs with updated depedency matrix 

modules/web/src/app/settings/admin/defaults/component.ts, modules/web/src/app/settings/admin/defaults/template.html
We shouldn't refer to docs from the [main branch](https://docs.kubermatic.com/kubermatic/main). 
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Use versioned docs intead of main 

.typos.toml, hack/verify-spelling.sh, modules/api/pkg/ee/metering/report_config_handler.go, modules/api/pkg/handler/common/binding.go, modules/api/pkg/handler/common/provider/kubevirt.go, modules/api/pkg/handler/websocket/user_test.go, modules/api/pkg/provider/cloud/gcp/provider.go, modules/api/pkg/provider/cloud/gke/provider.go, modules/web/src/app/shared/components/label-form/component.ts
Adding typos configuration and fixing some typos.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Add typos config

modules/api/pkg/handler/websocket/terminal.go, modules/web/src/app/shared/components/terminal/component.ts
Manual backport of https://github.com/kubermatic/dashboard/pull/6799, skipped the package updates.
Fixes #
/kind bug
```release-note
Fix an issue where the cursor in the web terminal kept jumping to the beginning due to a sizing issue
```
```documentation
NONE
```
=> [release/v2.25] Fix web terminal cursor issue

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
This gets the repository ready for the first 2.26 builds.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> prepare 2.26.0-beta.0

Makefile, modules/api/Makefile, modules/api/cmd/kubermatic-api/swagger.json, modules/api/go.mod, modules/api/go.sum, modules/api/pkg/test/e2e/utils/apiclient/models/a_k_s.go, modules/api/pkg/test/e2e/utils/apiclient/models/a_w_s.go, modules/api/pkg/test/e2e/utils/apiclient/models/alibaba.go, modules/api/pkg/test/e2e/utils/apiclient/models/anexia.go, modules/api/pkg/test/e2e/utils/apiclient/models/azure.go, modules/api/pkg/test/e2e/utils/apiclient/models/baremetal.go, modules/api/pkg/test/e2e/utils/apiclient/models/digitalocean.go, modules/api/pkg/test/e2e/utils/apiclient/models/e_k_s.go, modules/api/pkg/test/e2e/utils/apiclient/models/fake.go, modules/api/pkg/test/e2e/utils/apiclient/models/g_c_p.go, modules/api/pkg/test/e2e/utils/apiclient/models/g_k_e.go, modules/api/pkg/test/e2e/utils/apiclient/models/hetzner.go, modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt.go, modules/api/pkg/test/e2e/utils/apiclient/models/nutanix.go, modules/api/pkg/test/e2e/utils/apiclient/models/openstack.go, modules/api/pkg/test/e2e/utils/apiclient/models/openstack_cloud_spec.go, modules/api/pkg/test/e2e/utils/apiclient/models/packet.go, modules/api/pkg/test/e2e/utils/apiclient/models/provider_preset.go, modules/api/pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director.go, modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere.go, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
This is getting the repository ready for the next beta, expected on the weekend or Monday.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Prepare 2.26.0 beta.1

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Getting ready for the next out-of-bands release.
/hold because I need to double-check if there other changes in KKP 2.23.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.23] prepare 2.23.19

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Getting ready for the next out-of-bands release.
/hold because I need to double-check if there other changes in KKP 2.24.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.24] prepare 2.24.13

Makefile, modules/api/Makefile, modules/api/cmd/kubermatic-api/swagger.json, modules/api/go.mod, modules/api/go.sum, modules/api/pkg/test/e2e/utils/apiclient/models/datacenter_spec_openstack.go, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Getting ready for the next out-of-bands release.
/hold because I need to double-check if there other changes in KKP 2.25.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.25] prepare 2.25.9

hack/images/web-terminal/Dockerfile, hack/images/web-terminal/release.sh, modules/api/pkg/handler/websocket/terminal.go
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Terminal: Update dependencies

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
Yar! (Yet Another Regression)
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.25] prepare 2.25.11

modules/web/src/app/cluster/details/cluster/machine-deployment-details/template.html, modules/web/src/app/project/style.scss, modules/web/src/app/project/template.html, modules/web/src/app/serviceaccount/token/style.scss, modules/web/src/app/settings/admin/applications/style.scss, modules/web/src/app/settings/admin/applications/template.html, modules/web/src/app/settings/admin/bucket-settings/style.scss, modules/web/src/app/settings/admin/defaults/static-labels-form/style.scss, modules/web/src/app/settings/admin/defaults/static-labels-form/template.html, modules/web/src/app/settings/admin/defaults/template.html, modules/web/src/app/settings/admin/limits/style.scss, modules/web/src/app/settings/admin/limits/template.html, modules/web/src/app/settings/admin/presets/edit-dialog/theme.scss, modules/web/src/app/settings/admin/presets/theme.scss, modules/web/src/app/settings/admin/seed-configurations/style.scss, modules/web/src/app/settings/admin/seed-configurations/template.html, modules/web/src/app/shared/components/add-project-dialog/template.html, modules/web/src/app/shared/components/application-list/style.scss, modules/web/src/app/shared/components/application-list/template.html, modules/web/src/app/wizard/step/cluster/template.html, modules/web/src/assets/css/material/_main.scss, modules/web/src/assets/css/material/_theme.scss, modules/web/src/assets/themes/dark.scss
- ### Fix spacing between icon buttons on MD details page:
**Before:**
**After:**
- ### Fix mat-chips input field height and spacing issues:
**Before:**
**After:**
- ### Fix textarea input resizing issue:
**Before:**
**After:**
- ### Fix disabled provider logo icon color:
**Before:**
**After:**
- ### Fix label chips color:
**Before:**
**After:**
- Fix projects card view layout.
- Miscellaneous spacing and alignment fixes.
Ref: #6762 
Fixes #6860 
/kind design
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> UI UX fixes

modules/api/pkg/handler/v2/cluster_default/cluster_default.go
Fixes #6877
/kind bug
```release-note
Fix CNI plugin defaulting for Edge cloud provider
```
```documentation
NONE
```
=> Fix CNI plugin defaulting for edge

hack/images/web-terminal/release.sh, modules/api/pkg/handler/websocket/terminal.go
Fixes #
/kind chore
```release-note
Update web-terminal image to v0.9.1
```
```documentation
NONE
```
/hold
=> Update web-terminal image to v0.9.1

modules/web/src/app/shared/components/terminal/terminal-toolbar/template.html
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix tooltip for web terminal

modules/web/cypress.config.ts, modules/web/cypress/e2e/v2/stories/ssh-keys.spec.ts
Retries for flaky tests.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> Add retries for integration tests

modules/web/src/app/settings/admin/applications/component.ts, modules/web/src/app/settings/admin/applications/template.html, modules/web/src/app/shared/components/application-list/style.scss, modules/web/src/app/shared/components/event-card/style.scss
- Display notification when application is updated.
- Disable "Default" toggle if application is enforced:
- Fix spacing around logo in applications table:
Fixes #6857 
Ref https://github.com/kubermatic/dashboard/issues/6788#issuecomment-2357871935
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Default applications improvements

modules/web/src/app/settings/admin/defaults/static-labels-form/component.ts, modules/web/src/app/settings/admin/defaults/static-labels-form/template.html, modules/web/src/app/settings/admin/defaults/template.html, modules/web/src/app/shared/components/label-form/component.ts, modules/web/src/app/shared/components/label-form/template.html, modules/web/src/assets/css/material/_main.scss
[Screencast from 27 أيلول, 2024 +03 10:38:50 ص.webm](https://github.com/user-attachments/assets/3205d4d3-9b4d-43a7-84bf-1537a6c34c67)
[Screencast from 27 أيلول, 2024 +03 10:44:53 ص.webm](https://github.com/user-attachments/assets/1d28d6aa-210b-4c79-8e91-73a5abb4c77b)
ref #6776 
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> static labels enhancement

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
The stream of bugfixes for 2.26 has mostly calmed down and we're close to the release. Let's signal this by creating an RC.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> prepare 2.26.0-rc.0

modules/web/src/app/settings/admin/applications/component.ts
Prevent system applications from re-appearing after an application is updated.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Prevent system applications from re-appearing after an application is updated

modules/web/src/app/node-data/component.ts
Only allow Ubuntu OS for baremetal provider.
Fixes #
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> Only allow Ubuntu OS for baremetal provider

modules/web/src/app/node-data/basic/provider/vmware-cloud-director/component.ts
Select correct template value when editing MD of VCD provider.
Fixes #
/kind bug
```release-note
Select correct template value when editing MD of VCD provider.
```
```documentation
NONE
```
=> Select correct template value when editing MD of VCD provider

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
Heading for the finish line. :checkered_flag: 
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.26] Prepare 2.26.0

modules/web/cypress.config.ts, modules/web/cypress/support/e2e.ts, modules/web/package-lock.json, modules/web/package.json
upgrade cypress to version 13.15.0
Fixes #6828
```release-note
NONE
```
```documentation
NONE
```
=> Upgrade Cypress to version 13

modules/api/cmd/kubermatic-api/main.go, modules/api/cmd/kubermatic-api/swagger.json
This PR is to bump the KKP API version in the swagger.json. 
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> Bump KKP API version

modules/web/src/app/component.ts, modules/web/src/app/core/services/page-title.ts, modules/web/src/app/shared/entity/common.ts, modules/web/src/app/shared/model/Config.ts, modules/web/src/assets/config/config.json
Added a new `postfix_page_title` property in the UI config to allow setting a custom postfix for the page title.
Fixes #6917 
/kind feature
```release-note
Added a new `postfix_page_title` property in the UI config to allow setting a custom postfix for the page title.
```
```documentation
TBD
```
=> Allow adding a postfix to the page title

modules/web/src/app/node-data/basic/provider/aws/component.ts
Fix missing AMI value in edit machine deployment dialog.
Fixes #7001 
/kind bug
```release-note
Fix missing AMI value in edit machine deployment dialog.
```
```documentation
NONE
```
=> Fix missing AMI value in edit machine deployment dialog

modules/api/pkg/handler/v2/kubernetes-dashboard/login.go
Add groups scope for kubernetes-dashboard auth. More details in https://github.com/kubermatic/dashboard/issues/6895
Fixes #6895
/kind bug
```release-note
Fix a bug where `groups` scope was missing in authentication request for kubernetes-dashboard
```
```documentation
NONE
```
=> Add groups scope for kubernetes-dashboard auth

modules/web/src/app/cluster/details/cluster/template.html, modules/web/src/app/settings/admin/defaults/template.html, modules/web/src/app/settings/admin/opa/template.html, modules/web/src/app/wizard/step/cluster/template.html
Updating the deprecation notice for OPA that was introduced in https://github.com/kubermatic/dashboard/pull/6990
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update deprecation notice for OPA

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
This prepares the next KKP patch release.
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.26] prepare 2.26.2

modules/web/src/app/shared/components/labels/style.scss, modules/web/src/app/shared/components/labels/template.html
Reverts kubermatic/dashboard#6888
This solution has caused more problems than it fixed so I'll create a separate issue to track this and we'll need to come up with a different solution.
Fixes #6981
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> Revert "Fix alignment of long label keys and values"

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
This PR is to add changelog and bump dashboard version for KKP next patch release 2.24.15 - Jan 2025
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.24] Bump dashboard version for KKP next patch release 2.24.15

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json, modules/web/src/assets/config/changelog.json
This PR is to add changelog and bump dashboard version for KKP next patch release 2.25.13 - Jan 2025.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.25] Bump dashboard version for KKP next patch release 2.25.13

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go, modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
Time to gear up for the next KKP release.
```release-note
NONE
```
```documentation
NONE
```
=> prepare 2.27.0-alpha.0

modules/api/go.mod, modules/api/go.sum, modules/api/hack/gen-api-client.sh, modules/api/hack/update-swagger.sh, modules/api/hack/verify-swagger.sh
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix API client and swagger spec generation

modules/api/pkg/api/v1/types.go, modules/api/pkg/api/v1/types_test.go
Fixes #7087
/kind bug
```release-note
vSphere: fix a bug where updating replicas of machine deployments was causing machine rotation
```
```documentation
NONE
```
=> Fix machine deployment update for vSphere

modules/api/Makefile
Instead of running multiple scripts, we can simply the code generation task by introducing a make target `update-codegen`.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Add a single make target for code generation

modules/web/package.json
Update license year.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update license year

modules/web/src/app/cluster/details/cluster/machine-deployment-details/template.html, modules/web/src/app/node-data/template.html, modules/web/src/app/shared/components/cluster-summary/template.html
Following the suggestions from https://github.com/kubermatic/dashboard/issues/7010, to make the max replicas and min replicas settings more intuitive from a UX perspective.
Fixes #7010
/kind design
```release-note
NONE
```
```documentation
NONE
```
=> UX improvements for min/max replicas

modules/web/src/app/dynamic/enterprise/cluster-backups/list/backups/component.ts, modules/web/src/app/dynamic/enterprise/cluster-backups/list/restore/component.ts
Fix Velero logs logs command in error message of failed backups and restores.
Fixes #7048
/kind bug
```release-note
Fix Velero logs command in error message of failed backups and restores.
```
```documentation
NONE
```
=> Fix error message for failed backups and restores

modules/web/src/app/dynamic/enterprise/group/add-group-dialog/template.html, modules/web/src/app/dynamic/enterprise/group/edit-group-dialog/template.html, modules/web/src/app/dynamic/enterprise/group/template.html, modules/web/src/app/member/add-member/template.html, modules/web/src/app/member/edit-member/template.html
Fix some hints message in the member and group dialogs.
Ref #7127
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix hints in group and members dialogs

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
Getting closer to the release...
```release-note
NONE
```
```documentation
NONE
```
=> prepare 2.27.0-beta.0

modules/web/src/app/node-data/component.ts, modules/web/src/app/shared/components/application-list/edit-application-dialog/component.ts, modules/web/src/app/shared/components/application-list/edit-application-dialog/template.html, modules/web/src/app/wizard/step/applications/component.ts
Fix small issues introduced after default applications namespace implementation.
Also added both namespaces in edit application dialog:
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix small applications issues

Makefile, modules/api/Makefile, modules/api/go.mod, modules/api/go.sum, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
2.27.1 follows after 2.27.0.
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.27] prepare 2.27.1

modules/api/hack/run-api.sh
The values of `FEATURE_GATES` variable were not being propagated through flags to the API.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Pass feature gates flag to API in run-api script

modules/api/pkg/resources/machine/machinedeployment.go
```release-note
Updated Dashboard API to use correct OSP which is selected while creating a cluster.
```
=> [release/v2.25] (fix): use OSP from node instead of default OSP from dc

modules/api/pkg/handler/v2/clusterbackup/storage-location/wrappers_ce.go
This PR updates wrapper_ce.go for CBSL to include missing function args while calling createCBSL
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> (fix): Update CBSL wrapper in CE to prevent build issues while using CE tag

.prow/api.yaml, .prow/common.yaml, .prow/frontend.yaml, hack/lib.sh, modules/web/containers/chrome-headless/Dockerfile, modules/web/containers/chrome-headless/release.sh, modules/web/containers/custom-dashboard/Dockerfile
This PR is to update the image tag for KKP owned images
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> Update the image tag for KKP owned images

modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/component.ts, modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/template.html, modules/web/src/app/settings/admin/defaults/component.ts, modules/web/src/app/settings/admin/defaults/template.html, modules/web/src/app/shared/entity/backup.ts, modules/web/src/app/shared/entity/settings.ts
Add functionality to configure checksum algorithm for backup storage location. A new setting has also been in admin settings to configure default checksum algorithm value.
**Admin Settings:**
**Backup Storage Location Dialog:**
Fixes #7260 
/kind feature
```release-note
Add functionality to configure checksum algorithm for backup storage location.
```
```documentation
TBD
```
=> Add functionality to configure checksum algorithm for backup storage location

modules/web/src/app/cluster/details/cluster/style.scss, modules/web/src/app/cluster/details/cluster/template.html, modules/web/src/app/settings/admin/defaults/template.html, modules/web/src/app/settings/admin/opa/component.ts, modules/web/src/app/settings/admin/opa/style.scss, modules/web/src/app/settings/admin/opa/template.html, modules/web/src/app/wizard/step/cluster/style.scss, modules/web/src/app/wizard/step/cluster/template.html
Re-add this PR: https://github.com/kubermatic/dashboard/pull/6990
**Admin settings- default page:**
**Admin settings OPA page:**
**Cluster detail page:**
**Cluster wizard:**
Fixes #6988 
/kind feature
```release-note
NONE
```
```documentation
NONE
```
=> Add OPA deprecated warning message

Makefile, modules/api/Makefile, modules/web/Makefile, modules/web/package-lock.json, modules/web/package.json
This PR prepares the dashboard for prepare 2.28.0-alpha.2
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> prepare 2.28.0-alpha.2

modules/web/src/app/cluster-template/component.ts, modules/web/src/app/cluster-template/style.scss, modules/web/src/app/cluster-template/template.html, modules/web/src/app/cluster/details/cluster/component.ts, modules/web/src/app/cluster/details/cluster/style.scss, modules/web/src/app/cluster/details/cluster/template.html, modules/web/src/app/cluster/list/cluster/component.ts, modules/web/src/app/cluster/list/cluster/template.html, modules/web/src/app/settings/admin/seed-configurations/seed-configurations-details/component.ts, modules/web/src/app/settings/admin/seed-configurations/seed-configurations-details/style.scss, modules/web/src/app/settings/admin/seed-configurations/seed-configurations-details/template.html, modules/web/src/app/wizard/step/provider-datacenter/component.ts, modules/web/src/app/wizard/step/provider-datacenter/style.scss, modules/web/src/app/wizard/step/provider-datacenter/template.html
add a deprecation warning for Equinix Metal provider.
```release-note
Deprecate Equinix Metal provider
```
```documentation
NONE
```
=> Add a deprecation warning for Equinix Metal

modules/web/src/app/wizard/step/applications/component.ts
This PR adds missing labels to the ApplicationInstallation
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Add labels to ApplicationInstallation

modules/api/pkg/ee/kyverno/policy-template/handler.go, modules/web/src/app/cluster/details/cluster/edit-cluster/template.html, modules/web/src/app/dynamic/enterprise/kyverno-policies/cluster-policies/template.html, modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/component.ts, modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/template.html, modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/template.html, modules/web/src/app/settings/admin/nav/template.html, modules/web/src/app/shared/components/cluster-summary/template.html, modules/web/src/app/shared/entity/kyverno.ts, modules/web/src/app/wizard/step/cluster/template.html
**fix : The helper text here needs to improve. Right now this doesn't make much sense so isn't really helpful**
**fix: Improvements in the `Create Policy Template` dialog**
**fix: This shouldn't probably be called "Kyverno Integration" but instead "Kyverno Policy Management" or something** similar. Also add a tooltip of what Kyverno Integration would do.
**fix: Wrong message on hover**
**fix: No proper message when policy templates is empty**
Fixes #7384
<!--
Add one of the following kinds:
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix UI kyverno issues

modules/web/src/app/cluster/details/cluster/edit-cluster/template.html, modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/component.ts, modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/template.html, modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/style.scss, modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/template.html, modules/web/src/app/shared/components/editor/component.ts
Fixing minor UI/UX issues.
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
=> Fix UX issues for Kyverno

modules/web/src/app/wizard/step/cluster/template.html
This PR fixes a minor cosmetic alignment issue with the OPA checkbox
**Before:**
**After:**
Fixes #
/kind design
Minor Cosmetic fix
```release-note
NONE
```
```documentation
NONE
```
=> Fix OPA Checkbox alignment

modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts, modules/web/src/app/wizard/step/cluster/component.ts
This is an manual cherry-pick of #7453
/assign ahmedwaleedmalik
```release-note
KubeLB: Fix a bug where enforcement on a datacenter was not enabling KubeLB for the user clusters in the dashboard.
```
/kind bug
=> [release/v2.27] KubeLB: Fix a bug with enforcement

modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts, modules/web/src/app/cluster/details/cluster/edit-cluster/template.html, modules/web/src/app/wizard/step/cluster/component.ts, modules/web/src/app/wizard/step/cluster/template.html
General improvements for tooltips for KubeLB.
Fixes #
/kind chore
This PR re-iterates on https://github.com/kubermatic/dashboard/pull/7458 and fixes more tooltip wordings and a few issues from that PR. Since https://github.com/kubermatic/dashboard/pull/7458 already has a release note, I settled with having release note as `NONE` for this one.
```release-note
NONE
```
```documentation
NONE
```
=> Improve tooltips for KubeLB

modules/api/go.mod, modules/api/go.sum
This PR is to bump dependencies for KKP and MC.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.26] Bump KKP and MC dependencies

modules/api/go.mod, modules/api/go.sum
This PR is to bump KKP dependencies with latest commit c3a24952efd944c9c192881f406af83b1a60cda4
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.28] Bump KKP dependencies

modules/api/pkg/resources/machine/common.go
(cherry picked from commit 004e0bca63e117dd632f8a3f8863eebf0d2c4f47)
This is a manual cherry picked from commit 004e0bca63e117dd632f8a3f8863eebf0d2c4f47
Fixes #
/kind bug
```release-note
Skip setting custom CPUs field in machine deployment for Kubevirt user clusters.
```
```documentation
None
```
=> [release/v2.27] Skip setting kubevirt cpu value when an instance type is chosen (#7493)

.prow/api.yaml, .prow/common.yaml, .prow/frontend.yaml, hack/verify-spelling.sh, modules/api/hack/gen-api-client.sh, modules/api/hack/update-swagger.sh, modules/api/hack/verify-licenses.sh, modules/web/containers/chrome-headless/Dockerfile, modules/web/containers/custom-dashboard/Dockerfile
This PR is to bump Go build image version
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.27] Bump Go build image version

.prow/api.yaml, .prow/common.yaml, .prow/frontend.yaml, hack/verify-spelling.sh, modules/api/hack/gen-api-client.sh, modules/api/hack/update-swagger.sh, modules/api/hack/verify-licenses.sh, modules/web/containers/chrome-headless/Dockerfile, modules/web/containers/custom-dashboard/Dockerfile
This PR is to bump Go build image version.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
=> [release/v2.26] Bump Go build image version
